import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.items_mgr
import ui.root
import ui.ui_economy
import ui.ui_player_info
import ssl.hf2p.engine_ctrl
import ssl.hf2p.ui_ingame
import ssl.hf2p.ui_globals
import ui.hf2p_CashPanel.hf2p_CashPanel


/*************************************************************
* ScoringEvent
* 
*************************************************************/
class UiScoringEvent : UiWidgetContainer
   func StartFadeIn()
      Props.visible := true
      Widgets.item.GotoAndPlay("fadein")
      //delay kill, this, FADE_OUT_WAIT
      //OnFadeOutReady() : 3.0, FADE_OUT_WAIT
   end
   
   func OnFadeOutReady()
      //StartFadeOut()
      //GenerateEvent("#OnListItemFadeOut")
   end
   
   func StartFadeOut()
      Widgets.item.GotoAndPlay("fadeout")
   end
   
   func StartWait()
      Widgets.item.GotoAndPlay("wait")
   end   
   
   func SetIdle()
      Widgets.item.GotoAndStop("wait")
      GotoAndStop(0)
   end   
   
   func StartSlide()
      GotoAndPlay("move")
      //delay kill, this, SLIDE_AWAY
      //OnListItemSlideFinished() : 3.0, SLIDE_AWAY
   end   
   
   func OnListItemSlideFinished()
     // GenerateEvent("#OnListItemSlideFinished")
   end
   
   func SetNone()
      Props.visible := false
      Widgets.item.GotoAndStop("wait")
      //GotoAndStop("move")
   end   
end

class UiScoringEventVM
   var   wgt            : UiScoringEvent     = null
   var   eventId        : ObservableProperty = $OM.Property("")
   var   eventIcon      : ObservableProperty = $OM.Calculated(this, "GetEventlIcon")
   var   eventName      : ObservableProperty = $OM.Calculated(this, "GetEventName")
   var   eventScore     : ObservableProperty = $OM.Calculated(this, "GetEventScore")

   func InitWgt(_wgt : UiScoringEvent)
      wgt := _wgt
   end
   
   func SetEventId(_eventId : string)
      //SetIdle()
      eventId.Set(_eventId)
   end
   
   func GetEventlIcon() : string      
      var uiComp : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(eventId.Get())
      return (string)uiComp.icon.Get()      
   end
   
   func GetEventName() : string
      var uiComp        : GL_ComponentUI           = (GL_ComponentUI)$UiGlobals.componentsUI.Get(eventId.Get())
      var scoringComp   : GL_ComponentScoringEvent = (GL_ComponentScoringEvent)$UiGlobals.componentsScoringEvent.Get(eventId.Get())
      var score         : int                      = (int)scoringComp.reward_wp.Get()
      var ret           : string                   = "{STRING}: +{STRING}~" + (string)uiComp.name.Get() + "," + (string)score
      return ret
   end

   func GetEventScore() : int
      var scoringComp : GL_ComponentScoringEvent = (GL_ComponentScoringEvent)$UiGlobals.componentsScoringEvent.Get(eventId.Get())
      return (int)scoringComp.reward_wp.Get()            
   end

   func StartFadeIn()
      if (wgt != null)
         wgt.StartFadeIn()
      end
   end
      
   func SetIdle()
      if (wgt != null)
         wgt.SetIdle()
      end
   end
   
   func StartFadeOut()
      if (wgt != null)
         wgt.StartFadeOut()         
      end      
   end
   
   func StartWait()
      if (wgt != null)
         wgt.StartWait()         
      end      
   end
   
   func StartSlide()
      if (wgt != null)
         wgt.StartSlide()         
      end      
   end
   
   func SetNone()
      if (wgt != null)
         wgt.SetNone()         
      end            
   end
end

/*************************************************************
* ScoringEventsList
* 
*************************************************************/
class UiScoringEventsList : UiWidgetContainer
   
end

class UiScoringEventsListVM
   var   wgt                  : UiScoringEventsList   = null
   var   events               : vector
   var   totalElems           : int                   = 12
   var   listData             : vector
   var   entryDuration        : float                 = 3.0
   var   entryDurationGrow    : float                 = 1.0
   var   entryAddDuration     : float                 = 1.0
   var   entryAddDurationGrow : float                 = 0.3
   var   isIdleTotals         : bool                  = true
   
   func InitWgt(_wgt : UiWidget, _entryDuration : float, _entryDurationGrow : float, _entryAddDuration : float, _entryAddDurationGrow : float)
      entryDuration        := _entryDuration
      entryDurationGrow    := _entryDurationGrow
      entryAddDuration     := _entryAddDuration
      entryAddDurationGrow := _entryAddDurationGrow
      wgt := (UiScoringEventsList)_wgt
      var i : int
      for i := 0 to totalElems - 1
         var scoringEvent : UiScoringEventVM = events.Get(i)
         scoringEvent.InitWgt((UiScoringEvent)wgt.GetWidget("item" + (string)(i)))      
      end
      Clear()
   end
   
   func GetTotalElems() : int
      return totalElems
   end
   
   func SetIsIdleTotals(_isIdleTotals : bool)
      isIdleTotals := _isIdleTotals
   end

   func Clear()
      var i : int 
      for i := 0 to GetTotalElems() - 1
         var scoringEvent  : UiScoringEventVM   = events.Get(i)
         scoringEvent.SetNone()
      end
   end
   
   func UiScoringEventsListVM()
      var i : int
      for i := 0 to GetTotalElems() - 1
         var scoringEvent : UiScoringEventVM = new UiScoringEventVM()
         //scoringEvent.SetEventId()
         events.Push(scoringEvent)
      end
   end
   
   func OnListItemFadeOut()
      var i : int
      for i := 0 to GetTotalElems() - 1
         var scoringEvent : UiScoringEventVM = events.Get(i)
         scoringEvent.StartSlide()
      end      
      var stayDuration : float = entryAddDuration / 2
      if (isIdleTotals)
         stayDuration := (entryDuration - entryAddDuration / 2)
      end
      if (listData.Count() <= 1)
         wgt.GenerateEvent("#HudScoringEventFinishedAll")
      end
      OnListItemSlideFinished() : stayDuration
   end
   
   func OnListItemSlideFinished()
      if (listData.Count() > 0)
         var i : int
         for i := 0 to GetTotalElems() - 1
            var scoringEvent : UiScoringEventVM = events.Get(i)
            scoringEvent.SetIdle()
         end
      
         var scoringEvent  : UiScoringEventVM   = events.Get(listData.Count() - 1)
         scoringEvent.SetNone()
         
         for i := 0 to listData.Count() - 2
            listData.Set(i, listData.Get(i + 1))
         end
         listData.Pop()
         
         for i := 0 to listData.Count() - 1
            scoringEvent := events.Get(i)
            var eventId: string = listData.Get(i)
            scoringEvent.SetEventId(eventId)
         end
         
         if (listData.Count() > 0)
            scoringEvent := events.Get(0)                     
            scoringEvent.StartFadeOut() : (entryAddDuration / 2)
            OnListItemFadeOut() : (entryAddDuration / 2)
            if (listData.Count() == GetTotalElems() - 1)
               wgt.GenerateEvent("#HudScoringEventFinished")
            end
            SetIsIdleTotals(false)
         end            
      end
   end
   
   func AllowNextEvent()
      wgt.GenerateEvent("#HudScoringEventFinished")
   end
   
   func AllowNextEventDelayed(_dt : float)
      AllowNextEvent() : _dt
   end
   
   func AddNewEvent(_eventId : string)
      if (listData.Count() < GetTotalElems())
         var i             : int                = listData.Count()
         var scoringEvent  : UiScoringEventVM   = events.Get(i)
         listData.Push(_eventId)
         scoringEvent.SetEventId(_eventId)
         scoringEvent.StartFadeIn()
         if (i == 0)
            scoringEvent.StartFadeOut() : (entryDuration - entryAddDuration / 2)
            OnListItemFadeOut() : (entryDuration - entryAddDuration / 2)
         end
         if (listData.Count() < GetTotalElems())
            //AllowNextEventDelayed(5) //entryDurationGrow * 0.8)
            AllowNextEventDelayed(entryDurationGrow * 0.8)
         end
      end
   end
end

/*************************************************************
* ScoringEventsTotal
* 
*************************************************************/
class UiScoringEventsTotal : TweeningNum
   var currentFrame : int = 15
      
   func OnValueUpdated()
      currentFrame := currentFrame + 10
      if (currentFrame > 79)
         currentFrame := 79
      end
      GotoAndStop(currentFrame)
      Widgets.scoringTotalAnimCont.GotoAndPlay("income")
      Widgets.scoringTotalAnimCont.totalsAnimCont.scoreTxt.orangeGlow.orangeGlow.GotoAndPlay(1)
   end   
   
   func OnTweenStart()
      Props.visible := true
      GotoAndPlay("fadein")
      Widgets.scoringTotalAnimCont.GotoAndPlay("income")
      Widgets.scoringTotalAnimCont.totalsAnimCont.scoreTxt.orangeGlow.orangeGlow.GotoAndPlay(1)
      currentFrame := 15
   end   
   
   func OnTweenEnd()
      GotoAndPlay("fadeOut")
      //Widgets.scoringTotalAnimCont.GotoAndPlay("income")
      //Widgets.scoringTotalAnimCont.totalsAnimCont.scoreTxt.orangeGlow.orangeGlow.GotoAndPlay(1)
   end  
   
   func SetInitial()
      GotoAndStop(1000)
   end
end

class UiScoringEventsTotalVM : TweeningNumVm
   var   totalScore           : ObservableProperty    = $OM.Property(0)
   var   cumulValue           : float                 = 0
   var   scoringTotalTxt      : ObservableProperty    = $OM.Calculated(this, "GetScoringTotalTxt")
   var   glowWidth            : ObservableProperty    = $OM.Calculated(this, "GetGlowWidth")
   var   entryDuration        : float                 = 3.0
   var   entryDurationGrow    : float                 = 1.0
   var   entryAddDuration     : float                 = 1.0
   var   entryAddDurationGrow : float                 = 0.3
   var   wasReset             : bool                  = true
   var   isFadingOut          : bool                  = false
   
   override IsUpdateOnEnable//() : bool
      return true
   end
   
   override IsSkipFirstUpdate//() : bool
      return false
   end
   
   func InitWgt(_wgt : UiWidget, _entryDuration : float, _entryDurationGrow : float, _entryAddDuration : float, _entryAddDurationGrow : float)
      var p : params
      p.widget             := _wgt
      entryDuration        := _entryDuration
      entryDurationGrow    := _entryDurationGrow
      entryAddDuration     := _entryAddDuration
      entryAddDurationGrow := _entryAddDurationGrow
      Init(p)
      Wgt().SetInitial()
   end
   
   override GetObservable //() : ObservableProperty
      return totalScore
   end   
   
   override GetObservableVal //() : GetObservableVal
      return (int)GetObservable().Get()
   end   
   
   override GetTweenSound//() : string
      return ""
   end
   
   override GetDuration//() : float
      return entryDurationGrow
   end
   
   override GetAddDuration//() : float
      return entryAddDurationGrow
   end
   
   func Wgt() : UiScoringEventsTotal
      return (UiScoringEventsTotal)wgt
   end

   override OnValueUpdated //()
      if (wgt != null)
         Wgt().OnValueUpdated()
      end
   end   
   
   override OnTweenStart //()
      if (wasReset)
         wasReset := false
         if (wgt != null)
            Wgt().OnTweenStart()
         end
      else
         if (wgt != null)
            Wgt().OnValueUpdated()
         end
      end
   end   
   
   override OnTweenPreStart//()
      if (wasReset)
         ResetValue(0)      
      end
   end
   
   func FinishTween()
      if (wgt != null)
         Wgt().OnTweenEnd()
      end      
      StartFadeOut()
   end
      
   func IsFadingOut() : bool
      return isFadingOut
   end
   
   func StartFadeOut()
      KillFadeOutDelay()
      isFadingOut := true
      StopFadeout() : GetDuration(), SCORING_TOTALS_FADE_OUT_DELAY
   end
   
   func StopFadeout()
      if (isFadingOut)
         cumulValue  := 0      
         wasReset    := true
         ResetValue(0)
      
         KillFadeOutDelay()
         isFadingOut := false
         if (wgt != null)
            wgt.GenerateEvent("#HudScoringTotalsFadedOut")
         end
      end
   end
   
   func KillFadeOutDelay()
      delay kill, this, SCORING_TOTALS_FADE_OUT_DELAY
      isFadingOut := true
   end
   
   override OnTweenEnd //()
      var currentTime   : float = 0
      if (wgt != null)
         wgt.GenerateEvent("#OnTotalsGrowFinished")
      end
   end   

   func GetScoringTotalTxt() : string
      var ret : string = "+" + (string)((int)tweenedValue.Get())
      return "+" + (string)((int)tweenedValue.Get())
   end
      
   func GetGlowWidth() : float
      var ret : float = (int)tweenedValue.Get()
      if (wgt != null)
         scoringTotalTxt.Invalidate()
         var textW : float = wgt.Props.textW
         ret := textW + 10
      else
         ret := 240
      end
      return ret
   end
   
   override IsAutomaticUpdates // () : bool
      return false
   end
   
   func AddNewEvent(_eventId : string)
      var scoringComp   : GL_ComponentScoringEvent = (GL_ComponentScoringEvent)$UiGlobals.componentsScoringEvent.Get(_eventId)
      var score         : int = (int)scoringComp.reward_wp.Get()      
      cumulValue := cumulValue + score
      var curValue : float = (float)totalScore.Get()
      totalScore.Set(cumulValue)
      OnUpdateVal(totalScore.Get())
   end
end

/*************************************************************
* HudMedals
* 
*************************************************************/
class UiHudMedals : UiWidgetContainer

handle OnActivate // ()
   Props.x := 827
   Props.y := 75
end

handle OnEnterState("Visible")
   Props.visible := true
   GenerateEvent("#HudMedalsVisible")
end

handle OnEnterState("Initial")
   Props.visible := false
   GenerateEvent("#HudMedalsInitial")
end

func StartMedalAnim(_showTime : float)
   Widgets.medalsContainer.medalsContent.GotoAndPlay("slidingDown1")   
   FinishMedalAnim() : _showTime
end

func FinishMedalAnim()
   GenerateEvent("#HudMedalAnimFinished")   
end

end

/*************************************************************
* HudMedalsVM
* 
*************************************************************/
class UiHudMedalVM
   var medalId       : ObservableProperty = $OM.Property("")
   var medalIcon     : ObservableProperty = $OM.Calculated(this, "GetMedalIcon")
   var medalName     : ObservableProperty = $OM.Calculated(this, "GetMedalName")
   
   func SetMedalId(_medalId : string)
      medalId.Set(_medalId)
   end
   
   func GetMedalIcon() : string      
      var uiComp : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(medalId.Get())
      return (string)uiComp.icon.Get()      
   end
   
   func GetMedalName() : string
      var uiComp : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(medalId.Get())
      return (string)uiComp.name.Get()            
   end
end

class UiHudMedalsVM : UiWidgetContainer
   var   isSubscribed      : bool                     = false
   var   wgt               : UiHudMedals              = null
   var   currentMedal      : string                   = ""
   var   medalIdx          : int                      = 0
   var   medal1            : UiHudMedalVM             = new UiHudMedalVM()
   var   medal2            : UiHudMedalVM             = new UiHudMedalVM()
   var   medal3            : UiHudMedalVM             = new UiHudMedalVM()
   var   scoringEvents     : UiScoringEventsListVM    = new UiScoringEventsListVM()
   var   scoringTotal      : UiScoringEventsTotalVM   = new UiScoringEventsTotalVM()
   var   loopSoundPlaying  : bool                     = false
   
   var   medalsDuration       : float                    = 2.0
   var   medalsStayDuration   : float                    = 1.5
   
   var   entryDuration        : float                    = 2.0
   var   entryDurationGrow    : float                    = 1.0
   var   entryAddDuration     : float                    = 1.0
   var   entryAddDurationGrow : float                    = 1.0

   
   func Init(p : params)
      wgt := p.widget
      scoringEvents.InitWgt((UiWidget)wgt.GetWidget("scoreEventsList"), entryDuration, entryDurationGrow, entryAddDuration, entryAddDurationGrow)
      scoringTotal.InitWgt((UiWidget)wgt.GetWidget("scoringEventTotals"), entryDuration, entryDurationGrow, entryAddDuration, entryAddDurationGrow)
   end

   func Term()
      UnsubscribeFromEvents()
   end

   func SubscribeToEvents()
      if (! isSubscribed)
         isSubscribed := true
         scoringTotal.EnableTweenVM()
         $UiIngame.scoring_event.Subscribe(this, "UpdateScoringEvents")
         $UiIngame.medal.Subscribe(this, "UpdateMedals")
         UpdateScoringEvents()
         UpdateMedals()
      end
   end

   func UnsubscribeFromEvents()
      StopMedalFadeout()
      if (isSubscribed)
         scoringTotal.DisableTweenVM()
         $UiIngame.scoring_event.Unsubscribe(this, "UpdateScoringEvents")
         $UiIngame.medal.Unsubscribe(this, "UpdateMedals")
         isSubscribed := false
      end      
      StopLoopingSounds()
   end

   func StopLoopingSounds()
      $root.stopSound("score_tally_looping")
      loopSoundPlaying := false
   end

   func HudMedalsVisible()
      loopSoundPlaying := false
      SubscribeToEvents()
   end

   func HudMedalsInitial()
      UnsubscribeFromEvents()
   end
      
   func HudMedalAnimFinished()
      StopMedalFadeout()
      StartMedalFadeout() : (medalsStayDuration), FADE_OUT_MEDALS
      $UiIngame.MedalNext() 
   end

   func HudScoringEventFinished()
      $UiIngame.ScoringEventNext()
   end
   
   func HudScoringTotalsFadedOut()
      $UiIngame.ScoringEventNext()
   end
   
   func HudScoringEventFinishedAll()
      $root.playSound("score_tally_end")
      scoringTotal.FinishTween()
   end
         
   func OnTotalsGrowFinished()
      StopLoopingSounds()
      scoringEvents.SetIsIdleTotals(true)
   end
      
   func StartMedalFadeout()
      StartMedalShow("")
   end
   
   func StopMedalFadeout()
      delay kill, this, FADE_OUT_MEDALS
   end

   func UpdateScoringEventOrMedal(_eventId : string, _isMedal : bool)
      if (_eventId != "")
         if (_isMedal)
            StartMedalShow(_eventId)
         else
            StartEventShow(_eventId)
         end
      end      
   end   

   func UpdateScoringEvents()
      if (! scoringTotal.IsFadingOut())
         var eventId : string = (string)$UiIngame.scoring_event.Get()
         UpdateScoringEventOrMedal(eventId, false)
      end
   end   
   
   func UpdateMedals()
      var eventId: string = (string)$UiIngame.medal.Get()
      UpdateScoringEventOrMedal(eventId, true)
   end   
   
   func StartEventShow(_scoringEventId: string)     
      if (_scoringEventId != "")
         scoringEvents.AddNewEvent(_scoringEventId)
         scoringTotal.AddNewEvent(_scoringEventId)
         if (_scoringEventId != "")
            if (! loopSoundPlaying)
               loopSoundPlaying := true
               $root.playSound("score_tally_start")
               $root.playSound("score_tally_looping")
            end
         end
      end      
   end 
   
   func StartMedalShow(_scoringEventId: string)      
      StopMedalFadeout()
      if (wgt != null)
         medal1.SetMedalId(currentMedal)
         medal2.SetMedalId(_scoringEventId)
         wgt.StartMedalAnim(medalsDuration)
         currentMedal := _scoringEventId
         if (currentMedal != "")
            $root.playSound("medals_popup")
         end
      end
   end
end
