import ssl.lib.logging
import ssl.lib.events
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_popup
import ssl.hf2p.engine_ctrl
import ui.ui_party_monitor
import ui.ui_matchmaking
import ssl.observables
import ssl.lib.ui.bindings.bindings
import ssl.hf2p.ui_globals
import ui.hf2p_SlidingScreens.hf2p_Armory.hf2p_Armory


class UiChallengesStatsRankVM
   var challengeId         : ObservableProperty    = $OM.Property("")
   var idx                 : ObservableProperty    = $OM.Property(0)
   var isCompleted         : ObservableProperty    = $OM.Property(false)
   var isLocked            : ObservableProperty    = $OM.Property(false)
   var rankFrame           : ObservableProperty    = $OM.Calculated(this, "GetRankFrame")
   var desc                : ObservableProperty    = $OM.Calculated(this, "GetDesc")
   var rewardPoints        : ObservableProperty    = $OM.Calculated(this, "GetRewardsPoints")
   var rewardFrame         : ObservableProperty    = $OM.Calculated(this, "GetRewardsFrame")
   var challenge           : ObservableProperty    = $OM.Calculated(this, "GetChallenge")
   var challengeState      : ObservableProperty    = $OM.Calculated(this, "GetChallengeState")
   var challengeStateFrame : ObservableProperty    = $OM.Calculated(this, "GetChallengeStateFrame")
   
   func GetChallenge() : GL_ComponentChallenge
      var ret : GL_ComponentChallenge = (GL_ComponentChallenge)$UiGlobals.componentsChallenge.Get(challengeId.Get())
      return ret
   end
   
   func GetChallengeVal() : GL_ComponentChallenge
      return (GL_ComponentChallenge)challenge.Get()
   end
   
   func GetIdxVal() : int
      return (int)idx.Get()
   end
   
   func GetRankFrame() : string
      var ret     : string = ""
      var idxVal  : int    = GetIdxVal()
      if (idxVal == -1)
         ret := "gray"
      elif (idxVal == 0)
         ret := "bronze"
      elif (idxVal == 1)
         ret := "silver"
      elif (idxVal == 2)
         ret := "gold"
      else
         ret := "gray"
      end
      return ret      
   end
   
   func GetDesc() : string
      var ret        : string
      var challenge  : GL_ComponentChallenge = GetChallengeVal()
      if (challenge != null)    
         ret := challenge.GetDescString((string)challengeId.Get())
      end
      return ret
   end
   
   func GetRewardsPoints() : string
      var ret           : string
      var comp          : GL_ComponentChallenge = GetChallengeVal()
      var reward_tokens : vector = comp.rewards_tokens.Get()
      if reward_tokens.Count() > 0
         var token : GL_TokenState = reward_tokens.Get(0)
         ret := (string)$UiGlobals.Int64ToInt(token.value.Get())
      end
      return ret     
   end
   
   func GetRewardsFrame() : string
      var ret : string
      var comp : GL_ComponentChallenge = GetChallengeVal()
      var reward_tokens : vector = comp.rewards_tokens.Get()
      if reward_tokens.Count() > 0
         var token : GL_TokenState = reward_tokens.Get(0)
         ret := $UiGlobals.GetTokenFrame((string)token.name.Get())
      end
      return ret
   end
   
   func GetChallengeState() : int
      var ret : int = 0
      // 0 = locked
      // 1 = open
      // 2 = completed
      if ((bool)isCompleted.Get())
         ret := 2
      elif ((bool)isLocked.Get())
         ret := 0
      else
         ret := 1
      end
      
      return ret
   end
   
   func GetChallengeStateFrame() : string
      var challengeState   : int    = GetChallengeState()
      var ret              : string = "open"
      if (challengeState == 0)
         ret := "lock"
      elif (challengeState == 1)
         ret := "open"
      elif (challengeState == 2)
         ret := "closed"
      end
      return ret
   end
end

class UiChallengesStatsProgressVM
   var challengeId      : ObservableProperty    = $OM.Property("")
   var counter          : ObservableProperty    = $OM.Property(null)
   var curCounterTxt    : ObservableProperty    = $OM.Calculated(this, "GetCurCounterTxt")
   var totalCounterTxt  : ObservableProperty    = $OM.Calculated(this, "GetTotalCounterTxt")
   var desc             : ObservableProperty    = $OM.Calculated(this, "GetDesc")
   var progress         : ObservableProperty    = $OM.Calculated(this, "GetProgress")
   var progressX        : ObservableProperty    = $OM.Calculated(this, "GetProgressX")
   var challenge        : ObservableProperty    = $OM.Calculated(this, "GetChallenge")
   var blinkFactor      : ObservableProperty = $OM.Property(1.0)
   
   func GetCounter() : GL_ComponentChallengeCounter
      var ret : GL_ComponentChallengeCounter = (GL_ComponentChallengeCounter)counter.Get()
      return ret
   end
   
   func GetChallenge() : GL_ComponentChallenge
      var ret : GL_ComponentChallenge = (GL_ComponentChallenge)$UiGlobals.componentsChallenge.Get(challengeId.Get())
      return ret
   end
   
   func GetChallengeVal() : GL_ComponentChallenge
      return (GL_ComponentChallenge)challenge.Get()
   end
   
   func GetCurCounterTxt() : string
      var ret        : string
      var counterVal : GL_ComponentChallengeCounter = GetCounter()
      if (counterVal != null)
         ret := (string)(int)counterVal.value.Get()
      end
      return ret
   end
   
   func GetTotalCounterTxt() : string
      var ret : string
      var counterVal : GL_ComponentChallengeCounter = GetCounter()
      if (counterVal != null)
         ret := (string)(int)counterVal.value_max.Get()
      end
      return ret
   end
   
   func GetDesc() : string
      var ret        : string
      var challenge  : GL_ComponentChallenge = GetChallengeVal()
      if (challenge != null)    
         ret := challenge.GetDescString((string)challengeId.Get())
      end
      return ret
   end
   
   func GetProgress() : float
      var ret : float = 1.0
      var counterVal : GL_ComponentChallengeCounter = GetCounter()
      if (counterVal != null)
         ret := (float)counterVal.progress.Get() * (float)blinkFactor.Get()         
      end
      return ret
   end
   
   func GetProgressX() : float
      var progress   : float = (float)progress.Get()
      var ret        : float = -365 + progress * 364
      return ret     
   end
   
   func blinkProgress(p : params) : bool
      if (!IsVoid(p.blinkProgress))
         blinkFactor.Set(p.blinkProgress)
      end
      return false
   end
end


class UiChallengesStatsVM
   var challengeItemId     : ObservableProperty    = $OM.Property("")
   var challengeId         : ObservableProperty    = $OM.Property("")
   var nextChallengeId     : ObservableProperty    = $OM.Calculated(this, "GetNextChallengeId")
   var nextChallenge       : ObservableProperty    = $OM.Calculated(this, "GetNextChallenge")
   var componentItem       : ObservableProperty    = $OM.Calculated(this, "GetItemComponent")
   var componentItemNext   : ObservableProperty    = $OM.Calculated(this, "GetItemNextComponent")
   var compUI              : ObservableProperty    = $OM.Calculated(this, "GetCompUI")
   var itemCompUI          : ObservableProperty    = $OM.Calculated(this, "GetItemCompUI")
   
   // header   
   var nextName            : ObservableProperty    = $OM.Calculated(this, "GetNextName")
   var nextIcon            : ObservableProperty    = $OM.Calculated(this, "GetNextIcon")
   var name                : ObservableProperty    = $OM.Calculated(this, "GetName")
   var desc                : ObservableProperty    = $OM.Calculated(this, "GetDesc")
   var progressTxt         : ObservableProperty    = $OM.Calculated(this, "GetTxtProgress")
   var isComplete          : ObservableProperty    = $OM.Calculated(this, "InProgress")
   var totalReward         : ObservableProperty    = $OM.Calculated(this, "GetTotalPoints")
   var tpFrame             : ObservableProperty    = $OM.Calculated(this, "GetTpFrame")
   var progress            : ObservableProperty    = $OM.Calculated(this, "GetProgress")
   var challengeComplete   : ObservableProperty    = $OM.Calculated(this, "IsComplete")
   var goldAnim            : ObservableProperty    = $OM.Calculated(this, "GetHeadFrame")
   var blinkFactor         : ObservableProperty    = $OM.Property(1.0)
   
   // ranks
   var isRanksVisible      : ObservableProperty    = $OM.Calculated(this, "GetIsRanksVisible")
   var challengesVec       : ObservableProperty    = $OM.Calculated(this, "GetChallengesVec")
   var challengesVecCount  : ObservableProperty    = $OM.Calculated(this, "GetChallengesVecCount")
   
   // progress
   var isProgressVisible   : ObservableProperty    = $OM.Calculated(this, "GetIsProgressVisible")
   var progressVec         : ObservableProperty    = $OM.Calculated(this, "GetProgressVec")
   var progressVecCount    : ObservableProperty    = $OM.Calculated(this, "GetProgressVecCount")
   
   // items   
   var isItemsVisible      : ObservableProperty    = $OM.Calculated(this, "GetIsItemsVisible")
   var followingItem       : ObservableProperty    = $OM.Calculated(this, "GetFollowItem")
   var followingItemType   : ObservableProperty    = $OM.Calculated(this, "GetFollowingItemType")
   var followingItemName   : ObservableProperty    = $OM.Calculated(this, "GetFollowingItemName")
   var followingItemIcon   : ObservableProperty    = $OM.Calculated(this, "GetFollowingItemIcon")
   var equipFrame          : ObservableProperty    = $OM.Calculated(this, "GetEquipFrame")
   var equipFollowItem     : ObservableProperty    = $OM.Calculated(this, "IsFollowItemEquip")
   var armorParts          : ObservableProperty    = $OM.Calculated(this, "GetFollowingArmorParts") 
   
   func Init(challengeItemIdVal: string, challengeIdVal: string)
      challengeItemId.Set(challengeItemIdVal)
      challengeId.Set(challengeIdVal)
   end
   
   func Term()
      challengeItemId.Set("")
   end
   
   func GetNextChallengeId() : string
      var ret : string
      if (challengeItemId.Get() != "")
         ret := GetItemComponentVal().GetNextChallengeId()
      else
         ret := (string)challengeId.Get()
      end
      return ret
   end
   
   func GetChallengeItem() : string
      return (string)challengeItemId.Get()
   end
   
   func GetChallengeId() : string
      return (string)challengeId.Get()
   end
   
   func GetNextChallenge() : GL_ComponentChallenge
      var ret : GL_ComponentChallenge = (GL_ComponentChallenge)$UiGlobals.componentsChallenge.Get(nextChallengeId.Get())
      return ret
   end
   
   func GetItemComponent() : GL_ComponentItem
      var ret : GL_ComponentItem = (GL_ComponentItem)$UiGlobals.componentsItem.Get(challengeItemId.Get())
      return ret
   end
   
   func GetItemNextComponent() : GL_ComponentItem
      var ret : GL_ComponentItem = (GL_ComponentItem)$UiGlobals.componentsItem.Get(nextChallengeId.Get())
      return ret
   end
   
   func GetItemComponentVal() : GL_ComponentItem
      return (GL_ComponentItem)componentItem.Get()
   end
   
   func GetItemNextComponentVal() : GL_ComponentItem
      return (GL_ComponentItem)componentItemNext.Get()
   end
   
   // header   
   func GetCompUI() : GL_ComponentUI      
      var challengeId   : string          = (string)nextChallengeId.Get()
      var compUIVal     : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(challengeId)
      return compUIVal
   end
   
   func GetItemCompUI() : GL_ComponentUI      
      var itemChallengeId   : string          = (string)challengeItemId.Get()
      var compUIVal     : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(itemChallengeId)
      return compUIVal
   end
   
   func GetCompUIVal() : GL_ComponentUI
      return (GL_ComponentUI)compUI.Get()
   end
   
   func GetItemCompUIVal() : GL_ComponentUI
      return (GL_ComponentUI)itemCompUI.Get()
   end
   
   func GetNextName() : string
      var compUI : GL_ComponentUI = GetCompUIVal()
      return (string)compUI.name.Get()
   end
   
   func GetNextIcon() : string
      var compUI : GL_ComponentUI = GetCompUIVal()
      return (string)compUI.icon.Get()
   end
   
   func GetName() : string
      var compUI : GL_ComponentUI = GetItemCompUIVal()
      return (string)compUI.name.Get()
   end
   
   func GetDesc() :  string
      var ret : string = ""
      var challenge  : GL_ComponentChallenge = GetNextChallenge()
      ret := challenge.GetDescString(GetNextChallengeId())
      return ret 
   end
   
   func GetTxtProgress() : string
      var ret        : string
      var counter    : GL_ComponentChallengeCounter = null
      var challenge  : GL_ComponentChallenge = GetNextChallenge()
      var counters   : vector = challenge.counters.Get()
      if (counters.Count() > 0)
         counter := (GL_ComponentChallengeCounter)counters.Get(0)
      end
      if (counter != null)
         if ((bool)isComplete.Get())
            ret := "carousel_challenge_completed"
         else
            ret := (string)(int)counter.value.Get() + "/" + (string)(int)counter.value_max.Get() + "~"
         end
      end
      return ret     
   end
   
   func InProgress() : bool
      var ret : bool = componentItemNext.Get().IsComplete()
      return ret
   end
   
   func GetHeadFrame() : string
      var ret : string = "none"
      if ((bool)challengeComplete.Get())
         ret := "gold"
      end
      return ret
   end
   
   func GetTotalPoints() : string
      var ret : string
      var comp  : GL_ComponentChallenge = GetNextChallenge()
      var reward_tokens : vector = comp.rewards_tokens.Get()
      if reward_tokens.Count() > 0
         var token : GL_TokenState = reward_tokens.Get(0)
         ret := (string)$UiGlobals.Int64ToInt(token.value.Get())
      end
      return ret     
   end
   
   func GetTpFrame() : string
      var ret : string
      var comp : GL_ComponentChallenge = GetNextChallenge()
      var reward_tokens : vector = comp.rewards_tokens.Get()
      if reward_tokens.Count() > 0
         var token : GL_TokenState = reward_tokens.Get(0)
         ret := $UiGlobals.GetTokenFrame((string)token.name.Get())
      end
      return ret
   end
   
   func GetProgress() : float
      var ret        : float
      var counter    : GL_ComponentChallengeCounter = null
      var challenge  : GL_ComponentChallenge = GetNextChallenge()
      var counters   : vector = challenge.counters.Get()
      if (counters.Count() > 0)
         counter := (GL_ComponentChallengeCounter)counters.Get(0)
      end
      if ((bool)isComplete.Get())
         ret := 1
      else   
         if (counter != null)
            ret := (float)counter.progress.Get() * (float)blinkFactor.Get()
         end
      end   
      return ret     
   end
   
   func BarTint() : params
      var clr : params
      clr.r  := 71
      clr.g  := 122
      clr.b  := 169
      if ((bool)challengeComplete.Get())
         clr.r  := 225
         clr.g  := 204
         clr.b  := 84
      end     
      return clr
   end
   
   func IsComplete() : bool
      var ret : bool = GetItemComponent().IsComplete()
      return ret      
   end
   
   func blinkProgress(p : params) : bool
      if (!IsVoid(p.blinkProgress))
         blinkFactor.Set(p.blinkProgress)
      end
      return false
   end
   
   // ranks
   func GetChallengesVec() : vector
      var ret              : vector
      if (GetChallengeItem() != "")
         var compItem         : GL_ComponentItem = GetItemComponentVal()
         var challengesVecVal : vector = compItem.related_challenges.Get()
         var i                : int
         for i := 0 to challengesVecVal.Count() - 1
            var rankVM : UiChallengesStatsRankVM = new UiChallengesStatsRankVM()
            rankVM.idx.Set(i)
            rankVM.isCompleted.Set(i <= compItem.GetCurrentChallengeRankVal())
            rankVM.isLocked.Set(i > (compItem.GetCurrentChallengeRankVal() + 1))
            rankVM.challengeId.Set((string)(challengesVecVal.Get(i).value.Get()))
            ret.Push(rankVM)
         end
      end
      return ret
   end   
   
   func GetChallengesVecCount() : int
      var ret : int = challengesVec.Get().Count()
      return ret
   end   
   
   func GetIsRanksVisible() : bool
      return GetChallengeItem() != "" and (int)challengesVecCount.Get() > 0
   end
   
   // progress
   func GetProgressVec() : vector
      var ret : vector
      if (GetChallengeId() != "")
         var compChallenge : GL_ComponentChallenge = (GL_ComponentChallenge)$UiGlobals.componentsChallenge.Get(GetChallengeId())
         var countersVec   : vector = compChallenge.counters.Get()
         var i             : int
         for i := 0 to countersVec.Count() - 1
            var progressVM : UiChallengesStatsProgressVM = new UiChallengesStatsProgressVM()
            progressVM.challengeId.Set(GetChallengeId())
            progressVM.counter.Set(countersVec.Get(i))
            ret.Push(progressVM)
         end
      end
      return ret
      
      // Test Fill (counters from all challenges)
      /*
      var compItem         : GL_ComponentItem = GetItemComponentVal()
      var challengesVecVal : vector = compItem.related_challenges.Get()
      var ret              : vector
      var i                : int
      for i := 0 to challengesVecVal.Count() - 1
         var challengeId   : string = (string)(challengesVecVal.Get(i).value.Get())         
         var compChallenge : GL_ComponentChallenge = (GL_ComponentChallenge)$UiGlobals.componentsChallenge.Get(challengeId)
         var countersVec   : vector = compChallenge.counters.Get()
         if (countersVec.Count() > 0)
            var progressVM : UiChallengesStatsProgressVM = new UiChallengesStatsProgressVM()
            progressVM.challengeId.Set(challengeId)
            progressVM.counter.Set(countersVec.Get(0))
            ret.Push(progressVM)            
         end
      end
      return ret
      */
   end   
   
   func GetProgressVecCount() : int
      var ret : int = progressVec.Get().Count()
      return ret
   end   
   
   func GetIsProgressVisible() : bool
      return GetChallengeId() != "" and (int)progressVecCount.Get() > 0
   end
   
   // items
   func GetFollowItem() : string
      var compShop   : GL_ComponentShop   = (GL_ComponentShop)$UiGlobals.componentsShop.Get(challengeItemId.Get())
      var item       : string             = compShop.GetUnlockItem()
      return item
   end
   
   func GetFollowingItemName() : string
      var ret : string = ""
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get((string)followingItem.Get())
      ret := (string)compUI.name.Get()
      return ret
   end
   
   func GetFollowingItemIcon() : string
      var ret : string = ""
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get((string)followingItem.Get())
      ret := (string)compUI.icon_med.Get()
      return ret
   end
   
   func GetFollowingArmorParts() : vector
      var ret     : vector
      var armorId : string
      if ((int)followingItemType.Get() == $uiEnums.ITEM_TYPE_ARMOR_SUIT)
         armorId := (string)followingItem.Get()
      end   
      if ($UiGlobals.componentsArmorSuit.Exist(armorId))
         var parts : vector = ((GL_ComponentArmorSuit)$UiGlobals.componentsArmorSuit.Get(armorId)).parts.Get()
         var i : int
         for i := 0 to 4
            ret.Push("")
         end
         for i := 0 to parts.Count() - 1
            var armorPartId   : string = (string)(parts.Get(i).value.Get())
            var armorType     : int    = $UiGlobals.GetArmorPartType(armorPartId)
            if (armorType >= 0 and armorType < ret.Count())
               ret.Set(armorType, armorPartId)
            end
         end
      end
      return ret
   end
      
   func GetFollowingArmorPartsIcon(idx : int) : string
      var ret  : string = ""
      var vec  : vector = armorParts.Get()
      if (idx >= 0 and idx < vec.Count())
         var item : string = vec.Get(idx) 
         var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(item)
         ret := (string)compUI.icon.Get()
      end
      return ret
   end
   
   func GetArmorPartsFrame(idx : int) : string
      return (string)equipFrame.Get()
   end
   
   func GetArmorPartsLabel(idx : int) : string
      var ret  : string = ""
      var vec  : vector = armorParts.Get()
      if (idx >= 0 and idx < vec.Count())
         var item : string = vec.Get(idx)
         var armorType : int = $UiGlobals.GetArmorPartType(item)      
         if (armorType == $uiEnums.ARMOR_PART_HELMET)
            ret := "carousel_armor_helmet"
         elif (armorType == $uiEnums.ARMOR_PART_SHOULDER)
            ret := "carousel_armor_shoulder"   
         elif (armorType == $uiEnums.ARMOR_PART_CHEST)
            ret := "carousel_armor_chest"   
         elif (armorType == $uiEnums.ARMOR_PART_ARMS)
            ret := "carousel_armor_arms"   
         elif (armorType == $uiEnums.ARMOR_PART_LEGS)
            ret := "carousel_armor_legs"   
         end
      end
      return ret
   end
   
   func GetFollowingItemType() : int
      var ret : int = $uiEconomy.GetItemType((string)followingItem.Get())
      return ret
   end
   
   func IsFollowItemEquip() : bool
      var ret : bool = false
      var equipState : int = $uiPlayerInfo.GetItemEquipState((string)followingItem.Get(), (int)$UserDataStorage.local_user.currentWeaponLoadoutIdx.Get())      
      if (equipState == $uiEnums.CHALLENGE_ITEM_STATE_EQUIPPED)
         ret := true
      end
      return ret
   end
   
   func GetEquipFrame() : string
      var ret : string = "off"
      if ((bool)equipFollowItem.Get())
         ret := "on"
      end
      return ret
   end
   
   func IsFollowingItemSuit() : bool
      var ret :bool = false
      if ((int)followingItemType.Get() == $uiEnums.ITEM_TYPE_ARMOR_SUIT)
         ret := true
      end
      return ret
   end 
   
   func IsFollowingItemArmor() : bool
      var ret :bool = false
      if ((int)followingItemType.Get() == $uiEnums.ITEM_TYPE_ARMOR)
         ret := true
      end
      return ret
   end
   
   func GetIsItemsVisible() : bool
      return GetChallengeItem() != ""
   end
   
end

class UiChallengesPopupStatsVM : UiChallengesStatsVM
   var isVisible           : ObservableProperty    = $OM.Property(false)
   
   // layout variables
   var contentWidth        : ObservableProperty    = $OM.Property(300.0)
   var contentHeight       : ObservableProperty    = $OM.Property(300.0)
   
   var headingYPos         : ObservableProperty    = $OM.Property(0.0)
   var ranksYPos           : ObservableProperty    = $OM.Property(0.0)
   var progressYPos        : ObservableProperty    = $OM.Property(0.0)
   var itemsYPos           : ObservableProperty    = $OM.Property(0.0)
   var closeButtonYPos     : ObservableProperty    = $OM.Property(0.0)
   
   var wgt                 : UiWidget
   
   func InvalidateSize()
      if (wgt != null)
         var content : UiWidget = (UiWidget)wgt.GetWidget("content")
       
         var currentYPos : float = 0
         headingYPos.Set(currentYPos)
         // hack (import problem)
         currentYPos := 156 //currentYPos + content.Widgets.heading.height
         
         if ((bool)isRanksVisible.Get())
            ranksYPos.Set(currentYPos)
            var bound : params = content.Widgets.ranks.GetBoundingRect()
            currentYPos := currentYPos + bound.y2
         end    
         
         if ((bool)isProgressVisible.Get())
            progressYPos.Set(currentYPos)
            var bound : params = content.Widgets.progress.GetBoundingRect()
            currentYPos := currentYPos + bound.y2
         end           
         
         if ((bool)isItemsVisible.Get())
            itemsYPos.Set(currentYPos)
            currentYPos := currentYPos + content.Widgets.items.height
         end           
         
         closeButtonYPos.Set(currentYPos)
         currentYPos := currentYPos + content.Widgets.closeButton.height
                  
         contentHeight.Set(currentYPos + 1)
         contentWidth.Set(wgt.Widgets.content.closeButton.width + 4)
         challengeComplete.Invalidate()
         goldAnim.Invalidate()
      end
   end
      
   func GetContentSize() : params
      var ret : params
      
      ret.width   := (float)contentWidth.Get()
      ret.height  := (float)contentHeight.Get()
            
      return ret
   end
   
end

class UiChallengesPopup : UiWidgetContainer
   handle OnBindingsActivate // ()
      GetDC().UpdateSize()
   end
   
   func ShowPopup()
      GetDC().ShowPopup()
   end

   func HidePopup()
      GetDC().HidePopup()
   end
end

class UiChallengesPopupVM
   var isVisible           : ObservableProperty          = $OM.Property(false)
   var clientAreaWidth     : ObservableProperty          = $OM.Property(1)
   var clientAreaHeight    : ObservableProperty          = $OM.Property(1)
   var challengeStats      : UiChallengesPopupStatsVM    = new UiChallengesPopupStatsVM()
   var wgt                 : UiWidgetContainer           = null

   func Init(p : params)
      wgt := p.widget
      challengeStats.wgt := p.widget.GetWidget("content")
      
      var challengeItemId  : string 
      var challengeId      : string 
      if (!IsVoid(p.challengeItemId))
         challengeItemId := p.challengeItemId
      end      
      if (!IsVoid(p.challengeId))
         challengeId := p.challengeId
      end      
      challengeStats.Init(challengeItemId, challengeId)
      //ShowPopup() : 0.4, DELAY_SHOW
   end
            
   func Term()
      challengeStats.Term()
      //delay kill, this, DELAY_SHOW
   end   
      
   func ShowPopup()
      isVisible.Set(true)
      challengeStats.isVisible.Set(true)
      UpdateSize()
      wgt.Widgets.content.StartDefaultBlinking(0, 0.5)
   end

   func HidePopup()
      Term()
      isVisible.Set(false)
   end
   
   func UpdateSize()
      challengeStats.InvalidateSize()      
      // popup-only function
      //wgt.InvalidateSize()
   end      
end
