import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.user_data
import ssl.hf2p.ui_globals

class UiPlayerInfoPanel : UiWidgetContainer

handle OnEnteringState("Visible")
   Props.visible := true
   GotoAndPlay("fadeIn")
   StartDefaultBlinking(10.0/35.0)
end   

handle OnEnterState("Visible")
end

handle OnEnteringState("Hidden")
   Props.visible := true
   GotoAndPlay("fadeOut")
end   

handle OnEnterState("Hidden")
end
end

class UiPlayerInfoPanelBar : UiWidgetContainer
   var blinkStartScale  : float = 0
   var maxTime          : float = 0.4
   var hasCounterVar    : bool  = false 
      
   func OnAddXpAnim(p : params) : bool
      
      var tweenParm:params
      
      tweenParm.propName   := "counterVal"
      tweenParm.duration   := 2
      tweenParm.fadeType   := "linear"
      tweenParm.startVal   := 0         
      tweenParm.endVal     := 1
      AddTweenCb("counterValTween", tweenParm)
      hasCounterVar := true
      return true
   end
   
   func OnAddXpNoAnim(p : params) : bool
      
      var tweenParm:params
      
      tweenParm.propName   := "counterVal"
      tweenParm.duration   := 2
      tweenParm.fadeType   := "linear"
      tweenParm.startVal   := 0         
      tweenParm.endVal     := 1
      AddTweenCb("counterValTween", tweenParm)
      counterValTween("complete")
      return true
   end
   
   func OnPostmatchSkip(p : params) : bool
      RemTweens()
      if (hasCounterVar)
         counterValTween("complete")
      end
      return true
   end
   
   func counterValTween(updType:string)
      var p : params
      p.value := Props.counterVal 
      p.updType := updType
      GenerateEvent("#XpBarUpdate", p)
   end
   
   func BlinkOverride(_phase : int, _dt : float) : bool
      var ret :  bool = false
      if (_dt > maxTime)
         ret := true
      end
      
      if (_phase == 0)
         blinkStartScale := Props.scaleX
      elif (_phase == 1)
         var tmpScale : float = _dt / maxTime
         if (_dt >= 0)
            tmpScale := $root.sqrt(tmpScale)
         else 
            tmpScale := 0
         end
         
         if (tmpScale > 1)
            tmpScale := 1.0
         end
         if (tmpScale < 0)
            tmpScale := 0.0
         end
         //tmpScale := tmpScale * tmpScale
         tmpScale       := blinkStartScale * tmpScale         
         Props.scaleX := tmpScale
      elif (_phase == 2)
         Props.scaleX := blinkStartScale
      end      
      return ret
   end   
end

class UiPlayerInfoPanelVM
   var curLvl            : ObservableProperty = $OM.Calculated(this, "GetCurLvl")
   var curLvlName        : ObservableProperty = $OM.Calculated(this, "GetCurLvlName")
   var nxtLvl            : ObservableProperty = $OM.Calculated(this, "GetNxtLvl")
   var nxtLvlName        : ObservableProperty = $OM.Calculated(this, "GetNxtLvlName")
   var progress          : ObservableProperty = $OM.Calculated(this, "GetProgress")
   var curRankIcon       : ObservableProperty = $OM.Calculated(this, "GetCurRankIcon")
   var nextRankIcon      : ObservableProperty = $OM.Calculated(this, "GetNextRankIcon")
   var isProcessing      : ObservableProperty = $OM.Property(false)
   var progressUpdating  : ObservableProperty = $OM.Property(0)
   var curLvlUpdating    : ObservableProperty = $OM.Property(0)
   var nextLvlUpdating   : ObservableProperty = $OM.Property(0)
   var curLvlIdUpdating  : ObservableProperty = $OM.Property("")
   var nextLvlIdUpdating : ObservableProperty = $OM.Property("")
   var boostTint1        : ObservableProperty = $OM.Calculated(this, "GetBoostTint1")  
   var boostTint2        : ObservableProperty = $OM.Calculated(this, "GetBoostTint2")
   var enableTechBtn     : ObservableProperty = $OM.Property(false)
   
   func UiPlayerInfoPanelVM()
      curLvl.Get()
      curLvlName.Get()
      nxtLvl.Get()
      nxtLvlName.Get()
      progress.Get()
   end
   
   func OnPostmatchStarted(p : params) : bool
      progressUpdating.Set($root.pregameLevelProgress * 500 + 1)
      curLvlUpdating.Set($root.pregameLevel)
      nextLvlUpdating.Set($root.pregameLevel + 1)
      curLvlIdUpdating.Set($root.pregameLevelId)
      nextLvlIdUpdating.Set($root.pregameLevelNextId)
      isProcessing.Set(true)
      return false
   end
   
   func OnPostmatchSkip(p : params) : bool
      isProcessing.Set(false)
      return false
   end
   
   func XpBarUpdate(p : params) : bool
      var frame : int
      var oldXp : float = $root.pregameLevelProgress
      var newXp : float = (float)$UserDataStorage.local_user.level_progress.Get()
      var oldLvl : int = $root.pregameLevel
      var newLvl : int = (int)$UserDataStorage.local_user.level.Get()
      var oldLvlId : string = $root.pregameLevelId
      var newLvlId : string = (string)$UserDataStorage.local_user.level_id.Get()
      var oldLvlNextId : string = $root.pregameLevelNextId
      var newLvlNextId : string = (string)$UserDataStorage.local_user.level_next_id.Get()
      if oldLvl == newLvl
         frame := (int)(((newXp - oldXp) * p.value + oldXp) * 500 + 1)
         progressUpdating.Set(frame)
      else
         var firstPart : float = (1 - oldXp) / (1 - oldXp + newXp)
         var secondPart : float = 1 - firstPart
         if p.value < firstPart
            frame := (int)((p.value * (1 - oldXp) / firstPart + oldXp) * 500 + 1)
            progressUpdating.Set(frame)
            curLvlUpdating.Set(oldLvl)
            nextLvlUpdating.Set(oldLvl + 1)
            curLvlIdUpdating.Set(oldLvlId)
            nextLvlIdUpdating.Set(oldLvlNextId)
         else 
            if secondPart > 0
               frame := (int)((p.value - firstPart) * newXp / secondPart * 500 + 1)
            else
               frame := 1
            end
            progressUpdating.Set(frame)
            curLvlUpdating.Set(newLvl)
            nextLvlUpdating.Set(newLvl + 1)
            curLvlIdUpdating.Set(newLvlId)
            nextLvlIdUpdating.Set(newLvlNextId)
         end
      end
      if (p.updType == "complete")
         isProcessing.Set(false)
      end
      return true
   end
   
   func GetCurLvl() : *
      var ret : int = 0
      if isProcessing.Get() == true 
         ret := (int)curLvlUpdating.Get()
      else
         ret := (int)$UserDataStorage.local_user.level.Get()
      end
      return ret
   end

   func GetCurLvlName() : *
      var lvl_id : string = ""
      if isProcessing.Get() == true 
         lvl_id := (string)curLvlIdUpdating.Get()
      else
         lvl_id := (string)$UserDataStorage.local_user.level_id.Get()
      end
      var uiComp  : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(lvl_id)
      var ret     : string          = (string)uiComp.name.Get()
      return ret
   end

   func GetNxtLvl() : *
      var ret : int = 0
      if isProcessing.Get() == true 
         ret := (int)nextLvlUpdating.Get()
      else
         ret := (int)$UserDataStorage.local_user.level_next.Get()
      end
      return ret
   end

   func GetNxtLvlName() : *
      var lvl_id : string = ""
      if isProcessing.Get() == true 
         lvl_id := (string)nextLvlIdUpdating.Get()
      else
         lvl_id := (string)$UserDataStorage.local_user.level_next_id.Get()
      end
      var uiComp  : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(lvl_id)
      var ret     : string          = (string)uiComp.name.Get()
      return ret
   end
   
   func GetProgress() : *
      var ret :  int = 0
      if isProcessing.Get() == true
         ret := (int)progressUpdating.Get()
      else
         ret := (int)((float)$UserDataStorage.local_user.level_progress.Get() * 500 + 1)
      end
      return ret
   end
   
   func GetCurRankIcon() : string
      var lvl_id : string = ""
      if isProcessing.Get() == true 
         lvl_id := (string)curLvlIdUpdating.Get()
      else
         lvl_id := (string)$UserDataStorage.local_user.level_id.Get()
      end
      var uiComp  : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(lvl_id)
      var ret     : string          = (string)uiComp.icon.Get()
      return ret
   end
   
   func GetNextRankIcon() : string
      var lvl_id : string = ""
      if isProcessing.Get() == true 
         lvl_id := (string)nextLvlIdUpdating.Get()
      else
         lvl_id := (string)$UserDataStorage.local_user.level_next_id.Get()
      end
      var uiComp  : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(lvl_id)
      var ret     : string          = (string)uiComp.icon.Get()
      return ret
   end
   
   func GetBoostTint1() : params
      var p : params
      p.r  := 225
      p.g  := 162
      p.b  := 38
      return p
   end
   
   func GetBoostTint2() : params
      var p : params
      p.r  := 68
      p.g  := 195
      p.b  := 233
      return p
   end   
end