import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.user_data
import ssl.hf2p.ui_globals
import ssl.hf2p.engine_ctrl

class UiRacePanel : UiWidgetContainer

handle OnEnteringState("Visible")
   /*
   Props.visible         := true
   Props.mouseEnabled    := true
   Props.mouseChildren   := true
   GotoAndPlay("fadeIn")
   StartDefaultBlinking(12.0/35.0)
   */
end   

handle OnEnterState("Visible")
end

handle OnEnteringState("Hidden")
   /*
   Props.visible         := true
   Props.mouseEnabled    := false
   Props.mouseChildren   := false
   GotoAndPlay("fadeOut")
   */
end   

handle OnEnterState("Hidden")
end

end

class UiRacePanelVM
   func ChangeToElite(p : params) : bool
      if (CanChangeRace())
         $UiGlobals.async_operations.user_set_race.Start($uiEnums.PLAYER_RACE_COVENANT)
      end
      return true
   end
   
   func ChangeToSpartan(p : params) : bool
      if (CanChangeRace())
         $UiGlobals.async_operations.user_set_race.Start($uiEnums.PLAYER_RACE_SPARTAN)
      end
      return true
   end
   
   func SwitchRace(p : params) : bool
      if (CanChangeRace())
         if ((int)$UserDataStorage.local_user.race.Get() == $uiEnums.PLAYER_RACE_SPARTAN)
            $UiGlobals.async_operations.user_set_race.Start($uiEnums.PLAYER_RACE_COVENANT)
         elif ((int)$UserDataStorage.local_user.race.Get() == $uiEnums.PLAYER_RACE_COVENANT)
            $UiGlobals.async_operations.user_set_race.Start($uiEnums.PLAYER_RACE_SPARTAN)
         end
      end
      return true
   end
   
   func CanChangeRace() : bool
      return $UiGlobals.async_operations.user_set_race.CanStart()
   end
   
   func IsChange2CovenantEnabled() : bool
      return CanChangeRace() and (int)$UserDataStorage.local_user.race.Get() == $uiEnums.PLAYER_RACE_SPARTAN
   end
   
   func IsChange2SpartanEnabled() : bool
      return CanChangeRace() and (int)$UserDataStorage.local_user.race.Get() == $uiEnums.PLAYER_RACE_COVENANT
   end
end
