import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.items_mgr
import ui.hf2p_SlidingScreens.hf2p_WeaponConf.hf2p_WeaponConf

class contentContainer_UiContent : UiWidgetContainer

var   isSlidingElement  : bool  = false
var   curPerk           : string 

func OnTacticalPackagesUpdateDisplayData(p: params): bool
   return true
end

func Init()
end

func SwitchToScreen()
   Widgets().upgradesList.SetFocus()
end

handle OnEnteringState("Initial")
   Log("ui~content", "TacticalPackages OnEntering Initial!!!")
   //GetWidgetSSL().AddTween("alpha", 0.0,     Props().adelay, "linear")
end          

handle OnEnterState("Initial")
   Log("ui~content", "TacticalPackages onEnter Initial!!!")
   Set("visible", false)            
   $hq.ShopVideoEndSafe()
end          

handle OnEnteringState("Visible")
   Log("ui~content", "TacticalPackages OnEntering VISIBLE!!!")         
   Init()         
   Set("visible", true)
   //AddTween("alpha", 1.0,     Props().adelay, "linear")
end  

handle OnEnterState("Visible")
   Log("ui~content", "TacticalPackages onEnter VISIBLE!!!")         
end

func PrepareSlide()
   if (GetStateName() != "Visible")
      SetStateName("Visible")
   end
   GenerateEvent("#OpenedTacticalPackages")
   StartDefaultBlinking(0.3)
end

func PrepareHideSlide()
   $hq.ShopVideoEndSafe()
end

func DisableSlide()
   if (GetStateName() != "Initial")
      SetStateName("Initial")
   end
end

func OnItemPurchased(p : params) : bool
   if (p.isOK)
      GenerateEvent("#OnTacticalPurchased", p)
   end
   return true
end

func SetListSelection(p : params) : bool
   Widgets().upgradesList.SetSelectionIdx(p.idx)
   return false
end

func OnBlinkItemList(p : params) : bool
   Widgets().upgradesList.SetSelectionIdx(0)
   Widgets().upgradesList.StartDefaultBlinking(0.0)
   $root.playSound("screen_rollout")
   return false
end

end

class TacticalStatsVM
   var perkItemId    : ObservableProperty = $OM.Property("")
   
   var perkDuration  : ObservableProperty = $OM.Calculated(this, "GetDuration")
   var perkCost      : ObservableProperty = $OM.Calculated(this, "GetCost")
   var perkCooldown  : ObservableProperty = $OM.Calculated(this, "GetCooldown")
   
   func TacticalStatsVM()
      
   end
   
   func GetPerkStats() : GL_ComponentConsumable
      var itemIdStr  : string = (string)perkItemId.Get()
      var   perk   :  GL_ComponentConsumable = null
      if (itemIdStr != "")
         perk :=  (GL_ComponentConsumable)$UiGlobals.componentsConsumable.Get(itemIdStr)
      end
      return perk
   end
   
   func GetDuration () : float 
      var   perk   :  GL_ComponentConsumable = GetPerkStats()
      var   ret    :  float = 0
      if (perk != null)
         ret := (float)perk.duration.Get()
      end
      return ret
   end   
   
   func GetCost () : int 
      var   perk   :  GL_ComponentConsumable = GetPerkStats()
      var   ret    :  int = 0
      if (perk != null)
         ret := (int)perk.cost.Get()
      end
      return ret
   end 
   
   func GetCooldown () : float 
      var   perk   :  GL_ComponentConsumable = GetPerkStats()
      var   ret    :  float = 0
      if (perk != null)
         ret := (float)perk.cooldown.Get()
      end
      return ret
   end
   
end

class TacticalPackagesVM : ItemShopBaseVM
   var TacticalStatsVM   : TacticalStatsVM     = new TacticalStatsVM()
   var isDescItemConsumable : ObservableProperty = $OM.Calculated(this, "GetIsDescItemConsumable")
   
   func TacticalPackagesVM()
      shopType := $uiEnums.SHOP_TYPE_TACTICAL
   end
   
   func Term(p : params)
      //mouseOverItemId.Unsubscribe(descpanelVM, "UpdateItemId")
      BaseTerm()
   end
   
   override GetIsVideoIcons //() : bool
      var ret = (bool)isDescItemConsumable.Get()
      return ret
   end
   
   func GetIsDescItemConsumable() : bool
      var ret = false
      if mouseOverItemId.Get() != ""
         ret := $UiGlobals.componentsConsumable.Exist(mouseOverItemId.Get())
      end
      return ret
   end
         
   override OnPanelButtonClicked
      Log("ui~content", "wc_OnPanelButtonClicked: " + Params2Str(p))
      if (! IsVoid(p.widget.itemType) and ! p.widget.selected)
         var itemType :  int = p.widget.itemType
         itemQuality.Set(0)
         itemCat.Set(itemType)
      end
      DoBlink()
      return false
   end
   
   override UpdateSelectedItem
      descpanelVM.itemId.Set(mouseOverItemId.Get())
      offersModuleVM.UpdateItemId((string)mouseOverItemId.Get())
      TacticalStatsVM.perkItemId.Set(mouseOverItemId.Get())
   end
   
   override GetItemList
      var ret     :  vector
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         if (! IsVoid(shop.tactical_packages) and shop.tactical_packages.Get().Count() > (int)itemQuality.Get())
            var subshop    :  GL_ShopSection = (GL_ShopSection)shop.tactical_packages.Get().Get((int)(itemQuality.Get()))
            if (! IsVoid(subshop.shelves.Get()) and subshop.shelves.Get().Count() > (int)itemCat.Get())
               var shelf      :  GL_ShopShelf   = (GL_ShopShelf)subshop.shelves.Get().Get((int)(itemCat.Get()))
               if (! IsVoid(shelf.items.Get()))
                  ret := SortShopItems(shelf.items.Get())
               end
            end
         end
      end
      return ret
   end   
   
   override GetSections
      var sections   : vector
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         if (! IsVoid(shop.tactical_packages) and shop.tactical_packages.Get().Count() > (int)itemQuality.Get())
            var subshop    :  GL_ShopSection = (GL_ShopSection)shop.tactical_packages.Get().Get((int)(itemQuality.Get()))
            var i          : int
            
            for i := 0 to subshop.shelves.Get().Count() - 1
               var shelf      : GL_ShopShelf    = (GL_ShopShelf)subshop.shelves.Get().Get(i) 
               var uiID    : string = (string)shelf.shelf_id.Get()
               var name    : string  = (string)((GL_ComponentUI)$UiGlobals.componentsUI.Get(uiID)).name.Get()
               if (name == "")
                  name := uiID
               end
               var sectionDesc : params
               sectionDesc.label    := name
               sectionDesc.is_hot   := false
               sectionDesc.has_new  := shelf.HasNewItems()
               sections.Push(sectionDesc.Clone())
            end
         end
      end
      while (sections.Count() < GetMaxSections())
         var sectionDesc : params
         sectionDesc.label    := ""
         sectionDesc.is_hot   := false
         sectionDesc.has_new  := false
         sections.Push(sectionDesc.Clone())
      end
      return sections      
   end


   func OpenedTacticalPackages(p : params) : bool
      sections.Invalidate()
      itemCategories.Invalidate()
      itemList.Invalidate()
      offersModuleVM.isWide.Set(true)
      bigIconPic.Invalidate()
      if ($UiGlobals.shop.openParams.isValid)         
         $UiGlobals.shop.openParams.isValid := false
         itemQuality.Set($UiGlobals.shop.openParams.sectionIdx)
         itemCat.Set($UiGlobals.shop.openParams.shelfIdx)
         selectedIdx.Set($UiGlobals.shop.openParams.itemIdx)
         SetListSelection($UiGlobals.shop.openParams.itemIdx)
      else
         itemCat.Set(0)
         itemQuality.Set(0)
      end
      return true
   end      

   func OnTacticalPurchased(p : params) : bool
      offersModuleVM.Go2LoadoutAfterPurchase(p.itemID)
      return true
   end
   
   override CallRenderBigVideo
      if (wgt != null and wgt.GetStateName() == "Visible" and _video != "" and _video != "unknown")
         $hq.ShopVideoEndSafe()
         $hq.ShopVideoBeginSafe(_video)
      end      
   end
end