import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_manager
import ssl.hf2p.engine_ctrl
import ssl.observables
import ssl.hf2p.ui_globals
import ui.ui_economy
import ssl.hf2p.user_data
import ui.root
import ui.libs.hf2p_SlidingScreens.hf2p_sliding_screens_lib
import ui.libs.hf2p_WeaponConf_lib.hf2p_WeaponConf_lib
import ui.libs.hf2p_ChallengesScreen_lib.hf2p_ChallengesScreen_lib

/*************************************************************
* UiItemChallengesScreen
* 
*************************************************************/
class UiItemChallengesScreen : UiSlidingScreenPageBase
   func BlinkFull()
      StartDefaultBlinking()
   end
   
   func BlinkFast()
      Widgets().challengesList.StartDefaultBlinking(0, 1.5)      
   end
   
   func ResetList()
      Widgets().challengesList.list.scrollPosition := 0
   end
end

/*************************************************************
* UiItemChallengesTabsVM
* 
*************************************************************/
class UiItemChallengesTabsVM : UiGenericShopTabsVM
   
   func UiItemChallengesTabsVM()
     // tabLabels.Invalidate()
   end
   
   override GetTabLabels//() : vector
      //hack
      var ret : vector
      if ((bool)isActive.Get())
         if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
            var shop    :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
            if (! IsVoid(shop.career))
               var i : int
               for i := 0 to shop.career.Get().Count() - 1
                  var subshop : GL_ShopSection = (GL_ShopSection)shop.career.Get().Get(i)
                  var uiID    : string = (string)subshop.section_id.Get()
                  var name    : string  = (string)((GL_ComponentUI)$UiGlobals.componentsUI.Get(uiID)).name.Get()
                  if (name == "")
                     name := uiID
                  end
                  if (name != "") 
                     var p : params
                     p.label := name
                     ret.Push(p)
                  end
               end
            end
         end
      end
      return ret
   end
   
   /*
   override GetTabLabels//() : vector
      var ret : vector
      var i : int
      for i := 0 to 4
         var p : params
         p.label := "TAB_" + (string)(i+1) + "~"
         ret.Push(p)
      end
      return ret
   end
   */
end

/*************************************************************
* UiItemChallengesLIRVM
* 
*************************************************************/
class UiItemChallengesLIRVM
   var challengeItemId  : ObservableProperty    = $OM.Property($uiEnums.TECH_EMPTY)
   var progress         : ChallengeProgressVM   = new ChallengeProgressVM()
   var tmpVar           : int                   = 0
   var tmpVar2          : ObservableProperty    = $OM.Property(0)
   var isLocked         : ObservableProperty    = $OM.Calculated(this, "GetIsLocked") 
   var wgt              : UiWidget              = null
   
   func Init(p : params)
      wgt := p.widget
      if (! IsVoid(p.challengeItemId))
         challengeItemId.Set(p.challengeItemId)
         progress.InitVM(p.challengeItemId, GetNextChallenge(), GetNextRank(), 0, IsComplete())
      end
   end
   
   func OnItemChallengeLirClicked(p : params) : bool
      var pp : params
      pp.tech := (string)challengeItemId.Get()
      wgt.GenerateEvent("#OpenTechCard", pp)
      return false
   end
   
   func GetItemComponent() : GL_ComponentItem
      var ret : GL_ComponentItem = (GL_ComponentItem)$UiGlobals.componentsItem.Get(challengeItemId.Get())
      return ret
   end
   
   func GetNextChallenge() : string
      var ret : string = GetItemComponent().GetNextChallengeId()
      return ret
   end
      
   func GetIsLocked() : bool
      var shopComp   : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(challengeItemId.Get())
      var inventComp : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(challengeItemId.Get())
      var ret        : bool                  = shopComp.IsLocked() or (int)inventComp.ownership_type.Get() != $uiEnums.ITEM_OWN_TYPE_PURCHASED
      return ret
   end
   
   func IsComplete() : bool
      var ret : bool = GetItemComponent().IsComplete()
      return ret      
   end
   
   func IsInProgress() : bool
      var ret : bool = !GetIsLocked() and !IsComplete()
      return ret
   end      
   
   func GetMedalFrame(rank : int) : string
      var ret  : string = ""
      if (rank == -1)
         ret := "gray"
      elif (rank == 0)
         ret := "bronze"
      elif (rank == 1)
         ret := "silver"
      elif (rank == 2)
         ret := "gold"
      else
         ret := "gray"
      end
      return ret
   end   
   
   func IsItemEquippedForChallenge() : bool
      var compShop   : GL_ComponentShop   = (GL_ComponentShop)$UiGlobals.componentsShop.Get(challengeItemId.Get())
      var item       : string             = compShop.GetUnlockItem()
      var equipState : int                = $uiPlayerInfo.GetItemEquipState(item)      
      var ret        : bool               = equipState == $uiEnums.CHALLENGE_ITEM_STATE_EQUIPPED
      return ret
   end
   
   func GetChallengeStateFrame() : string
      var ret  : string
      var rank : int = GetCurrentRank()
      if (rank == GetMaxRank())
         ret := "state3"
      elif (IsItemEquippedForChallenge())
         ret := "state2"
      else
         ret := "state1"
      end         
      return ret
   end
   
   func GetMaxRank() : int
      return GetItemComponent().GetChallengesCount() - 1
   end
   
   func GetCurrentRank() : int
      return GetItemComponent().GetCurrentChallengeRank()
   end
   
   func GetNextRank() : int
      var ret : int = GetItemComponent().GetNextChallengeRank()
      return ret
   end
   
   func GetId() : string
      return (string)challengeItemId.Get()
   end
   
   func GetTechLabel() : string
      var ret     : string
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(GetId())
      ret := (string)compUI.name.Get() 
      return ret
   end
   
   func GetTechIcon() : string
      var ret     : string
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(GetId())
      ret := (string)compUI.icon_med.Get() 
      return ret
   end
end

/*************************************************************
* UiItemChallengesScreenVM
* 
*************************************************************/
class UiItemChallengesScreenVM : UiSlidingScreenPageBaseVM
   var tabs          : UiItemChallengesTabsVM = new UiItemChallengesTabsVM()
   var wgt           : UiItemChallengesScreen = null 
      
   func Init(p : params)
      wgt := p.widget
      tabs.selectedTabIdx.Subscribe(this, "OnTabChange")
   end
      
   func Term()
      tabs.selectedTabIdx.Unsubscribe(this, "OnTabChange")
   end

   func ResetList()
      if (wgt != null)
         wgt.ResetList()   
      end      
   end

   func OnTabChange(_val : *)
      ResetList()
      StartBlink(false)
   end
   
   func StartBlink(_isFull : bool)
      if (wgt != null)
         if (_isFull)
            wgt.BlinkFull()
         else
            wgt.BlinkFast()
         end
      end      
   end
   
   override OnOpen // ()
      StartBlink(true)      
   end
   
   override PrepareSlide // ()
      StartBlink(true)
   end
   
   func GetSelectedTabIdx() : int
      return (int)tabs.selectedTabIdx.Get()
   end
         
   func GetItemChallenges() : vector
      isActive.Get()
            
      var ret : vector
      if (! IsVoid($UiGlobals.shop.race_shops.Get()) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         if (!IsVoid(shop) and shop!=null and ! IsVoid(shop.career.Get()) and shop.career.Get().Count() > GetSelectedTabIdx())
            var subshop : GL_ShopSection = (GL_ShopSection)shop.career.Get().Get(GetSelectedTabIdx())
            if (! IsVoid(subshop.shelves))
               var i : int
               for i := 0 to subshop.shelves.Get().Count() - 1
                  var shelf      :  GL_ShopShelf   = (GL_ShopShelf)subshop.shelves.Get().Get(i)
                  if (! IsVoid(shelf.items.Get()))
                     var j : int
                     for j := 0 to shelf.items.Get().Count() - 1
                        var techId : string = (string)shelf.items.Get().Get(j).value.Get()
                        if (techId != $uiEnums.TECH_EMPTY and techId != $uiEnums.TECH_COMING)
                           var p : params
                           p.challengeItemId := techId
                           ret.Push(p)
                        end
                     end   
                  end
               end   
            end
         end
      end
      tabs.isActive.Set(isActive.Get())
      return ret      
   end
end
