import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_manager
import ssl.hf2p.engine_ctrl
import ssl.observables
import ssl.hf2p.ui_globals
import ui.ui_economy
import ssl.hf2p.user_data
import ui.root

class animatedContent_contentContainer_UiContent_3 : UiWidgetContainer

func FillChallengeList()
	var challengesVec:vector
	var i: int
	for i := 0 to 5                     
		var listEntry:params		
		listEntry.label         := "challenge_" + (string)i		         
		listEntry.progress      := 0.5
		listEntry.img           := "allUpgrade"
		challengesVec.Push(listEntry)
    end    
    Widgets().screenChallenge.challengeListCont.challengeList.SetData(challengesVec)
end

func FillChallengeInfo()
   var challengesInfoVec:vector
	var i: int
	for i := 0 to 3                     
      var listEntry:params		
      listEntry.label         := "challengeInfo_" + (string)i		         
      listEntry.curProgress   := 400
      listEntry.maxValue      := 500
      listEntry.scale         := 0.8
      challengesInfoVec.Push(listEntry)
   end    
   Widgets().screenChallenge.challengeInfo.challengeProgressList.SetData(challengesInfoVec)
end

func FillDesc()
   Widgets().screenChallenge.challengeDesc.challengeIcn.pic := "boost_cooldown"
   Widgets().screenChallenge.challengeDesc.textField1 := "challengeName"
   Widgets().screenChallenge.challengeDesc.textField2 := "desc1"
   Widgets().screenChallenge.challengeDesc.textField3 := "desc2"
end

func FillRewardCont()
   Widgets().screenChallenge.rewardCont.rewardHeader := " Header"
   Widgets().screenChallenge.rewardCont.rewardDesc := " Desc"
   Widgets().screenChallenge.rewardCont.rewardAttach.pic := "iconHelmet"  
end

handle OnEnteringState("Initial")
end   

handle OnEnterState("Initial")
   Set("visible", false)            
end   

handle OnEnteringState("Visible")
   Set("visible", true)
   //FillChallengeList()
   //FillChallengeInfo()
   //FillDesc()
   FillRewardCont()
end   

handle OnEnterState("Visible")
   Log("ui~content", "hf2p_ChallengesScreen OnEnter (Visible state)")	  
end

func PrepareSlide()
   if (GetStateName() != "Visible")
      SetStateName("Visible")
      GenerateEvent("#OpenChallengeScr")
   end
end

func PrepareHideSlide()
end

func DisableSlide()
   if (GetStateName() != "Initial")
      SetStateName("Initial")
   end
end

func SwitchToScreen()
end

end

class ChallengesVM
   var challengeList         : ObservableProperty = $OM.Calculated(this, "GetChallengeList")
   var duration              : ObservableProperty = $OM.Property("daily")
   var selectedChallengeIdx  : ObservableProperty = $OM.Property(0)
   var selectedChallenge     : ObservableProperty = $OM.Calculated(this, "GetSelectedChallenge")
   var overChallengeIdx      : ObservableProperty = $OM.Property(0)
   var overChallenge         : ObservableProperty = $OM.Calculated(this, "GetMouseOverChallenge")
   
   var descPanelVM           : DescChallengesVM    = new DescChallengesVM()
   var infoPanelVM           : InfoChallengesVM    = new InfoChallengesVM()
   
   func OpenChallengeScr(p : params) : bool
      duration.Invalidate()
      challengeList.Invalidate()
      selectedChallengeIdx.Set(0)
      descPanelVM.challengeId.Set((string)GetSelectedChallenge().id.Get())
      infoPanelVM.challengeCounters.Set(GetSelectedChallenge().counters.Get())
      return false
   end
   
   func GetChallengeList() : vector
      var ret : vector
      var filter : string = (string)duration.Get()
      var challenges : UD_Challenges = $UserDataStorage.local_user.challenges
      if (filter == $uiEnums.CHALLENGE_DURATION_DAILY)
         ret := challenges.challenges_daily.Get()
      elif (filter == $uiEnums.CHALLENGE_DURATION_WEEKLY)   
         ret := challenges.challenges_weekly.Get()
      elif (filter == $uiEnums.CHALLENGE_DURATION_MONTHLY)   
         ret := challenges.challenges_monthly.Get()
      end   
      return ret
   end
   
   func GetSelectedChallenge() : UD_Challenge
      var challenge    : UD_Challenge = null      
      var challengeVec   : vector = challengeList.Get()
      var idx : int = (int)selectedChallengeIdx.Get()
      if (idx >= 0 and idx < challengeVec.Count())  
         challenge := (UD_Challenge)challengeVec.Get(idx)
      end
      return challenge
   end
   
   func GetMouseOverChallenge() : UD_Challenge
      var challenge    : UD_Challenge = null
      var challengeVec   : vector = challengeList.Get()
      var idx : int = (int)overChallengeIdx.Get()
      if (idx >= 0 and idx < challengeVec.Count())  
         challenge := (UD_Challenge)challengeVec.Get(idx)
      end
      return challenge
   end
   
   func onDurationBtnClick(p : params) : bool
      if (! IsVoid(p.widget.duration) and ! p.widget.selected)
         var challengeDuration : string = p.widget.duration
         duration.Set(challengeDuration)
      end
      return false
   end   
   
   func onChallengeListClick(p : params) : bool
      selectedChallengeIdx.Set(p.index)
      var challengeId : string = (string)GetSelectedChallenge().id.Get()
      var challengeCounters : vector = GetSelectedChallenge().counters.Get()
      descPanelVM.challenge.Set(GetSelectedChallenge())
      descPanelVM.challengeId.Set(challengeId)
      infoPanelVM.challengeCounters.Set(challengeCounters)
      return false
   end
   
   func onChallengeListOver(p:params) : bool
      overChallengeIdx.Set(p.index)
      var overChallengeId : string = (string)GetMouseOverChallenge().id.Get()
      var overChallengeCounters : vector = GetMouseOverChallenge().counters.Get()
      descPanelVM.challengeId.Set(overChallengeId)
      infoPanelVM.challengeCounters.Set(overChallengeCounters)
      return false
   end
   
end

class ChallengesLIRVM
   var wgt              : UiWidget = null
   var challenge        : ObservableProperty = $OM.Property(null)
   var challengeName    : ObservableProperty = $OM.Calculated(this, "GetChallengeName")
   var challengeIcon    : ObservableProperty = $OM.Calculated(this, "GetChallengeIcon")
   var challengeScale   : ObservableProperty = $OM.Calculated(this, "GetChallengeProgress") 
   
   func Init(p : params)
      wgt := p.widget
      if (! IsVoid(p.challenge))
         var udChallenge : UD_Challenge = p.challenge
         challenge.Set(udChallenge)
      end
   end
   
   func GetChallenge() : UD_Challenge
      var ret : UD_Challenge = null
      if (challenge != null)
         ret := (UD_Challenge)challenge.Get()
      end
      return ret
   end
   
   func GetChallengeName() : string
      var ret : string = ""
      if (GetChallenge() != null)
         var challengeId : string = (string)GetChallenge().id.Get()
         var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(challengeId)
         ret := (string)compUI.name.Get() // challengeId
      end
      return ret
   end
   
   func GetChallengeIcon() : string
      var ret : string = ""
      if (GetChallenge() != null)
         var challengeId : string = (string)GetChallenge().id.Get()
         var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(challengeId)
         ret := (string)compUI.icon.Get() // "boost_cooldown"
      end
      return ret
   end
   
   func GetChallengeProgress() : float
      var ret : float = 1.0
      if (GetChallenge() != null)
         ret := (float)GetChallenge().progress.Get()
      end
      return ret
   end
   
end

class DescChallengesVM
   var challenge             : ObservableProperty = $OM.Property(null)
   var challengeId           : ObservableProperty = $OM.Property("")
   var challengeName         : ObservableProperty = $OM.Calculated(this, "GetName")
   var challengeIcon         : ObservableProperty = $OM.Calculated(this, "GetIcon")
   var challengeDesc         : ObservableProperty = $OM.Calculated(this, "GetDesc")
   var challengeShortDesc    : ObservableProperty = $OM.Calculated(this, "GetShortDesc")
   
   func DescChallengesVM()
   end
   
   func GetChallenge() : UD_Challenge
      var ret : UD_Challenge = null
      if (challenge.Get() != null)
         ret := (UD_Challenge)challenge.Get()
      end
      return ret
   end
   
   func GetName () : string
      var ret : string
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get((string)challengeId.Get())
      ret :=  (string)compUI.name.Get()
      return ret
   end
   
   func GetIcon () : string
      var ret : string
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get((string)challengeId.Get())
      ret := (string)compUI.icon.Get()
      return ret
   end
   
   func GetDesc () : string
      var ret : string
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get((string)challengeId.Get())
      ret := (string)compUI.desc.Get()
      if (ret != "")
         ret := ret
         
         var challengeVar  : UD_Challenge = GetChallenge()
         if (challengeVar != null)
            var i             : int
            var countersCount : int = challengeVar.GetCountersCount()
            for i := 0 to countersCount - 1
               var maxVal  : int = -1
               var counter : UD_ChallengeCounter = challengeVar.GetCounter(i)
               if (counter != null)
                  maxVal := (int)counter.value_max.Get()
               end         
               ret := ret + "," + (string)maxVal
            end            
         end
      end
      return ret
   end
   
   func GetCountersCount() : int
      var challengeVar  : UD_Challenge = GetChallenge()
      var ret           : int = 0
      if (challengeVar != null)
         ret := challengeVar.counters.Get().Length()
      end
      return ret
   end
   
      
   func GetShortDesc () : string
      var ret : string
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get((string)challengeId.Get())
      ret := (string)compUI.desc_short.Get()
      return ret
   end
   
end

class InfoChallengesVM
   var challengeCounters           : ObservableProperty = $OM.Property(null)
end

class ChallengeCountersLIRVM
   var challengeCounter           : ObservableProperty = $OM.Property(null)
   var counterType                : ObservableProperty = $OM.Calculated(this, "GetCounterType")
   var counterLabel               : ObservableProperty = $OM.Calculated(this, "GetCounterLabel")
   var counterCur                 : ObservableProperty = $OM.Calculated(this, "GetCounterCurValue")
   var counterMax                 : ObservableProperty = $OM.Calculated(this, "GetCounterMaxValue")
   var counterScale               : ObservableProperty = $OM.Calculated(this, "GetProgressBarScale")
   
   func Init(p : params)
      var test :  params = p
      if (! IsVoid(p.challengeCounter))
         var udChallengeCounter : UD_ChallengeCounter = p.challengeCounter
         challengeCounter.Set(udChallengeCounter)
      end
   end
   
   func GetCounter() : UD_ChallengeCounter
      var ret : UD_ChallengeCounter = null
      if (challengeCounter != null)
         ret := (UD_ChallengeCounter)challengeCounter.Get()
      end
      return ret
   end
   
   func GetCounterType()
      
   end
   
   func GetCounterLabel() : string
      var ret : string = ""
      if (GetCounter() != null)
         var counterId  : string          = (string)GetCounter().id.Get()
         var compUI     : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(counterId)
         var desc       : string          = (string)compUI.desc.Get()
         if (desc != "")
            ret := desc + "," + (string)GetCounterMaxValue()            
         end
      end
      return ret
   end
   
   func GetCounterCurValue() : int
      var counterValue : int = 0
      if (GetCounter() != null)
         counterValue := (int)GetCounter().value.Get()
      end
      return counterValue
   end
   
   func GetCounterMaxValue() : int
      var counterValue : int = 0
      if (GetCounter() != null)
         counterValue := (int)GetCounter().value_max.Get()
      end
      return counterValue
   end
   
   func GetProgressBarScale() : float
      var ret : float = 1.0
      if (GetCounter() != null)
         ret := (float)GetCounter().progress.Get()
      end
      return ret
   end
   
end
