import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.items_mgr
import ui.root

class UiWcWpnList : UiWidgetContainer

var   itemType    : string = ""
var   maxSlots    : int    = 9
var   curSlots    : int    = 9
var   slotOffset  : int    = 0
var   elemList    : vector   
var   minWidth    : float = 964


func SetMinWidth(_minWidth: float = -1)
minWidth := _minWidth
end

func ArrangeSlots()
   Log("ui~wc_WpnList", "ArrangeSlots")
   var hspace0    : float  = 64
   var hspace     : float  = 40
   var itemWidth  : float  = Widgets.item1.width //+ hspace
   //itemWidth := 170

   var x0   : float = 86
   var curx : float = x0
   var y0   : float = 5
   var i    : int
   var w    : float = itemWidth / 2.0

   for i := 1 to maxSlots
      var slot : * = GetSlot(i)
      if (slot.Props.visible)
         w := slot.Widgets.wpnSlot.textWidth
         
         if (i > 1)
            curx  := curx
         else
            curx  := hspace0 / 2
         end
         //curx := curx + w / 2  + hspace / 2
         slot.Props.x      := curx
         slot.Props.y      := y0
         
         //slot.Widgets.wpnSlot.selectedX := -20
         slot.Widgets.wpnSlot.selectedX := -30
         slot.Widgets.wpnSlot.selectedSize := 60 + w //curx - itemWidth / 2.0
         
         var dataIdx : int = i - 1 
         var hasNew  : bool = false
         if (dataIdx >= 0 and dataIdx < elemList.Count())
            var p : params = elemList.Get(dataIdx)
            if (! IsVoid(p.has_new))
               hasNew := p.has_new
            end
         end
         slot.Widgets.wpnSlot.newItemBookmark.visible := hasNew
         
         curx  := curx + w + hspace        
      else
         break
      end
   end

   var totalW : float = (curx)
   if (minWidth != -1)
      if (totalW < minWidth) 
         totalW := minWidth
      end
   end
   //Widgets.itemBack.scaleX := totalW / 1050.0
   Widgets.itemBack._width := totalW
end

func FillSlotWithElements(_selection: int = -1)
   var i             : int
   var slotIdx       : int = 1
   var anySelected   : bool = false
   var enable        : bool 
   for i := 0 to elemList.Count() - 1
      var isSelected : bool   = i == _selection
      if (isSelected)
         anySelected := true
      end
      if (IsVoid(elemList.Get(i).enable))
         enable := true
      else
         enable := elemList.Get(i).enable      
      end
      GetSlot(slotIdx).Init(elemList.Get(i).id, elemList.Get(i).name, slotIdx + slotOffset, isSelected, enable)
      slotIdx := slotIdx + 1
      if (slotIdx > curSlots)
         break
      end         
   end
   while (slotIdx <= curSlots)
      GetSlot(slotIdx).Init("", "", slotIdx + slotOffset, false)
      slotIdx := slotIdx + 1
   end   

   if (! anySelected and elemList.Count() > 0)   
      GetSlot(1).Init(elemList.Get(0).id, elemList.Get(0).name, 0 + slotOffset, true)
   end
   ArrangeSlots()
end

func GetSlot(idx:int):*
   return GetWidget("item" + idx)
end

func SetListData(_elems: vector, _selection: int = -1)
   itemType := ""
   elemList := _elems
   ArrangeSlots()
   FillSlotWithElements(_selection)
end

func CustomSet(propName : string, propVal : *) : bool
   if (propName == "items")
      var prevCount : int = elemList.Count()
      itemType := ""
      if (propVal != null and !IsVoid(propVal))
         elemList := propVal
      else
         elemList.Clear()
      end
      ArrangeSlots()
      FillSlotWithElements(0)
      if (prevCount != elemList.Count())
         StartDefaultBlinking(0.0, 3.0)
      end
      ArrangeSlots():0
      return true
   end
   return false
end

end
