import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ui.ui_party_monitor
import ui.hf2p_SlidingScreens.hf2p_SlidingScreens
import ssl.observables
import ssl.lib.ui.bindings.bindings
import ssl.hf2p.ui_globals
import ui.hf2p_SlidingScreens.hf2p_SlidingScreens

class UiSlidingScreensLoot : UiSlidingScreens

override Init
   var flowButtonParm   : params
   
   isLooping := true
   flowElements.Clear()
   
   Widgets().background.visible    := true
   Widgets().flowButtons.Props().y := 145
   
   totalElems := 1
   
   flowButtonParm.label       := "main_loot_box"
   flowButtonParm.idx         := 0
   flowButtonParm.name        := $uiEnums.SLIDING_PAGE_LOOTBOX
   flowButtonParm.showFrame   := true
   flowButtonParm.showBg      := true   
   flowElements.Push(flowButtonParm.Clone())      

   var startingIndex : int = GetScreenIndexByName(startingScreen)
   if (startingIndex < 0)
      startingIndex := 0
   end
   GetDC().UpdateCloseBtnVisible()
   Widgets().flowButtons.SetMaxWidth(720)
   Widgets().flowButtons.InitElements(flowElements, startingIndex)
end

override HasLobbyMode // () : bool
   return false
end

end
