import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ui.ui_party_monitor
import ui.hf2p_SlidingScreens.hf2p_SlidingScreens
import ssl.observables
import ssl.lib.ui.bindings.bindings
import ssl.hf2p.ui_globals
import ui.hf2p_SlidingScreens.hf2p_SlidingScreens
import ui.hf2p_SlidingScreens.hf2p_profile_screen.hf2p_profile_screen

class UiSlidingScreensMainMenu : UiSlidingScreens

var isLeaveLobbyBtnVisible : ObservableProperty = $OM.Property(false)

override Init
   var flowButtonParm   : params
   
   isLooping := true
   flowElements.Clear()
   
   Widgets().background.visible     := true
   Widgets().flowButtons.Props().y  := 145
   isLeaveLobbyBtnVisible.Set(false)
   
   totalElems := 15
   
   if (GetViewMode() == $uiEnums.SLIDING_SCREENS_MODE_SHOP_SMALL and $uiPartyMonitor.GetLobbyMode() != "")
      viewMode := $uiEnums.SLIDING_SCREENS_MODE_SHOP
   end
   
   if (GetViewMode() == $uiEnums.SLIDING_SCREENS_MODE_SHOP or GetViewMode() == "")  
      isLeaveLobbyBtnVisible.Set(true)
      
      if ($uiMatchmaking.GetIsRematch())
         flowButtonParm.label       := "main_postmatch"
         flowButtonParm.idx         := 10
         flowButtonParm.name        := $uiEnums.SLIDING_PAGE_POSTMATCH
         flowButtonParm.showFrame   := false
         flowButtonParm.showBg      := false   
         flowElements.Push(flowButtonParm.Clone())
      end
      /*
      flowButtonParm.label       := "carousel_restock"
      flowButtonParm.idx         := 11
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_RESTOCK
      flowButtonParm.showBg      := true
      flowButtonParm.showFrame   := false
      flowElements.Push(flowButtonParm.Clone())
      */
      flowButtonParm.label       := "main_weapons"
      flowButtonParm.idx         := 0
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_WEAPONS
      flowButtonParm.showFrame   := true
      flowButtonParm.showBg      := true   
      flowElements.Push(flowButtonParm.Clone())

      flowButtonParm.label       := "main_tactical_packages"
      flowButtonParm.idx         := 1
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_TACTICAL
      flowButtonParm.showFrame   := true
      flowButtonParm.showBg      := true   
      flowElements.Push(flowButtonParm.Clone())

      flowButtonParm.label       := "main_armory"
      flowButtonParm.idx         := 2
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_ARMORY
      flowButtonParm.showBg      := false
      flowButtonParm.showFrame   := false
      flowElements.Push(flowButtonParm.Clone())

      if ($uiPartyMonitor.GetLobbyMode() == "")
         flowButtonParm.label    := "carousel_spartan"
         flowButtonParm.idx      := 9
         flowButtonParm.name     := $uiEnums.SLIDING_PAGE_SPARTAN
         flowButtonParm.showBg   := false
         flowButtonParm.showFrame:= false
         flowButtonParm.hasConfirmationOnClose := true
         flowElements.Push(flowButtonParm.Clone())      
      
         //flowButtonParm.label    := "carousel_bundles"
         //flowButtonParm.idx      := 3
         //flowButtonParm.name     := "Bundles"
         //flowButtonParm.showFrame:= true
         //flowButtonParm.showBg   := true   
         //flowElements.Push(flowButtonParm.Clone())
      end
      
      if ($uiPartyMonitor.GetLobbyMode() != "")
         flowButtonParm.label    := "lobby_lobby"
         flowButtonParm.idx      := 4
         flowButtonParm.name     := $uiEnums.SLIDING_PAGE_LOBBY
         flowButtonParm.showFrame:= false
         flowButtonParm.showBg   := true   
         flowElements.Push(flowButtonParm.Clone())
         isLooping               := false
      end
   elif (GetViewMode() == $uiEnums.SLIDING_SCREENS_MODE_PROFILE)
      flowButtonParm.label       := "main_profile"
      flowButtonParm.idx         := 5
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_PROFILE
      flowButtonParm.showFrame   := true
      flowButtonParm.showBg      := true //false   
      flowElements.Push(flowButtonParm.Clone())
      /*
      flowButtonParm.label       := "main_profile_present"
      flowButtonParm.idx         := 14 
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_PROFILE_PRESENT
      flowButtonParm.showFrame   := true
      flowButtonParm.showBg      := true   
      flowElements.Push(flowButtonParm.Clone())
      */
   elif (GetViewMode() == $uiEnums.SLIDING_SCREENS_MODE_CHALLENGES)
      flowButtonParm.label       := "carousel_btn_item_challenges"
      flowButtonParm.idx         := 13
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_ITEM_CHALLENGES
      flowButtonParm.showFrame   := true
      flowButtonParm.showBg      := true   
      flowElements.Push(flowButtonParm.Clone())
      /*
      flowButtonParm.label       := "carousel_btn_challenges"
      flowButtonParm.idx         := 6
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_CHALLENGES
      flowButtonParm.showFrame   := true
      flowButtonParm.showBg      := true   
      flowElements.Push(flowButtonParm.Clone())
      
      /*
      flowButtonParm.label       := "carousel_clans"
      flowButtonParm.idx         := 7
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_CLANS
      flowButtonParm.showFrame   := true
      flowButtonParm.showBg      := true   
      flowElements.Push(flowButtonParm.Clone())

      flowButtonParm.label       := "carousel_leaderboards"
      flowButtonParm.idx         := 8
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_LEADERBOARDS
      flowButtonParm.showFrame   := true
      flowButtonParm.showBg      := true   
      flowElements.Push(flowButtonParm.Clone())
      */
   elif (GetViewMode() == $uiEnums.SLIDING_SCREENS_MODE_SHOP_SMALL)
      isLeaveLobbyBtnVisible.Set(true)
      /*
      flowButtonParm.label       := "main_postmatch"
      flowButtonParm.idx         := 10
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_POSTMATCH
      flowButtonParm.showFrame   := false
      flowButtonParm.showBg      := false   
      flowElements.Push(flowButtonParm.Clone())
      
      flowButtonParm.label       := "carousel_restock"
      flowButtonParm.idx         := 11
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_RESTOCK
      flowButtonParm.showBg      := true
      flowButtonParm.showFrame   := false
      flowElements.Push(flowButtonParm.Clone())
      
      flowButtonParm.label       := "carousel_bundles"
      flowButtonParm.idx         := 3
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_BUNDLES
      flowButtonParm.showBg      := true
      flowButtonParm.showFrame   := true
      flowElements.Push(flowButtonParm.Clone())
      */
      flowButtonParm.label       := "main_weapons"
      flowButtonParm.idx         := 0
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_WEAPONS
      flowButtonParm.showFrame   := true
      flowButtonParm.showBg      := true   
      flowElements.Push(flowButtonParm.Clone())

      flowButtonParm.label       :=  "main_tactical_packages"
      flowButtonParm.idx         := 1
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_TACTICAL
      flowButtonParm.showFrame   := true
      flowButtonParm.showBg      := true   
      flowElements.Push(flowButtonParm.Clone())

      flowButtonParm.label       := "main_armory"
      flowButtonParm.idx         := 2
      flowButtonParm.name        := $uiEnums.SLIDING_PAGE_ARMORY
      flowButtonParm.showBg      := false
      flowButtonParm.showFrame   := false
      flowElements.Push(flowButtonParm.Clone())

      isLooping                  := true
   elif (GetViewMode() == $uiEnums.SLIDING_SCREENS_MODE_SPARTAN)
      flowButtonParm.label    := "carousel_spartan"
      flowButtonParm.idx      := 9
      flowButtonParm.name     := $uiEnums.SLIDING_PAGE_SPARTAN
      flowButtonParm.showBg   := false
      flowButtonParm.showFrame:= false
      flowButtonParm.hasConfirmationOnClose := true
      flowElements.Push(flowButtonParm.Clone())      
      
      isLooping               := false
   /*
   elif (GetViewMode() == $uiEnums.SLIDING_SCREENS_MODE_LOOT)
      flowButtonParm.label    := "carousel_lootBox"
      flowButtonParm.idx      := 12
      flowButtonParm.name     := $uiEnums.SLIDING_PAGE_LOOTBOX
      flowButtonParm.showBg   := true
      flowButtonParm.showFrame:= true
      flowButtonParm.hasConfirmationOnClose := true
      flowElements.Push(flowButtonParm.Clone())      
      
      isLooping               := false
   */
   elif (GetViewMode() == $uiEnums.SLIDING_SCREENS_MODE_TECH_TREE)
      flowButtonParm.label    := "carousel_tech_tree"
      flowButtonParm.idx      := 12
      flowButtonParm.name     := $uiEnums.SLIDING_PAGE_TECHTREE
      flowButtonParm.showBg   := true
      flowButtonParm.showFrame:= false
      flowButtonParm.hasConfirmationOnClose := false
      flowElements.Push(flowButtonParm.Clone())      
      
      isLooping               := false
   end   
   
   var startingIndex : int = GetScreenIndexByName(startingScreen)
   if (startingIndex < 0)
      startingIndex := 0
   end
   GetDC().UpdateCloseBtnVisible()
   Widgets().flowButtons.SetMaxWidth(720)
   Widgets().flowButtons.InitElements(flowElements, startingIndex)
end

override HasLobbyMode // () : bool
   return (bool)isLeaveLobbyBtnVisible.Get()
end

end