import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.game_preferences
import ssl.hf2p.hq
import ui.libs.hf2p_SlidingScreens.hf2p_sliding_screens_lib

class UiVideoAdvanced : UiSlidingScreenPageSettings

var isUpdatingScreen : int    = 0
var maxPresets       : int    = 5

func StartUpdatingScreenValues()
   isUpdatingScreen := isUpdatingScreen + 1
end

func StopUpdatingScreenValues()
   if (isUpdatingScreen > 0)
      isUpdatingScreen := isUpdatingScreen - 1
   end
end

func GetSettingsScreen() : params
   var ret : params
   ret.textureResolution         := Widgets.stepperTextureResolution.selection
   ret.textureFilteringQuality   := Widgets.stepperTextureFiltering.selection
   ret.lightingQuality           := Widgets.stepperLightningQuality.selection
   ret.effectsQuality            := Widgets.stepperEffectsQuality.selection
   ret.shadowQuality             := Widgets.stepperShadowQuality.selection
   ret.detailsQuality            := Widgets.stepperDetails.selection
   ret.postprocessQuality        := Widgets.stepperPostprocess.selection
   ret.motionBlur                := Widgets.checkboxMotionBlur.selected
   return ret   
end

func UpdateScreenControls()
   StartUpdatingScreenValues()
   var presetOptions : vector = $hf2pPreferences.GetQualityPresetOptions()
   var presetCurrent : int    = $hf2pPreferences.GetUserQualityPreset()
   var i             : int
   for i := 0 to maxPresets - 1
      var wgt : UiWidget = Widgets.presetsAttach.tabs.GetWidget("tab" + (string)i)
      if (i < presetOptions.Count())
         wgt.Props.visible     := true
         wgt.Props.selected    := i == presetCurrent
         wgt.Props.label       := presetOptions.Get(i)
         
         var isMouseEnabled         : bool = i < (presetOptions.Count() - 1)
         wgt.Props.mouseEnabled   := isMouseEnabled
         wgt.Props.mouseChildren  := isMouseEnabled
      else
         wgt.Props.selected    := false
         wgt.Props.visible     := false
      end
   end
   StopUpdatingScreenValues()
   Widgets.labelChangeNotice.visible := IsRestartNeeded($hf2pPreferences.GetSavedAdvancedVideoParams(), $hf2pPreferences.GetUserAdvancedVideoSettings())
end

func ApplySettingsScreen(settings : params)
   StartUpdatingScreenValues()
   
   if (!IsVoid(settings.textureResolution))
      Widgets.stepperTextureResolution.selection := settings.textureResolution
   end
   if (!IsVoid(settings.textureFilteringQuality))
      Widgets.stepperTextureFiltering.selection  := settings.textureFilteringQuality
   end
   if (!IsVoid(settings.lightingQuality))
      Widgets.stepperLightningQuality.selection  := settings.lightingQuality
   end
   if (!IsVoid(settings.effectsQuality))
      Widgets.stepperEffectsQuality.selection    := settings.effectsQuality
   end
   if (!IsVoid(settings.shadowQuality))
      Widgets.stepperShadowQuality.selection     := settings.shadowQuality
   end
   if (!IsVoid(settings.detailsQuality))
      Widgets.stepperDetails.selection           := settings.detailsQuality
   end
   if (!IsVoid(settings.postprocessQuality))
      Widgets.stepperPostprocess.selection       := settings.postprocessQuality
   end
   if (!IsVoid(settings.motionBlur))
      Widgets.checkboxMotionBlur.selected        := settings.motionBlur
   end     
   UpdateScreenControls()
   
   StopUpdatingScreenValues()
end

func TabClicked(p : params) : bool
   if (!IsVoid(p.widget.tabIdx))
      var tabIdx        : int = p.widget.tabIdx
      var presetOptions : vector = $hf2pPreferences.GetQualityPresetOptions()
      if (tabIdx < presetOptions.Count())
         StartUpdatingScreenValues()
         $hf2pPreferences.SetUserQualityPreset(tabIdx)
         ApplySettingsScreen($hf2pPreferences.GetUserAdvancedVideoSettings())
         StopUpdatingScreenValues()
      end
   end
   return false
end

func ApplySettingsUser(settings : params)
   $hf2pPreferences.SetUserAdvancedVideoSettings(settings)
   ApplySettingsScreen($hf2pPreferences.GetUserAdvancedVideoSettings())
end

override Init // ()
   
   Widgets.stepperTextureResolution.SetDataCustom($hf2pPreferences.GetTextureResolutionOptions())
   Widgets.stepperTextureFiltering.SetDataCustom($hf2pPreferences.GetTextureFilteringQualityOptions())
   Widgets.stepperLightningQuality.SetDataCustom($hf2pPreferences.GetLightingQualityOptions())
   Widgets.stepperEffectsQuality.SetDataCustom($hf2pPreferences.GetEffectsQualityOptions())
   Widgets.stepperShadowQuality.SetDataCustom($hf2pPreferences.GetShadowQualityOptions())
   Widgets.stepperDetails.SetDataCustom($hf2pPreferences.GetDetailsQualityOptions())
   Widgets.stepperPostprocess.SetDataCustom($hf2pPreferences.GetPostprocessQualityOptions())
   
   $hf2pPreferences.SaveAdvancedVideoParams()
   ApplySettingsScreen($hf2pPreferences.GetUserAdvancedVideoSettings())   
end

override Reset // ()
   Log("ui~advanced_video", "reset settings")
   $hf2pPreferences.SetUserAdvancedVideoSettings($hf2pPreferences.GetDefaultVideoSettings())
   ApplySettingsScreen($hf2pPreferences.GetUserAdvancedVideoSettings())
end

func CheckCanApply() : bool
   var ret           : bool   = false
   var checkResult   : int    = $hf2pPreferences.CheckApplyUserAdvancedVideoSettings(true)
   if (checkResult == $hf2pPreferences.VIDEO_CHECK_ERROR_NONE)
      ret := true
   else
      ShowErrorMb(checkResult)
   end
   return ret   
end

override Apply //() : bool //if true than close screens
   if (CheckCanApply())
      $hf2pPreferences.CheckApplyUserAdvancedVideoSettings(false)
      ApplySettingsScreen($hf2pPreferences.GetUserAdvancedVideoSettings())
   end
   return false
end

func ShowErrorMb(errCode : int)   
   var pp:params
   pp.mbType         := $uiEnums.MB_TYPE_INFO
   pp.titleTxt       := "msg_ui_settings_vid_err_hdr"
   pp.messageTxt     := "msg_ui_settings_vid_err_txt"
   if (errCode == $hf2pPreferences.VIDEO_CHECK_ERROR_UNSIFFICIENT_MEM_XP)
      pp.messageTxt     := "msg_ui_settings_vid_err_mem_xp"      
   else if (errCode == $hf2pPreferences.VIDEO_CHECK_ERROR_UNSIFFICIENT_MEM)
      pp.messageTxt     := "msg_ui_settings_vid_err_mem"      
   end
   GenerateEvent("SlidingScreenDialogRequest", pp)
end

func IsRestartNeeded(p1 : params, p2 : params) : bool
   var ret : bool = false
      
   if (!IsVoid(p1.textureResolution) and !IsVoid(p2.textureResolution))
      ret := ret or (p1.textureResolution != p2.textureResolution)      
   end
   
   return ret
end

override HaveUnsavedChanges // () :  bool   
   var ret : bool = $hf2pPreferences.HasAdvancedVideoChanges()
   return ret
end

func SetCurrentEngineSettings()
   $hf2pPreferences.SaveAdvancedVideoParams()
   ApplySettingsScreen($hf2pPreferences.GetSavedAdvancedVideoParams())
end

override Revert // ()
   ApplySettingsUser($hf2pPreferences.GetSavedAdvancedVideoParams())
   SetCurrentEngineSettings()
end

func OnCheckBoxValueChange(p:params):bool
   return OnSomethingWasChanged(p)
end

func OnStepperIndexChange(p:params):bool
   return OnSomethingWasChanged(p)
end

func OnSomethingWasChanged(p:params):bool
   if (isUpdatingScreen == 0)
      ApplySettingsUser(GetSettingsScreen())
   end
   return false
end

handle OnEnteringState("Initial")
end          

handle OnEnterState("Initial")
   Set("visible", false)
end  
        
handle OnEnteringState("Visible")
   ApplySettingsScreen($hf2pPreferences.GetUserAdvancedVideoSettings())
   Set("visible", true)
   StartDefaultBlinking(0.5, 1.0)
end  

handle OnLeavingState("Visible")
end

override SwitchToScreen // ()
   Log("ui~content", "Video setting SwitchSlide")
   Props.visible := true
end

override PrepareSlide // ()
   Log("ui~content", "Video setting PrepareSlide")
   if (GetStateName() != "Visible")
      SetStateName("Visible")
   end
   Props.visible := true
   var p: params
   p.state := "s_videoCont"
   GenerateEvent("ChangeFakeBackground", p)
end

override PrepareHideSlide // ()
   StartDefaultBlinking(0.5, 1.0)
end

override DisableSlide // ()
   if (GetStateName() != "Initial")
      Log("ui~content", "Video setting DisableSlide")
      Props.visible := false
      SetStateName("Initial")
   end
end
end
