import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ui.root
import ui.ui_player_info

class TweeningNum : UiWidget
   var isActive : bool
   
   func StartTweening(_startVal : float, _endVal : float, _duration : float, _isUpdate : bool = false)
      var tweenParm : params
      tweenParm.propName   := "tweenVar"
      tweenParm.startVal   := _startVal         
      tweenParm.endVal     := _endVal
      tweenParm.duration   := _duration
      tweenParm.fadeType   := "linear"

      if (_startVal != _endVal)
         AddTweenCb("TweenFunc", tweenParm) 
      else
         var p : params
         p.val       := _endVal
         p.updType   := $uiEnums.TWEEN_UPD_TYPE_COMPLETE
         GenerateEvent("#OnTweenUpdate", p)      
      end      
   end
   
   func StopTweening()
      RemTweens()
   end
   
   func TweenFunc(updType:string)  
      var p : params
      p.val       := Props.tweenVar
      p.updType   := updType
      GenerateEvent("#OnTweenUpdate", p)
   end  
   
   func SetIsActive(_isActive : bool)
      if (isActive != _isActive)
         isActive := _isActive
         if (isActive)
            GenerateEvent("#EnableTweenVM")
         else
            GenerateEvent("#DisableTweenVM")         
         end
      end
   end
end

class TweeningNumVm
   var wgt              : TweeningNum        = null
   var tweenedValue     : ObservableProperty = $OM.Calculated(this, "GetTweenedValue")
   var innerValue       : float              = 0
   var isTweening       : bool               = false
   var tweenStart       : float              = 0
   var tweenEnd         : float              = 0
   var curTween         : float              = 0
   var isSoundPlaying   : bool               = false
   var isSubscribed     : bool               = false
   var totalDuration    : float              = 1.0
   var isFirstUpdate    : bool               = true
   
   
   func IsUpdateOnEnable() : bool
      return true
   end
   
   func IsSkipFirstUpdate() : bool
      return true
   end
   
   func IsAutomaticUpdates() : bool
      return true
   end
   
   func EnableTweenVM(p : params = null) : bool
      if (! isSubscribed)
         Reset()
         isSubscribed := true
         if (IsAutomaticUpdates())
            GetObservable().Subscribe(this, "OnUpdateVal")
         end
      end
      if (IsUpdateOnEnable())
         OnUpdateVal()
      end
      return true
   end
   
   func DisableTweenVM(p : params = null) : bool
      if (isSubscribed)
         if (IsAutomaticUpdates())
            GetObservable().Unsubscribe(this, "OnUpdateVal")
         end
         isSubscribed := false
      end
      return true
   end
   
   func Init(p : params)
      wgt := p.widget
   end
   
   func Term()
      DisableTweenVM()
      StopSound()
   end
   
   func OnValueUpdated()
   end   
   
   func OnTweenStart()
   end   
   
   func OnTweenEnd()
   end   
         
   func TweeningNumVm()
   end
   
   func GetObservable() : ObservableProperty
      return $UserDataStorage.local_user.gold 
   end
      
   func GetObservableVal() : float
      return (float)$UiGlobals.Int64ToInt($UserDataStorage.local_user.gold.Get())
   end
   
   func GetTweenedValue() : string
      var val : string = (string)((int)innerValue)
      return val
   end
   
   func GetTweenSound() : string
      return ""
   end
   
   func GetDuration() : float
      return 2
   end
      
   func GetAddDuration() : float
      return 1
   end
   
   func GetTimeLeft() : float
      return totalDuration * (1 - curTween)
   end
   
   func ResetValue(_val : float)
      curTween       := 0         
      totalDuration  := GetDuration()
      innerValue     := _val 
      tweenStart     := _val
      tweenEnd       := _val
      tweenedValue.Invalidate()
   end
   
   func Reset()
      isFirstUpdate := true
   end
   
   func OnTweenPreStart()
      
   end
   
   func OnUpdateVal(_val : * = null)
      var newVal : float = GetObservableVal()
      if (isFirstUpdate)
         isFirstUpdate  := false
         ResetValue(newVal)
      elif (newVal != tweenEnd)
         if (isTweening)
            tweenEnd := newVal
            if (wgt != null and GetAddDuration() > 0)
               wgt.StopTweening()
               var currentTime   : float = totalDuration * curTween
               var timeLeft      : float = totalDuration - currentTime
               totalDuration     := timeLeft + GetAddDuration()
               curTween          := 0
               tweenStart        := innerValue
               tweenEnd          := newVal            
               wgt.StartTweening(0.0, 100, totalDuration)
            end
            UpdateTweenVal()
            OnValueUpdated()
         else
            if (wgt != null)
               OnTweenPreStart()
               isTweening     := true
               tweenStart     := innerValue
               tweenEnd       := newVal
               curTween       := 0
               totalDuration  := GetDuration()
               OnTweenStart()
               StartSound()
               wgt.StartTweening(0, 100, totalDuration)
            end
         end
      elif (newVal == tweenEnd)
         newVal := tweenEnd
      end
   end   
   
   func UpdateTweenVal()
      var curVal : float = tweenStart + (tweenEnd - tweenStart) * curTween 
      innerValue := curVal 
      tweenedValue.Invalidate()
   end
   
   func StartSound()
      Log("ui~cash_panel", "StartSound called")
      if (! isSoundPlaying)
         var soundVal : string = GetTweenSound()
         Log("ui~cash_panel", "StartSound = [" + soundVal + "]")
         if (soundVal != "")
            $root.playSound(soundVal)
            isSoundPlaying := true
         end
      end
   end
   
   func StopSound()
      Log("ui~cash_panel", "StopSound called")
      if (isSoundPlaying)
         var soundVal : string = GetTweenSound()
         Log("ui~cash_panel", "StopSound = [" + soundVal + "]")
         if (soundVal != "")
            $root.stopSound(soundVal)
         end
         isSoundPlaying := false
      end
   end
   
   func OnTweenUpdate(p : params) : bool
      curTween := p.val / 100.0
      if (p.updType == $uiEnums.TWEEN_UPD_TYPE_COMPLETE)
         Log("ui~cash_panel", "TWEEN_UPD_TYPE_COMPLETE")
         StopSound()
         isTweening  := false
         OnTweenEnd()
      end
      UpdateTweenVal()
      return true
   end
end

class TweeningNumVmGp : TweeningNumVm
   override GetObservable //() : ObservableProperty
      return $UserDataStorage.local_user.gold 
   end   
   
   override GetObservableVal //() : GetObservableVal
      return (float)$UiGlobals.Int64ToInt(GetObservable().Get())
   end   
   
   override GetTweenSound//() : string
      Log("ui~cash_panel_gold", "tween_sound = menu_gold_tally")
      return "menu_gold_tally"
   end
   
   override GetDuration//() : float
      return 1.5
   end
end

class TweeningNumVmCr : TweeningNumVm
   var isProcessing : ObservableProperty = $OM.Property(false)
   var credit : ObservableProperty = $OM.Calculated(this, "GetCredit")
   
   func GetCredit() : *
      var ret : int = 0
      if isProcessing.Get() == true
         ret := $root.pregameCredit
      else
         ret := (int)$UserDataStorage.local_user.cr.Get()
      end
      return ret
   end
   
   func OnPostmatchStarted(p : params) : bool
      //isProcessing.Set(true)
      return false
   end
   
   func OnAddCreditsAnim(p : params) : bool
      isProcessing.Set(false)
      return false
   end
   
   func OnPostmatchSkip(p : params) : bool
      isProcessing.Set(false)
      return false
   end
   
   override GetObservable //() : ObservableProperty
      return credit
   end   
   
   override GetObservableVal //() : GetObservableVal
      return (float)$UiGlobals.Int64ToInt(GetObservable().Get())
   end   
   
   override GetTweenSound//() : string
      if isProcessing.Get() == true
         Log("ui~cash_panel_credits", "tween_sound = null")
         return ""
      else
         Log("ui~cash_panel_credits", "tween_sound = menu_credit_tally")
         return "menu_credit_tally"
      end
   end
   
   override GetDuration//() : float
      if isProcessing.Get() == true
         return 0
      else
         return 2
      end
   end
end

class UiCashPanel : UiWidgetContainer

var isActive   : bool   = false

func SetIsActive(_isActive: bool)
   isActive := _isActive
   Widgets.creditsValCont.SetIsActive(_isActive)
   Widgets.goldValCont.SetIsActive(_isActive)
end

func GetIsActive(): bool
   return isActive
end

handle OnEnterState("Hidden")
   SetIsActive(false)
   Log("ui~cashPanel", "Cash panel enter hidden")
   GotoAndPlay("fadeOut")
end

handle OnEnteringState("Hidden")   
   Props.visible := true
   GotoAndPlay("fadeOut") 
end

handle OnEnteringState("Visible")
   Props.visible := true
   GotoAndPlay("fadeIn")
   StartDefaultBlinking(10.0/35.0)
   GenerateEvent("#OnShowCashPanel")
end

handle OnEnterState("Visible")
   Log("ui~cashPanel", "Cash panel enter visible")
   SetIsActive(true)
end

func BuyGoldClicked(p : params) : bool
   //$user_service.SetWeaponLoadoutWeapon(0,0, "blabla")
   $UiGlobals.backend_requests.real_money_purchase.Start("gold100")
   return false
end

func BuyBoostBtnClicked(p : params) : bool
   //add boost scr
   return false
end

end

class UiCashPanelVM
   
   var isBuyGoldEnabled : ObservableProperty = $OM.Calculated(this, "GetIsBuyGoldEnabled")
   var xpBoost          : ObservableProperty = $OM.Property(0)
   var crBoost          : ObservableProperty = $OM.Property(0)
   
   func GetIsBuyGoldEnabled() : bool
      var ret : bool = false
      //ret := (int)$UiGlobals.backend_requests.real_money_purchase.progress.state.Get() == $uiEnums.BACKEND_REQUEST_STATE_NONE
      return ret
   end
   
   func GetXpBoostLabel() : string
      var ret : string
      if ((int)xpBoost.Get() == 0)
         ret := "main_ui_xp"
      else   
         ret := "main_xp_boost_percent," + (string)(int)xpBoost.Get()
      end
      return " "
   end
   
   func GetCrBoostLabel() : string
      var ret : string
      if ((int)crBoost.Get() == 0)
         ret := "main_ui_cr"
      else   
         ret := "main_cr_boost_percent," + (string)(int)crBoost.Get()
      end
      return " "
   end
   
   func GetChaleengeBoostLabel() : string
      return " "
   end
   
   func GetBoostTime(boost : string) : int
      var ret     : int
      if ($uiEconomy.GetItemOwnType(boost) == $uiEnums.ITEM_OWN_TYPE_RENTED)
         var uiInventoryItem : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(boost)
         var ownTime : int = (int)uiInventoryItem.ownership_time.Get() - (int)$UiGlobals.timer.Get()
         ret := ownTime
      end
      return ret   
   end
   
   func GetBoostTimeLabel(boost : string) : wstring
      var ret     : wstring      
      if ($uiEconomy.GetItemOwnType(boost) == $uiEnums.ITEM_OWN_TYPE_RENTED)
         ret := $root.MakeUiTimerStringMinutes(GetBoostTime(boost), true)
      end
      return ret
   end
   
   func GetBoostFrame(boost : string) : string
      var ret : string = "off"
      if (GetBoostTime(boost) > 0)
         ret := "on"
      end
      return ret
   end
   
end
