import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_manager
import ssl.hf2p.engine_ctrl
import ssl.hf2p.items_mgr
import ssl.observables
import ssl.hf2p.ui_globals
import ssl.hf2p.hq
import ui.root
import ui.ui_economy
import ui.ui_player_info
import ssl.hf2p.clan_data

class UiClansSearch : UiWidgetContainer

handle OnEnterState("Initial")
   Set("visible", false)            
end 

handle OnEnterState("Hidden")
end          

handle OnEnteringState("Visible")
   Set("visible", true)
end  

func SwitchToScreen()
end

func PrepareSlide()
   if (GetStateName() != "Visible")
      SetStateName("Visible")
   end
end

func PrepareHideSlide()
end

func DisableSlide()
   if (GetStateName() != "Hidden")
      SetStateName("Hidden")
   end
end

end

class UiClansSearchInputTf : UiWidgetContainer
   func inputEvent(p : params) : bool
      var isTerminated  : bool   = false
      var keyCode       : int    = p.keyCode
      if (p.isDown == true and keyCode == $uiKeys.VK_ENTER)
         GenerateEvent("#OnSearchBarEnterPressed")
         isTerminated := true
      end
      if (keyCode == $uiKeys.VK_DOWN or keyCode == $uiKeys.VK_UP or keyCode == $uiKeys.VK_TAB or keyCode == $uiKeys.VK_ENTER)
         isTerminated := true
      end
      if (isTerminated)
         p.eventState.SetIsTerminated(isTerminated)
      end
      return false
   end
end

class ClansSearchVM
   var wgt : *
   
   var SearchResult : ObservableProperty = $OM.Property(null)
   var SelectedItem : ObservableProperty = $OM.Property(null)
   
   func Init(p : params)
      wgt := p.widget
   end
   
   func Term(p : params)
   end
   
   func GetSelectedClanMemberList() : vector
      if IsValid(SelectedItem.Get())
         var cd : ClanData = (ClanData)$ClanDataStorage.clans.Get(SelectedItem.Get().value.Get())
         if cd.has_membership.Get() == false
            $clan_service.RequestData(SelectedItem.Get().value.Get(), $uiEnums.CLAN_DATA_MEMBERSHIP)
         end
         return cd.membership.members.Get()
      else
         return new vector
      end
   end
   
   func OnSearchBarEnterPressed()
      var searchText : string = wgt.Widgets().searchBar.text
      var isValidResult = $clan_service.IsValidClanName($UiGlobals.String2WString(searchText))
      
      if isValidResult == 0
         $UiGlobals.async_operations.clan_find_by_name.Start(searchText, "ClanSearchComplete")
      else
         if isValidResult == 1
            var par: params
            par.mbType     := "Info"
            par.titleTxt   := "msg_ui_warning"
            par.messageTxt := "msg_clan_name_too_short"
            $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
         elif isValidResult == 2
            var par: params
            par.mbType     := "Info"
            par.titleTxt   := "msg_ui_warning"
            par.messageTxt := "msg_clan_name_too_long"
            $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
         end
         SearchResult.Set(null)
         SelectedItem.Set(null)
      end
   end
   
   func OnClanSearchComplete(p : params) : bool
      var searchResult : * = $UiGlobals.async_operations.clan_find_by_name.result.Get()
      SearchResult.Set(searchResult)
      return true
   end
   
   func OnSearchResultIndexChanged(p : params) : bool
      if IsValid(SearchResult.Get())
         var resultVector : vector = SearchResult.Get()
         SelectedItem.Set(resultVector.Get(p.index))
      end
      return true
   end
end

class ClanSearchResultItemVM
   var clan_id : GL_UID = null
   
   func Init(p : params)
      if (IsValid(p.clan_id) and p.clan_id != null)
         clan_id := p.clan_id
         if (clan_id.IsValid())
            $clan_service.RequestData(p.clan_id.value.Get(), $uiEnums.CLAN_DATA_BASE)
         end
      end
   end
   
   func GetClanName() : *
      if clan_id != null and clan_id.IsValid() and $ClanDataStorage.clans.Get(clan_id.value.Get()).has_base.Get()
         return $ClanDataStorage.clans.Get(clan_id.value.Get()).base.clan_name.Get()
      end
      return "???"
   end
end
