import ssl.lib.ui.ui_widget_container

class animatedContent_contentContainer_UiContent_4 : UiWidgetContainer

var   isSlidingElement  :  bool  = false

func Init()
end

handle OnEnterState("Initial")
   Set("visible", false)            
end          

handle OnEnteringState("Visible")
   Init()         
   Set("visible", true)
end  

func PrepareSlide()
   if (GetStateName() != "Visible")
      SetStateName("Visible")
   end
end

func PrepareHideSlide()
end

func DisableSlide()
   if (GetStateName() != "Initial")
      SetStateName("Initial")
   end
end
end
