import ssl.observables
import ssl.hf2p.ui_globals
import ssl.lib.ui.bindings.bindings
import ssl.lib.ui.bindings.bindings
import ui.root
import ssl.lib.types

/***************************************************************
* GL_String
*
***************************************************************/   
class GL_String : UiSslBindableBase
   var value  : ObservableProperty = null
end

/***************************************************************
* GL_User
*
***************************************************************/   
class GL_User : UiSslBindableBase
   var id   : ObservableProperty = null
end

/***************************************************************
* GL_UID
*
***************************************************************/   
class GL_UID : UiSslBindableBase
   native func Equals   (val : *)   : bool
   native func IsValid  ()          : bool
   native func ToStr    ()          : string

   var value  : ObservableProperty = null
   
   func InitDefault()
      if (value == null) 
         value := $OM.Property($UiGlobals.GetInvalidUIDVal())         
      else
         value.Set($UiGlobals.GetInvalidUIDVal())
      end
   end
   
   func GetVal() : *
      return value.Get()
   end
   
   func IsValidVal() : bool
      var uidStr  : string = $UserDataStorage.UID2Str(value.Get())
      var ret     : bool   = (uidStr != "0" and uidStr != "")
      return ret
   end

   func IsValidSSL() : bool
      return IsValidVal()
   end
end

/***************************************************************
* GL_TokenState
*
***************************************************************/   
class GL_TokenState : UiSslBindableBase
   var name   : ObservableProperty = null
   var value  : ObservableProperty = null
end

/***************************************************************
* UD_Social
*
***************************************************************/   
class UD_Social : UiSslBindableBase
   var following              : ObservableProperty = null
end

/***************************************************************
* UD_Presence
*
***************************************************************/   
class UD_Presence : UiSslBindableBase
   var presence_state         : ObservableProperty = null
end

/***************************************************************
* UD_WeaponLoadout
*
***************************************************************/   
class UD_WeaponLoadout : UiSslBindableBase
   var primary_weapon         : ObservableProperty = null
   var secondary_weapon       : ObservableProperty = null
   var grenades               : ObservableProperty = null
   var booster                : ObservableProperty = null
   var consumable_first       : ObservableProperty = null
   var consumable_second      : ObservableProperty = null
   var consumable_third       : ObservableProperty = null
   var consumable_fourth      : ObservableProperty = null

// ssl-only
   var crOfferCosts           : ObservableProperty = $OM.Calculated(this, "GetCrOfferCostsVec")
   var gpOfferCosts           : ObservableProperty = $OM.Calculated(this, "GetGpOfferCostsVec")

   func InvalidateCosts()
      crOfferCosts.Invalidate()
      gpOfferCosts.Invalidate()
   end

   func GetCrOfferCostsVec() : vector
      var ret : vector
      var shopShelf  : GL_ShopShelf = $UiGlobals.shop.GetInternalShelf(0, "section_loadouts", "shelf_weapon_loadouts")
      if (shopShelf != null)
         var loadoutIdx : int
         for loadoutIdx := 0 to shopShelf.items.Get().Count() - 1
            var loadoutId    : string = (string)shopShelf.items.Get().Get(loadoutIdx).value.Get()
            var shopComp     : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(loadoutId)
            if (shopComp.offers.Get().Count() > 0)
               var loadoutOffer : GL_ComponentShopOffer = (GL_ComponentShopOffer)shopComp.offers.Get().Get(0)
               ret.Push((string)loadoutOffer.GetCrCost())
            else
               ret.Push("n/a~")
            end
         end
      end
      while (ret.Count() < 5)
         ret.Push("n/a~")
      end
      return ret 
   end

   func GetGpOfferCostsVec() : vector
      var ret : vector
      var shopShelf  : GL_ShopShelf = $UiGlobals.shop.GetInternalShelf(0, "section_loadouts", "shelf_weapon_loadouts")
      if (shopShelf != null)
         var loadoutIdx : int
         for loadoutIdx := 0 to shopShelf.items.Get().Count() - 1
            var loadoutId    : string = (string)shopShelf.items.Get().Get(loadoutIdx).value.Get()
            var shopComp     : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(loadoutId)
            if (shopComp.offers.Get().Count() > 0)
               var loadoutOffer : GL_ComponentShopOffer = (GL_ComponentShopOffer)shopComp.offers.Get().Get(0)
               ret.Push((string)loadoutOffer.GetGlCost())
            else
               ret.Push("n/a~")
            end
         end
      end
      while (ret.Count() < 5)
         ret.Push("n/a~")
      end
      return ret 
   end

   func GetWeaponTint(weaponId :  string) : params
      var   tint     : params = $uiEconomy.GetWeaponPrimaryArrtibuteColor("unknown")
      if (weaponId != "")
         var   weapon   :  GL_ComponentWeapon = (GL_ComponentWeapon)$UiGlobals.componentsWeapon.Get(weaponId)
         if (weapon != null)
            tint := $uiEconomy.GetWeaponPrimaryArrtibuteColor((string)weapon.primary_attribute_id.Get())
         end
      end
      return tint
   end
   
   func IsWeaponTintVisible(weaponId :  string) : bool
      var ret : bool = false
      if (weaponId != "")
         var   weapon   :  GL_ComponentWeapon = (GL_ComponentWeapon)$UiGlobals.componentsWeapon.Get(weaponId)
         if (weapon != null)
            ret := (string)weapon.primary_attribute_id.Get() != "none" and (string)weapon.primary_attribute_id.Get() != ""
         end
      end
      return ret
   end
   
   func RemoveTacticalPackage(p : params) : bool
      $user_service.SetWeaponLoadoutConsumable($hf2pEngine.GetUIPlayerModelId(), p.loadoutIdx, p.tacticalPackageIdx, "")
      return true
   end
   
   
   func GetOfferCostCr(loadoutIdx : int) : string
      var ret     : string
      var costVec : vector = crOfferCosts.Get()
      if (loadoutIdx >= 0 and loadoutIdx < costVec.Count())
         ret := costVec.Get(loadoutIdx)
      end
      return ret
   end
   
   func GetOfferCostGp(loadoutIdx : int) : string
      var ret     : string
      var costVec : vector = gpOfferCosts.Get()
      if (loadoutIdx >= 0 and loadoutIdx < costVec.Count())
         ret := costVec.Get(loadoutIdx)
      end
      return ret
   end
   
   func GetPackageByIdx(idx : int) : string
      var ret : string
      if (idx == 0)
         ret := (string)consumable_first.Get()
      elif (idx == 1)
         ret := (string)consumable_second.Get()
      elif (idx == 2)
         ret := (string)consumable_third.Get()
      elif (idx == 3)
         ret := (string)consumable_fourth.Get()
      end
      return ret
   end   
   
   func GetItemBySlotIdx(idx : int) : string
      var ret : string
      if (idx == 0)
         ret := (string)primary_weapon.Get()
      elif (idx == 1)
         ret := (string)secondary_weapon.Get()
      elif (idx == 2)
         ret := (string)grenades.Get()
      elif (idx == 3)
         ret := (string)consumable_first.Get()
      elif (idx == 4)
         ret := (string)consumable_second.Get()
      elif (idx == 5)
         ret := (string)consumable_third.Get()
      elif (idx == 6)
         ret := (string)consumable_fourth.Get()
      elif (idx == 7)
         ret := (string)booster.Get()
      end
      return ret
   end
   
   func GetSlotTypeAndSubType(idx : int) : params
      return $uiEnums.weaponSlotIdxToItemTypeVec.Get(idx)
   end
end

/***************************************************************
* UD_WeaponLoadouts
*
***************************************************************/   
class UD_WeaponLoadouts : UiSslBindableBase
   var active_loadout_index : ObservableProperty = null
   var loadouts             : ObservableProperty = null // vector
end

/***************************************************************
* UD_RaceWeaponLoadouts
*
***************************************************************/   
class UD_RaceWeaponLoadouts : UiSslBindableBase
   var spartan : UD_WeaponLoadouts   = null
   var elite   : UD_WeaponLoadouts   = null
end

/***************************************************************
* UD_ArmorLoadoutBonuses
*
***************************************************************/   
class UD_ArmorLoadoutBonuses : UiSslBindableBase
   var armor_class_id            : ObservableProperty = null  

   var current_value             : ObservableProperty = null 
   var current_level             : ObservableProperty = null   

   var percent_value   : ObservableProperty = $OM.Calculated(this, "GetPercentValue", true)
   var percent_value2  : ObservableProperty = $OM.Calculated(this, "GetPercentValue2", true)
   var modifiers_text  : ObservableProperty = $OM.Calculated(this, "GetModifiersText", true)
   
   func GetPercentValue() : float
      var ret :  float
      ret := (float)current_value.Get()
      ret := ret / 25.0
      return ret            
   end
   
   func GetPercentValue2() : float
      var ret :  float
      ret := (float)current_value.Get() + 1.0
      ret := ret / 26.0
      return ret            
   end
      
   func GetModifiersText() : string
      var result : string = ""
      return result
   end

end

/***************************************************************
* UD_ArmorLoadout
*
***************************************************************/   
class UD_ArmorLoadout : UiSslBindableBase
   var armor            : ObservableProperty = null

// ssl-only
   var bonuses_sorted         : ObservableProperty = $OM.Calculated(this, "GetBonusesSorted", true)
   var bonuses_sorted_count   : ObservableProperty = $OM.Calculated(this, "GetBonusesSortedCount", true)
   
   var crOfferCosts           : ObservableProperty = $OM.Calculated(this, "GetCrOfferCostsVec")
   var gpOfferCosts           : ObservableProperty = $OM.Calculated(this, "GetGpOfferCostsVec")
   
   func InvalidateCosts()
      crOfferCosts.Invalidate()
      gpOfferCosts.Invalidate()
   end
   
   func GetBonusesSorted() : vector
      var result : vector
      return result
   end
   
   func GetBonusesSortedCount() : int
      var result : int = 0
      return result
   end
   

   func GetCrOfferCostsVec() : vector
      var ret : vector
      var shopShelf  : GL_ShopShelf = $UiGlobals.shop.GetInternalShelf(0, "section_loadouts", "shelf_armor_loadouts")
      if (shopShelf != null)
         var loadoutIdx : int
         for loadoutIdx := 0 to shopShelf.items.Get().Count() - 1
            var loadoutId    : string = (string)shopShelf.items.Get().Get(loadoutIdx).value.Get()
            var shopComp     : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(loadoutId)
            if (shopComp.offers.Get().Count() > 0)
               var loadoutOffer : GL_ComponentShopOffer = (GL_ComponentShopOffer)shopComp.offers.Get().Get(0)
               ret.Push((string)loadoutOffer.GetCrCost())
            else
               ret.Push("n/a~")
            end
         end
      end
      while (ret.Count() < 5)
         ret.Push("n/a~")
      end
      return ret 
   end

   func GetGpOfferCostsVec() : vector
      var ret : vector
      var shopShelf  : GL_ShopShelf = $UiGlobals.shop.GetInternalShelf(0, "section_loadouts", "shelf_armor_loadouts")
      if (shopShelf != null)
         var loadoutIdx : int
         for loadoutIdx := 0 to shopShelf.items.Get().Count() - 1
            var loadoutId    : string = (string)shopShelf.items.Get().Get(loadoutIdx).value.Get()
            var shopComp     : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(loadoutId)
            if (shopComp.offers.Get().Count() > 0)
               var loadoutOffer : GL_ComponentShopOffer = (GL_ComponentShopOffer)shopComp.offers.Get().Get(0)
               ret.Push((string)loadoutOffer.GetGlCost())
            else
               ret.Push("n/a~")
            end
         end
      end
      while (ret.Count() < 5)
         ret.Push("n/a~")
      end
      return ret 
   end
   
   func GetOfferCostCr(loadoutIdx : int) : string
      var ret     : string
      var costVec : vector = crOfferCosts.Get()
      if (loadoutIdx >= 0 and loadoutIdx < costVec.Count())
         ret := costVec.Get(loadoutIdx)
      end
      return ret
   end
   
   func GetOfferCostGp(loadoutIdx : int) : string
      var ret     : string
      var costVec : vector = gpOfferCosts.Get()
      if (loadoutIdx >= 0 and loadoutIdx < costVec.Count())
         ret := costVec.Get(loadoutIdx)
      end
      return ret
   end
   
end

/***************************************************************
* UD_ArmorLoadouts
*
***************************************************************/   
class UD_ArmorLoadouts : UiSslBindableBase
   var active_loadout_index : ObservableProperty = null
   var loadouts             : ObservableProperty = null // vector
   var colors               : ObservableProperty = null
end

/***************************************************************
* UD_RaceArmorLoadouts
*
***************************************************************/   
class UD_RaceArmorLoadouts : UiSslBindableBase
   var spartan : UD_ArmorLoadouts   = null
   var elite   : UD_ArmorLoadouts   = null
end

/***************************************************************
* UD_Customizations
*
***************************************************************/   
class UD_Customizations : UiSslBindableBase
   var character_active_index : ObservableProperty = null

   var account_label          : ObservableProperty = null
   var emblem                 : ObservableProperty = null

   var colors                 : ObservableProperty = null
end

/***************************************************************
* UD_Character
*
***************************************************************/   
class UD_Character : UiSslBindableBase
   var armor                        : ObservableProperty = null

   var primary_weapon               : ObservableProperty = null
   var secondary_weapon             : ObservableProperty = null
   var grenades                     : ObservableProperty = null

   var support_package              : ObservableProperty = null
   var tactical_package_first       : ObservableProperty = null
   var tactical_package_second      : ObservableProperty = null
   var tactical_package_third       : ObservableProperty = null
   var tactical_package_fourth      : ObservableProperty = null  
end

/***************************************************************
* UD_Stats
*
***************************************************************/   
class UD_Stats : UiSslBindableBase
   var xp_level_current                : ObservableProperty = null
   var xp_level_next                   : ObservableProperty = null
   var kills                           : ObservableProperty = null
   var deaths                          : ObservableProperty = null
   var suicides                        : ObservableProperty = null
   var assists                         : ObservableProperty = null
   var kd                              : ObservableProperty = null
   var online_time_sec                 : ObservableProperty = null
   var online_time_last_change_sec     : ObservableProperty = null
   var game_time_played_sec            : ObservableProperty = null
   var games                           : ObservableProperty = null
   var games_won                       : ObservableProperty = null
   var games_lost                      : ObservableProperty = null
   var games_tie                       : ObservableProperty = null
   var games_win_loss                  : ObservableProperty = null
   var wp                              : ObservableProperty = null
   var wp_per_game                     : ObservableProperty = null
   var wp_per_minute                   : ObservableProperty = null
   
   var onlineTimeStr                   : ObservableProperty = $OM.Calculated(this, "GetOnlineTime", true)
   var scorePerGameStr                 : ObservableProperty = $OM.Calculated(this, "GetScorePerGameStr", true)
   
   func GetOnlineTime() : string
      var ret : string
      var time  : int  = (int)game_time_played_sec.Get()
      ret := $root.MakeUiTimerString(time)
      return ret
   end
         
   func GetScorePerGameStr() : string
      var ret  : string
      ret := $root.Float2Str2Dec((float)wp_per_game.Get())
      return ret      
   end
end

/***************************************************************
* UD_Base
*
***************************************************************/   
class UD_Base : UiSslBindableBase
   var nickname   : ObservableProperty = null
   var clan_id    : ObservableProperty = null
   var clan_tag   : ObservableProperty = null
   var level      : ObservableProperty = null
   var level_id   : ObservableProperty = null
   
   var full_nickname : ObservableProperty = $OM.Calculated(this, "GetFullNickName", true)   
   
   func GetFullNickName() : wstring
      if clan_tag.Get() != ""
         var p : params
         p.decorL := $UiGlobals.String2WString("[")
         p.decorR := $UiGlobals.String2WString("]")
         var result : * = p.decorL + clan_tag.Get() + p.decorR + nickname.Get()
         return result
      end
      return nickname.Get()
   end
end

/***************************************************************
* UserData
*
***************************************************************/   
class UserData : UiSslBindableBase
   var has_base                  : ObservableProperty = null
   var has_stats                 : ObservableProperty = null
   var has_presence              : ObservableProperty = null
   var has_social                : ObservableProperty = null
   var has_customizations        : ObservableProperty = null
   var has_armor_loadouts        : ObservableProperty = null
   var has_weapon_loadouts       : ObservableProperty = null

   var has_character_spartan_slot_0 : ObservableProperty = null
   var has_character_spartan_slot_1 : ObservableProperty = null
   var has_character_spartan_slot_2 : ObservableProperty = null

   var base             : UD_Base               = null
   var stats            : UD_Stats              = null
   var presence         : UD_Presence           = null
   var social           : UD_Social             = null

   var customizations   : UD_Customizations     = null
   var armor_loadouts   : UD_RaceArmorLoadouts  = null
   var weapon_loadouts  : UD_RaceWeaponLoadouts = null
   
   var character_spartan_slot_0 : UD_Character = null
   var character_spartan_slot_1 : UD_Character = null
   var character_spartan_slot_2 : UD_Character = null

// ssl-only
   var canRenderBiped   : ObservableProperty    = $OM.Calculated(this, "GetCanRenderBiped", true)
   
   func CanRenderBiped() : bool
      return (bool)canRenderBiped.Get()
   end
   
   func GetCanRenderBiped() : bool
      var ret : bool = true
      
      ret := (bool)(has_customizations.Get()) and ret
      ret := GetHasActiveCharacter() and ret
      
      return ret
   end
   
   func GetCharacterByIdx(idx : int) : UD_Character
      if idx == 0
         return character_spartan_slot_0
      elif idx == 1
         return character_spartan_slot_1
      else
         return character_spartan_slot_2
      end
   end
   
   func GetActiveCharacter() : UD_Character
      return GetCharacterByIdx((int)customizations.character_active_index.Get())
   end
   
   func GetHasCharacterByIdx(idx : int) : bool
      if idx == 0
         return (bool)has_character_spartan_slot_0.Get()
      elif idx == 1
         return (bool)has_character_spartan_slot_1.Get()
      else
         return (bool)has_character_spartan_slot_2.Get()
      end
   end
   
   func GetHasActiveCharacter() : bool
      return GetHasCharacterByIdx((int)customizations.character_active_index.Get())
   end   
end

/***************************************************************
* UD_ChallengeCounter
*
***************************************************************/   
class UD_ChallengeCounter : UiSslBindableBase
   var id         : ObservableProperty = null
   var type       : ObservableProperty = null
   var value      : ObservableProperty = null
   var value_max  : ObservableProperty = null
   var progress   : ObservableProperty = null
end

/***************************************************************
* UD_Challenge
*
***************************************************************/   
class UD_Challenge : UiSslBindableBase
   var id         : ObservableProperty = null

   var progress   : ObservableProperty = null

   var counters   : ObservableProperty = null
   
   //ssl-extensions
   func IsCompleted() : bool
      var progressVal   : float  = (float)progress.Get()
      var ret           : bool   = progressVal >= 1.0
      return ret
   end   
   
   func GetCountersCount() : int
      var countersVec : vector = counters.Get()
      return countersVec.Count()
   end
   
   func GetCounter(_idx : int) : UD_ChallengeCounter
      var ret           : UD_ChallengeCounter   = null
      var countersVec   : vector                = counters.Get()
      if (_idx >= 0 and _idx < countersVec.Count())
         ret := countersVec.Get(_idx)
      end
      return ret
   end
end

/***************************************************************
* UD_Challenges
*
***************************************************************/   
class UD_Challenges : UiSslBindableBase
   var challenges_daily    : ObservableProperty = null
   var challenges_weekly   : ObservableProperty = null
   var challenges_monthly  : ObservableProperty = null
end

/***************************************************************
* UserDataLocal
*
***************************************************************/   
class UserDataLocal : UiSslBindableBase
   var uid                       : ObservableProperty = null
   var gold                      : ObservableProperty = null
   var cr                        : ObservableProperty = null
   var race                      : ObservableProperty = null
   var level                     : ObservableProperty = null
   var level_id                  : ObservableProperty = null  
   var level_next                : ObservableProperty = null
   var level_next_id             : ObservableProperty = null
   var level_progress            : ObservableProperty = null
   var class_id                  : ObservableProperty = null   

   var weapon_loadouts_unlocked  : ObservableProperty = null
   var armor_loadouts_unlocked   : ObservableProperty = null

   var token_renames             : ObservableProperty = null
   var token_class_selection     : ObservableProperty = null
   var tokens                    : ObservableProperty = null

   var is_ui_tutorial_complete   : ObservableProperty = null

   var recent_users              : ObservableProperty = null

   var challenges                : UD_Challenges = null

//extensions
   var currentLoadout            : ObservableProperty = $OM.Calculated(this, "GetCurrentLoadout", true)
   var isPartyLeader             : ObservableProperty = $OM.Calculated(this, "IsPartyLeader", true)
   var goldVal                   : ObservableProperty = $OM.Calculated(this, "GetGold", true)
   var crVal                     : ObservableProperty = $OM.Calculated(this, "GetCredits", true)
   var currentArmorLoadoutIdx    : ObservableProperty = $OM.Calculated(this, "GetCurrentArmorLoadoutIdx", true)
   var currentWeaponLoadoutIdx   : ObservableProperty = $OM.Calculated(this, "GetCurrentWeaponLoadoutIdx", true)
   var isWaitingLoadout          : ObservableProperty = $OM.Calculated(this, "GetIsWaitingLoadout", true)
   
   func GetCurrentArmorLoadoutIdx() : int
      var ud : UserData = (UserData) $UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
      return (int)ud.armor_loadouts.spartan.active_loadout_index.Get()
   end
   
   func GetArmorLoadout(_idx : int = -1) : UD_ArmorLoadout
      var ret : UD_ArmorLoadout  = null
      var idx : int              = _idx
      if (idx == -1)
         idx := GetCurrentArmorLoadoutIdx()
      end
      var ud         : UserData  = (UserData) $UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
      var loadouts   : vector    = ud.armor_loadouts.spartan.loadouts.Get()
      if (idx >= 0 and idx < loadouts.Count())
         ret := loadouts.Get(idx)
      end
      return ret
   end
   
   func GetShowroomArmorLoadout(_idx : int = -1) : UD_ArmorLoadout
      var ret : UD_ArmorLoadout  = null
      var idx : int              = _idx
      if (idx == -1)
         idx := (int)$UiGlobals.showroom.armor_loadouts.spartan.active_loadout_index.Get()
      end
      var loadouts : vector = $UiGlobals.showroom.armor_loadouts.spartan.loadouts.Get()
      if (idx >= 0 and idx < loadouts.Count())
         ret := loadouts.Get(idx)
      end
      return ret
   end
   
   func GetCurrentWeaponLoadoutIdx() : int
      var ud : UserData = (UserData) $UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
      return (int)ud.weapon_loadouts.spartan.active_loadout_index.Get()
   end
   
   func GetWeaponLoadout(_idx : int = -1) : UD_WeaponLoadout
      var ret : UD_WeaponLoadout  = null
      var idx : int              = _idx
      if (idx == -1)
         idx := GetCurrentWeaponLoadoutIdx()
      end
      var ud         : UserData  = (UserData) $UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
      var loadouts   : vector    = ud.weapon_loadouts.spartan.loadouts.Get()
      if (idx >= 0 and idx < loadouts.Count())
         ret := loadouts.Get(idx)
      end
      return ret
   end
   
   func GetCurrentLoadout() : UD_ArmorLoadout
      var ud : UserData = (UserData) $UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
      var lInd :  int = (int)ud.armor_loadouts.spartan.active_loadout_index.Get()
      var al :  UD_ArmorLoadout = (UD_ArmorLoadout)ud.armor_loadouts.spartan.loadouts.Get().Get(ud.armor_loadouts.spartan.active_loadout_index.Get())
      return al
   end
   
   func IsPartyLeader() : bool
      var pd : GL_ComponentUserPartyData = (GL_ComponentUserPartyData) $UiGlobals.componentsUserPartyData.Get($UserDataStorage.local_user.uid.Get())
      return (bool)pd.is_party_leader.Get()
   end
   
   func IsPartyLeaderVisible() : bool
      var partyMembers : vector = $UiGlobals.party.members.Get()
      return partyMembers.Count() > 1
   end
   
   func IsInParty() : bool
      var partyMembers : vector = $UiGlobals.party.members.Get()
      return partyMembers.Count() > 1
   end
   
   func GetTokenCount(tokenId : string) : *
      var ret  : * = $UiGlobals.IntToInt64(0)
      var i    : int
      var tokensVec : vector = tokens.Get()
      for i := 0 to tokensVec.Count() - 1
         var tokenState : GL_TokenState   = tokensVec.Get(i)
         var id         : string          = (string)tokenState.name.Get()
         if (id == tokenId)
            ret := tokenState.value.Get()
            break
         end
      end
      return ret
   end
   
   func GetGold() : *
      var ret  : * = GetTokenCount($uiEnums.TOKEN_GOLD)
      return ret
   end
   
   func GetCredits() : *
      var ret  : * = GetTokenCount($uiEnums.TOKEN_CREDITS)
      return ret
   end
   
   func GetIsWaitingLoadout() : bool
      var ret  : bool      = false      
      var ud   : UserData  = (UserData) $UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
      
      if (!(bool)ud.has_character_spartan_slot_0.Get())
         ret := true
         $user_service.RequestData($UserDataStorage.local_user.uid.Get(), $uiEnums.USER_DATA_CHARACTER_SLOT_0)
      end
      
      if (!(bool)ud.has_character_spartan_slot_1.Get())
         ret := true
         $user_service.RequestData($UserDataStorage.local_user.uid.Get(), $uiEnums.USER_DATA_CHARACTER_SLOT_1)
      end
      
      if (!(bool)ud.has_character_spartan_slot_2.Get())
         ret := true
         $user_service.RequestData($UserDataStorage.local_user.uid.Get(), $uiEnums.USER_DATA_CHARACTER_SLOT_2)
      end
      
      if (!(bool)ud.has_customizations.Get())
         ret := true
         $user_service.RequestData($UserDataStorage.local_user.uid.Get(), $uiEnums.USER_DATA_CUSTOMIZATIONS)
      end
      
      return ret
   end
   
   func GetEmblemId() : string
      var ret : string = $UserDataStorage.GetPlayerEmblemId(uid.Get())
      return ret
   end
   
   func GetEmblemIcon() : string
      var ret : string = $UserDataStorage.GetPlayerEmblemIcon(uid.Get())
      return ret
   end
end

/***************************************************************
* UserDataStorage
*
***************************************************************/   
class UserDataStorage : UiSslBindableBase
   var local_user : UserDataLocal      = null
   var users      : UiSslBindableMap   = null
   var invalidUID : GL_UID             = null
   var tmpUID     : GL_UID             = null
   
   func UserDataStorage()
      $UiGlobals.Init()
   end

   func GetUserDataAndData(_uid : *, _requestBase : bool = false) : UserData
      var ret : UserData = (UserData)users.Get(_uid)
      if (_requestBase and !(bool)ret.has_base.Get() and IsValidUID(_uid))
         $user_service.RequestData(_uid, $uiEnums.USER_DATA_BASE)
      end
      return ret
   end

   func GetInvalidUID() : *
      return invalidUID.value.Get()
   end
   
   func IsValidUID(_uid : *) : bool
      return UID2Str(_uid) != "0"
   end
   
   func UID2Str(_uid : *) : string
      tmpUID.value.Set(_uid)
      var ret : string = tmpUID.ToStr()
      return ret
   end
   
   func NewEmptyUID() : GL_UID
      var ret :  GL_UID = new GL_UID()
      ret.InitDefault()
      return ret
   end
   
   func IsEqualUIDs(_uid1 : *, _uid2 : *) : bool
      var uid1Str : string = UID2Str(_uid1)
      var uid2Str : string = UID2Str(_uid2)
      var ret     : bool   = uid1Str == uid2Str
      return ret
   end
   
   func IsLocalUID(_uid : *) : bool
      return IsEqualUIDs(_uid, local_user.uid.Get())
   end
   
   func IsInParty(_uid : *) : bool
      var ret        : bool      = false
      var partyVec   : vector    = $UiGlobals.party.members.Get()
      var i          : int
      for i := 0 to partyVec.Count() - 1
         var partyUID : GL_UID  = (GL_UID)partyVec.Get(i)
         if ($UserDataStorage.IsEqualUIDs(_uid, partyUID.value.Get()))
            ret := true
            break
         end
      end      
      return ret
   end
      
   func IsFriend(_uid : *) : bool
      var ret        : bool      = false
      var ud         : UserData  = (UserData)$UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
      var friendsVec : vector    = ud.social.following.Get()
      var i          : int
      for i := 0 to friendsVec.Count() - 1
         var friendUID : GL_UID  = (GL_UID)friendsVec.Get(i)
         if ($UserDataStorage.IsEqualUIDs(_uid, friendUID.value.Get()))
            ret := true
            break
         end
      end      
      return ret
   end
   
   func IsClanmate(_uid : *) : bool
      var ud         : UserData  = GetUserDataAndData(_uid, true)
      var udLocal    : UserData  = GetUserDataAndData(local_user.uid.Get(), true)      
      var ret        : bool      = false
      if (IsValidUID(udLocal.base.clan_id.Get()))
         ret := IsEqualUIDs(ud.base.clan_id.Get(), udLocal.base.clan_id.Get())
      end
      return ret
   end
   
   func GetUserColorCode(uid : *) : string
      if IsLocalUID(uid)
         return "me"
      elif IsClanmate(uid)
         return "clanmate"
      elif IsFriend(uid)
         return "friend"
      end
      return "defuser"
   end
   
   func GetPlayerStatusColorCode(_uid : *) : string
      var isLocal       :  bool     = IsLocalUID(_uid)
      var colorTag      :  string   = GetColorDefault()
      if (isLocal) 
         colorTag := GetColorLocal()
      else 
         var isFriend      :  bool     = IsFriend(_uid)
         var isClanmate    :  bool     = IsClanmate(_uid)
         if (isClanmate)
            colorTag := GetColorClanmate()         
         elif (isFriend)
            colorTag := GetColorFriend()
         end
      end
      return colorTag      
   end
   
   func GetPlayerEmblemId(_uid : *) : string
      var ret : string = "dummy"
      return ret
   end
   
   func GetPlayerLabel(uid : *, big : bool = false) : string
      var ret : string  =  ""
      var ud : UserData = $UserDataStorage.GetUserDataAndData(uid, true)
      if (!(bool)(ud.has_customizations.Get()))
         if ($UserDataStorage.IsValidUID(uid))
            $user_service.RequestData(uid, $uiEnums.USER_DATA_CUSTOMIZATIONS)
         end
      else
         var uiComp : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(ud.customizations.account_label.Get())
         if (big)
            ret := (string)uiComp.icon_big.Get()
         else
            ret := (string)uiComp.icon.Get()
         end
      end
      if (big and (ret == "" or ret == "unknown" or ret == "no_icon"))
         ret := "playerCardDefault"
      elif (ret == "" or ret == "unknown" or ret == "no_icon")
         ret := "defaultPlayerNameplate"
      end
      return ret
   end
   
   func GetPlayerEmblemIcon(_uid : *) : string
      var ret : string = ""  
      //if (IsEqualUIDs(local_user.uid.Get(), _uid))
      //   ret := "emb_standart2"
      //end
      var ud : UserData  = GetUserDataAndData(_uid, true)
      var compUi : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(ud.customizations.emblem.Get())
      ret := (string)compUi.icon.Get()
      if (ret == "") // tmp
         ret := "emb_standart1"
      end   
      return ret
   end
   
   func GetColorLocal() : string
      return "#f0e91e"
   end
   
   func GetColorPrivate() : string
      return "#CB5DCD"
   end
   
   func GetColorTeam() : string
      return "#FFC000"
   end
   
   func GetColorTeamRed() : string
      return "#f42727"
   end
   
   func GetColorTeamBlue() : string
      return "#466DF3"
   end
   
   func GetColorFriend() : string
      return "#52e800"
   end
   
   func GetColorClanmate() : string
      return "#FFA5FA"
   end
   
   func GetColorDefault() : string
      return "#FFFFFF"
   end
   
   func GetColorParty() : string
      return "#33FF99"
   end
   
   func GetColorSelected() : string
      return "#0072FF"
   end
   

   func GetPlayerPresenceColorCode(_uid : *) : string
      var ud         : UserData  = (UserData)$UserDataStorage.users.Get(_uid)
      var pState     : int       = (int)ud.presence.presence_state.Get()            
      var colorTag   : string    = "#808080"
      if (pState == $uiEnums.USER_PRESENCE_STATE_OFFLINE)
         colorTag := "#808080"
      elif (pState == $uiEnums.USER_PRESENCE_STATE_ONLINE)
         colorTag := "#00FF00"
      elif (pState == $uiEnums.USER_PRESENCE_STATE_INGAME)
         colorTag := "#FFFF00"
      else         
         colorTag := "#000000"
      end
      return colorTag      
   end
   
   func IsOnline(_uid : *) : bool
      var ud            : UserData  = (UserData)users.Get(_uid)
      var presenseState : int       = (int)ud.presence.presence_state.Get()
      return presenseState == $uiEnums.USER_PRESENCE_STATE_ONLINE or presenseState == $uiEnums.USER_PRESENCE_STATE_INGAME
   end
   
   func GetLocalUserData() : UserData
      var ud : UserData := (UserData)users.Get(local_user.uid.Get())
      return ud
   end
   
   func InvalidateWeaponLoadouts()
      var ud   : UserData = (UserData)$UserDataStorage.users.Get(local_user.uid.Get())
      var i    : int
      for i := 0 to ud.armor_loadouts.spartan.loadouts.Get().Count() - 1
         var ld : UD_WeaponLoadout = ud.weapon_loadouts.spartan.loadouts.Get().Get(i)
         ld.InvalidateCosts()
      end
   end
   
   func InvalidateArmorLoadouts()
      var ud   : UserData = (UserData)$UserDataStorage.users.Get(local_user.uid.Get())
      var i    : int
      for i := 0 to ud.armor_loadouts.spartan.loadouts.Get().Count() - 1
         var ld : UD_ArmorLoadout = ud.armor_loadouts.spartan.loadouts.Get().Get(i)
         ld.InvalidateCosts()
      end
   end
end
var $UserDataStorage : UserDataStorage
