import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_manager
import ssl.hf2p.engine_ctrl
import ssl.observables
import ssl.hf2p.ui_globals
import ui.ui_economy
import ssl.hf2p.user_data
import ui.root

class UiSlidingScreenPageBase : UiWidgetContainer
   handle OnEnteringState("Initial")
   end   

   handle OnEnterState("Initial")
      Set("visible", false)            
   end   

   handle OnEnteringState("Visible")
      Set("visible", true)
   end   

   handle OnEnterState("Visible")
   end

   func PrepareSlide()
      if (GetStateName() != "Visible")
         SetStateName("Visible")
         GenerateEvent("#OpenSlidingPage")
      else
         GenerateEvent("#PrepareSlide")
      end
   end

   func PrepareHideSlide()
   end

   func DisableSlide()
      if (GetStateName() != "Initial")
         SetStateName("Initial")
         GenerateEvent("#CloseSlidingPage")
      else
         GenerateEvent("#DisableSlide")
      end
   end

   func SwitchToScreen()
   end
end

class UiSlidingScreenPageBaseVM
   var isActive   : ObservableProperty = $OM.Property(false)
   
   func OpenSlidingPage(p : params) : bool
      isActive.Set(true)
      OnOpen() : 0.1
      return true
   end
   
   func PrepareSlide()
      
   end
   
   func DisableSlide()
      
   end
   
   func OnOpen()
      
   end
   
   func OnClose()
      
   end
   
   func CloseSlidingPage(p : params) : bool
      isActive.Set(false)
      OnClose()
      return true
   end   
end
