import ssl.lib.ui.ui_widget_container
import ui.root
import ssl.lib.logging
import ssl.hf2p.ui_ingame

class UiVictoryScreen : UiWidgetContainer

handle OnEnterState("Initial")
   Props.visible := false
end

handle OnEnteringState("Victory")
   Widgets.victory.Props.visible := true
   Widgets.defeat.Props.visible := false
   Widgets.tie.Props.visible := false
end

handle OnEnteringState("Defeat")
   Widgets.victory.Props.visible := false
   Widgets.defeat.Props.visible := true
   Widgets.tie.Props.visible := false
end

handle OnEnteringState("Tie")
   Widgets.victory.Props.visible := false
   Widgets.defeat.Props.visible := false
   Widgets.tie.Props.visible := true
end

handle OnEnterState("VictoryRunnerState")  
   var matchResult   : int    = (int)$UiIngame.match_result.tie_victory_defeat.Get()
   var isTeamMode    : bool   = (int)$UiIngame.team_index.Get() > $uiEnums.PLAYER_TEAM_NONE
   Props.visible   := true
   if (matchResult == $uiEnums.MATCH_RESULT_TIE)
      Widgets.tie.victoryHeader.tf := "ingame_endmatch_tie"
      Widgets.tie.descV.tf := "ingame_endmatch_tie_desc"
      $root.playSound("game_end_defeat")
      SetStateName("Tie")
   elif (matchResult == $uiEnums.MATCH_RESULT_VICTORY)
      Widgets.victory.victoryHeader.tf := "ingame_endmatch_victory"
      Widgets.victory.descV.tf := "ingame_endmatch_victory_desc"
      $root.playSound("game_end_victory")
      SetStateName("Victory")
   elif (matchResult == $uiEnums.MATCH_RESULT_DEFEAT)
      if (isTeamMode)
         Widgets.defeat.defeatHeader.tf := "ingame_endmatch_defeat"
         Widgets.defeat.descV.tf := "ingame_endmatch_defeat_desc"
         $root.playSound("game_end_defeat")
         SetStateName("Defeat")
      else
         Widgets.tie.victoryHeader.tf := "ingame_endmatch_match_complete"
         Widgets.tie.descV.tf := "ingame_endmatch_match_complete_desc"
         $root.playSound("game_end_defeat")
         SetStateName("Tie")
      end
   end
   
   
end

handle OnEnterState("Victory")
   GetParentWidget().SetStateName("VictoryFadeout")
end

handle OnEnterState("Defeat")
   GetParentWidget().SetStateName("VictoryFadeout")
   Props.visible := true
end

handle OnEnterState("Tie")
   GetParentWidget().SetStateName("VictoryFadeout")
   Props.visible := true
end

end