import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.game_preferences
import ui.menu_manager_as3

class UiRebindKeys : UiWidgetContainer


var setup_index : int = -1
var setup_primary : bool = true
var pause_to_show_key : bool = false
var preferences_biped : bool = true

var is_inited = false

var biped_keys : vector
var vehicle_keys : vector

func onBipedSelected(p:params):bool
Log("ui~rebind_keys", "__________________________________________________ On Biped Selected")
   preferences_biped := true
   Widgets().bipedTab.selected   := true
   Widgets().vehicleTab.selected := false
   Widgets().keyList.SetActionLabels($hf2pPreferences.GetActionLabels(preferences_biped))
   Widgets().keyList.SetKeys(biped_keys)
   Widgets().keyList.StartDefaultBlinking(0.2, 0.5)
   return false
end

func onVehicleSelected(p:params):bool
Log("ui~rebind_keys", "__________________________________________________ On Vehicle Selected")
   preferences_biped := false
   Widgets().vehicleTab.selected := true
   Widgets().bipedTab.selected   := false
   Widgets().keyList.SetActionLabels($hf2pPreferences.GetActionLabels(preferences_biped))
   Widgets().keyList.SetKeys(vehicle_keys)
   Widgets().keyList.StartDefaultBlinking(0.2, 0.5)
   return false
end

func Init()
   is_inited := true
   preferences_biped := true
   Widgets().vehicleTab.selected := false
   Widgets().bipedTab.selected   := true
   
Log("ui~rebind_keys", "__________________________________________________ On INIT")
   if (biped_keys.Count() == 0)
      biped_keys := $hf2pPreferences.GetKeyBinds(preferences_biped)
      vehicle_keys := $hf2pPreferences.GetKeyBinds(!preferences_biped)
   end

   Widgets().keyList.SetActionLabels($hf2pPreferences.GetActionLabels(preferences_biped))
   Widgets().keyList.SetKeys(biped_keys)
end

func ReInit()
   is_inited := true
   preferences_biped := true
   Widgets().vehicleTab.selected := false
   Widgets().bipedTab.selected   := true
   
   biped_keys := $hf2pPreferences.GetKeyBinds(true)
   vehicle_keys := $hf2pPreferences.GetKeyBinds(false)
end

func HaveUnsavedChanges() :  bool
   if (!is_inited)
      return false
   end
   
   var biped_keys_pref : vector
   var vehicle_keys_pref : vector

   var i : int 
   
   biped_keys_pref := $hf2pPreferences.GetKeyBinds(true)
   vehicle_keys_pref := $hf2pPreferences.GetKeyBinds(false)
   
   for i := 0 to biped_keys.Last()
      if (biped_keys.Get(i).primary != biped_keys_pref.Get(i).primary or biped_keys.Get(i).alternative != biped_keys_pref.Get(i).alternative)
         return true
      end
   end
   
   for i := 0 to vehicle_keys.Last()
      if (vehicle_keys.Get(i).primary != vehicle_keys_pref.Get(i).primary or vehicle_keys.Get(i).alternative != vehicle_keys_pref.Get(i).alternative)
         return true
      end
   end
   
   return false
end

func Reset()
   preferences_biped := true
   Widgets().vehicleTab.selected := false
   Widgets().bipedTab.selected   := true
   
   biped_keys := $hf2pPreferences.GetDefaultKeyBinds(true)
   vehicle_keys := $hf2pPreferences.GetDefaultKeyBinds(false)
   
   Widgets().keyList.SetActionLabels($hf2pPreferences.GetActionLabels(preferences_biped))
   Widgets().keyList.SetKeys(biped_keys)
end

func Apply()
   if (is_inited)
      $hf2pPreferences.SetKeyBinds(vehicle_keys, false)
      $hf2pPreferences.SetKeyBinds(biped_keys, true)
      
      GenerateEvent("OnApplyFinished")
   end
end

func PrimaryKeySetup(p:params):bool
   Log("ui~rebindpressevent", "Event index = " + (string)(p.index))
   ActionKeySetup(p.index, true)
   return false
end

func AltKeySetup(p:params):bool
   Log("ui~rebindpressevent", "Event index = " + (string)(p.index))
   ActionKeySetup(p.index, false)
   return false
end

func ActionKeySetup(index : int, primary : bool)
   Log("ui~rebindpressevent", "item clicked resolving")
   if (setup_index >= 0)
      // we are in the middle of binding a key already
      return
   end

   /*Widgets().bindBox.msg := "Press button for " + $hf2pPreferences.GetActionLabels(preferences_biped).Get(index) + " action, press ESC to cancel"
   Widgets().bindBox.btn := ""
   Widgets().bindBox.visible := true
   Widgets().bindBox.SetModal()*/
   
   var pp:params
   pp.callbackEvent  := ""
   pp.mbType := "BindBox"
   pp.callbackTarget := Widgets().keyList
   pp.titleTxt       := "settings_rebind_key" //"Press button for " + $hf2pPreferences.GetActionLabels(preferences_biped).Get(index) + " action, press ESC to cancel"
   pp.messageTxt     := ""
   
   GenerateEvent("OnSlidingScreenDialogRequest", pp)
   
   Log("ui~rebindpressevent", "now box must be showing!!!")

   setup_index := index
   setup_primary := primary
   $menu_manager_as3.PostKeyPressRequest()
   Log("ui~rebindpressevent", "ActionKeySetup end")
end

func CloseBindBox()
   Log("ui~rebindpressevent", "close bind box")
   Widgets().bindBox.visible := false
   pause_to_show_key := false
   setup_index := -1
end

global event OnKeyPress(p:params)
   Log("ui~rebindpressevent", "rebindkeypress")
   if (setup_index == -1 or pause_to_show_key)
      return
   end
Log("ui~rebindpressevent", "rebindkeypress1")
   if (p.key == 0)
      pause_to_show_key := false
      CloseBindBox()
      return
   end

Log("ui~rebindpressevent", "rebindkeypress2")
   RemoveKey(p.key, preferences_biped)
   if (setup_primary)
      if (preferences_biped)
         biped_keys.Get(setup_index).primary := p.key 
      else
         vehicle_keys.Get(setup_index).primary := p.key
      end
      Widgets().keyList.SetPrimaryKey(setup_index, p.key)
   else
      if (preferences_biped)
         biped_keys.Get(setup_index).alternative := p.key 
      else
         vehicle_keys.Get(setup_index).alternative := p.key
      end
      Widgets().keyList.SetAltKey(setup_index, p.key)
   end
Log("ui~rebindpressevent", "rebindkeypress3")
   // close bind action box in 1 second
   pause_to_show_key := true
   CloseBindBox() : 1
end

func RemoveKey(keycode : int, biped :  bool)
   var i : int

   var vec : *
   var pp : params
   
   pp.desc := "key_already_used"
   pp.message := "settings_lbl_key_was_aready_rebinded"
   
   if  (biped)
      vec := biped_keys
   else
      vec := vehicle_keys
   end
   
   for i := 0 to vec.Last()
      if (vec.Get(i).primary == keycode)
         GenerateEvent("OnSlidingScreenDialogControl", pp)
         vec.Get(i).primary := -1
      end
      if (vec.Get(i).alternative == keycode)
         GenerateEvent("OnSlidingScreenDialogControl", pp)
         vec.Get(i).alternative := -1
      end
   end
end

handle OnEnteringState("Initial")
   AddTween("alpha", 0.0, Props().adelay, "linear")
end          

handle OnEnterState("Initial")
   Set("visible", false)            
end  
        
handle OnEnteringState("Visible")
   Init()
   StartDefaultBlinking(0.2, 1.0)
   Set("visible", true)
   AddTween("alpha", 1.0, Props().adelay, "linear")
end  
end
