import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_manager
import ssl.hf2p.engine_ctrl
import ssl.observables
import ssl.hf2p.ui_globals
import ui.ui_economy
import ssl.hf2p.user_data
import ui.root

class UiContent : UiWidgetContainer

var isSlidingElement :  bool     = false

func OpenBuyDialogue(p : params) : bool
   var itemId : string = p.itemId
   var offer : GL_ComponentShopOffer = p.offer
   var isGold : bool = p.isGold
   var playerCurrency = 0
   var offerString : string
   var offerCost : int
   if offer == null
      return true
   end
   if isGold
      playerCurrency := (int)$UserDataStorage.local_user.gold.Get()
      offerString := (string)offer.gl_offer.Get()
      offerCost := (int)offer.gl_cost.Get()
   else
      playerCurrency := (int)$UserDataStorage.local_user.cr.Get()
      offerString := (string)offer.cr_offer.Get()
      offerCost := (int)offer.cr_cost.Get()
   end
   if offerString != ""
      var par: params
      par.itemID        :=  itemId
      par.offer         := offerString
      if isGold
         par.priceGold     := offerCost
      else
         par.priceCredit   := offerCost
      end
      if (offerCost <= playerCurrency)
         // is rent ?
         var ret : int = 0
         ret := (int)offer.rent_duration.Get()
         if (ret > 0)
            par.isRent := true
         end
         // end 
         par.mbType           := "ConfirmBuy"
         par.callbackEvent    := "OnItemPurchased"
         par.callbackTarget   := Props()
      else
         par.mbType     := "Info"
         par.titleTxt   := "msg_ui_warning"
         if isGold
            par.messageTxt := "msg_ui_not_enough_gp"
         else
            par.messageTxt := "msg_ui_not_enough_cr"
         end
      end
      $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
   end
   return true
end

func OnLeaveLobby() : bool
   Log("ui~content", " WeaponConfig::OnLeaveLobby() ")
   GenerateEvent("LeaveLobby")
   return false
end

func SwitchToScreen()   
   Widgets().weaponList.SetFocus()   
end

func OnOpenLoadoutBtnClicked(p:params):bool
   Log("ui~content", "OnOpenLoadoutBtnClicked")
   GenerateEvent("SeeLoadout", p)
   return false
end

handle OnEnteringState("Initial")
   Log("ui~content", "Weapon Config OnEntering Initial!!!")
end          

handle OnEnterState("Initial")
   Log("ui~content", "Weapon Config onEnter Initial!!!")
   Set("visible", false)            
end          

handle OnEnteringState("Visible")
   Log("ui~content", "Weapon Config OnEntering VISIBLE!!!")         
   Set("visible", true)
end  

handle OnEnterState("Visible")
   Log("ui~content", "Weapon Config onEnter VISIBLE!!!")         
end

func PrepareSlide()
   if (GetStateName() != "Visible")
      SetStateName("Visible")
   end
   EnableFakeBg()
   GenerateEvent("#OpenedWeaponConfig")
   StartDefaultBlinking(0.3)
end

func PrepareHideSlide()
end

func OnBlinkItemList(p : params) : bool
   Widgets().weaponList.SetSelectionIdx(0)
   Widgets().weaponList.StartDefaultBlinking(0.0)
   Widgets().loadoutSelector.StartDefaultBlinking(0.0)
   BarsBlink() : 0
   $root.playSound("screen_rollout")
   return false
end

func BarsBlink()
   Widgets().progressBars.StartDefaultBlinking(-0.4, 1.1)
end

func DisableSlide()
   if (GetStateName() != "Initial")
      SetStateName("Initial")
   end
end

func EnableFakeBg()
   var p: params
   p.state := "weapons"
   GenerateEvent("ChangeFakeBackground", p)
end

func OnItemPurchased(p : params) : bool
   if (p.isOK)
      GenerateEvent("#OnWeaponPurchased", p)
   end
   return true
end

func SetListSelection(p : params) : bool
   Widgets().weaponList.SetSelectionIdx(p.idx)
   return false
end

end

class WeaponItemLIR
   var wgt           : UiWidget = null
   var itemId        : ObservableProperty = $OM.Property("")

   var minOffer      : ObservableProperty = $OM.Calculated(this, "GetMinOffer") 
   var maxDiscount   : ObservableProperty = $OM.Calculated(this, "GetMaxDiscount") 

   var weaponTint    : ObservableProperty = $OM.Calculated(this, "GetWeaponTint")
   var isWeaponTintVisible : ObservableProperty = $OM.Calculated(this, "GetIsWeaponTintVisible")
   var offerGp       : ObservableProperty = $OM.Calculated(this, "GetOfferGp")
   var offerCr       : ObservableProperty = $OM.Calculated(this, "GetOfferCr")
   var ownType       : ObservableProperty = $OM.Calculated(this, "GetOwnType")
   var isOffers      : ObservableProperty = $OM.Calculated(this, "GetIsOffers")
   var rentStatus    : ObservableProperty = $OM.Calculated(this, "GetRentStatus")
   var rentStatusColor :  ObservableProperty = $OM.Calculated(this, "GetRentStatusColor")
   var weaponIndicatorScaleX    : ObservableProperty = $OM.Calculated(this, "GetWeaponIndicatorScaleX")
   var isGpCrLock    : ObservableProperty = $OM.Calculated(this, "GetIsGpCrLock")
   var equipIcn      : ObservableProperty = $OM.Calculated(this, "GetEquipIcon") 
   var isNew         : ObservableProperty = $OM.Calculated(this, "GetIsNew")
   var itemQuality   : ObservableProperty = $OM.Calculated(this, "GetWeaponQuality")
   
   func Init(p : params)
      wgt := p.widget
      if (! IsVoid(p.itemId))
         itemId.Set(p.itemId)
      end
      wgt.Props().mouseChildren := true
   end
   
   func Update(p : params)
      itemId.Set(p.itemId)
   end
   
   func OnItemPriceGoldClicked(p : params) : bool
      var p2 : params
      p2.itemId := itemId.Get()
      p2.offer := $UiGlobals.componentsShop.Get(itemId.Get()).GetMinimalOffer()
      p2.isGold := true
      wgt.GenerateEvent("#OpenBuyDialogue", p2)
      return true
   end
   
   func OnItemPriceCrClicked(p : params) : bool
      var p2 : params
      p2.itemId := itemId.Get()
      p2.offer := $UiGlobals.componentsShop.Get(itemId.Get()).GetMinimalOffer()
      p2.isGold := false
      wgt.GenerateEvent("#OpenBuyDialogue", p2)
      return true
   end
   
   func OnItemLirClicked(p : params) : bool
      var x : * = wgt.Props().mouseChildren
      
      if isNew.Get() == true
         $hq.ShopNewClear((string)itemId.Get())
      end
      return true
   end
   
   func GetMinOffer() : GL_ComponentShopOffer
      var ret : GL_ComponentShopOffer = null
      if ((bool)isOffers.Get())
         var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)itemId.Get())
         if (shopComp.offers.Get().Count() > 0)
            ret := shopComp.GetMinimalOffer()
         end
      end
      return ret
   end
      
   func GetMaxDiscount() : string
      var ret : string = ""
      if ((bool)isOffers.Get())
         var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)itemId.Get())
         if (shopComp.offers.Get().Count() > 0)
            var maxDisc : float = 0
            var i : int
            for i := 0 to shopComp.offers.Get().Count() - 1
               var offer : GL_ComponentShopOffer = shopComp.offers.Get().Get(i)
               if (float)offer.cr_sale_percentage.Get() > maxDisc
                  maxDisc := (float)offer.cr_sale_percentage.Get()
               end
               if (float)offer.gl_sale_percentage.Get() > maxDisc
                  maxDisc := (float)offer.gl_sale_percentage.Get()
               end
            end
            if maxDisc > 0
               ret := "-" + (string)(int)(maxDisc * 100) + "%"
            end
         end
      end
      return ret
   end
      
   func GetIsGpCrLock() : bool
      var ret : bool
      ret := IsCrLock() and IsGlLock()
      return ret
   end
   
   func GetWeaponTint() : params
      var itemIdS :  * = itemId.Get()
      var itemIdStr :  string = (string)itemId.Get()
      var   tint     : params = $uiEconomy.GetWeaponPrimaryArrtibuteColor("unknown")
      if (itemIdStr != "")
         var   weapon   :  GL_ComponentWeapon = (GL_ComponentWeapon)$UiGlobals.componentsWeapon.Get(itemIdStr)
         if (weapon != null)
            tint := $uiEconomy.GetWeaponPrimaryArrtibuteColor((string)weapon.primary_attribute_id.Get())
         end
      end
      return tint
   end
   
   func GetIsWeaponTintVisible() : bool
      var itemIdS :  * = itemId.Get()
      var itemIdStr :  string = (string)itemId.Get()
      var ret     : bool = false
      if (itemIdStr != "")
         var   weapon   :  GL_ComponentWeapon = (GL_ComponentWeapon)$UiGlobals.componentsWeapon.Get(itemIdStr)
         if (weapon != null)
            ret := (string)weapon.primary_attribute_id.Get() != "none" and (string)weapon.primary_attribute_id.Get() != ""
         end
      end
      return ret
   end
   
   func GetWeaponQuality() : string
      var ret : string = "common"
      var itemIdStr : string = (string)itemId.Get()
      if (itemIdStr != "")
         ret := (string)$UiGlobals.componentsUI.Get(itemIdStr).quality.Get()
      end
      return ret  
   end
   
   func GetWeaponIndicatorScaleX() : float
      var ret : float
      var ownTypeVal :  int = GetOwnType()
      if (ownTypeVal == $uiEnums.ITEM_OWN_TYPE_NONE)
         ret := 1.0
      else
         ret := 2.625
      end
      return ret
   end
   
   func GetEquipIcon() : bool
      var ret : bool
      var uiInventoryItem : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)itemId.Get())
      var equipType : int = (int)uiInventoryItem.equipped_state.Get()
      if (equipType == 2)
         ret := true
      else   
         ret := false
      end
      return ret
   end 
   
   func GetIsNew() : bool
      var ret = $uiEconomy.GetIsItemNew((string)itemId.Get())
      return ret
   end
   
   func GetOfferGp() : string
      if minOffer.Get() != null
         var offer = (GL_ComponentShopOffer)minOffer.Get()
         return (string)(int)offer.gl_cost.Get()
      else
         return "carousel_offer_na_small"
      end
   end
   
   func GetOfferCr() : string
      if minOffer.Get() != null
         var offer = (GL_ComponentShopOffer)minOffer.Get()
         return (string)(int)offer.cr_cost.Get()
      else
         return "carousel_offer_na_small"
      end
   end

   func GetOwnType() : int
      return $uiEconomy.GetItemOwnType((string)itemId.Get())
   end
   
   func GetIsOffers() : bool
      var ret : bool
      //if (GetOwnType() == $uiEnums.ITEM_OWN_TYPE_NONE and (IsGlLock() or IsCrLock()))         
      //if (GetOwnType() == $uiEnums.ITEM_OWN_TYPE_NONE or IsGlLock() or IsCrLock())         
      if (GetOwnType() == $uiEnums.ITEM_OWN_TYPE_NONE)         
         ret := true
      else
         ret := false
      end
      return ret
   end
   
   func GetRentTime() : int
      var ret        : int = 0
      var ownTypeVal : int = (int)ownType.Get()
      if (ownTypeVal == $uiEnums.ITEM_OWN_TYPE_RENTED)
         var uiInventoryItem : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)itemId.Get())
         var ownTime : int = (int)uiInventoryItem.ownership_time.Get() - (int)$UiGlobals.timer.Get()
         ret := ownTime
      end
      return ret      
   end
      
   func IsLocked() : bool
      return $uiEconomy.IsItemLocked((string)itemId.Get())
   end
   
   func IsGlLock() : bool
      return $uiEconomy.IsItemLockedGl((string)itemId.Get())
   end

   func IsCrLock() : bool
      return $uiEconomy.IsItemLockedCr((string)itemId.Get())
   end
   
   func GetRentStatusColor() : int
      return $uiEconomy.GetItemRentTintColor((string)itemId.Get())
   end
   
   func GetRentStatus() : string
      var ret        : string      
      
      var ownTypeVal : int = (int)ownType.Get()
      if (ownTypeVal == $uiEnums.ITEM_OWN_TYPE_PURCHASED)
         ret := "carousel_rent_time_purchased"
      elif (ownTypeVal == $uiEnums.ITEM_OWN_TYPE_RENTED)
         var ownTime : int = GetRentTime()
         if (ownTime > 0)
            ret := $root.MakeUiTimerStringMinutes(ownTime, true)
         else
            ret := "carousel_rent_time_expiring"
         end
      end
      
      return ret
   end
 end

class ItemDescPanelVM
   var itemId           : ObservableProperty = $OM.Property("")
   var itemDesc         : ObservableProperty = $OM.Calculated(this, "GetItemDesc")
   var itemSubDesc      : ObservableProperty = $OM.Calculated(this, "GetItemSubDesc")
   var itemName         : ObservableProperty = $OM.Calculated(this, "GetItemName")
   var isLockLineGp     : ObservableProperty = $OM.Calculated(this, "GetIsLockLineGp")
   var lockLineGp       : ObservableProperty = $OM.Calculated(this, "GetLockLineGp")
   var lockLineGpCoordY : ObservableProperty = $OM.Calculated(this, "GetLockLineGpCoordY")
   var isLockLineCr     : ObservableProperty = $OM.Calculated(this, "GetIsLockLineCr")
   var lockLineCr       : ObservableProperty = $OM.Calculated(this, "GetLockLineCr")
   var lockLineCrCoordY : ObservableProperty = $OM.Calculated(this, "GetLockLineCrCoordY")
   var weaponClr        : ObservableProperty = $OM.Calculated(this, "GetWeaponColor")
      
   func GetItemDesc() : string
      var ret     : string
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get((string)itemId.Get())
      ret := (string)compUI.desc.Get()
      return ret
   end
   
   func GetWeaponColor() : int
      var itemIdS   : * = itemId.Get()
      var itemIdStr : string = (string)itemId.Get()
      var tint      : params = $uiEconomy.GetWeaponPrimaryArrtibuteColor("unknown")
      var clr       : int = 0 
      if (itemIdStr != "")
         var   weapon   :  GL_ComponentWeapon = (GL_ComponentWeapon)$UiGlobals.componentsWeapon.Get(itemIdStr)
         if (weapon != null)
            tint := $uiEconomy.GetWeaponPrimaryArrtibuteColor((string)weapon.primary_attribute_id.Get())
            clr := $root.RGB2Clr(tint.r, tint.g, tint.b)
         end
      end
      return clr
   end
   
   func GetOwnType() : int
      return $uiEconomy.GetItemOwnType((string)itemId.Get())
   end
   
   func GetItemName() : string
      var ret     : string
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get((string)itemId.Get())
      ret := (string)compUI.name.Get()
      return ret
   end

   func GetItemSubDesc() : string
      var ret     : string = ""
      return ret
   end
   
   func GetIsLockLineGp() : bool
      return $uiEconomy.IsItemLockedGl((string)itemId.Get()) or $uiEconomy.IsItemLockedCr((string)itemId.Get())
   end
   
   func GetLockLineGp() : string
      var ret : string = ""
      if (GetIsLockLineGp())
         ret := (string)$uiEconomy.GetItemLockedGlLvl((string)itemId.Get())
      end
      return ret
   end
   
   func GetLockLineGpCoordY() : float
      var ret : float = 3
      if (GetIsLockLineCr())
         ret := -24
      end
      return ret
   end
   
   func GetIsLockLineCr() : bool
      return false
   end
   
   func GetLockLineCr() : string
      var ret : string = ""
      if (GetIsLockLineCr())
         ret := (string)$uiEconomy.GetItemLockedCrLvl((string)itemId.Get())
      end
      return ret
   end
   
   func GetLockLineCrCoordY() : float
      var ret : float = 3
      return ret
   end
   
   func UpdateItemId(val : string)
      itemId.Set(val)
   end
end

class ProgressBarsVM
   var itemId        : ObservableProperty = $OM.Property("")
   var colorDef      : ObservableProperty = $OM.Calculated(this, "GetDefColor")
   var colorDefInt   : ObservableProperty = $OM.Calculated(this, "GetDefColorInt")
   var colorDmg      : ObservableProperty = $OM.Calculated(this, "GetColorDmg")
   var colorAcc      : ObservableProperty = $OM.Calculated(this, "GetColorAcc")
   var colorRof      : ObservableProperty = $OM.Calculated(this, "GetColorRof")
   var colorAmmo     : ObservableProperty = $OM.Calculated(this, "GetColorAmmo")
   var colorAmmoTf   : ObservableProperty = $OM.Calculated(this, "GetColorAmmoInt")
   var colorRange    : ObservableProperty = $OM.Calculated(this, "GetColorRange") 
   var scaleDmg      : ObservableProperty = $OM.Calculated(this, "GetScaleDmg")
   var scaleAcc      : ObservableProperty = $OM.Calculated(this, "GetScaleAcc")
   var scaleRof      : ObservableProperty = $OM.Calculated(this, "GetScaleRof")
   var scaleAmmo     : ObservableProperty = $OM.Calculated(this, "GetScaleAmmo")
   var scaleRange    : ObservableProperty = $OM.Calculated(this, "GetScaleRange")
   var clipSize      : ObservableProperty = $OM.Calculated(this, "GetClipSize")
   // cmp
   var curLoadoutIdx : ObservableProperty = $OM.Property("")
   var itemQ         : ObservableProperty = $OM.Property(0)
   var dmgBar        : ObservableProperty = $OM.Calculated(this, "GetScaleDmgBar") 
   var dmgBarCmp     : ObservableProperty = $OM.Calculated(this, "GetScaleDmgBarCmp")
   var accBar        : ObservableProperty = $OM.Calculated(this, "GetScaleAccBar")
   var accBarCmp     : ObservableProperty = $OM.Calculated(this, "GetScaleAccBarCmp")
   var rofBar        : ObservableProperty = $OM.Calculated(this, "GetScaleRofBar")
   var rofBarCmp     : ObservableProperty = $OM.Calculated(this, "GetScaleRofBarCmp")
   var rngBar        : ObservableProperty = $OM.Calculated(this, "GetScaleRngBar")
   var rngBarCmp     : ObservableProperty = $OM.Calculated(this, "GetScaleRngBarCmp")
   var colorMin      : ObservableProperty = $OM.Calculated(this, "GetMinColor")
   var colorMax      : ObservableProperty = $OM.Calculated(this, "GetMaxColor")
   //var cmpBarColor   : ObservableProperty = $OM.Calculated(this, "GetCmpBarColor")
   
   func UpdateItemId(val : string)
      itemId.Set(val)
   end
   
   func GetScaleDmgBar() : float
      var ret : float
      var selectedWpn  :  GL_ComponentWeapon = GetWpnStats()
      var wpnStat      :  float = 0
      var myWpn        :  GL_ComponentWeapon = GetMyWeapon()
      var myWpnStat    :  float = 0 
      if (selectedWpn == null or myWpn == null)
         return 0
      end
      // null check
      wpnStat := (float)selectedWpn.damage.Get()
      myWpnStat := (float)myWpn.damage.Get()
      if (wpnStat >= myWpnStat)
         ret := myWpnStat
      else
         ret := wpnStat
      end
      return ret
   end
   
   func GetScaleDmgBarCmp() : float
      var ret : float
      var selectedWpn  :  GL_ComponentWeapon = GetWpnStats()
      var wpnStat      :  float = 0
      var myWpn        :  GL_ComponentWeapon = GetMyWeapon()
      var myWpnStat    :  float = 0 
      if (selectedWpn == null or myWpn == null)
         return 0
      end
      // null check
      wpnStat := (float)selectedWpn.damage.Get()
      myWpnStat := (float)myWpn.damage.Get()
      if (wpnStat >= myWpnStat)
         ret := wpnStat
      else
         ret := myWpnStat
      end
      return ret 
   end
   
   func GetScaleAccBar() : float
      var ret : float
      var selectedWpn  :  GL_ComponentWeapon = GetWpnStats()
      var wpnStat      :  float = 0
      var myWpn        :  GL_ComponentWeapon = GetMyWeapon()
      var myWpnStat    :  float = 0 
      if (selectedWpn == null or myWpn == null)
         return 0
      end
      wpnStat := (float)selectedWpn.accuracy.Get()
      myWpnStat := (float)myWpn.accuracy.Get()
      if (wpnStat >= myWpnStat)
         ret := myWpnStat
      else
         ret := wpnStat
      end
      return ret
   end
   
   func GetScaleAccBarCmp() : float
      var ret : float
      var selectedWpn  :  GL_ComponentWeapon = GetWpnStats()
      var wpnStat      :  float = 0
      var myWpn        :  GL_ComponentWeapon = GetMyWeapon()
      var myWpnStat    :  float = 0 
      if (selectedWpn == null or myWpn == null)
         return 0
      end
      wpnStat := (float)selectedWpn.accuracy.Get()
      myWpnStat := (float)myWpn.accuracy.Get()
      if (wpnStat >= myWpnStat)
         ret := wpnStat
      else
         ret := myWpnStat
      end
      return ret 
   end
   
   func GetScaleRofBar() : float
      var ret : float
      var selectedWpn  :  GL_ComponentWeapon = GetWpnStats()
      var wpnStat      :  float = 0
      var myWpn        :  GL_ComponentWeapon = GetMyWeapon()
      var myWpnStat    :  float = 0 
      if (selectedWpn == null or myWpn == null)
         return 0
      end
      wpnStat := (float)selectedWpn.rate_of_fire.Get()
      myWpnStat := (float)myWpn.rate_of_fire.Get()
      if (wpnStat >= myWpnStat)
         ret := myWpnStat
      else
         ret := wpnStat
      end
      return ret
   end
   
   func GetScaleRofBarCmp() : float
      var ret : float
      var selectedWpn  :  GL_ComponentWeapon = GetWpnStats()
      var wpnStat      :  float = 0
      var myWpn        :  GL_ComponentWeapon = GetMyWeapon()
      var myWpnStat    :  float = 0 
      if (selectedWpn == null or myWpn == null)
         return 0
      end
      wpnStat := (float)selectedWpn.rate_of_fire.Get()
      myWpnStat := (float)myWpn.rate_of_fire.Get()
      if (wpnStat >= myWpnStat)
         ret := wpnStat
      else
         ret := myWpnStat
      end
      return ret 
   end
   
   func GetScaleRngBar() : float
      var ret : float
      var selectedWpn  :  GL_ComponentWeapon = GetWpnStats()
      var wpnStat      :  float = 0
      var myWpn        :  GL_ComponentWeapon = GetMyWeapon()
      var myWpnStat    :  float = 0 
      if (selectedWpn == null or myWpn == null)
         return 0
      end
      wpnStat := (float)selectedWpn.range.Get()
      myWpnStat := (float)myWpn.range.Get()
      if (wpnStat >= myWpnStat)
         ret := myWpnStat
      else
         ret := wpnStat
      end
      return ret
   end
   
   func GetScaleRngBarCmp() : float
      var ret : float
      var selectedWpn  :  GL_ComponentWeapon = GetWpnStats()
      var wpnStat      :  float = 0
      var myWpn        :  GL_ComponentWeapon = GetMyWeapon()
      var myWpnStat    :  float = 0 
      if (selectedWpn == null or myWpn == null)
         return 0
      end
      wpnStat := (float)selectedWpn.range.Get()
      myWpnStat := (float)myWpn.range.Get()
      if (wpnStat >= myWpnStat)
         ret := wpnStat
      else
         ret := myWpnStat
      end
      return ret 
   end
   
   func GetCmpBarColor(paramName : string) : params
      var ret : params
      var selectedWpn  :  GL_ComponentWeapon = GetWpnStats()
      var wpnStat      :  float = 0
      var myWpn        :  GL_ComponentWeapon = GetMyWeapon()
      var myWpnStat    :  float = 0 
      if (selectedWpn == null or myWpn == null)
         ret.r  := 33
         ret.g  := 61
         ret.b  := 98
         return ret
      end
      if (paramName == "dmg")
         wpnStat := (float)selectedWpn.damage.Get()
         myWpnStat := (float)myWpn.damage.Get()
      elif  (paramName == "acc")
         wpnStat := (float)selectedWpn.accuracy.Get()
         myWpnStat := (float)myWpn.accuracy.Get()
      elif  (paramName == "rof")
         wpnStat := (float)selectedWpn.rate_of_fire.Get()
         myWpnStat := (float)myWpn.rate_of_fire.Get()
      elif  (paramName == "rng")
         wpnStat := (float)selectedWpn.range.Get()
         myWpnStat := (float)myWpn.range.Get()
      end
      if (wpnStat >= myWpnStat)
         ret.r  := 166
         ret.g  := 248
         ret.b  := 255
      else
         ret.r  := 48
         ret.g  := 76
         ret.b  := 103
      end
      return ret
   end
   
   func GetMinColor() : params
      var ret: params
      ret.r  := 33
      ret.g  := 61
      ret.b  := 98
      return ret
   end
   
   func GetMaxColor() : params
      var ret: params
      ret.r  := 143
      ret.g  := 228
      ret.b  := 255
      return ret
   end
   
   func GetPrimaryQuality() : int
      var i : int
      for i := 0 to $UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get()).weapons.Get().Count() - 1
         if $UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get()).weapons.Get().Get(i).section_id.Get() == "section_weapons_primary"
            return i
         end
      end
      return -1
   end
   
   func GetSecondaryQuality() : int
      var i : int
      for i := 0 to $UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get()).weapons.Get().Count() - 1
         if $UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get()).weapons.Get().Get(i).section_id.Get() == "section_weapons_secondary"
            return i
         end
      end
      return -1
   end
   
   func GetMyWeapon() : GL_ComponentWeapon
      var wpnStr : string
      var quality : int = (int)itemQ.Get()
      var weapon   :  GL_ComponentWeapon = null
      var ud : UserData = (UserData) $UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
      var loadout : UD_WeaponLoadout = (UD_WeaponLoadout)ud.weapon_loadouts.spartan.loadouts.Get().Get((int)ud.weapon_loadouts.spartan.active_loadout_index.Get())
      if (quality == GetPrimaryQuality())
         wpnStr := (string)loadout.primary_weapon.Get()
      elif (quality == GetSecondaryQuality())
         wpnStr := (string)loadout.secondary_weapon.Get()
      else // hack
         wpnStr := (string)itemId.Get()
      end
      weapon :=  (GL_ComponentWeapon)$UiGlobals.componentsWeapon.Get(wpnStr)
      return weapon
   end
   
   func GetPrimaryAttribute() : string      
      var itemIdStr  : string = (string)itemId.Get()
      var ret        : string = ""
      if (itemIdStr != "")
         var   weapon   :  GL_ComponentWeapon = (GL_ComponentWeapon)$UiGlobals.componentsWeapon.Get(itemIdStr)
         if (weapon != null)
            ret := (string)weapon.primary_attribute_id.Get()
         end
      end
      return ret
   end
   
   func GetAttributeColor(_attribute : string, _primaryAttribute : string) : params
      var ret : params = $uiEconomy.GetWeaponPrimaryArrtibuteColor("unknown")
      if (_attribute == _primaryAttribute)
         ret := $uiEconomy.GetWeaponPrimaryArrtibuteColor(_attribute)
      elif (_primaryAttribute == "power") 
         ret := $uiEconomy.GetWeaponPrimaryArrtibuteColor(_primaryAttribute)
      end
      return ret
   end
   
   func GetWpnStats() : GL_ComponentWeapon
      var itemIdStr  : string = (string)itemId.Get()
      var   weapon   :  GL_ComponentWeapon = null
      if (itemIdStr != "")
         weapon :=  (GL_ComponentWeapon)$UiGlobals.componentsWeapon.Get(itemIdStr)
      end
      return weapon
   end
   
   func GetScaleDmg() : float
      var   weapon   :  GL_ComponentWeapon = GetWpnStats()
      var   ret      :  float = 0
      if (weapon != null)
         ret := (float)weapon.damage.Get()
      end
      return ret
   end
   
   func GetScaleAcc() : float
      var   weapon   :  GL_ComponentWeapon = GetWpnStats()
      var   ret      :  float = 0
      if (weapon != null)
         ret := (float)weapon.accuracy.Get()
      end
      return ret
   end

   func GetScaleRof() : float
      var   weapon   :  GL_ComponentWeapon = GetWpnStats()
      var   ret      :  float = 0
      if (weapon != null)
         ret := (float)weapon.rate_of_fire.Get()
      end
      return ret
   end

   func GetScaleAmmo() : float
      var   weapon   :  GL_ComponentWeapon = GetWpnStats()
      var   ret      :  float = 0
      if (weapon != null)
         //ret := (float)weapon.reload_speed.Get()
      end
      return ret
   end
   
   func GetScaleRange() : float
      var   weapon   :  GL_ComponentWeapon = GetWpnStats()
      var   ret      :  float = 0
      if (weapon != null)
         ret := (float)weapon.range.Get()
      end
      return ret
   end 
   
   func GetClipSize() : int
      var   weapon   :  GL_ComponentWeapon = GetWpnStats()
      var ret : int = 0 
      if (weapon != null)
         ret := (int)weapon.clip_size.Get()
      end
      return ret
   end
   
   func GetDefColor() : params
      var ret : params = $uiEconomy.GetWeaponPrimaryArrtibuteColor("unknown")
      return ret
   end
   
   func GetDefColorInt : int
      var defClr : params = $uiEconomy.GetWeaponPrimaryArrtibuteColor("unknown")
      var clr : int = $root.RGB2Clr(defClr.r, defClr.g, defClr.b)
      return clr
   end
   
   func GetColorDmg() : params
      return GetAttributeColor("damage", GetPrimaryAttribute())
   end

   func GetColorAcc() : params
      return GetAttributeColor("accuracy", GetPrimaryAttribute())
   end
   
   func GetColorRof() : params
      return GetAttributeColor("rof", GetPrimaryAttribute())
   end
   
   func GetColorAmmo() : params
      return GetAttributeColor("ammo", GetPrimaryAttribute())
   end
   
   func GetColorAmmoInt() : int
      var ret : int = 16777215
      if (GetPrimaryAttribute() == "ammo")
         var p : params = GetColorAmmo()
         ret := $root.RGB2Clr(p.r, p.g, p.b)
      end  
      return ret
   end
   
   func GetColorRange() : params
      return GetAttributeColor("range", GetPrimaryAttribute())
   end
   
end

class OffersLineVM
   var itemId     : ObservableProperty = $OM.Property("")
   var offerIdx   : ObservableProperty = $OM.Property(0)
   var isVisible  : ObservableProperty = $OM.Property(false)
   var isWide     : ObservableProperty = $OM.Property(false)
   var yPos       : ObservableProperty = $OM.Property(0.0)
   var offer      : ObservableProperty = $OM.Calculated(this, "GetOffer")
   var isGpOffer  : ObservableProperty = $OM.Calculated(this, "GetIsGpOffer")
   var gpOffer    : ObservableProperty = $OM.Calculated(this, "GetGpOffer")
   var gpCost     : ObservableProperty = $OM.Calculated(this, "GetGpCost")
   var gpOldCost  : ObservableProperty = $OM.Calculated(this, "GetGpOldCost")
   var gpDiscount : ObservableProperty = $OM.Calculated(this, "GetGpDiscount")
   var gpAlpha    : ObservableProperty = $OM.Calculated(this, "GetGpAlpha")
   var isCrOffer  : ObservableProperty = $OM.Calculated(this, "GetIsCrOffer")
   var crOffer    : ObservableProperty = $OM.Calculated(this, "GetCrOffer")
   var crCost     : ObservableProperty = $OM.Calculated(this, "GetCrCost")
   var crOldCost  : ObservableProperty = $OM.Calculated(this, "GetCrOldCost")
   var crDiscount : ObservableProperty = $OM.Calculated(this, "GetCrDiscount")
   var crAlpha    : ObservableProperty = $OM.Calculated(this, "GetCrAlpha")
   var durationTxt   : ObservableProperty = $OM.Calculated(this, "GetDurationTxt")
   var durationLabel : ObservableProperty = $OM.Calculated(this, "GetDurationLabel")
   var shopWidget : UiWidget = null
      
   func OnUnlockWpnGoldBtnClick(p : params) : bool
      var p2 : params
      p2.itemId := itemId.Get()
      p2.offer := offer.Get()
      p2.isGold := true
      shopWidget.GenerateEvent("#OpenBuyDialogue", p2)
      return true
   end
         
   func OnUnlockWpnCrBtnClick(p : params) : bool
      var p2 : params
      p2.itemId := itemId.Get()
      p2.offer := offer.Get()
      p2.isGold := false
      shopWidget.GenerateEvent("#OpenBuyDialogue", p2)
      return true
   end
   
   func GetOffer() : GL_ComponentShopOffer
      var itemIdVal  : string                = (string)itemId.Get()
      var ret        : GL_ComponentShopOffer = null
      if (itemIdVal != "")
         var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)itemId.Get())
         if (shopComp.offers.Get().Count() > 0)
            var offerIdxVal : int = (int)offerIdx.Get()
            if (offerIdxVal < shopComp.offers.Get().Count())
               ret := (GL_ComponentShopOffer)shopComp.offers.Get().Get(offerIdxVal)
            end
         end
      end
      return ret      
   end
   
   
   func GetOwnType() : int
      return $uiEconomy.GetItemOwnType((string)itemId.Get())
   end
   
   func IsGlLock() : bool
      return $uiEconomy.IsItemLockedGl((string)itemId.Get())
   end

   func IsCrLock() : bool
      return $uiEconomy.IsItemLockedCr((string)itemId.Get())
   end
   
   func GetIsGpOffer() : bool
      return ((string)gpOffer.Get()) != "" and ! IsGlLock() and IsOffersRequestsEnabled() and ! $uiPartyMonitor.IsMatchCountdown()
   end
   
   func IsOffersRequestsEnabled() : bool
      var ret : bool = false
      ret := (int)$UiGlobals.backend_requests.apply_offer.progress.state.Get() == $uiEnums.BACKEND_REQUEST_STATE_NONE
      return ret
   end
   
   func GetGpCost() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = "carousel_offer_na_small"
      if (offerVal != null)
         if ((int)offerVal.gl_cost.Get() > 0)
            ret := (string)offerVal.gl_cost.Get()
         end
      end
      return ret
   end
   
   func GetGpOldCost() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = "carousel_offer_na_small"
      if (offerVal != null)
         if ((float)offerVal.gl_sale_percentage.Get() < 1)
            ret := (string)(int)((int)offerVal.gl_cost.Get() / (1 - (float)offerVal.gl_sale_percentage.Get()))
         else
            ret := "0"
         end
      end
      Fire("UpdateCrossOutLines")
      return ret
   end
   
   func GetGpDiscount() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = ""
      if (offerVal != null)
         if ((int)offerVal.gl_cost.Get() > 0 and (float)offerVal.gl_sale_percentage.Get() > 0)
            ret := "-" + (string)(int)((float)offerVal.gl_sale_percentage.Get() * 100) + "%"
         end
      end
      return ret
   end
   
   func GetGpAlpha() : float
      var ret : float = 100
      if (GetGpOffer() == "")
         ret := 40
      end
      return ret
   end
   
   func GetCrAlpha() : float
      var ret : float = 100
      if (GetCrOffer() == "")
         ret := 40
      end
      return ret
   end
   
   func GetGpOffer() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = ""
      if (offerVal != null)
         if ((int)offerVal.gl_cost.Get() > 0)
            ret := (string)offerVal.gl_offer.Get()
         end
      end
      return ret
   end
   
   func GetIsCrOffer() : bool
      return ((string)crOffer.Get()) != "" and ! IsCrLock() and IsOffersRequestsEnabled() and ! $uiPartyMonitor.IsMatchCountdown()
   end
   
   func GetCrCost() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = "carousel_offer_na_small"
      if (offerVal != null)
         if ((int)offerVal.cr_cost.Get() > 0)
            ret := (string)offerVal.cr_cost.Get()
         end
      end
      return ret
   end
   
   func GetCrOldCost() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = "carousel_offer_na_small"
      if (offerVal != null)
         if ((float)offerVal.cr_sale_percentage.Get() < 1)
            ret := (string)(int)((int)offerVal.cr_cost.Get() / (1 - (float)offerVal.cr_sale_percentage.Get()))
         else
            ret := "0"
         end
      end
      Fire("UpdateCrossOutLines")
      return ret
   end
   
   func GetCrDiscount() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = ""
      if (offerVal != null)
         if ((int)offerVal.cr_cost.Get() > 0 and (float)offerVal.cr_sale_percentage.Get() > 0)
            ret := "-" + (string)(int)((float)offerVal.cr_sale_percentage.Get() * 100) + "%"
         end
      end
      return ret
   end

   func GetCrCostInt() : int
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : int                   = 0
      if (offerVal != null)
         ret := (int)offerVal.cr_cost.Get()
      end
      return ret
   end
   
   func GetGpCostInt() : int
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : int                   = 0
      if (offerVal != null)
         ret := (int)offerVal.gl_cost.Get()
      end
      return ret
   end
   
   func GetDurationTxt() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = ""
      if (offerVal != null)
         var durationParm : params = offerVal.DurationToStrings()
         ret := durationParm.daysCount
      end
      return ret
   end

   func GetDurationLabel() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = ""
      if (offerVal != null)
         var durationParm : params = offerVal.DurationToStrings()
         ret := durationParm.daysLabel
      end
      return ret
   end

   func GetCrOffer() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = ""
      if (offerVal != null)
         if ((int)offerVal.cr_cost.Get() > 0)
            ret := (string)offerVal.cr_offer.Get()         
         end
      end
      return ret
   end
end

class OffersModuleVM
   var parentVM : ItemShopBaseVM = null
   
   var itemId        : ObservableProperty = $OM.Property("")
   var offersCount   : ObservableProperty = $OM.Calculated(this, "GetOffersCount")
   var canAssign     : ObservableProperty = $OM.Calculated(this, "GetCanAssign")
   var hasOffers     : ObservableProperty = $OM.Calculated(this, "GetHasOffers")
   var offers        : ObservableProperty = $OM.Calculated(this, "GetOffers")
   var headerY       : ObservableProperty = $OM.Calculated(this, "GetHeaderY")
   var headerText    : ObservableProperty = $OM.Calculated(this, "GetHeaderText")   
   var assignY       : ObservableProperty = $OM.Calculated(this, "GetAssignY")
   var assignAlpha   : ObservableProperty = $OM.Calculated(this, "GetAssignAlpha")
   var assignEnabled : ObservableProperty = $OM.Calculated(this, "GetAssignEnabled")
   var assignText    : ObservableProperty = $OM.Calculated(this, "GetAssignText")
   var ownTypeInternal:ObservableProperty = $OM.Calculated(this, "GetOwnTypeInternal")
   var lockStatus    : ObservableProperty = $OM.Calculated(this, "GetLockStatus")
   var isWide        : ObservableProperty = $OM.Property(false)
   var purchasedTxt  : ObservableProperty = $OM.Property("carousel_txt_purchased")
   var nonPurchasedTxt: ObservableProperty = $OM.Property("carousel_txt_non_purchased")
   var addTimeTxt    : ObservableProperty = $OM.Property("carousel_txt_purchased_add_time")
   var rentTxt       : ObservableProperty = $OM.Property("carousel_txt_non_purchased_rent")
   var isSpartanArmory : ObservableProperty = $OM.Property(false)
   var shopWidget    : UiWidget           = null
   var wgt           : UiWidget           = null
   var offerLines    : vector
   var maxOffers     : int = 5
   var y0            : float = 262.0
   //var offer0        : ObservableProperty = $OM.Property(null)   
   var isSubscribed  : bool               = false
      
      
   func SubscribeToUpdates()
      if (! isSubscribed)
         hasOffers.Subscribe(this, "UpdateOfferLinesSubsciption")
         offersCount.Subscribe(this, "UpdateOfferLinesSubsciption")
         isSubscribed := true         
      end
   end
   
   func UnsubscribeFromUpdates()
      if (isSubscribed)
         hasOffers.Unsubscribe(this, "UpdateOfferLinesSubsciption")
         offersCount.Unsubscribe(this, "UpdateOfferLinesSubsciption")
         isSubscribed := false
      end      
   end
   
   func Term()
      UnsubscribeFromUpdates()
   end
   
   func OnAssignBtnClicked(p : params) : bool
      if (((string)itemId.Get()) != "" and ((string)itemId.Get()) != "null")
         if lockStatus.Get() == "locked"
            var compShop : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(itemId.Get())
            $UiGlobals.techOpenTechId := (string)compShop.requirement.Get()
            shopWidget.GenerateEvent("OpenTechTreeScreen")
         else
            UpdateItemId((string)itemId.Get())
            offersCount.Invalidate()
            Go2Loadout(0.0, (string)itemId.Get())
         end
      end
      return false
   end

   func AssignItem(_itemId :  string)
      //$user_service.SetLoadout(_itemId)
   end
   
   func AssignWeapon(_itemId :  string)
      $user_service.SetWeaponLoadoutWeapon($hf2pEngine.GetUIPlayerModelId(), (int)parentVM.selectedLoadoutIdx.Get(), _itemId)
   end
   
   func AssignArmor(_armorId :  string)
      var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(_armorId)
      
      $user_service.SetArmorLoadoutItem($hf2pEngine.GetUIPlayerModelId(), (int)parentVM.selectedArmorLoadoutIdx.Get(), _armorId)      
   end
   
   global event OnSpartanStoreOpen()
      isSpartanArmory.Set(true)
   end

   global event OnSpartanStoreClose()
      isSpartanArmory.Set(false)
   end

   func Go2LoadoutAfterPurchase(_itemId : string)
      if (! $uiPartyMonitor.IsMatchCountdown())
         Go2Loadout(0.0, _itemId)
      end
   end
   
   func GetItemIdVal() : string
      return (string)itemId.Get()
   end
      
   func Go2Loadout(_delay: float = 0.0, _itemId : string)
      var itemType : int = $uiEconomy.GetItemType(_itemId)
      if itemType == $uiEnums.ITEM_TYPE_WEAPON
         //AssignWeapon(_itemId)
         Go2LoadoutType("weapon", _itemId): _delay
      elif itemType == $uiEnums.ITEM_TYPE_TACTICAL
         Go2LoadoutType("consumable", _itemId): _delay
      elif itemType == $uiEnums.ITEM_TYPE_ARMOR
         //AssignArmor(_itemId)
         Go2LoadoutType("armor", _itemId) : _delay
      elif itemType == $uiEnums.ITEM_TYPE_ARMOR_SUIT
         Go2LoadoutType("armor_suit", _itemId) : _delay
      elif itemType == $uiEnums.ITEM_TYPE_UNKNOWN
         if parentVM.shopType == $uiEnums.SHOP_TYPE_TACTICAL
            Go2LoadoutType("booster", _itemId): _delay
         elif parentVM.shopType == $uiEnums.SHOP_TYPE_WEAPON
            //AssignItem(_itemId)
            Go2LoadoutType("weapon", _itemId): _delay
         end
      end
   end

   func Go2LoadoutType(_loadoutType: string, _itemId : string)
      if (_loadoutType == "weapon")
         Go2WeaponLoadout(_itemId)
      else if (_loadoutType == "consumable")
         Go2TacticalLoadout(_itemId)
      else if (_loadoutType == "booster")
         Go2BoosterLoadout(_itemId)
      else if (_loadoutType == "armor")
         Go2ArmoryLoadout(_itemId)
      else if (_loadoutType == "armor_suit")
         Go2ArmoryLoadout(_itemId)
      end
   end

   func Go2WeaponLoadout(_itemId : string)
      var p       : params
      p.itemId       := _itemId
      p.minSlotIdx   := 0
      p.maxSlotIdx   := 2
      p.closeEvent   := "openWeaponConfig"
      $sslWidgetMgr.GenerateEvent("openLoadoutAssignWpnConf", p)
   end

   func Go2TacticalLoadout(_itemId : string)
      var p:params
      p.itemId       := _itemId
      p.minSlotIdx   := 3
      p.maxSlotIdx   := 8
      p.closeEvent   := "openTacticalPackages"
      $sslWidgetMgr.GenerateEvent("openLoadoutAssignPerks", p)
   end

   func Go2BoosterLoadout(_itemId : string)
      var p:params
      p.itemId       := _itemId
      p.minSlotIdx   := 7
      p.maxSlotIdx   := 7
      p.closeEvent   := "openTacticalPackages"
      $sslWidgetMgr.GenerateEvent("openLoadoutAssignBooster", p)
   end

   func Go2ArmoryLoadout(_itemId : string)
      Log("ui~wc_weaponContBig", "Go2ArmoryLoadout (itemID) -> ( " + _itemId + " )")
      var p:params
      p.armorId   := _itemId       
      p.armorType := "item"
      
      $sslWidgetMgr.GenerateEvent("openArmorLoadoutAssgin", p)
   end
   
   func OffersModuleVM()
      var i : int
      for i := 0 to maxOffers - 1
         var offerLine : OffersLineVM = new OffersLineVM()
         offerLine.offerIdx.Set(i)
         offerLines.Push(offerLine)
      end
   end
   
   func UpdateOfferLinesSubsciption()
      UpdateOfferLines()
   end
   
   func UpdateOfferLines()
      var i             : int
      var totalOffers   : int    = (int)offersCount.Get()
      for i := 0 to maxOffers - 1
         var offerLine : OffersLineVM = offerLines.Get(i)
                  
         var y : float = y0 - 47.0 * (i + 1)
         offerLine.yPos.Set(y)                  
         offerLine.itemId.Set(itemId.Get())
         offerLine.shopWidget := shopWidget
         
         if (i < totalOffers)
            offerLine.isVisible.Set(true)
         else
            offerLine.isVisible.Set(false)
         end         
         offerLine.isWide.Set((bool)isWide.Get())
      end
   end
      
   func UpdateItemId(_itemId : string)
      itemId.Set(_itemId)
      UpdateOfferLines()
      UnsubscribeFromUpdates()
      SubscribeToUpdates()
   end
   
   func GetOffersCount() : int
      var ret : int
      ret := GetOffers().Count()
      if (GetOwnType() == $uiEnums.ITEM_OWN_TYPE_PURCHASED)
         ret := 0
      end
      return ret
   end
   
   func GetCanAssign() : bool
      var ret : bool
      
      ret := GetOwnType() != $uiEnums.ITEM_OWN_TYPE_NONE and ! $uiPartyMonitor.IsMatchCountdown()            
      
      return ret
   end

   func GetHasOffers() : bool
      var ret : bool
      if (GetOwnType() != $uiEnums.ITEM_OWN_TYPE_PURCHASED and GetOffers().Count() > 0)
         ret := true
      end
      return ret 
   end
   
   func CompareOffers(a : GL_ComponentShopOffer, b : GL_ComponentShopOffer) : int
      var da   : int = (int)a.rent_duration.Get()
      var db   : int = (int)b.rent_duration.Get()
      var ret  : int = 0
      if (da > db)
         ret := -1
      elif (da < db)
         ret := 1
      end
      return ret
   end 
   
   func GetOffers() : vector
      var ret        : vector
      var shopComp   : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)itemId.Get())
      var ownType    : int = GetOwnType()
      if (shopComp.offers.Get().Count() > 0)
         ret := shopComp.offers.Get()
         ret.Sort(this, "CompareOffers")
      end
      return ret
   end
   
   func GetOwnTypeInternal() : int
      var ret        : int = 0
      var shopComp   : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)itemId.Get())
      if (shopComp.bundled_items.Get().Count() > 0)         
         ret := $uiEnums.ITEM_OWN_TYPE_PURCHASED
         var i : int
         for i := 0 to shopComp.bundled_items.Get().Count() - 1
            var item : GL_ComponentShopBundledItem = (GL_ComponentShopBundledItem)shopComp.bundled_items.Get().Get(i)
            var inventItem : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)item.item_id.Get())
            var itemStatus : int = (int)inventItem.ownership_type.Get()
            if (itemStatus == $uiEnums.ITEM_OWN_TYPE_NONE)
               ret := $uiEnums.ITEM_OWN_TYPE_NONE
            elif (itemStatus == $uiEnums.ITEM_OWN_TYPE_RENTED)            
               ret := $uiEnums.ITEM_OWN_TYPE_RENTED
            end
         end         
      else
         var inventItem : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)itemId.Get())      
         ret := (int)inventItem.ownership_type.Get()
      end
      
      return ret
   end
   
   func GetLockStatus() : string
      var ret : string = "none"
      var compShop : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(itemId.Get())
      if compShop.requirement.Get() != ""
         var compInventory : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(compShop.requirement.Get())
         if compInventory.ownership_type.Get() == $uiEnums.ITEM_OWN_TYPE_PURCHASED
            ret := "unlocked"
         else
            ret := "locked"
         end
      end
      return ret
   end
   
   func GetOwnType() : int
      var ret : int = (int)ownTypeInternal.Get()
      return ret
   end
   
   func GetHeaderY() : float
      var ret              : float = 0
      var offersCountVal   : int = (int)offersCount.Get()
      ret := y0 - 47.0 * offersCountVal - 45
      return ret      
   end

   func GetHeaderText() : string
      var ret : string
      if (GetOwnType() == $uiEnums.ITEM_OWN_TYPE_NONE)
         if ($uiEconomy.IsItemPurchasable(GetItemIdVal()))
            ret := (string)nonPurchasedTxt.Get()
         else
            ret := (string)rentTxt.Get()
         end
      else
         var ci : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(itemId.Get())
         var es : int = (int)ci.equipped_state.Get()
         if es == 2 and isSpartanArmory.Get() == true
            ret := "carousel_txt_assigned"
         else
            if ($uiEconomy.IsItemPurchasable(GetItemIdVal()))
               ret := (string)purchasedTxt.Get()
            else
               ret := (string)addTimeTxt.Get()
            end
         end
      end
      return ret
   end
      
   func GetAssignY() : float
      var ret : float = 0
      ret := y0
      return ret      
   end

   func GetAssignAlpha() : float
      var ret : float = 0
      if (((bool)assignEnabled.Get()) == true)
         ret := 100.0
      else
         ret := 20.0
      end
      return ret      
   end

   func GetAssignText() : string
      var ret : string = "carousel_ui_btn_assign"
      var type : int = GetOwnType()
      
      if (type != $uiEnums.ITEM_OWN_TYPE_NONE)
         ret := "carousel_ui_btn_assign"
      elif ($uiEconomy.IsItemLocked((string)itemId.Get()))
         //ret := "carousel_ui_btn_assign_locked"
         ret := "carousel_goto_tech_tree"
      else 
         ret := "carousel_ui_btn_unavailable"
      end
      
      return ret      
   end
   
   func GetAssignEnabled() : bool
      var ret : bool = false
      if (bool)canAssign.Get() or lockStatus.Get() == "locked"
         ret := true
      else
         ret := false
      end
      return ret      
   end
   
   func Init(p : params)
      wgt := p.widget
   end
end


class ItemShopBaseVM
   var shopType         : int                = $uiEnums.SHOP_TYPE_NONE
   var itemList         : ObservableProperty = $OM.Calculated(this, "GetItemList")
   var itemQuality      : ObservableProperty = $OM.Property(0)
   var selectedIdx      : ObservableProperty = $OM.Property(0)
   var mouseOverIdx     : ObservableProperty = $OM.Property(0)
   var itemCat          : ObservableProperty = $OM.Property(0)   
   var catCount         : ObservableProperty = $OM.Calculated(this, "GetCatCount")
   var selectedItemId   : ObservableProperty = $OM.Calculated(this, "GetSelectedItemId")
   var mouseOverItemId  : ObservableProperty = $OM.Calculated(this, "GetMouseOverItemId")
   var selectedItem     : ObservableProperty = $OM.Calculated(this, "GetSelectedItem")
   var itemCategories   : ObservableProperty = $OM.Calculated(this, "GetItemCategories")
   var sections         : ObservableProperty = $OM.Calculated(this, "GetSections")   
   var descpanelVM      : ItemDescPanelVM    = new ItemDescPanelVM()
   var offersModuleVM   : OffersModuleVM     = new OffersModuleVM()
   var bigIconPic       : ObservableProperty = $OM.Calculated(this, "GetBigIconPic")
   var bigIconVideo     : ObservableProperty = $OM.Calculated(this, "GetBigIconVideo")
   var isVideoIcons     : ObservableProperty = $OM.Calculated(this, "GetIsVideoIcons")
   var isVideoVisible   : ObservableProperty = $OM.Property(false)
   var isRentTimer      : ObservableProperty = $OM.Property(false)
   var wgt              : UiWidget           = null
   var rentTimeLeft     : ObservableProperty = $OM.Calculated(this, "GetRentTimeLeft")
   var rentTimeLeftClr  : ObservableProperty = $OM.Calculated(this, "GetRentTimeLeftClr")
   var itemName         : ObservableProperty = $OM.Calculated(this, "GetItemName")
   var selectedLoadoutIdx      : ObservableProperty = $OM.Calculated(this, "GetSelectedWeaponLoadoutIdx")
   var selectedArmorLoadoutIdx : ObservableProperty = $OM.Calculated(this, "GetSelectedArmorLoadoutIdx")

   func Init(p : params)
      wgt                        := p.widget
      offersModuleVM.shopWidget  := wgt
   end
      
   func OpenBuyDialogue(p : params) : bool
      var itemId : string = p.itemId
      var offer : GL_ComponentShopOffer = p.offer
      var isGold : bool = p.isGold
      var playerCurrency = 0
      var offerString : string
      var offerCost : int
      if offer == null
         return true
      end
      if isGold
         playerCurrency := (int)$UserDataStorage.local_user.gold.Get()
         offerString := (string)offer.gl_offer.Get()
         offerCost := (int)offer.gl_cost.Get()
      else
         playerCurrency := (int)$UserDataStorage.local_user.cr.Get()
         offerString := (string)offer.cr_offer.Get()
         offerCost := (int)offer.cr_cost.Get()
      end
      if offerString != ""
         var par: params
         par.itemID        :=  itemId
         par.offer         := offerString
         if isGold
            par.priceGold     := offerCost
         else
            par.priceCredit   := offerCost
         end
         if (offerCost <= playerCurrency)
            // is rent ?
            var ret : int = 0
            ret := (int)offer.rent_duration.Get()
            if (ret > 0)
               par.isRent := true
            end
            // end 
            par.mbType           := "ConfirmBuy"
            par.callbackEvent    := "OnItemPurchased"
            par.callbackTarget   := wgt.Props()
         else
            par.mbType     := "Info"
            par.titleTxt   := "msg_ui_warning"
            if isGold
               par.messageTxt := "msg_ui_not_enough_gp"
            else
               par.messageTxt := "msg_ui_not_enough_cr"
            end
         end
         $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
      end
      return true
   end
   
   func ItemShopBaseVM()
      mouseOverItemId.Subscribe(this, "UpdateSelectedItem")   
      itemQuality.Subscribe(this, "itemQualityChanged")
      offersModuleVM.parentVM := this
      offersModuleVM.isWide.Subscribe(this, "OnIsWideChanged")
   end
   
   func BaseTerm()
      itemQuality.Unsubscribe(this, "itemQualityChanged")
      mouseOverItemId.Unsubscribe(this, "UpdateSelectedItem")
      offersModuleVM.isWide.Unsubscribe(this, "OnIsWideChanged")
      offersModuleVM.parentVM := null
      offersModuleVM.Term()
      $sslWidgetMgr.PrintStats()
      offersModuleVM := null
      $sslWidgetMgr.PrintStats()
   end
   
   func GetLoadoutsObservable() : ObservableProperty
      var ret : ObservableProperty = null
      return null
   end
            
   func OnIsWideChanged(_val : *)
      offersModuleVM.UpdateOfferLines()
   end
   
   func LoadoutSelectButtonClicked(p : params) : bool
      var loadoutIndex : int = (int)p.widget.Get("idx")
      if loadoutIndex != selectedLoadoutIdx.Get()
         $user_service.SetWeaponLoadoutActive(0, loadoutIndex)
      end
      return true
   end
   
   func ArmorLoadoutSelectButtonClicked(p : params) : bool
      var loadoutIndex : int = (int)p.widget.Get("idx")
      if loadoutIndex != selectedArmorLoadoutIdx.Get()
         $user_service.SetArmorLoadoutActive(0, loadoutIndex)
      end
      return true
   end
      
   func GetSelectedWeaponLoadoutIdx() : *
      var ud : UserData = (UserData) $UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
      var loadoutIndex :  int = (int)ud.weapon_loadouts.spartan.active_loadout_index.Get()
      return loadoutIndex
   end
   
   func GetSelectedArmorLoadoutIdx() : *
      var ud : UserData = (UserData) $UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
      var loadoutIndex :  int = (int)ud.armor_loadouts.spartan.active_loadout_index.Get()
      return loadoutIndex
   end
      
   func itemQualityChanged(newVal : *)
      var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
      var subshop : GL_ShopSection = (GL_ShopSection)shop.weapons.Get().Get((int)newVal)
      var uiID    : string = (string)subshop.section_id.Get()
      $UiGlobals.AssigningItemCategory := uiID
   end
   
   func GetRentTime() : int
      var ret     : int
      var itemId  : string = (string)mouseOverItemId.Get()
      if ($uiEconomy.GetItemOwnType(itemId) == $uiEnums.ITEM_OWN_TYPE_RENTED)
         var uiInventoryItem : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(itemId)
         var ownTime : int = (int)uiInventoryItem.ownership_time.Get() - (int)$UiGlobals.timer.Get()
         ret := ownTime
      end
      return ret   
   end   
   
   func SetListSelection(_idx : int)
      if (wgt != null)
         var p : params
         p.idx := _idx
         wgt.GenerateEvent("SetListSelection", p)
      end
   end
   
   func GetRentTimeLeftClr() : int
      return $uiEconomy.GetItemRentTintColor((string)mouseOverItemId.Get())
   end   
   
   func GetItemName() : string
      var ret     : string
      if ((bool)isRentTimer.Get())
         var itemId  : string = (string)mouseOverItemId.Get()
         if ($uiEconomy.GetItemOwnType(itemId) == $uiEnums.ITEM_OWN_TYPE_RENTED)
            ret := "carousel_rent_time_left"
         end
      end
      return ret
   end
   
   func GetRentTimeLeft() : wstring
      var ret     : wstring
      if ((bool)isRentTimer.Get())
         var itemId  : string = (string)mouseOverItemId.Get()
         if ($uiEconomy.GetItemOwnType(itemId) == $uiEnums.ITEM_OWN_TYPE_RENTED)
            //ret := $root.MakeUiTimerStringMinutes(GetRentTime(), true)
            ret := $root.MakeUiTimerSubHead(GetRentTime())
         end
      end
      return ret
   end
   
   func CallRenderBigVideo(_video : string)
      var video : string = GetMouseOverItemId()
      if (wgt != null and wgt.GetStateName() == "Visible" and video != "" and video != "unknown")
         $hq.TextureRenderWeaponShop(video)
      end      
   end
   
   func GetBigIconPic() : string
      var ret        : string = ""
      var videoPic   : string = ""
      var uiComp     : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(mouseOverItemId.Get())
      if ((bool)isVideoIcons.Get())
         videoPic := (string)uiComp.video.Get()
         CallRenderBigVideo(videoPic)
         isVideoVisible.Set(true)
      else
         ret := (string)uiComp.icon_big.Get()
         isVideoVisible.Set(false)
      end
      return ret
   end
      
   func GetBigIconVideo() : string
      var ret        : string = ""
      var uiComp     : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(mouseOverItemId.Get())
      ret := (string)uiComp.video.Get()
      return ret
   end
   
   func GetIsVideoIcons() : bool
      return true
   end
   
   func GetCatCount() : *
      var ret : int = 0
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         if (! IsVoid(shop.weapons.Get()) and shop.weapons.Get().Count() > (int)itemQuality.Get())
            var subshop    :  GL_ShopSection = (GL_ShopSection)shop.weapons.Get().Get((int)(itemQuality.Get()))
            ret := subshop.shelves.Get().Count()
         end         
      end
      return ret
   end
            
   func UpdateSelectedItem(val : *)
      descpanelVM.itemId.Set(val)
      offersModuleVM.UpdateItemId((string)val)
   end
   
   func OnSubTabSelected(p:params):bool
      if (! IsVoid(p.itemCatIdx))
         itemCat.Set((int)p.itemCatIdx)
         selectedIdx.Set(0)
         UpdateSubTab()
      end
      return true
   end
   
   func DoBlink()
      if (wgt != null)
         wgt.GenerateEvent("BlinkItemList")
      end
   end

   func UpdateSubTab()
      DoBlink()
   end

   func OnPanelButtonClicked(p:params):bool
      return false
   end
   
   func wc_OnPanelButtonClicked(p:params):bool
      selectedIdx.Set(0)
      return OnPanelButtonClicked(p)
   end
   
   
   func wcSelectedItem(p:params):bool
      return false
   end
   
   
   func OnItemSlotSelect(p:params):bool
      mouseOverIdx.Set((int)p.idx)
      if (! p.isFocusOnly)
         selectedIdx.Set((int)p.idx)         
      end
      //UpdateSelectedItem()
      return true
   end
   
   func OnItemSlotMouseOut(p:params):bool
      mouseOverIdx.Set((int)selectedIdx.Get())
      //UpdateSelectedItem()
      return true
   end
         
   func GetSelectedItem() : GL_String
      var selectedIdxInt   : int = (int)selectedIdx.Get()
      var itemsList        : vector = GetItemList()
      if (selectedIdxInt >= 0 and selectedIdxInt < itemsList.Count())
         return itemsList.Get(selectedIdxInt)
      end
      return null
   end
   
   func GetMaxSections() : int
      return 5
   end
   
   func GetSections() : vector
      var sections   : vector
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         var i          : int
         for i := 0 to shop.weapons.Get().Count() - 1
            var subshop : GL_ShopSection = (GL_ShopSection)shop.weapons.Get().Get(i)
            var uiID    : string = (string)subshop.section_id.Get()
            var name    : string  = (string)((GL_ComponentUI)$UiGlobals.componentsUI.Get(uiID)).name.Get()
            if (name == "")
               name := uiID
            end
            var sectionDesc : params
            sectionDesc.label    := name
            sectionDesc.is_hot   := false
            sectionDesc.has_new  := subshop.HasNewItems()
            sections.Push(sectionDesc.Clone())
         end
      end
      while (sections.Count() < GetMaxSections())
         var sectionDesc : params
         sectionDesc.label    := ""
         sectionDesc.is_hot   := false
         sectionDesc.has_new  := false
         sections.Push(sectionDesc.Clone())
      end
      return sections
   end
   
   func GetItemCategories() : vector
      var itemCatList   : vector
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop          :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         if (! IsVoid(shop.weapons.Get()) and shop.weapons.Get().Count() > (int)itemQuality.Get())
            var subshop       :  GL_ShopSection = (GL_ShopSection)shop.weapons.Get().Get((int)(itemQuality.Get()))              
            var i             : int
            
            for i := 0 to subshop.shelves.Get().Count() - 1
               var shelf         : GL_ShopShelf    = (GL_ShopShelf)subshop.shelves.Get().Get(i) 
               var listElem      : params
               listElem.name     := (string)((GL_ComponentUI)$UiGlobals.componentsUI.Get(shelf.shelf_id.Get())).name.Get()
               listElem.id       := (string)shelf.shelf_id.Get()
               listElem.has_new  := shelf.HasNewItems()
               itemCatList.Push(listElem)
            end
         end
      end
      return itemCatList      
   end
   
   func CompareShopItems(itemA : GL_String, itemB : GL_String) : int
      var itemIdA    : string             = (string)itemA.value.Get()
      var itemIdB    : string             = (string)itemB.value.Get()
      var shopCompA  : GL_ComponentShop   = (GL_ComponentShop)$UiGlobals.componentsShop.Get(itemIdA)
      var shopCompB  : GL_ComponentShop   = (GL_ComponentShop)$UiGlobals.componentsShop.Get(itemIdB)
      var availA     : int                = (int)shopCompA.availability.Get()
      var availB     : int                = (int)shopCompB.availability.Get()
      var ret        : int                = 0      
      
      if (availA > availB)
         ret := 1
      elif (availA < availB)
         ret := -1
      end
      
      return ret      
   end
   
   func SortShopItems(items : vector) : vector
      var ret : vector = items
      ret.Sort(this, "CompareShopItems")
      return ret
   end
         
   func GetItemList() : vector
      var ret : vector
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         if (! IsVoid(shop.weapons.Get()) and shop.weapons.Get().Count() > (int)itemQuality.Get())
            var subshop    :  GL_ShopSection = (GL_ShopSection)shop.weapons.Get().Get((int)(itemQuality.Get()))
            if (! IsVoid(subshop.shelves.Get()) and subshop.shelves.Get().Count() > (int)itemCat.Get())
               var shelf      :  GL_ShopShelf   = (GL_ShopShelf)subshop.shelves.Get().Get((int)(itemCat.Get()))
               if (! IsVoid(shelf.items.Get()))
                  ret := SortShopItems(shelf.items.Get())
               end
            end
         end         
      end
      return ret
   end      
   
   func GetSelectedItemId() : string
      var item :  string      
      var items : vector = itemList.Get()
      
      var idx : int = (int)selectedIdx.Get()
      if (idx >= 0 and idx < items.Count())  
         var glitem :  GL_String = (GL_String)items.Get(idx)
         item := (string)glitem.value.Get()
      end
      
      return item
   end

   func GetMouseOverItemId() : string
      var item :  string      
      var items : vector = itemList.Get()
      
      var idx : int = (int)mouseOverIdx.Get()
      if (idx >= 0 and idx < items.Count())  
         var glitem :  GL_String = (GL_String)items.Get(idx)
         item := (string)glitem.value.Get()
      end
            
      return item
   end   
end

class WeaponConfVM : ItemShopBaseVM
   var progressBarsVM   : ProgressBarsVM     = new ProgressBarsVM()
   //
   func WeaponConfVM()
      shopType := $uiEnums.SHOP_TYPE_WEAPON
      isVideoIcons.Set(true)
      isRentTimer.Set(true)
   end   
   
   override GetLoadoutsObservable //() : ObservableProperty
      var udLocal : UserDataLocal = $UserDataStorage.local_user
      return udLocal.weapon_loadouts_unlocked
   end
      
   override OnPanelButtonClicked
      Log("ui~content", "wc_OnPanelButtonClicked: " + Params2Str(p))
      if (! IsVoid(p.widget.itemType) and ! p.widget.selected)
         var itemType :  int = p.widget.itemType
         if (itemType >= 0)
            itemCat.Set(0)
            itemQuality.Set(itemType)
         end
      end
      UpdateSelectedItem(mouseOverItemId.Get())
      DoBlink()
      return false
   end

   func Term(p : params)
      //mouseOverItemId.Unsubscribe(descpanelVM, "UpdateItemId")
      BaseTerm()
   end
         
   func OpenedWeaponConfig(p : params) : bool
      sections.Invalidate()
      itemCategories.Invalidate()
      itemQuality.OnChanged()
      itemList.Invalidate()   
      offersModuleVM.isWide.Set(true)
      catCount.Invalidate()
      if ($UiGlobals.shop.openParams.isValid)         
         $UiGlobals.shop.openParams.isValid := false
         itemQuality.Set($UiGlobals.shop.openParams.sectionIdx)
         itemCat.Set($UiGlobals.shop.openParams.shelfIdx)
         selectedIdx.Set($UiGlobals.shop.openParams.itemIdx)
         SetListSelection($UiGlobals.shop.openParams.itemIdx)
      else
         itemCat.Set(0)
         itemQuality.Set(0)
      end
      return true
   end
      
   override UpdateSelectedItem
      descpanelVM.itemId.Set(mouseOverItemId.Get())
      offersModuleVM.UpdateItemId((string)mouseOverItemId.Get())
      progressBarsVM.itemId.Set(mouseOverItemId.Get())
      progressBarsVM.curLoadoutIdx.Set((int)selectedLoadoutIdx.Get())
      ////////////
      ////HACK////
      ////////////
      progressBarsVM.itemQ.Set((int)itemQuality.Get())
   end   
   
   func OnWeaponPurchased(p : params) : bool
      offersModuleVM.Go2LoadoutAfterPurchase(p.itemID)
      return true
   end
end

class CrossOutLineHelper : UiWidget
   global event UpdateCrossOutLines()
      var textWidth : float = (float)Get("tfOldPriceWidth")
      GetWidget("lineOldPrice").Set("_width", textWidth + 5)
   end
end
