import ssl.lib.logging
import ssl.lib.events
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.engine_ctrl
import ui.root
import ui.ui_party_monitor
import ssl.hf2p.ui_globals

class UiLoadingScreen : UiWidgetContainer

handle OnActivate
   Log("ui~hf2p_soading_screen", "OnActivate()")
   //Widgets.loadoutCont.fakeProgress.scaleX := 0.25
end

func OnLoadingProgress(p : params) : bool
   var progress : float = (float)(p.progress)
   //Widgets.loadoutCont.fakeProgress.progressOver.scaleX := progress / 500.0
   return false
end

end

class LoadingScreenVM
   var LoadingBarOffset : ObservableProperty = $OM.Calculated(this, "GetLoadingBarOffset")
   var LoadingBarScale  : ObservableProperty = $OM.Calculated(this, "GetLoadingBarScale")
   
   func LoadingScreenVM()
      LoadingBarOffset.Get()
   end
      
   func GetLoadingBarOffset() : *
      var ret : float = -314.0 + (150 + 314.0) * (float)($UiGlobals.loading_data.progress.Get())
      return ret
   end
   
   func GetLoadingBarScale() : float
      var ret : float = (float)($UiGlobals.loading_data.progress.Get()) * 2.365
      return ret
   end
end
