import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.engine_ctrl
import ssl.hf2p.items_mgr
import ssl.hf2p.user_service
import ssl.hf2p.game_preferences
import ssl.hf2p.ui_ingame
import ssl.lib.ui.ui_widget_manager
import ssl.hf2p.engine_ctrl
import ssl.observables
import ssl.hf2p.ui_globals
import ui.ui_economy
import ssl.hf2p.user_data
import ui.root

import ui.libs.hf2p_MainMenu_lib.hf2p_MainMenu_lib

class UiLoadoutSelect : UiWidgetContainer


var isSelectingSlot : bool = false

var prevScr       : string
var curLoadoutIdx : int
var highlightLoadoutIdx : int
var wpnAssign     : bool 
var assignMode    : string
var clickFlag     : bool = false
var minSlotIdx    : int = 0
var maxSlotIdx    : int = 7
var assignItemId  : string
var enteringState : string
var subscribe     : bool = false

func VisualizeLoadoutArsenal(loadoutIdx: int)
   Log("ui~loadoutSelect", "VisualizeLoadoutArsenal  " + assignItemId)
   $user_service.SetWeaponLoadoutWeapon(GetRaceIdx(), loadoutIdx, assignItemId)       
end

func VisualizeLoadoutAfterBuy(loadoutIdx: int)
   Log("ui~loadoutSelect", "VisualizeLoadoutAfterBuy")
   UpdateLoadoutStatus(loadoutIdx)   
   ShowSelectLoadoutButtons()
end

func GetKeyBindText(biped : bool, keyId : string) : string
   var labels : vector = $hf2pPreferences.GetActionLabels(biped)
   var labelIdx : int = -1
   var i : int
   for i := 0 to labels.Count() - 1
      if labels.Get(i) == keyId
         labelIdx := i
         break
      end
   end
   var keys : vector = $hf2pPreferences.GetKeyBinds(biped)
   var keyIdx : int = keys.Get(labelIdx).primary
   var keyLabels : vector = $hf2pPreferences.GetKeyLabels()
   var keyLabel : string = ""
   if keyIdx == -1
      keyIdx := keys.Get(labelIdx).alternative
   end
   if keyIdx != -1
      keyLabel := keyLabels.Get(keyIdx)
   end
   return keyLabel
end

func UpdateLoadoutStatusPart2(_loadoutIdx: int, _savePerks : bool = false)
   var loadoutSlot : * = GetLoadout(_loadoutIdx)
   var hasLoadout : bool   = true //$sslUserStates.HasItem(loadoutSlot.Props().loadoutName)
   var udLocal : UserDataLocal = $UserDataStorage.local_user
   var unlockedLoadouts : int = (int)udLocal.weapon_loadouts_unlocked.Get()
   hasLoadout := _loadoutIdx < unlockedLoadouts
   if (hasLoadout)
      //loadoutSlot.Props().btnBox.GotoAndStop("Unlocked")
      loadoutSlot.Props().subText := loadoutSlot.Props().loadoutLabel      
      EnableLoadoutElements(_loadoutIdx, loadoutSlot.Props().loadoutName, _savePerks) : 0
      
      loadoutSlot.Widgets().btnBox.btn3.text2 := GetKeyBindText(true, "settings_actions_throw_grenade")
      loadoutSlot.Widgets().btnBox.btn4.text2 := GetKeyBindText(true, "settings_actions_use_consumable_1")
      loadoutSlot.Widgets().btnBox.btn5.text2 := GetKeyBindText(true, "settings_actions_use_consumable_2")
      loadoutSlot.Widgets().btnBox.btn6.text2 := GetKeyBindText(true, "settings_actions_use_consumable_3")
      loadoutSlot.Widgets().btnBox.btn7.text2 := GetKeyBindText(true, "settings_actions_use_consumable_4")
   else
      //loadoutSlot.Props().btnBox.GotoAndStop("Locked")
      loadoutSlot.Props().subText := loadoutSlot.Props().defSubText      
   end   
   //loadoutSlot.SetLockedState(! hasLoadout, GetStateName() == "Assign2Loadout")
   loadoutSlot.SetLockedState(! hasLoadout, false)
   var slotMouseEnabled: bool = hasLoadout or GetStateName() == "Assign2Loadout"
   loadoutSlot.Props().mouseChildren   := slotMouseEnabled and (GetStateName() != "SeeLoadout" and GetStateName() != "SelectLoadout" and GetStateName() != "SelectLoadoutPregame")
   loadoutSlot.Props().mouseEnabled    := slotMouseEnabled
   loadoutSlot.Props().ingameBg.visible := (GetStateName() == "SelectLoadout" or GetStateName() == "SelectLoadoutPregame")
end

func UpdateLoadoutStatus(_loadoutIdx: int, _savePerks : bool = false)
   var loadoutSlot: * = GetLoadout(_loadoutIdx)
   var hasLoadout : bool   = true //$sslUserStates.HasItem(loadoutSlot.Props().loadoutName)
   var udLocal : UserDataLocal = $UserDataStorage.local_user
   var unlockedLoadouts : int = (int)udLocal.weapon_loadouts_unlocked.Get()
   hasLoadout := _loadoutIdx < unlockedLoadouts
   if (hasLoadout)
      loadoutSlot.GotoAndStop("up")
   else
      loadoutSlot.GotoAndStop("disabled")
   end
   loadoutSlot.Props().enabled  := hasLoadout
   UpdateLoadoutStatusPart2(_loadoutIdx, _savePerks)
end

func UpdateLoadoutOffersLine(_loadoutIdx : int)
   var hasLoadout : bool
   var udLocal : UserDataLocal = $UserDataStorage.local_user
   var unlockedLoadouts : int = (int)udLocal.weapon_loadouts_unlocked.Get()
   hasLoadout := _loadoutIdx < unlockedLoadouts
   if (GetStateName() == "SeeLoadout")
      if (hasLoadout)
         Widgets().slots.Get("offerPanel" + _loadoutIdx).visible := false
      else
         Widgets().slots.Get("offerPanel" + _loadoutIdx).visible := true
         EnableOfferLine(_loadoutIdx, unlockedLoadouts)
      end   
   else
      Widgets().slots.Get("offerPanel" + _loadoutIdx).visible := false
   end
end

func EnableOfferLine(_loadoutIdx : int, _unlockedLoadouts : int)
   if (_loadoutIdx > _unlockedLoadouts)
      Widgets().slots.Get("offerPanel" + _loadoutIdx).tfItemName := "carousel_ui_btn_unavailable"
      Widgets().slots.Get("offerPanel" + _loadoutIdx).alpha := 100
      Widgets().slots.Get("offerPanel" + _loadoutIdx).offerButtons.crBuyBtn.enabled := false
      Widgets().slots.Get("offerPanel" + _loadoutIdx).offerButtons.gpBuyBtn.enabled := false
   else
      Widgets().slots.Get("offerPanel" + _loadoutIdx).tfItemName := "carousel_txt_non_purchased"
      Widgets().slots.Get("offerPanel" + _loadoutIdx).alpha := 100
      Widgets().slots.Get("offerPanel" + _loadoutIdx).offerButtons.crBuyBtn.enabled := true
      Widgets().slots.Get("offerPanel" + _loadoutIdx).offerButtons.gpBuyBtn.enabled := true
   end
end

func GetObservableLoadoutCount() : ObservableProperty
   var udLocal : UserDataLocal = $UserDataStorage.local_user
   return udLocal.weapon_loadouts_unlocked
end

func CheckUpdateLoadout(val : *)  
   var i : int
   for i := 0 to 4
      UpdateLoadoutStatus(i, true)
   end
   for i:= 1 to 4
      UpdateLoadoutOffersLine(i)
   end 
end

func IsShowSelectLoadoutBtns(): bool
   return (GetStateName() == "ChoiceLoadoutBtn")
end

func ShowSelectLoadoutButtons()      
   if (IsShowSelectLoadoutBtns())
      if ($UiGlobals.DeathScreenLoadoutsMode.Get() == "weapons")
         Widgets().RespawnPanel.loadouts.loadout0.Init(1, "Loadout0", "carousel_loadout_1", false)
         Widgets().RespawnPanel.loadouts.loadout1.Init(2, "Loadout1", "carousel_loadout_2", false)
         Widgets().RespawnPanel.loadouts.loadout2.Init(3, "Loadout2", "carousel_loadout_3", false)
         Widgets().RespawnPanel.loadouts.loadout3.Init(4, "Loadout3", "carousel_loadout_4", false)
         Widgets().RespawnPanel.loadouts.loadout4.Init(5, "Loadout4", "carousel_loadout_5", false)
      else
         Widgets().RespawnPanel.loadouts.loadout0.Init(1, "Loadout0", "carousel_armor_1", true)
         Widgets().RespawnPanel.loadouts.loadout1.Init(2, "Loadout1", "carousel_armor_2", true)
         Widgets().RespawnPanel.loadouts.loadout2.Init(3, "Loadout2", "carousel_armor_3", true)
         Widgets().RespawnPanel.loadouts.loadout3.Init(4, "Loadout3", "carousel_armor_4", true)
         Widgets().RespawnPanel.loadouts.loadout4.Init(5, "Loadout4", "carousel_armor_5", true)
      end
      Widgets().RespawnPanel.GenerateEvent("#ShowRespawnPanel")
   else   
      Widgets().RespawnPanel.GenerateEvent("#HideRespawnPanel")
   end
end

func GetDisabledColorTint(_slotIdx: int): params
   var ret: params
   if (_slotIdx < 4)
      ret.r := 255
      ret.g := 255
      ret.b := 255
      ret.a := 255
      ret.v := 255
   else
      ret.r := 128
      ret.g := 128
      ret.b := 128
      ret.a := 255
      ret.v := 255
   end
   return ret
end

func GetEnabledColorTint(_slotIdx: int): params
   var ret: params
   ret.r := 255
   ret.g := 255
   ret.b := 255
   ret.a := 255
   ret.v := 255
   return ret
end

func GetStateColorTint(_isEnabled: bool, _slotIdx: int): params
   var ret: params
   if (_isEnabled)
      ret := GetEnabledColorTint(_slotIdx)
   else
      ret := GetDisabledColorTint(_slotIdx)
   end
   return ret
end

func GetStateBgColorTint(_isEnabled: bool, _slotIdx: int): params
   var ret: params
   if (_isEnabled)
      ret.r := 255
      ret.g := 255
      ret.b := 255
      ret.a := 255
      ret.v := 255
   else
      ret.r := 64
      ret.g := 64
      ret.b := 64
      ret.a := 64
      ret.v := 64
   end
   return ret
end

func IsAssignSlotEnabled(i: int): bool
   var ret: bool = false
   if (GetStateName() != "Assign2Loadout")
      ret := false
   else
      ret := (i - 1) >= minSlotIdx and (i - 1) <= maxSlotIdx
   end
   return ret
end

func EnableLoadoutElements(_idx: int, loadoutName:string, _savePerks: bool = false)
   var btnIdx : int
   
   if GetStateName() == "Assign2Loadout"
      for btnIdx := 1 to 3 // weapons and grenade
         var isClickable : bool = IsAssignSlotEnabled(btnIdx)
         Widgets().slots.Get(loadoutName).btnBox.Get("btn" + btnIdx).selected  := isClickable
         Widgets().slots.Get(loadoutName).btnBox.Get("btn" + btnIdx).enabled  := isClickable
         Widgets().slots.Get(loadoutName).btnBox.Get("btn" + btnIdx).mouseEnabled  := false
      end
      
      for btnIdx := 4 to 8 // tactical packages and booster
         var isClickable : bool = IsAssignSlotEnabled(btnIdx)
         Widgets().slots.Get(loadoutName).btnBox.Get("btn" + btnIdx).selected  := isClickable
         Widgets().slots.Get(loadoutName).btnBox.Get("btn" + btnIdx).enabled  := isClickable
         Widgets().slots.Get(loadoutName).btnBox.Get("btn" + btnIdx).mouseEnabled  := isClickable
      end
   else
      for btnIdx := 1 to 3 // weapons and grenade
         var isClickable : bool = IsAssignSlotEnabled(btnIdx)
         Widgets().slots.Get(loadoutName).btnBox.Get("btn" + btnIdx).selected  := isClickable
         Widgets().slots.Get(loadoutName).btnBox.Get("btn" + btnIdx).enabled  := true
         Widgets().slots.Get(loadoutName).btnBox.Get("btn" + btnIdx).mouseEnabled  := false
      end
      
      for btnIdx := 4 to 8 // tactical packages and booster
         var isClickable : bool = IsAssignSlotEnabled(btnIdx)
         Widgets().slots.Get(loadoutName).btnBox.Get("btn" + btnIdx).selected  := isClickable
         Widgets().slots.Get(loadoutName).btnBox.Get("btn" + btnIdx).enabled  := true
         Widgets().slots.Get(loadoutName).btnBox.Get("btn" + btnIdx).mouseEnabled  := isClickable
      end
   end
end

func OnUpdateLoadoutAfterBuy(p:params):bool
   Log("ui~loadoutSelect", "OnUpdateWpnContAfterBuy ...")
   if (p.isOK == true)
		UpdateLoadoutSlot(p.ItemID)    
      $root.playSound("menu_purchase_item")
      GenerateEvent("uiUpdatePlayerInfoAnim")      
   else
      Log("ui~loadoutSelect", "OnUpdateLoadoutAfterBuy - Cancel")
   end
   return false
end

func UpdateSlotsAfterBuy(p:params):bool
   Log("ui~loadoutSelect", "UpdateSlotsAfterBuy " + (string)(p.itemID))
   UpdateLoadoutSlot(p.itemID)    
   $root.playSound("menu_purchase_item")
   GenerateEvent("uiUpdatePlayerInfoAnim")
   return false
end

func UpdateLoadoutSlot(loadoutName:string)
   Log("ui~loadoutSelect", "UpdateLoadoutSlot")
	Widgets().slots.Get(loadoutName).alpha := 100
	Widgets().slots.Get(loadoutName).enabled := true 
	//Widgets().slots.Get(loadoutName).btnBox.lock.GotoAndPlay("unlocked")
	Widgets().slots.Get(loadoutName).btnBox.GoldV.visible := false
	Widgets().slots.Get(loadoutName).btnBox.CreditsV.visible := false
	VisualizeLoadoutAfterBuy(curLoadoutIdx)
end

func onLoadoutClicked(p: params): bool
   Log("ui~loadoutSelect", "onLoadoutClicked " + p.widget.idx)
	curLoadoutIdx := p.widget.idx
	var state: bool = true
   Log("ui~loadoutSelect", "!!! " + (string)(p.widget.GetName()) + " " + (string)(state) + " !!!")
   if GetStateName() == "Assign2Loadout"
      var loadoutIdx : int = p.widget.Get("idx")
      if wpnAssign
         //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         //!!!       HACK TO DIFFERENTIATE GRENADES FROM WEAPONS       !!!
         //!!!                     |   |   |   |                       !!!
         //!!!                     V   V   V   V                       !!!
         //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
         if assignItemId == "frag_grenade" or assignItemId == "plasma_grenade" or assignItemId == "spike_grenade" or assignItemId == "fire_grenade"
            $user_service.SetWeaponLoadoutGrenade(GetRaceIdx(), loadoutIdx, assignItemId)
         else
            $user_service.SetWeaponLoadoutWeapon(GetRaceIdx(), loadoutIdx, assignItemId)
         end
         acceptLoadout(p)
      end
   elif GetStateName() == "SeeLoadout"
      acceptLoadout(p)
   else // SelectLoadout state
      acceptLoadout(p)
   end	  
   return false
end

func onLoadoutOfferCrClicked(p : params) : bool
   var loadoutIdx   : int = p.widget.GetWidget("_parent").GetWidget("_parent").Props().idx
   var shop         : GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get(GetRaceIdx())
   var shopSection  : GL_ShopSection = shop.FindInternalSection("section_loadouts")
   var shopShelf    : GL_ShopShelf = shopSection.FindShelf("shelf_weapon_loadouts")
   var loadoutId    : string = (string)shopShelf.items.Get().Get(loadoutIdx).value.Get()
   var shopComp     : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(loadoutId)
   var loadoutOffer : GL_ComponentShopOffer = (GL_ComponentShopOffer)shopComp.offers.Get().Get(0)
   var offerId      : string  = loadoutOffer.GetCrOffer()
   var offerCr      : int     = loadoutOffer.GetCrCost()
   if (offerId != "")
      var par: params
      par.itemID        := loadoutId
      par.offer         := offerId
      par.priceCredit   := offerCr
      if (offerCr <= (int)$UserDataStorage.local_user.cr.Get())
         par.mbType           := "ConfirmBuy"
         par.callbackEvent    := "loadoutUpdate"
      else
         par.mbType     := "Info"
         par.titleTxt   := "msg_ui_warning"
         par.messageTxt := "msg_ui_not_enough_cr"
      end
      $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)         
   end
   return false
end

func onLoadoutOfferGpClicked(p : params) : bool
   var loadoutIdx   : int = p.widget.GetWidget("_parent").GetWidget("_parent").Props().idx
   var shop         : GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get(GetRaceIdx())
   var shopSection  : GL_ShopSection = shop.FindInternalSection("section_loadouts")
   var shopShelf    : GL_ShopShelf = shopSection.FindShelf("shelf_weapon_loadouts")
   var loadoutId    : string = (string)shopShelf.items.Get().Get(loadoutIdx).value.Get()
   var shopComp     : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(loadoutId)
   var loadoutOffer : GL_ComponentShopOffer = (GL_ComponentShopOffer)shopComp.offers.Get().Get(0)
   var offerId      : string  = loadoutOffer.GetGlOffer()
   var offerGl      : int     = loadoutOffer.GetGlCost()
   if (offerId != "")
      var par: params
      par.itemID        := loadoutId
      par.offer         := offerId
      par.priceGold     := offerGl
      if (offerGl <= (int)$UserDataStorage.local_user.gold.Get())
         par.mbType           := "ConfirmBuy"
         par.callbackEvent    := "loadoutUpdate"
      else
         par.mbType     := "Info"
         par.titleTxt   := "msg_ui_warning"
         par.messageTxt := "msg_ui_not_enough_gp"
      end
      $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)         
   end
   return false
end

func loadoutUpdate(p : params) : bool
   /*if (p.isOK)
      var i : int
      for i := 0 to 4
         UpdateLoadoutStatus(i, true)
      end
   end*/
   return true
end

func onPerksSlotClicked(p:params): bool
   var loadoutIdx : int = p.widget.GetWidget("_parent").GetWidget("_parent").Props().idx
   var perkIdx : int = p.widget.btnIdx - 4
   Log("ui~loadoutSelect", "onPerksSlotClicked " + (string)(loadoutIdx) + ", " + (string)(perkIdx))
   if (minSlotIdx > 2)   
      if (perkIdx >= 0 and perkIdx <= 3)
         $user_service.SetWeaponLoadoutConsumable(GetRaceIdx(), loadoutIdx, perkIdx, assignItemId)
         $user_service.SetWeaponLoadoutActive(GetRaceIdx(), loadoutIdx)
         clickFlag := true
      end
      return false
   end
   return true      
end

func onLoadoutElementClicked(p:params): bool
   /*
   var loadoutIdx       : int = p.widget.GetWidget("_parent").GetWidget("_parent").Props().idx
   var slotElementIdx   : int = p.widget.btnIdx - 1
   if (minSlotIdx <= 2)   
      if (slotElementIdx >= 0 and slotElementIdx <= 2)
         if (slotElementIdx == 0 or slotElementIdx == 1)
            $user_service.SetWeaponLoadoutWeapon(GetRaceIdx(), loadoutIdx, assignItemId)
         elif (slotElementIdx == 2)
            $user_service.SetWeaponLoadoutGrenade(GetRaceIdx(), loadoutIdx, assignItemId)
         end
         clickFlag := true
      end
      return false
   end
   */
   return true      
end

func onBoosterSlotClicked(p:params): bool
   /*
   if (minSlotIdx > 2)
      var loadoutIdx : int = p.widget.GetWidget("_parent").GetWidget("_parent").Props().idx
      $user_service.SetWeaponLoadoutBooster(GetRaceIdx(), loadoutIdx, assignItemId)
      clickFlag := true      
      return false
   end
   return true
   */
   var loadoutIdx : int = p.widget.GetWidget("_parent").GetWidget("_parent").Props().idx
   if (minSlotIdx > 2)   
      //$user_service.SetLoadout(assignItemId)
      $user_service.SetWeaponLoadoutBooster(GetRaceIdx(), loadoutIdx, assignItemId)
      $user_service.SetWeaponLoadoutActive(GetRaceIdx(), loadoutIdx)
      clickFlag := true
      return false
   end
   return true      
end

func onLoadoutMouseOver(p:params): bool
   highlightLoadoutIdx := p.widget.btnIdx
   Log("ui~loadoutSelect", "onLoadoutMouseOver " + (string)(highlightLoadoutIdx))
   return false
end

func acceptLoadout(p: params): bool
   Log("ui~loadoutSelect", "acceptLoadout")
   $user_service.SetWeaponLoadoutActive(GetRaceIdx(), p.widget.idx)
   if (GetStateName() == "SelectLoadoutPregame")    
      GenerateEvent("onPregameLoadoutAccepted")
      //SetStateName("Initial")  
   else 
      if (GetStateName() == "SelectLoadout")
         SetStateName("ChoiceLoadoutBtn")
      end
   end

   return false
end

func CloseLoadoutSelection()
   Log("ui~loadoutSelect", "onCloseLoadoutSelection - send")
   GenerateEvent("onCloseLoadoutSelection")
end

func doneA2l(p: params): bool
   if (! IsVoid(curLoadoutIdx))
      $user_service.SetWeaponLoadoutActive(GetRaceIdx(), curLoadoutIdx)
   end
   CloseLoadoutSelection()
   if (clickFlag)
      //AssignMessage()
   end
   return false
end

func AssignMessage()
   Log("ui~loadoutSelect", "AssignMessage")
   var   pp          : params
   pp.itemId         := assignItemId
   pp.isSkip         := true
   pp.mbType         := "AssignInfo"
   pp.callbackEvent  := "AssignMessageClosed"
   //pp.messageTxt     := "Text"
   pp.titleTxt       := "msg_ui_assigned_to_loadout" + (string)(curLoadoutIdx + 1)
   pp.closeTimeout   := 3
   GenerateEvent("MainMenuDialogRequest", pp)   
end

func GetRaceIdx() : int
   var idx: int = (int)$UserDataStorage.local_user.race.Get() //$hf2pEngine.GetUIPlayerModelId()
   return idx
end

func AssignMessageClosed(p:params):bool
   return false
end

func revertChanges()
   Log("ui~loadoutSelect", "revertChanges ")
   if (GetStateName() == "Assign2Loadout")
      // TODO: revert changes
   end
   CloseLoadoutSelection()
end

func loadoutChoiceClick(p: params): bool
   if (GetStateName() == "ChoiceLoadoutBtn")
      if $UiGlobals.DeathScreenLoadoutsMode.Get() == "weapons"
         SetStateName("SelectLoadout")
      else
         SetStateName("SelectArmorLoadout")
      end
      Log("ui~loadoutSelect", "loadoutChoiceClick")
   end
   return false
end

func onCancel(p: params): bool
   Log("ui~loadoutSelect", "onCancel")
   if GetStateName() == "SelectLoadout" or GetStateName() == "SelectArmorLoadout"
      SetStateName("ChoiceLoadoutBtn")
   else
      revertChanges()
   end	  
   return false
end

func AssignSlotsArsenal(p: params):bool
   Log("ui~loadoutSelect", "AssignSlotsArsenal_LOADOUT " + p.itemId)
   var category : string = $UiGlobals.AssigningItemCategory
   if category == "section_weapons_primary"
      minSlotIdx     := 0
      maxSlotIdx     := 0
   elif category == "section_weapons_secondary"
      minSlotIdx     := 1
      maxSlotIdx     := 1
   elif category == "section_weapons_grenade"
      minSlotIdx     := 2
      maxSlotIdx     := 2
   end
   assignItemId   := p.itemId
   prevScr        := p.closeEvent   
   wpnAssign      := true
   SetStateName("Assign2Loadout")
   return false
end

func AssignSlotsTacticalPack(p: params):bool
   Log("ui~loadoutSelect", "AssignSlotsTacticalPack")
   minSlotIdx     := 3
   maxSlotIdx     := 6
   assignItemId   := p.itemId
   prevScr        := p.closeEvent
   wpnAssign      := false
   SetStateName("Assign2Loadout")
   return false
end

func AssignSlotsBooster(p: params):bool
   Log("ui~loadoutSelect", "AssignSlotsBooster")
   minSlotIdx     := 7
   maxSlotIdx     := 7
   assignItemId   := p.itemId
   prevScr        := p.closeEvent
   wpnAssign      := false
   SetStateName("Assign2Loadout")
   return false
end

func OpenLoadoutScr(p:params):bool
   SetStateName("SeeLoadout")
   return false
end

func GetItemName(_itemId:string):string
   var ret:string 
   if (_itemId != "")
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(_itemId)
      ret := (string)compUI.name.Get()
      return ret
   end
   return ret
end

func GetLoadout(_loadoutIdx:int) : *
   return Widgets().slots.GetWidget("Loadout" + _loadoutIdx)
end

func GetSlotBtn(_slotIdx:int, _btnIdx:int): *
   return Widgets().slots.GetWidget("Loadout" + _slotIdx).Widgets().btnBox.GetWidget("btn" + _btnIdx)
end
   
func onLoadoutSmallBtnClick(p:params): bool
   Log("ui~loadoutSelect", "onLoadoutSmallBtnClicked " + p.widget.idx)
   if $UiGlobals.DeathScreenLoadoutsMode.Get() == "weapons"
      acceptLoadout(p)
      ShowSelectLoadoutButtons()
   else
      $user_service.SetArmorLoadoutActive(0, p.widget.idx)
   end
   return false   
end

handle OnChangeStateAny
   if (GetStateName() == "SeeLoadout" or GetStateName() == "Assign2Loadout" or GetStateName() == "SelectLoadout" or GetStateName() == "SelectLoadoutPregame")
      subscribe := true
      $UserDataStorage.InvalidateWeaponLoadouts()
      GetObservableLoadoutCount().Subscribe(this, "CheckUpdateLoadout")
      var i: int
      for i := 0 to 4
	     UpdateLoadoutStatus(i, true)
      end
      for i:= 1 to 4
         UpdateLoadoutOffersLine(i)
      end
   end
   ShowSelectLoadoutButtons()
end

handle OnEnteringState("Initial")
   if (subscribe)
      GetObservableLoadoutCount().Unsubscribe(this, "CheckUpdateLoadout")
      subscribe := false
   end
   enteringState := "Initial"
   //AddTween("alpha", 0.0, 0.15, "linear")
   Set("visible", false)// : 0.15
   $UiGlobals.DeathScreenLoadoutsMode.Set("weapons")
   ShowSelectLoadoutButtons()
   Widgets().ArmorLoadouts.SetStateName("Initial")
end          

handle OnEnterState("Initial")
   bLog("UI/INGAMESTATES", "Loadout: KillerPanel: Initial ")
   Widgets().KillerInfo.state := "Initial"
   Log("ui~loadoutSelect", "LoadoutPS_OnEnter_Initial")
   //Set("visible", false)           
end          

func InitFocus()
   SetFocus()
end

handle OnEnteringState("SeeLoadout")
   enteringState := "SeeLoadout"
   $user_service.RequestData($UserDataStorage.local_user.uid.Get(), $uiEnums.USER_DATA_WEAPON_LOADOUT)   
   Widgets().ArmorLoadouts.SetStateName("Initial")
   Widgets().LoadoutsModeToggleButton.visible := false
   Widgets().header.text := "UI_SEE_LOADOUT"
   Widgets().header.visible := false
   Widgets().cancelBtn.visible := true
   Widgets().cancelBtn.label := "main_btn_back"
   Widgets().doneBtn.visible := false
   Widgets().slots.visible := true
   Widgets().RespawnPanel.viewLoadoutsButton.visible := false
   Widgets().KillerInfo.state := "Initial"
   Set("visible", true)
   //AddTween("alpha", 1.0,     Props().adelay, "linear")
   isSelectingSlot := true
   clickFlag := false
   EnableFakeBg()
   InitFocus()
   StartBlink()   
end

handle OnLeavingState("SeeLoadout")
   //
end

handle OnEnteringState("Assign2Loadout")
   enteringState := "Assign2Loadout"
   Log("ui~loadoutSelect", "LoadoutPS_OnEntering_Visible_State_Assign2Loadout")
   Widgets().ArmorLoadouts.SetStateName("Initial")
   Widgets().LoadoutsModeToggleButton.visible := false
   $user_service.RequestData($UserDataStorage.local_user.uid.Get(), $uiEnums.USER_DATA_WEAPON_LOADOUT)      
   Widgets().header.text := "carousel_assign_to_loadout"
   Widgets().header.visible := false
   //Widgets().LoadoutGoldButton.visible := true
   Widgets().cancelBtn.visible := true
   Widgets().cancelBtn.label := "main_btn_back"
   Widgets().doneBtn.visible := true
   Widgets().slots.visible := true
   Widgets().RespawnPanel.viewLoadoutsButton.visible := false
   Widgets().KillerInfo.state := "Initial"
   //Widgets().background.alpha := 100
   Set("visible", true)
   //AddTween("alpha", 1.0,     Props().adelay, "linear")
   isSelectingSlot := true
   clickFlag := false
   EnableFakeBg()
   InitFocus()
   StartBlink()   
end  

handle OnLeavingState("Assign2Loadout")
   GenerateEvent("WeaponConfUpdateDisplayData")      
end

handle OnEnteringState("SelectLoadout")
   enteringState := "SelectLoadout"
   Log("ui~loadoutSelect", "LoadoutPS_OnEntering_Visible_State_SelectLoadout")
   Widgets().ArmorLoadouts.SetStateName("Initial")
   Widgets().LoadoutsModeToggleButton.visible := true
   Widgets().LoadoutsModeToggleButton.label := "ingame_quick_armor_loadouts"
   Widgets().cancelBtn.visible := true
   Widgets().cancelBtn.label := "main_cancel"
   //Widgets().LoadoutGoldButton.visible := false
   Widgets().doneBtn.visible := false
   Widgets().header.text := "carousel_select_loadout"
   Widgets().header.visible := true
   //Widgets().background.alpha := 0
   Widgets().slots.visible := true
   Widgets().RespawnPanel.viewLoadoutsButton.visible := false			
   Widgets().KillerInfo.state := "Initial"
   Set("visible", true)
   //AddTween("alpha", 1.0, Props().adelay, "linear")
   isSelectingSlot := false
   EnableFakeBg()
   InitFocus()
   StartBlink()   
end  

handle OnLeavingState("SelectLoadout")
   GenerateEvent("WeaponConfUpdateDisplayData") 
end

handle OnEnteringState("SelectLoadoutPregame")
   enteringState := "SelectLoadoutPregame"
   Log("ui~loadoutSelect", "LoadoutPS_OnEntering_Visible_State_SelectLoadout")
   Widgets().ArmorLoadouts.SetStateName("Initial")
   Widgets().LoadoutsModeToggleButton.visible := true
   Widgets().LoadoutsModeToggleButton.label := "ingame_quick_armor_loadouts"
   Widgets().cancelBtn.visible := false
   //Widgets().LoadoutGoldButton.visible := false
   Widgets().doneBtn.visible := false
   Widgets().header.text := "carousel_select_loadout"
   Widgets().header.visible := true
   //Widgets().background.alpha := 0
   Widgets().slots.visible := true
   Widgets().RespawnPanel.viewLoadoutsButton.visible := false			
   Widgets().KillerInfo.state := "Initial"
   Set("visible", true)
   //AddTween("alpha", 1.0, Props().adelay, "linear")
   isSelectingSlot := false
   InitFocus()
   StartBlink()
end  

handle OnLeavingState("SelectLoadoutPregame")
   GenerateEvent("WeaponConfUpdateDisplayData") 
end

handle OnEnteringState("ChoiceLoadoutBtn")
   enteringState := "ChoiceLoadoutBtn"
   Log("ui~loadoutSelect", "LoadoutPS_OnEntering_Visible_State_ChoiceLoadoutBtn")
   Widgets().ArmorLoadouts.SetStateName("Initial")
   Widgets().LoadoutsModeToggleButton.visible := false

   Widgets().cancelBtn.visible := false
   //Widgets().LoadoutGoldButton.visible := false
   Widgets().doneBtn.visible := false
   Widgets().header.text := "carousel_select_loadout"
   Widgets().header.visible := false
   //Widgets().background.alpha := 0	
   Widgets().slots.visible := false
   Widgets().RespawnPanel.viewLoadoutsButton.visible := true
   Widgets().RespawnPanel.respawnButton.SetFocus()
   bLog("UI/INGAMESTATES", "Loadout: KillerPanel: Visible ")
   Widgets().KillerInfo.state := "Visible" // (tmp) false
   Widgets().KillerInfo.ShowKillerInfo()
   Set("visible", true)
   InitFocus()
   StartBlink()
   //AddTween("alpha", 1.0, Props().adelay, "linear")
end  

handle OnLeavingState("ChoiceLoadoutBtn")
   GenerateEvent("WeaponConfUpdateDisplayData") 
end

handle OnEnteringState("SelectArmorLoadout")
   enteringState := "SelectArmorLoadout"
   Widgets().ArmorLoadouts.SetStateName("SelectArmorLoadoutIngame")
   Widgets().LoadoutsModeToggleButton.visible := true
   Widgets().LoadoutsModeToggleButton.label := "ingame_quick_weapon_loadouts"

   Log("ui~loadoutSelect", "LoadoutPS_OnEntering_Visible_State_SelectLoadout")
   Widgets().cancelBtn.visible := true
   Widgets().cancelBtn.label := "main_cancel"
   Widgets().slots.visible := false
   Widgets().RespawnPanel.viewLoadoutsButton.visible := false			
   Widgets().KillerInfo.state := "Initial"
   Set("visible", true)
   //AddTween("alpha", 1.0, Props().adelay, "linear")
   isSelectingSlot := false
   EnableFakeBg()
   InitFocus()
   StartBlink()   
end

handle OnEnteringState("SelectArmorLoadoutPregame")
   enteringState := "SelectArmorLoadoutPregame"
   Widgets().ArmorLoadouts.SetStateName("SelectArmorLoadoutIngame")
   Widgets().LoadoutsModeToggleButton.visible := true
   Widgets().LoadoutsModeToggleButton.label := "ingame_quick_weapon_loadouts"

   Log("ui~loadoutSelect", "LoadoutPS_OnEntering_Visible_State_SelectLoadout")
   Widgets().cancelBtn.visible := false
   Widgets().cancelBtn.label := "main_cancel"
   Widgets().slots.visible := false
   Widgets().RespawnPanel.viewLoadoutsButton.visible := false			
   Widgets().KillerInfo.state := "Initial"
   Set("visible", true)
   //AddTween("alpha", 1.0, Props().adelay, "linear")
   isSelectingSlot := false
   EnableFakeBg()
   InitFocus()
   StartBlink()   
end

func SetScreenAlpha(_alpha: float)
   Props().alpha := _alpha
end

func OnDialogShowTween(p: params): bool
   var alphaParm : float = p.dialogTweenParm
   if (GetStateName() != "Initial")
      SetScreenAlpha(100.0 - alphaParm * 95)
   end
   return true
end

func EnableFakeBg()
   var p: params
   if (minSlotIdx <= 2)
      p.state := "loadout"      
   else
      p.state := "loadoutTP"
   end
   GenerateEvent("ChangeFakeBackground", p)
end

func StartBlink()
   Props().alpha := 0.0
   AddTween("alpha", 1.0, 0.35, "linear")
   StartBlink2()
end

func StartBlink2()
   if enteringState != "ChoiceLoadoutBtn"
      $root.playSound("armory_screen_appear_hud")
   end
   var t0 : float = 0.0
   Widgets().slots.Loadout0.StartBlink(t0)
   Widgets().slots.Loadout1.StartBlink(t0)
   Widgets().slots.Loadout2.StartBlink(t0)
   Widgets().slots.Loadout3.StartBlink(t0)
   Widgets().slots.Loadout4.StartBlink(t0)
   Widgets().slots.offerPanel1.StartDefaultBlinking(t0 + 0.9)
   Widgets().slots.offerPanel2.StartDefaultBlinking(t0 + 0.9)
   Widgets().slots.offerPanel3.StartDefaultBlinking(t0 + 0.9)
   Widgets().slots.offerPanel4.StartDefaultBlinking(t0 + 0.9)
   Widgets().doneBtn.StartDefaultBlinking(t0 + 0.9)
   Widgets().cancelBtn.StartDefaultBlinking(t0 + 0.9)
end

func weaponsToggleButtonClicked(p : params) : bool
   $UiGlobals.DeathScreenLoadoutsMode.Set("weapons")
   ShowSelectLoadoutButtons()
   return false
end

func armorsToggleButtonClicked(p : params) : bool
   $UiGlobals.DeathScreenLoadoutsMode.Set("armors")
   ShowSelectLoadoutButtons()
   return false
end

func onArmoryLoadoutClicked2(p: params): bool
   //actual selecting armor loadout is in hf2p_ArmoryLoadout.ssl -> UiArmorLoadout::onArmoryLoadoutClicked
   if (GetStateName() == "SelectArmorLoadout")
      SetStateName("ChoiceLoadoutBtn")
   end
   return false
end

func OnLoadoutsModeToggleButtonClicked(p: params): bool
   if $UiGlobals.DeathScreenLoadoutsMode.Get() == "weapons"
      $UiGlobals.DeathScreenLoadoutsMode.Set("armors")
      if (GetStateName() == "SelectLoadout")
         SetStateName("SelectArmorLoadout")
      elif (GetStateName() == "SelectLoadoutPregame")
         SetStateName("SelectArmorLoadoutPregame")
      end
   else
      $UiGlobals.DeathScreenLoadoutsMode.Set("weapons")
      if (GetStateName() == "SelectArmorLoadout")
         SetStateName("SelectLoadout")
      elif (GetStateName() == "SelectArmorLoadoutPregame")
         SetStateName("SelectLoadoutPregame")
      end
   end
   return false
end

func inputEvent(p : params) : bool
   if (GetStateName() == "ChoiceLoadoutBtn")
      if (p.keyCode == $uiKeys.VK_SPACE and ! p.isDown)
         Widgets().RespawnPanel.respawnButton.SetFocus()
         Widgets().RespawnPanel.GenerateEvent("#respawnNowClick")
      end         
   else
      if (p.keyCode != $uiKeys.VK_ENTER and p.keyCode != $uiKeys.VK_SPACE)
         p.eventState.SetIsTerminated()      
      end
      if (p.keyCode == $uiKeys.VK_ESC and ! p.isDown)
         if (Widgets().cancelBtn.visible)
            onCancel(null)
         end
      elif (p.keyCode == $uiKeys.VK_ENTER and ! p.isDown)
         if (Widgets().doneBtn.visible)
            doneA2l(null)
         end
      end      
   end
   return false
end

end

class RespawnPanelVM
   var respawnTimerTxt        : ObservableProperty = $OM.Property("")
   var isRespawnTimerVisible  : ObservableProperty = $OM.Property(false)
   var isRepawnButtonEnabled  : ObservableProperty = $OM.Property(false)
   var isRepawnButtonVisible  : ObservableProperty = $OM.Property(false)
   var repawnButtonLabel      : ObservableProperty = $OM.Property("")
   var isRespawnPanelVisible  : ObservableProperty = $OM.Property(false)
   

   func Init(p : params)
      $UiIngame.state_timer.Subscribe(this, "UpdateControls")
      $UiIngame.respawn.is_auto_respawn_countdown.Subscribe (this, "UpdateControls")
      $UiIngame.respawn.is_early_respawn_enabled.Subscribe  (this, "UpdateControls")
      $UiIngame.respawn.is_early_respawn_requested.Subscribe(this, "UpdateControls")
   end
   
   func Term()
      $UiIngame.state_timer.Unsubscribe(this, "UpdateControls")
      $UiIngame.respawn.is_auto_respawn_countdown.Unsubscribe (this, "UpdateControls")
      $UiIngame.respawn.is_early_respawn_enabled.Unsubscribe  (this, "UpdateControls")
      $UiIngame.respawn.is_early_respawn_requested.Unsubscribe(this, "UpdateControls")
   end
   
   func ShowRespawnPanel(p : params) : bool
      isRespawnPanelVisible.Set(true)
      return true
   end
   
   func HideRespawnPanel(p : params) : bool
      isRespawnPanelVisible.Set(false)
      return true
   end
   
   func UpdateControls(_val : *)
      var is_auto_respawn_countdown       : bool   = (bool)$UiIngame.respawn.is_auto_respawn_countdown.Get()
      var is_early_respawn_enabled        : bool   = (bool)$UiIngame.respawn.is_early_respawn_enabled.Get()
      var is_early_respawn_requested      : bool   = (bool)$UiIngame.respawn.is_early_respawn_requested.Get()
      var timer                           : int    = GetRespawnTimer()
      
      var respawnTimerTxtSet              : string = ""
      var isRepawnButtonEnabledSet        : bool   = false
      var repawnButtonLabelSet            : string = ""
      var isRepawnButtonVisibleSet        : bool   = false
      
      
      if (is_early_respawn_enabled)         
         if (is_early_respawn_requested)            
            if (is_auto_respawn_countdown)
               // wait for auto respawn after request
               isRepawnButtonEnabledSet   := false
               isRepawnButtonVisibleSet   := true
               repawnButtonLabelSet       := "ingame_respawn_requested"
               respawnTimerTxtSet         := "ingame_auto_respawn_timer," + (string)(GetRespawnTimer())
            end
         else
            if (is_auto_respawn_countdown)
               // respawn now
               isRepawnButtonEnabledSet   := true
               isRepawnButtonVisibleSet   := true
               repawnButtonLabelSet       := "ingame_respawn_label_respawn_now"
               respawnTimerTxtSet         := ""
            else
               // do early request
               isRepawnButtonEnabledSet   := true
               isRepawnButtonVisibleSet   := true
               repawnButtonLabelSet       := "ingame_respawn_request"
               respawnTimerTxtSet         := "ingame_respawn_available_timer," + (string)(GetRespawnTimer())
            end
         end
      else
         if (is_auto_respawn_countdown)
            // wait auto respawn
            isRepawnButtonEnabledSet   := false
            isRepawnButtonVisibleSet   := is_auto_respawn_countdown
            if (is_auto_respawn_countdown)
               repawnButtonLabelSet    := "ingame_respawn_requested"
               respawnTimerTxtSet      := "ingame_auto_respawn_timer," + (string)(GetRespawnTimer())
            end
         end
      end
      isRepawnButtonEnabledSet := isRepawnButtonEnabledSet and (bool)isRespawnPanelVisible.Get()
            
      isRespawnTimerVisible.Set(respawnTimerTxtSet != "")
      respawnTimerTxt.Set(respawnTimerTxtSet)
      isRepawnButtonEnabled.Set(isRepawnButtonEnabledSet)
      isRepawnButtonVisible.Set(isRepawnButtonVisibleSet)
      repawnButtonLabel.Set(repawnButtonLabelSet)  
   end

   func respawnNowClick(p : params) : bool
      if ((bool)isRepawnButtonEnabled.Get() and (bool)isRepawnButtonVisible.Get())
         $UiIngame.EarlyRespawnRequest()
      end
      return true
   end

   func GetRespawnTimer() : int
      var timeCur : int = (int)$UiIngame.state_timer.Get()
      return timeCur
   end   
end