import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.items_mgr
import ui.root
import ui.ui_economy
import ui.ui_player_info
import ssl.hf2p.engine_ctrl

class UiArmoryPreviewCamera : UiWidgetContainer

var startCameraAngle : float = 0

func SetView(_armorType: string)
end

override StartDrag   
   startCameraAngle  := $hf2pEngine.GetRotatePlayerModel()
   var pp: params
   pp.dragEvent   := "ArmoryPreviewCameraDrag"
   pp.dragTarget  := this
   GenerateEvent("StartUniversalDrag", pp)
   return null
end

func OnArmoryPreviewCameraDrag(p: params): bool
   if (p.updateType == "update")
      $hf2pEngine.SetRotatePlayerModel(startCameraAngle + p.mouseOffset.x * 0.5)
   elif (p.updateType == "start")
      GenerateEvent("StartArmoryModelDrag")
   elif (p.updateType == "end")
      GenerateEvent("EndArmoryModelDrag")
   end
   return false
end
end

class UiArmoryRotate : UiWidgetContainer
   
   func OnStartArmoryModelDrag(p : params) : bool
      Props().anim := "over"
      return true
   end
   
   func OnEndArmoryModelDrag(p : params) : bool
      Props().anim := "up"
      return true
   end
end