import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_manager
import ssl.hf2p.engine_ctrl
import ssl.observables
import ssl.hf2p.ui_globals
import ui.ui_economy
import ssl.hf2p.user_data
import ui.root

/*************************************************************
* UiSlidingScreenPageBase
* 
*************************************************************/
class UiSlidingScreenPageBase : UiWidgetContainer
   handle OnEnteringState("Initial")
   end   

   handle OnEnterState("Initial")
   end   

   handle OnEnteringState("Visible")
   end   

   handle OnEnterState("Visible")
   end

   func PrepareSlide()
      if (GetStateName() != "Visible")
         SetStateName("Visible")
         GenerateEvent("#OpenSlidingPage")
      else
         GenerateEvent("#PrepareSlide")
      end
   end

   func PrepareHideSlide()
   end

   func DisableSlide()
      if (GetStateName() != "Initial")
         SetStateName("Initial")
         GenerateEvent("#CloseSlidingPage")
      else
         GenerateEvent("#DisableSlide")
      end
   end

   func SwitchToScreen()
   end
   
   func HasConfirmationOnClose() : bool
      return false
   end
   
   func OnCloseConfirmation(onAgree : refFUNC_PTR)
   end
end

/*************************************************************
* UiSlidingScreenPageBaseVM
* 
*************************************************************/
class UiSlidingScreenPageBaseVM
   var isActive   : ObservableProperty = $OM.Property(false)
   
   func OpenSlidingPage(p : params) : bool
      isActive.Set(true)
      OnOpen() : 0.1
      return true
   end
   
   func PrepareSlide // ()
      
   end
   
   func DisableSlide // ()
      
   end
   
   func OnOpen()
      
   end
   
   func OnClose()
      
   end
   
   func CloseSlidingPage(p : params) : bool
      isActive.Set(false)
      OnClose()
      return true
   end   
end

/*************************************************************
* UiSlidingScreenPageMainMenu
* 
*************************************************************/
class UiSlidingScreenPageMainMenu : UiSlidingScreenPageBase
   func GetPageDC() : UiSlidingScreenMainMenuPageVM
      return (UiSlidingScreenMainMenuPageVM)GetDC()
   end
   
   func GetSpartanCameraFlag() : bool
      return true
   end
end

/*************************************************************
* UiSlidingScreenMainMenuPageVM
* 
*************************************************************/
class UiSlidingScreenMainMenuPageVM : UiSlidingScreenPageBaseVM
   var parentVM : SlidingScreensMainMenuVM = null
   
   func Init(p : params)
      parentVM := (SlidingScreensMainMenuVM)p.widget.GetWidget("_parent").GetWidget("_parent").GetWidget("_parent").GetWidget("_parent").Get("DC")
      InitOverride(p)
   end
   
   func InitOverride(p : params)
   end
   
   func Term()
      TermOverride()
   end
   
   func TermOverride()
   end
   
   func LoadoutPanelSlotClicked(p : params) : bool
      return true
   end
   
   func GetLoadoutsHighlightedItem() : string
      return $uiEnums.EMPTY_STRING
   end
   
   func GetLoadoutsFilterId() : string
      return $uiEnums.EMPTY_STRING
   end   
end

/*************************************************************
* UiSlidingScreenPageSettings
* 
*************************************************************/
class UiSlidingScreenPageSettings : UiSlidingScreenPageBase
   func GetPageDC() : UiSlidingScreenSettingsPageVM
      return (UiSlidingScreenSettingsPageVM)GetDC()
   end
   
   func Init()
      
   end
   
   func ReInit()
      
   end
   
   func Revert()
      
   end
   
   func Reset()
      
   end
   
   func Apply() : bool
      return true
   end
   
   func HaveUnsavedChanges() : bool
      return false
   end
   
   func tryToCloseOrReturn() : bool
      return false
   end
end

/*************************************************************
* UiSlidingScreenSettingsPageVM
* 
*************************************************************/
class UiSlidingScreenSettingsPageVM : UiSlidingScreenPageBaseVM
end

