import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_manager
import ssl.hf2p.engine_ctrl
import ssl.observables
import ssl.hf2p.ui_globals
import ui.ui_economy
import ssl.hf2p.user_data
import ui.root

import ui.libs.hf2p_ItemPopup_lib.hf2p_ItemPopup_lib
import ui.libs.hf2p_SlidingScreens.hf2p_sliding_screens_lib

class UiWeaponConfScreen : UiSlidingScreenPageMainMenu

var isSlidingElement : bool   = false
var isHidden         : bool   = true

func focusOut(p : params) : bool
   if (IsVoid(p.toWidget))
      SetWeaponModelFocus()
   end
   return false
end

func OpenBuyDialogue(p : params) : bool
   var itemId : string = p.itemId
   var offer : GL_ComponentShopOffer = p.offer
   var isGold : bool = p.isGold
   var playerCurrency = 0
   var offerString : string
   var offerCost : int
   if offer == null
      return true
   end
   if isGold
      playerCurrency := (int)$UserDataStorage.local_user.gold.Get()
      offerString := (string)offer.gl_offer.Get()
      offerCost := (int)offer.gl_cost.Get()
   else
      playerCurrency := (int)$UserDataStorage.local_user.cr.Get()
      offerString := (string)offer.cr_offer.Get()
      offerCost := (int)offer.cr_cost.Get()
   end
   if offerString != ""
      var par: params
      par.itemID        :=  itemId
      par.offer         := offerString
      par.priceAmount   := offerCost
      if isGold
         par.priceUnit  := $uiEnums.TOKEN_GOLD
      else
         par.priceUnit  := $uiEnums.TOKEN_CREDITS
      end
      if (offerCost <= playerCurrency)
         // is rent ?
         var ret : int = 0
         ret := (int)offer.rent_duration.Get()
         if (ret > 0)
            par.isRent := true
         end
         // end 
         par.mbType           := "ConfirmBuy"
         par.callbackEvent    := "OnItemPurchased"
         par.callbackTarget   := Props
      else
         par.mbType     := "Info"
         par.titleTxt   := "msg_ui_warning"
         if isGold
            par.messageTxt := "msg_ui_not_enough_gp"
         else
            par.messageTxt := "msg_ui_not_enough_cr"
         end
      end
      $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
   end
   return true
end

func SetWeaponModelFocus()
   Widgets.itemDescModel.animWeaponsBig.SetFocus()   
end

func OnToggleInspection()
   SetWeaponModelFocus()
end

func inputEvent(p: params) : bool
   var code          : int    = p.keyCode
   var isTerminated  : bool   = false
   var ret           : bool   = GetDC().inputEvent(p)
   
   if (ret)   
      if (code == $uiKeys.VK_DOWN or code == $uiKeys.VK_UP or code == $uiKeys.VK_LEFT or code == $uiKeys.VK_RIGHT)
         isTerminated := true
      end
      
      if (code == $uiKeys.VK_W or code == $uiKeys.VK_A or code == $uiKeys.VK_S or code == $uiKeys.VK_D)
         isTerminated := true
      end
      
      if (isTerminated)
         $hf2pEngine.OnWeaponScreenKeyDown($uiEnums.UI_RTTS_WEAPONS_SHOP, code, p.isDown)
         p.eventState.SetIsTerminated(true)
      end
      ret := !isTerminated
   end
   return ret
end

func OnLeaveLobby() : bool
   Log("ui~content", " WeaponConfig::OnLeaveLobby() ")
   GenerateEvent("LeaveLobby")
   return false
end

override SwitchToScreen//()   
end

func OnOpenLoadoutBtnClicked(p:params):bool
   Log("ui~content", "OnOpenLoadoutBtnClicked")
   GenerateEvent("SeeLoadout", p)
   return false
end

handle OnEnteringState("Initial")
   Log("ui~content", "Weapon Config OnEntering Initial!!!")
end          

handle OnEnterState("Initial")
   Log("ui~content", "Weapon Config onEnter Initial!!!")
   Set("visible", false)            
   GenerateEvent("#CloseShop")
end          

handle OnEnteringState("Visible")
   Log("ui~content", "Weapon Config OnEntering VISIBLE!!!")         
   Set("visible", true)
end  

handle OnEnterState("Visible")
   Log("ui~content", "Weapon Config onEnter VISIBLE!!!")         
end

override PrepareSlide//()
   if (GetStateName() != "Visible")
      SetStateName("Visible")
   end
   EnableFakeBg()
   GenerateEvent("#OpenedWeaponConfig")
   if (isHidden)
      isHidden := false
      StartDefaultBlinking(0.3)
   end   
end

override PrepareHideSlide//()
   GenerateEvent("#HideShop")
   isHidden := true
end

func OnBlinkItemList(p : params) : bool
   Widgets.weaponConfContent.weaponList.SetSelectionIdx(0)
   Widgets.weaponConfContent.weaponList.StartDefaultBlinking(0.0)
   BarsBlink() : 0
   $root.playSound("screen_rollout")
   return false
end

func BarsBlink()
   Widgets.weaponConfContent.progressBars.StartDefaultBlinking(-0.4, 1.1)
end

override DisableSlide //()
   if (GetStateName() != "Initial")
      SetStateName("Initial")
   end
   isHidden := true
end

func EnableFakeBg()
   var p: params
   p.state := "weapons"
   GenerateEvent("ChangeFakeBackground", p)
end

func OnItemPurchased(p : params) : bool
   if (p.isOK)
      GenerateEvent("#OnWeaponPurchased", p)
   end
   return true
end

func SetListSelection(p : params) : bool
   Widgets.weaponConfContent.weaponList.SetSelectionIdx(p.idx)
   return false
end

override SaveState //() : params
   var ret : params = GetDC().SaveState()
   return ret
end

override LoadState // (p : params) : bool
   var ret : bool = GetDC().LoadState(p)
   return true
end

end

class WeaponItemLIR
   var wgt           : UiWidget = null
   var itemId        : ObservableProperty = $OM.Property("")

   var minOffer      : ObservableProperty = $OM.Calculated(this, "GetMinOffer") 
   var maxDiscount   : ObservableProperty = $OM.Calculated(this, "GetMaxDiscount") 

   var weaponTint    : ObservableProperty = $OM.Calculated(this, "GetWeaponTint")
   var isWeaponTintVisible : ObservableProperty = $OM.Calculated(this, "GetIsWeaponTintVisible")
   var offerGp       : ObservableProperty = $OM.Calculated(this, "GetOfferGp")
   var offerCr       : ObservableProperty = $OM.Calculated(this, "GetOfferCr")
   var ownType       : ObservableProperty = $OM.Calculated(this, "GetOwnType")
   var isOffers      : ObservableProperty = $OM.Calculated(this, "GetIsOffers")
   var rentStatus    : ObservableProperty = $OM.Calculated(this, "GetRentStatus")
   var rentStatusColor :  ObservableProperty = $OM.Calculated(this, "GetRentStatusColor")
   var weaponIndicatorScaleX    : ObservableProperty = $OM.Calculated(this, "GetWeaponIndicatorScaleX")
   var isGpCrLock    : ObservableProperty = $OM.Calculated(this, "GetIsGpCrLock")
   var isLevelLock   : ObservableProperty = $OM.Calculated(this, "GetIsLevelLock")
   var equipIcn      : ObservableProperty = $OM.Calculated(this, "GetEquipIcon")
   var equipLabel    : ObservableProperty = $OM.Calculated(this, "IsLabelEquip")
   var equipEmblem   : ObservableProperty = $OM.Calculated(this, "IsEmblemEquip")
   var isNew         : ObservableProperty = $OM.Calculated(this, "GetIsNew")
   var itemQuality   : ObservableProperty = $OM.Calculated(this, "GetWeaponQuality")
   
   func Init(p : params)
      wgt := p.widget
      if (! IsVoid(p.itemId))
         itemId.Set(p.itemId)
      end
      wgt.Props.mouseChildren := true
   end
   
   func Update(p : params)
      itemId.Set(p.itemId)
   end
   
   func OnItemPriceGoldClicked(p : params) : bool
      var p2 : params
      p2.itemId := itemId.Get()
      p2.offer := $UiGlobals.componentsShop.Get(itemId.Get()).GetMinimalOffer()
      p2.isGold := true
      wgt.GenerateEvent("#OpenBuyDialogue", p2)
      return true
   end
   
   func OnItemPriceCrClicked(p : params) : bool
      var p2 : params
      p2.itemId := itemId.Get()
      p2.offer := $UiGlobals.componentsShop.Get(itemId.Get()).GetMinimalOffer()
      p2.isGold := false
      wgt.GenerateEvent("#OpenBuyDialogue", p2)
      return true
   end
   
   func OnItemLirClicked(p : params) : bool
      var x : * = wgt.Props.mouseChildren
      if isNew.Get() == true
         $hq.ShopNewClear((string)itemId.Get())
      end
      return true
   end
   
   func GetMinOffer() : GL_ComponentShopOffer
      var ret : GL_ComponentShopOffer = null
      if ((bool)isOffers.Get())
         var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)itemId.Get())
         if (shopComp.offers.Get().Count() > 0)
            ret := shopComp.GetMinimalOffer()
         end
      end
      return ret
   end
      
   func GetMaxDiscount() : string
      var ret : string = ""
      if ((bool)isOffers.Get())
         var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)itemId.Get())
         if (shopComp.offers.Get().Count() > 0)
            var maxDisc : float = 0
            var i : int
            for i := 0 to shopComp.offers.Get().Count() - 1
               var offer : GL_ComponentShopOffer = shopComp.offers.Get().Get(i)
               if (float)offer.cr_sale_percentage.Get() > maxDisc
                  maxDisc := (float)offer.cr_sale_percentage.Get()
               end
               if (float)offer.gl_sale_percentage.Get() > maxDisc
                  maxDisc := (float)offer.gl_sale_percentage.Get()
               end
            end
            if maxDisc > 0
               ret := "-" + (string)(int)(maxDisc * 100) + "%"
            end
         end
      end
      return ret
   end
      
   func GetIsGpCrLock() : bool
      var ret : bool
      ret := IsCrLock() and IsGlLock()
      return ret
   end
   
   func GetIsLevelLock() : bool
      var ret : bool = false
      var userLvl  : int = (int)$UserDataStorage.local_user.level.Get()
      var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)itemId.Get())
      var itemLevel : int = (int)shopComp.unlock_level.Get()
      if itemLevel > userLvl
         ret := true
      end
      return ret
   end
   
   func GetWeaponTint() : params
      var itemIdS :  * = itemId.Get()
      var itemIdStr :  string = (string)itemId.Get()
      var   tint     : params = $uiEconomy.GetWeaponPrimaryArrtibuteColor("unknown")
      if (itemIdStr != "")
         var   weapon   :  GL_ComponentWeapon = (GL_ComponentWeapon)$UiGlobals.componentsWeapon.Get(itemIdStr)
         if (weapon != null)
            tint := $uiEconomy.GetWeaponPrimaryArrtibuteColor((string)weapon.primary_attribute_id.Get())
         end
      end
      return tint
   end
   
   func GetIsWeaponTintVisible() : bool
      var itemIdS :  * = itemId.Get()
      var itemIdStr :  string = (string)itemId.Get()
      var ret     : bool = false
      if (itemIdStr != "")
         var   weapon   :  GL_ComponentWeapon = (GL_ComponentWeapon)$UiGlobals.componentsWeapon.Get(itemIdStr)
         if (weapon != null)
            ret := (string)weapon.primary_attribute_id.Get() != "none" and (string)weapon.primary_attribute_id.Get() != ""
         end
      end
      return ret
   end
   
   func GetWeaponQuality() : string
      var ret : string = "common"
      var itemIdStr : string = (string)itemId.Get()
      if (itemIdStr != "")
         ret := (string)$UiGlobals.componentsUI.Get(itemIdStr).quality.Get()
      end
      return ret  
   end
   
   func GetWeaponIndicatorScaleX() : float
      var ret : float
      var ownTypeVal :  int = GetOwnType()
      if (ownTypeVal == $uiEnums.ITEM_OWN_TYPE_NONE)
         ret := 1.0
      else
         ret := 2.625
      end
      return ret
   end
   
   func GetEquipIcon() : bool
      var ret : bool
      var uiInventoryItem : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)itemId.Get())
      var equipType : int = (int)uiInventoryItem.equipped_state.Get()
      if (equipType == 2)
         ret := true
      else   
         ret := false
      end
      return ret
   end 
   
   func IsLabelEquip() : bool
      var ret     : bool   = false
      var myLabel : string = ""
      myLabel := $UserDataStorage.GetPlayerLabel($UserDataStorage.local_user.uid.Get())
      if (myLabel == (string)itemId.Get())
         ret := true
      end
      return ret
   end
   
   func IsEmblemEquip() :  bool
      var ret : bool = false
      var myEmblem : string = ""
      var ud : UserData = (UserData) $UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
      myEmblem := (string)ud.customizations.emblem.Get()
      if (myEmblem == (string)itemId.Get())
         ret := true
      end
      return ret 
   end
   
   func GetIsNew() : bool
      var ret = $uiEconomy.GetIsItemNew((string)itemId.Get())
      return ret
   end
   
   func GetOfferGp() : string
      var ret : string = "carousel_offer_na_small"
      if minOffer.Get() != null
         var offer = (GL_ComponentShopOffer)minOffer.Get()
         if ((int)offer.gl_cost.Get() > 0)
            ret := (string)(int)offer.gl_cost.Get()
         end   
      end
      return ret
   end
   
   func GetOfferCr() : string
      var ret : string = "carousel_offer_na_small"
      if minOffer.Get() != null
         var offer = (GL_ComponentShopOffer)minOffer.Get()
         if ((int)offer.cr_cost.Get() > 0)   
            ret := (string)(int)offer.cr_cost.Get()
         end
      end
      return ret
   end

   func GetOwnType() : int
      return $uiEconomy.GetItemOwnType((string)itemId.Get())
   end
   
   func GetIsOffers() : bool
      var ret : bool
      //if (GetOwnType() == $uiEnums.ITEM_OWN_TYPE_NONE and (IsGlLock() or IsCrLock()))         
      //if (GetOwnType() == $uiEnums.ITEM_OWN_TYPE_NONE or IsGlLock() or IsCrLock())         
      if (GetOwnType() == $uiEnums.ITEM_OWN_TYPE_NONE)         
         ret := true
      else
         ret := false
      end
      return ret
   end
   
   func GetRentTime() : int
      var ret        : int = 0
      var ownTypeVal : int = (int)ownType.Get()
      if (ownTypeVal == $uiEnums.ITEM_OWN_TYPE_RENTED)
         var uiInventoryItem : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)itemId.Get())
         var ownTime : int = (int)uiInventoryItem.ownership_time.Get() - (int)$UiGlobals.timer.Get()
         ret := ownTime
      end
      return ret      
   end
      
   func IsLocked() : bool
      return $uiEconomy.IsItemLocked((string)itemId.Get())
   end
   
   func IsGlLock() : bool
      return $uiEconomy.IsItemLockedGl((string)itemId.Get())
   end

   func IsCrLock() : bool
      return $uiEconomy.IsItemLockedCr((string)itemId.Get())
   end
   
   func GetRentStatusColor() : int
      return $uiEconomy.GetItemRentTintColor((string)itemId.Get())
   end
   
   func GetRentStatus() : string
      var ret        : string      
      
      var ownTypeVal : int = (int)ownType.Get()
      if (ownTypeVal == $uiEnums.ITEM_OWN_TYPE_PURCHASED)
         ret := "carousel_rent_time_purchased"
      elif (ownTypeVal == $uiEnums.ITEM_OWN_TYPE_RENTED)
         var ownTime : int = GetRentTime()
         if (ownTime > 0)
            ret := $root.MakeUiTimerStringMinutes(ownTime, true)
         else
            ret := "carousel_rent_time_expiring"
         end
      end
      
      return ret
   end
 end

class ItemDescPanelVM
   var itemId           : ObservableProperty = $OM.Property("")
   var itemDesc         : ObservableProperty = $OM.Calculated(this, "GetItemDesc")
   var itemSubDesc      : ObservableProperty = $OM.Calculated(this, "GetItemSubDesc")
   var itemName         : ObservableProperty = $OM.Calculated(this, "GetItemName")
   var isLockLineGp     : ObservableProperty = $OM.Calculated(this, "GetIsLockLineGp")
   var lockLineGp       : ObservableProperty = $OM.Calculated(this, "GetLockLineGp")
   var lockLineGpCoordY : ObservableProperty = $OM.Calculated(this, "GetLockLineGpCoordY")
   var isLockLineCr     : ObservableProperty = $OM.Calculated(this, "GetIsLockLineCr")
   var lockLineCr       : ObservableProperty = $OM.Calculated(this, "GetLockLineCr")
   var lockLineCrCoordY : ObservableProperty = $OM.Calculated(this, "GetLockLineCrCoordY")
   var weaponClr        : ObservableProperty = $OM.Calculated(this, "GetWeaponColor")
      
   func GetItemDesc() : string
      var ret     : string
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get((string)itemId.Get())
      ret := (string)compUI.desc.Get()
      return ret
   end
   
   func GetWeaponColor() : int
      var itemIdS   : * = itemId.Get()
      var itemIdStr : string = (string)itemId.Get()
      var tint      : params = $uiEconomy.GetWeaponPrimaryArrtibuteColor("unknown")
      var clr       : int = 0 
      if (itemIdStr != "")
         var   weapon   :  GL_ComponentWeapon = (GL_ComponentWeapon)$UiGlobals.componentsWeapon.Get(itemIdStr)
         if (weapon != null)
            tint := $uiEconomy.GetWeaponPrimaryArrtibuteColor((string)weapon.primary_attribute_id.Get())
            clr := $root.RGB2Clr(tint.r, tint.g, tint.b)
         end
      end
      return clr
   end
   
   func GetOwnType() : int
      return $uiEconomy.GetItemOwnType((string)itemId.Get())
   end
   
   func GetItemName() : string
      var ret     : string
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get((string)itemId.Get())
      ret := (string)compUI.name.Get()
      return ret
   end

   func GetItemSubDesc() : string
      var ret     : string = ""
      return ret
   end
   
   func GetIsLockLineGp() : bool
      return $uiEconomy.IsItemLockedGl((string)itemId.Get()) or $uiEconomy.IsItemLockedCr((string)itemId.Get())
   end
   
   func GetLockLineGp() : string
      var ret : string = ""
      if (GetIsLockLineGp())
         ret := (string)$uiEconomy.GetItemLockedGlLvl((string)itemId.Get())
      end
      return ret
   end
   
   func GetLockLineGpCoordY() : float
      var ret : float = 3
      if (GetIsLockLineCr())
         ret := -24
      end
      return ret
   end
   
   func GetIsLockLineCr() : bool
      return false
   end
   
   func GetLockLineCr() : string
      var ret : string = ""
      if (GetIsLockLineCr())
         ret := (string)$uiEconomy.GetItemLockedCrLvl((string)itemId.Get())
      end
      return ret
   end
   
   func GetLockLineCrCoordY() : float
      var ret : float = 3
      return ret
   end
   
   func UpdateItemId(val : string)
      itemId.Set(val)
   end
end

class OffersLineVM
   var itemId     : ObservableProperty = $OM.Property("")
   var offerIdx   : ObservableProperty = $OM.Property(0)
   var isVisible  : ObservableProperty = $OM.Property(false)
   var isWide     : ObservableProperty = $OM.Property(false)
   var yPos       : ObservableProperty = $OM.Property(0.0)
   var isLvlLock  : ObservableProperty = $OM.Calculated(this, "IsLvlLock")
   var offer      : ObservableProperty = $OM.Calculated(this, "GetOffer")
   var isGpOffer  : ObservableProperty = $OM.Calculated(this, "GetIsGpOffer")
   var gpOffer    : ObservableProperty = $OM.Calculated(this, "GetGpOffer")
   var gpCost     : ObservableProperty = $OM.Calculated(this, "GetGpCost")
   var gpOldCost  : ObservableProperty = $OM.Calculated(this, "GetGpOldCost")
   var gpDiscount : ObservableProperty = $OM.Calculated(this, "GetGpDiscount")
   var gpAlpha    : ObservableProperty = $OM.Calculated(this, "GetGpAlpha")
   var isCrOffer  : ObservableProperty = $OM.Calculated(this, "GetIsCrOffer")
   var crOffer    : ObservableProperty = $OM.Calculated(this, "GetCrOffer")
   var crCost     : ObservableProperty = $OM.Calculated(this, "GetCrCost")
   var crOldCost  : ObservableProperty = $OM.Calculated(this, "GetCrOldCost")
   var crDiscount : ObservableProperty = $OM.Calculated(this, "GetCrDiscount")
   var crAlpha    : ObservableProperty = $OM.Calculated(this, "GetCrAlpha")
   var durationTxt   : ObservableProperty = $OM.Calculated(this, "GetDurationTxt")
   var durationLabel : ObservableProperty = $OM.Calculated(this, "GetDurationLabel")
   var shopWidget : UiWidget = null
      
   func OnUnlockWpnGoldBtnClick(p : params) : bool
      var p2 : params
      p2.itemId := itemId.Get()
      p2.offer := offer.Get()
      p2.isGold := true
      shopWidget.GenerateEvent("#OpenBuyDialogue", p2)
      return true
   end
         
   func OnUnlockWpnCrBtnClick(p : params) : bool
      var p2 : params
      p2.itemId := itemId.Get()
      p2.offer := offer.Get()
      p2.isGold := false
      shopWidget.GenerateEvent("#OpenBuyDialogue", p2)
      return true
   end
   
   func GetOffer() : GL_ComponentShopOffer
      var itemIdVal  : string                = (string)itemId.Get()
      var ret        : GL_ComponentShopOffer = null
      if (itemIdVal != "")
         var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)itemId.Get())
         if (shopComp.offers.Get().Count() > 0)
            var offerIdxVal : int = (int)offerIdx.Get()
            if (offerIdxVal < shopComp.offers.Get().Count())
               ret := (GL_ComponentShopOffer)shopComp.offers.Get().Get(offerIdxVal)
            end
         end
      end
      return ret      
   end
   
   
   func GetOwnType() : int
      return $uiEconomy.GetItemOwnType((string)itemId.Get())
   end
   
   func IsGlLock() : bool
      return $uiEconomy.IsItemLockedGl((string)itemId.Get())
   end

   func IsCrLock() : bool
      return $uiEconomy.IsItemLockedCr((string)itemId.Get())
   end
   
   func IsLvlLock() : bool
      var ret : bool = false
      var userLvl  : int = (int)$UserDataStorage.local_user.level.Get()
      var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)itemId.Get())
      var itemLevel : int = (int)shopComp.unlock_level.Get()
      if itemLevel > userLvl
         ret := true
      end
      return ret 
   end
   
   func GetIsGpOffer() : bool
      return ((string)gpOffer.Get()) != "" and ! IsGlLock() and IsOffersRequestsEnabled() and ! $uiPartyMonitor.IsMatchCountdown()
   end
   
   func IsOffersRequestsEnabled() : bool
      var ret : bool = false
      ret := (int)$UiGlobals.backend_requests.apply_offer.progress.state.Get() == $uiEnums.BACKEND_REQUEST_STATE_NONE
      return ret
   end
   
   func GetGpCost() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = "carousel_offer_na_small"
      if (offerVal != null)
         if ((int)offerVal.gl_cost.Get() > 0)
            ret := (string)offerVal.gl_cost.Get()
         end
      end
      return ret
   end
   
   func GetGpOldCost() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = "carousel_offer_na_small"
      if (offerVal != null)
         if ((float)offerVal.gl_sale_percentage.Get() < 1)
            ret := (string)(int)((int)offerVal.gl_cost.Get() / (1 - (float)offerVal.gl_sale_percentage.Get()))
         else
            ret := "0"
         end
      end
      Fire("UpdateCrossOutLines")
      return ret
   end
   
   func GetGpDiscount() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = ""
      if (offerVal != null)
         if ((int)offerVal.gl_cost.Get() > 0 and (float)offerVal.gl_sale_percentage.Get() > 0)
            ret := "-" + (string)(int)((float)offerVal.gl_sale_percentage.Get() * 100) + "%"
         end
      end
      return ret
   end
   
   func GetGpAlpha() : float
      var ret : float = 100
      if (GetGpOffer() == "")
         ret := 40
      end
      return ret
   end
   
   func GetCrAlpha() : float
      var ret : float = 100
      if (GetCrOffer() == "")
         ret := 40
      end
      return ret
   end
   
   func GetGpOffer() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = ""
      if (offerVal != null)
         if ((int)offerVal.gl_cost.Get() > 0)
            ret := (string)offerVal.gl_offer.Get()
         end
      end
      return ret
   end
   
   func GetIsCrOffer() : bool
      return ((string)crOffer.Get()) != "" and ! IsCrLock() and IsOffersRequestsEnabled() and ! $uiPartyMonitor.IsMatchCountdown()
   end
   
   func GetCrCost() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = "carousel_offer_na_small"
      if (offerVal != null)
         if ((int)offerVal.cr_cost.Get() > 0)
            ret := (string)offerVal.cr_cost.Get()
         end
      end
      return ret
   end
   
   func GetCrOldCost() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = "carousel_offer_na_small"
      if (offerVal != null)
         if ((float)offerVal.cr_sale_percentage.Get() < 1)
            ret := (string)(int)((int)offerVal.cr_cost.Get() / (1 - (float)offerVal.cr_sale_percentage.Get()))
         else
            ret := "0"
         end
      end
      Fire("UpdateCrossOutLines")
      return ret
   end
   
   func GetCrDiscount() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = ""
      if (offerVal != null)
         if ((int)offerVal.cr_cost.Get() > 0 and (float)offerVal.cr_sale_percentage.Get() > 0)
            ret := "-" + (string)(int)((float)offerVal.cr_sale_percentage.Get() * 100) + "%"
         end
      end
      return ret
   end

   func GetCrCostInt() : int
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : int                   = 0
      if (offerVal != null)
         ret := (int)offerVal.cr_cost.Get()
      end
      return ret
   end
   
   func GetGpCostInt() : int
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : int                   = 0
      if (offerVal != null)
         ret := (int)offerVal.gl_cost.Get()
      end
      return ret
   end
   
   func GetDurationTxt() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = ""
      if (offerVal != null)
         var durationParm : params = offerVal.DurationToStrings()
         ret := durationParm.daysCount
      end
      return ret
   end

   func GetDurationLabel() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = ""
      if (offerVal != null)
         var durationParm : params = offerVal.DurationToStrings()
         ret := durationParm.daysLabel
      end
      return ret
   end

   func GetCrOffer() : string
      var offerVal   : GL_ComponentShopOffer = (GL_ComponentShopOffer)offer.Get()
      var ret        : string                = ""
      if (offerVal != null)
         if ((int)offerVal.cr_cost.Get() > 0)
            ret := (string)offerVal.cr_offer.Get()         
         end
      end
      return ret
   end
end

class OffersModuleVM
   var parentVM            : ItemShopBaseVM = null
   
   var itemId              : ObservableProperty = $OM.Property("")
   var offersCount         : ObservableProperty = $OM.Calculated(this, "GetOffersCount")
   var canAssign           : ObservableProperty = $OM.Calculated(this, "GetCanAssign")
   var hasOffers           : ObservableProperty = $OM.Calculated(this, "GetHasOffers")
   var offers              : ObservableProperty = $OM.Calculated(this, "GetOffers")
   var headerY             : ObservableProperty = $OM.Calculated(this, "GetHeaderY")
   var headerText          : ObservableProperty = $OM.Calculated(this, "GetHeaderText")   
   var assignY             : ObservableProperty = $OM.Calculated(this, "GetAssignY")
   var assignAlpha         : ObservableProperty = $OM.Calculated(this, "GetAssignAlpha")
   var assignEnabled       : ObservableProperty = $OM.Calculated(this, "GetAssignEnabled")
   var assignText          : ObservableProperty = $OM.Calculated(this, "GetAssignText")
   var timeRemainY         : ObservableProperty = $OM.Calculated(this, "GetTimeRemainY")
   var timeRemainTxt       : ObservableProperty = $OM.Calculated(this, "GetTimeRemainTxt")
   var timeRemainVisible   : ObservableProperty = $OM.Calculated(this, "GetTimeRemainVisible")
   var timeRemainFrame     : ObservableProperty = $OM.Calculated(this, "GetTimeRemainFrame")
   var ownTypeInternal     : ObservableProperty = $OM.Calculated(this, "GetOwnTypeInternal")
   var lockStatus          : ObservableProperty = $OM.Calculated(this, "GetLockStatus")
   var isWide              : ObservableProperty = $OM.Property(false)
   var purchasedTxt        : ObservableProperty = $OM.Property("carousel_txt_purchased")
   var nonPurchasedTxt     : ObservableProperty = $OM.Property("carousel_txt_non_purchased")
   var addTimeTxt          : ObservableProperty = $OM.Property("carousel_txt_purchased_add_time")
   var rentTxt             : ObservableProperty = $OM.Property("carousel_txt_non_purchased_rent")
   var isSpartanArmory     : ObservableProperty = $OM.Property(false)
   var shopWidget          : UiWidget           = null
   var wgt                 : UiWidget           = null
   var offerLines          : vector
   var maxOffers           : int = 5
   var y0                  : float = 262.0
   //var offer0        : ObservableProperty = $OM.Property(null)   
   var isSubscribed        : bool               = false
      
      
   func SubscribeToUpdates()
      if (! isSubscribed)
         hasOffers.Subscribe(this, "UpdateOfferLinesSubsciption")
         offersCount.Subscribe(this, "UpdateOfferLinesSubsciption")
         isSubscribed := true         
      end
   end
   
   func UnsubscribeFromUpdates()
      if (isSubscribed)
         hasOffers.Unsubscribe(this, "UpdateOfferLinesSubsciption")
         offersCount.Unsubscribe(this, "UpdateOfferLinesSubsciption")
         isSubscribed := false
      end      
   end
   
   func Term()
      UnsubscribeFromUpdates()
   end
   
   func OnAssignBtnClicked(p : params) : bool
      if (((string)itemId.Get()) != "" and ((string)itemId.Get()) != "null")
         if lockStatus.Get() == "locked"
            //var compShop : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(itemId.Get())
            //$UiGlobals.techOpenTechId := (string)compShop.requirement.Get()
            //shopWidget.GenerateEvent("OpenTechTreeScreen")
         else
            UpdateItemId((string)itemId.Get())
            offersCount.Invalidate()
            Go2Loadout(0.0, (string)itemId.Get())
         end
      end
      return false
   end

   func AssignItem(_itemId :  string)
      //$user_service.SetLoadout(_itemId)
   end
   
   func AssignWeapon(_itemId :  string)
      $user_service.SetWeaponLoadoutWeapon($hf2pEngine.GetUIPlayerModelId(), (int)parentVM.selectedLoadoutIdx.Get(), _itemId)
   end
   
   func AssignArmor(_armorId :  string)
      var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(_armorId)
      
      $user_service.SetArmorLoadoutItem($hf2pEngine.GetUIPlayerModelId(), (int)parentVM.selectedArmorLoadoutIdx.Get(), _armorId)      
   end
   
   global event OnSpartanStoreOpen()
      isSpartanArmory.Set(true)
   end

   global event OnSpartanStoreClose()
      isSpartanArmory.Set(false)
   end

   func Go2LoadoutAfterPurchase(_itemId : string)
      Go2LoadoutAfterPurchaseDelayed(_itemId) : 0
   end
   
   func Go2LoadoutAfterPurchaseDelayed(_itemId : string)
      if (! $uiPartyMonitor.IsMatchCountdown())
         var pp         : params
         pp.mbType            := $uiEnums.MB_TYPE_NO_YES
         pp.titleTxt          := "msg_equip_item_header"
         pp.messageTxt        := "msg_equip_item_text"
         pp.callbackEvent     := "OnEquipItemConfirmed"
         pp.itemID            := _itemId
         $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", pp)            
      end
   end
   
   func GetItemIdVal() : string
      return (string)itemId.Get()
   end
      
   func Go2Loadout(_delay: float = 0.0, _itemId : string)
      var p : params
      p.ItemID := _itemId
      p.isOK := true
      OnEquipItemConfirmed(p)
      /*
      var itemType : int = $uiEconomy.GetItemType(_itemId)
      if itemType == $uiEnums.ITEM_TYPE_WEAPON
         //AssignWeapon(_itemId)
         Go2LoadoutType("weapon", _itemId): _delay
      elif itemType == $uiEnums.ITEM_TYPE_TACTICAL
         Go2LoadoutType("consumable", _itemId): _delay
      elif itemType == $uiEnums.ITEM_TYPE_ARMOR
         //AssignArmor(_itemId)
         Go2LoadoutType("armor", _itemId) : _delay
      elif itemType == $uiEnums.ITEM_TYPE_ARMOR_SUIT
         Go2LoadoutType("armor_suit", _itemId) : _delay
      elif itemType == $uiEnums.ITEM_TYPE_UNKNOWN
         if parentVM.shopType == $uiEnums.SHOP_TYPE_TACTICAL
            Go2LoadoutType("booster", _itemId): _delay
         elif parentVM.shopType == $uiEnums.SHOP_TYPE_WEAPON
            //AssignItem(_itemId)
            Go2LoadoutType("weapon", _itemId): _delay
         end
      end
      */
   end

   func OnEquipItemConfirmed(p : params) : bool
      if p.isOK
         var slot = (int)parentVM.parentVM.loadoutSelectedSlotIndex.Get()
         if $UiGlobals.PassesAsTacticalPackageFilter(p.ItemID)
            if slot >= 4 and slot <= 7
               $user_service.EquipCharacterWithSlot(p.ItemID, slot - 4)
            end
         else
            if !(slot >= 4 and slot <= 7)
               $user_service.EquipCharacter(p.ItemID)
               if $UiGlobals.PassesAsArmorFilter(p.ItemID)
                  $hq.RenderLocalLoadouts()
               end
            end
         end
      end
      return true
   end

   func Go2LoadoutType(_loadoutType: string, _itemId : string)
      if (_loadoutType == "weapon")
         Go2WeaponLoadout(_itemId)
      else if (_loadoutType == "consumable")
         Go2TacticalLoadout(_itemId)
      else if (_loadoutType == "booster")
         Go2BoosterLoadout(_itemId)
      else if (_loadoutType == "armor")
         Go2ArmoryLoadout(_itemId)
      else if (_loadoutType == "armor_suit")
         Go2WeaponLoadout(_itemId)
      end
   end

   func Go2WeaponLoadout(_itemId : string)
      var p       : params
      p.itemId       := _itemId
      p.minSlotIdx   := 0
      p.maxSlotIdx   := 3
      p.closeEvent   := "openWeaponConfig"
      $sslWidgetMgr.GenerateEvent("openLoadoutAssignWpnConf", p)
   end

   func Go2TacticalLoadout(_itemId : string)
      var p:params
      p.itemId       := _itemId
      p.minSlotIdx   := 4
      p.maxSlotIdx   := 8
      p.closeEvent   := "openTacticalPackages"
      $sslWidgetMgr.GenerateEvent("openLoadoutAssignPerks", p)
   end

   func Go2BoosterLoadout(_itemId : string)
      var p:params
      p.itemId       := _itemId
      p.minSlotIdx   := 8
      p.maxSlotIdx   := 8
      p.closeEvent   := "openTacticalPackages"
      $sslWidgetMgr.GenerateEvent("openLoadoutAssignBooster", p)
   end

   func Go2ArmoryLoadout(_itemId : string)
      Log("ui~wc_weaponContBig", "Go2ArmoryLoadout (itemID) -> ( " + _itemId + " )")
      var p:params
      p.itemId   := _itemId       
      p.armorType := "item"
      
      $sslWidgetMgr.GenerateEvent("openArmorLoadoutAssgin", p)
   end
   
   func OffersModuleVM()
      var i : int
      for i := 0 to maxOffers - 1
         var offerLine : OffersLineVM = new OffersLineVM()
         offerLine.offerIdx.Set(i)
         offerLines.Push(offerLine)
      end
   end
   
   func UpdateOfferLinesSubsciption()
      UpdateOfferLines()
   end
   
   func UpdateOfferLines()
      var i             : int
      var totalOffers   : int    = (int)offersCount.Get()
      for i := 0 to maxOffers - 1
         var offerLine : OffersLineVM = offerLines.Get(i)
                  
         var y : float = y0 - 47.0 * (i + 1)
         offerLine.yPos.Set(y)                  
         offerLine.itemId.Set(itemId.Get())
         offerLine.shopWidget := shopWidget
         
         if (i < totalOffers)
            offerLine.isVisible.Set(true)
         else
            offerLine.isVisible.Set(false)
         end         
         offerLine.isWide.Set((bool)isWide.Get())
      end
   end
      
   func UpdateItemId(_itemId : string)
      itemId.Set(_itemId)
      UpdateOfferLines()
      UnsubscribeFromUpdates()
      SubscribeToUpdates()
   end
   
   func GetOffersCount() : int
      var ret : int
      ret := GetOffers().Count()
      if (GetOwnType() == $uiEnums.ITEM_OWN_TYPE_PURCHASED)
         ret := 0
      end
      return ret
   end
   
   func GetCanAssign() : bool
      var ret : bool
      
      ret := GetOwnType() != $uiEnums.ITEM_OWN_TYPE_NONE and ! $uiPartyMonitor.IsMatchCountdown()            
      
      return ret
   end

   func GetHasOffers() : bool
      var ret : bool
      if (GetOwnType() != $uiEnums.ITEM_OWN_TYPE_PURCHASED and GetOffers().Count() > 0)
         ret := true
      end
      return ret 
   end
   
   func CompareOffers(a : GL_ComponentShopOffer, b : GL_ComponentShopOffer) : int
      var da   : int = (int)a.rent_duration.Get()
      var db   : int = (int)b.rent_duration.Get()
      var ret  : int = 0
      if (da > db)
         ret := -1
      elif (da < db)
         ret := 1
      end
      return ret
   end 
   
   func GetOffers() : vector
      var ret        : vector
      var shopComp   : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)itemId.Get())
      var ownType    : int = GetOwnType()
      if (shopComp.offers.Get().Count() > 0)
         ret := shopComp.offers.Get()
         ret.Sort(this, "CompareOffers")
      end
      return ret
   end
   
   func GetOwnTypeInternal() : int
      var ret        : int = 0
      var shopComp   : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)itemId.Get())
      if (shopComp.bundled_items.Get().Count() > 0)         
         ret := $uiEnums.ITEM_OWN_TYPE_PURCHASED
         var i : int
         for i := 0 to shopComp.bundled_items.Get().Count() - 1
            var item : GL_ComponentShopBundledItem = (GL_ComponentShopBundledItem)shopComp.bundled_items.Get().Get(i)
            var inventItem : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)item.item_id.Get())
            var itemStatus : int = (int)inventItem.ownership_type.Get()
            if (itemStatus == $uiEnums.ITEM_OWN_TYPE_NONE)
               ret := $uiEnums.ITEM_OWN_TYPE_NONE
            elif (itemStatus == $uiEnums.ITEM_OWN_TYPE_RENTED)            
               ret := $uiEnums.ITEM_OWN_TYPE_RENTED
            end
         end         
      else
         var inventItem : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)itemId.Get())      
         ret := (int)inventItem.ownership_type.Get()
      end
      
      return ret
   end
   
   func GetLockStatus() : string
      var ret : string = "none"
      var compShop : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(itemId.Get())
      if compShop.requirement.Get() != ""
         var compInventory : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(compShop.requirement.Get())
         if compInventory.ownership_type.Get() == $uiEnums.ITEM_OWN_TYPE_PURCHASED
            ret := "unlocked"
         else
            ret := "locked"
         end
      end
      return ret
   end
   
   func GetOwnType() : int
      var ret : int = (int)ownTypeInternal.Get()
      return ret
   end
   
   func GetHeaderY() : float
      var ret              : float = 0
      var offersCountVal   : int = (int)offersCount.Get()
      ret := y0 - 47.0 * offersCountVal - 45
      return ret      
   end

   func GetHeaderText() : string
      var ret : string
      if (GetOwnType() == $uiEnums.ITEM_OWN_TYPE_NONE)
         if ($uiEconomy.IsItemPurchasable(GetItemIdVal()))
            ret := (string)nonPurchasedTxt.Get()
         else
            ret := (string)rentTxt.Get()
         end
      else
         var ci : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(itemId.Get())
         var es : int = (int)ci.equipped_state.Get()
         if es == 2 and isSpartanArmory.Get() == true
            ret := "carousel_txt_assigned"
         else
            if ($uiEconomy.IsItemPurchasable(GetItemIdVal()))
               ret := (string)purchasedTxt.Get()
            else
               ret := (string)addTimeTxt.Get()
            end
         end
      end
      return ret
   end
      
   func GetAssignY() : float
      var ret : float = 0
      ret := y0
      return ret      
   end
   
   func GetTimeRemainY() : float
      return (float)headerY.Get() - 23
   end

   func GetTimeRemainTxt() : wstring
      var ret : wstring
      if ((bool)timeRemainVisible.Get())
         ret := $root.MakeUiTimerSubHead(GetRentTime())
      end
      return ret      
   end
   
   func GetRentTime() : int
      var ret     : int
      if ((bool)timeRemainVisible.Get())
         var uiInventoryItem : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(itemId.Get())
         var ownTime : int = (int)uiInventoryItem.ownership_time.Get() - (int)$UiGlobals.timer.Get()
         ret := ownTime
      end
      return ret   
   end   
   
   func GetTimeRemainFrame() : string
      var ret        : string = "green"
      var timeLeft   : int    = GetRentTime()
      if (timeLeft <= 0 or timeLeft < $uiEnums.ITEM_RENT_ALERT_SECONDS)
         ret := "red"
      end
      return ret   
   end   
   
   func GetTimeRemainVisible() : bool
      var ret : bool = false
      if ($uiEconomy.GetItemOwnType((string)itemId.Get()) == $uiEnums.ITEM_OWN_TYPE_RENTED)
         ret := true
      end
      return ret
   end
   
   func GetAssignAlpha() : float
      var ret : float = 0
      if (((bool)assignEnabled.Get()) == true)
         ret := 100.0
      else
         ret := 20.0
      end
      return ret      
   end

   func GetAssignText() : string
      var ret : string = "carousel_ui_btn_assign"
      var type : int = GetOwnType()
      
      if (type != $uiEnums.ITEM_OWN_TYPE_NONE)
         ret := "carousel_ui_btn_assign"
      elif ($uiEconomy.IsItemLocked((string)itemId.Get()))
         ret := "carousel_ui_btn_assign_locked"
         //ret := "carousel_goto_tech_tree"
      else 
         ret := "carousel_ui_btn_unavailable"
      end
      
      return ret      
   end
   
   func GetAssignEnabled() : bool
      var ret : bool = false
      if (bool)canAssign.Get() or lockStatus.Get() == "locked"
         ret := true
      else
         ret := false
      end
      return ret      
   end
   
   func Init(p : params)
      wgt := p.widget
   end
end


class ItemShopBaseVM : UiSlidingScreenMainMenuPageVM
   var shopType         : int                = $uiEnums.SHOP_TYPE_NONE
   var itemList         : ObservableProperty = $OM.Calculated(this, "GetItemList")
   var itemQuality      : ObservableProperty = $OM.Property(0)
   var selectedIdx      : ObservableProperty = $OM.Property(0)
   var mouseOverIdx     : ObservableProperty = $OM.Property(0)
   var itemCat          : ObservableProperty = $OM.Property(0)   
   var catCount         : ObservableProperty = $OM.Calculated(this, "GetCatCount")
   var selectedItemId   : ObservableProperty = $OM.Calculated(this, "GetSelectedItemId")
   var mouseOverItemId  : ObservableProperty = $OM.Calculated(this, "GetMouseOverItemId")
   var selectedItem     : ObservableProperty = $OM.Calculated(this, "GetSelectedItem")
   var itemCategories   : ObservableProperty = $OM.Calculated(this, "GetItemCategories")
   var sections         : ObservableProperty = $OM.Calculated(this, "GetSections")   
   var descpanelVM      : ItemDescPanelVM    = new ItemDescPanelVM()
   var offersModuleVM   : OffersModuleVM     = new OffersModuleVM()
   var bigIconPic       : ObservableProperty = $OM.Calculated(this, "GetBigIconPic")
   var bigIconVideo     : ObservableProperty = $OM.Calculated(this, "GetBigIconVideo")
   var isVideoIcons     : ObservableProperty = $OM.Calculated(this, "GetIsVideoIcons")
   var isVideoVisible   : ObservableProperty = $OM.Property(false)
   var isRentTimer      : ObservableProperty = $OM.Property(false)
   var wgt              : UiWidget           = null
   var rentTimeLeft     : ObservableProperty = $OM.Calculated(this, "GetRentTimeLeft")
   var rentTimeLeftClr  : ObservableProperty = $OM.Calculated(this, "GetRentTimeLeftClr")
   var itemName         : ObservableProperty = $OM.Calculated(this, "GetItemName")
   var selectedLoadoutIdx      : ObservableProperty = $OM.Calculated(this, "GetSelectedWeaponLoadoutIdx")
   var selectedArmorLoadoutIdx : ObservableProperty = $OM.Calculated(this, "GetSelectedArmorLoadoutIdx")
   

   override InitOverride //(p : params)
      wgt                        := p.widget
      offersModuleVM.shopWidget  := wgt
      mouseOverItemId.Subscribe(this, "MouseOverItemIdChanged")
   end
   
   override TermOverride // ()
      mouseOverItemId.Unsubscribe(this, "MouseOverItemIdChanged")
   end
   
   func MouseOverItemIdChanged(itemId : string)
      var slotIndex : int = (int)parentVM.loadoutSelectedSlotIndex.Get()
      if $UiGlobals.PassesAsArmorFilter(itemId)
         parentVM.loadoutSelectedSlotIndex.Set(0)
      elif $UiGlobals.PassesAsPrimaryWeaponFilter(itemId)
         parentVM.loadoutSelectedSlotIndex.Set(1)
      elif $UiGlobals.PassesAsSecondaryWeaponFilter(itemId)
         parentVM.loadoutSelectedSlotIndex.Set(2)
      elif $UiGlobals.PassesAsGrenadeWeaponFilter(itemId)
         parentVM.loadoutSelectedSlotIndex.Set(3)
      elif $UiGlobals.PassesAsTacticalPackageFilter(itemId)
         if slotIndex < 4 or slotIndex > 7
            var newSlotIdx = 4
            var char : UD_Character = $UserDataStorage.GetLocalUserData().GetActiveCharacter()
            if char.tactical_package_first.Get() == ""
               newSlotIdx := 4
            elif char.tactical_package_second.Get() == ""
               newSlotIdx := 5
            elif char.tactical_package_third.Get() == ""
               newSlotIdx := 6
            elif char.tactical_package_fourth.Get() == ""
               newSlotIdx := 7
            end
            parentVM.loadoutSelectedSlotIndex.Set(newSlotIdx)
         end
      elif $UiGlobals.PassesAsSupportPackageFilter(itemId)
         parentVM.loadoutSelectedSlotIndex.Set(8)
      end
   end
   
   func inputEvent(p: params) : bool
      return false
   end
   
   func SaveState () : params
      var ret : params
      ret.itemQuality   := (int)itemQuality.Get()
      ret.itemCat       := (int)itemCat.Get()
      ret.selectedIdx   := (int)selectedIdx.Get()
      return ret
   end

   func LoadState (p : params) : bool
      if (!IsVoid(p.itemQuality))
         itemQuality.Set(p.itemQuality)
      end
      if (!IsVoid(p.itemCat))
         itemCat.Set(p.itemCat)
      end
      if (!IsVoid(p.selectedIdx))
         selectedIdx.Set(p.selectedIdx)
         SetListSelection(p.selectedIdx)
      end
      return true
   end

      
   func OpenBuyDialogue(p : params) : bool
      var itemId : string = p.itemId
      var offer : GL_ComponentShopOffer = p.offer
      var isGold : bool = p.isGold
      var playerCurrency = 0
      var offerString : string
      var offerCost : int
      if offer == null
         return true
      end
      if isGold
         playerCurrency := (int)$UserDataStorage.local_user.gold.Get()
         offerString := (string)offer.gl_offer.Get()
         offerCost := (int)offer.gl_cost.Get()
      else
         playerCurrency := (int)$UserDataStorage.local_user.cr.Get()
         offerString := (string)offer.cr_offer.Get()
         offerCost := (int)offer.cr_cost.Get()
      end
      if offerString != ""
         var par: params
         par.itemID        :=  itemId
         par.offer         := offerString
         par.priceAmount   := offerCost
         if isGold
            par.priceUnit  := $uiEnums.TOKEN_GOLD
         else
            par.priceUnit  := $uiEnums.TOKEN_CREDITS
         end
         if (offerCost <= playerCurrency)
            // is rent ?
            var ret : int = 0
            ret := (int)offer.rent_duration.Get()
            if (ret > 0)
               par.isRent := true
            end
            // end 
            par.mbType           := "ConfirmBuy"
            par.callbackEvent    := "OnItemPurchased"
            par.callbackTarget   := wgt.Props
         else
            par.mbType     := "Info"
            par.titleTxt   := "msg_ui_warning"
            if isGold
               par.messageTxt := "msg_ui_not_enough_gp"
            else
               par.messageTxt := "msg_ui_not_enough_cr"
            end
         end
         $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
      end
      return true
   end
   
   func ItemShopBaseVM()
      mouseOverItemId.Subscribe(this, "UpdateSelectedItem")   
      itemQuality.Subscribe(this, "itemQualityChanged")
      offersModuleVM.parentVM := this
      offersModuleVM.isWide.Subscribe(this, "OnIsWideChanged")
   end
   
   func BaseTerm()
      itemQuality.Unsubscribe(this, "itemQualityChanged")
      mouseOverItemId.Unsubscribe(this, "UpdateSelectedItem")
      offersModuleVM.isWide.Unsubscribe(this, "OnIsWideChanged")
      offersModuleVM.parentVM := null
      offersModuleVM.Term()
      $sslWidgetMgr.PrintStats()
      offersModuleVM := null
      $sslWidgetMgr.PrintStats()
   end
   
   func GetLoadoutsObservable() : ObservableProperty
      var ret : ObservableProperty = null
      return null
   end
            
   func OnIsWideChanged(_val : *)
      offersModuleVM.UpdateOfferLines()
   end
   
   func LoadoutSelectButtonClicked(p : params) : bool
      var loadoutIndex : int = (int)p.widget.Get("idx")
      if loadoutIndex != selectedLoadoutIdx.Get()
         $user_service.SetWeaponLoadoutActive(0, loadoutIndex)
         $UiBiLogger.LogWeaponLoadoutEvent("Select",loadoutIndex, "" , 0)
      end
      return true
   end
   
   func ArmorLoadoutSelectButtonClicked(p : params) : bool
      var loadoutIndex : int = (int)p.widget.Get("idx")
      if loadoutIndex != selectedArmorLoadoutIdx.Get()
         $user_service.SetArmorLoadoutActive(0, loadoutIndex)
         $UiBiLogger.LogArmorLoadoutEvent("Select",loadoutIndex, "")
      end
      return true
   end
      
   func GetSelectedWeaponLoadoutIdx() : *
      var ud : UserData = (UserData) $UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
      var loadoutIndex :  int = (int)ud.weapon_loadouts.spartan.active_loadout_index.Get()
      return loadoutIndex
   end
   
   func GetSelectedArmorLoadoutIdx() : *
      var ud : UserData = (UserData) $UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
      var loadoutIndex :  int = (int)ud.armor_loadouts.spartan.active_loadout_index.Get()
      return loadoutIndex
   end
      
   func itemQualityChanged(newVal : *)
      var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
      var subshop : GL_ShopSection = (GL_ShopSection)shop.weapons.Get().Get((int)newVal)
      var uiID    : string = (string)subshop.section_id.Get()
      $UiGlobals.AssigningItemCategory := uiID
   end
   
   func GetRentTime() : int
      var ret     : int
      var itemId  : string = (string)mouseOverItemId.Get()
      if ($uiEconomy.GetItemOwnType(itemId) == $uiEnums.ITEM_OWN_TYPE_RENTED)
         var uiInventoryItem : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(itemId)
         var ownTime : int = (int)uiInventoryItem.ownership_time.Get() - (int)$UiGlobals.timer.Get()
         ret := ownTime
      end
      return ret   
   end   
   
   func SetListSelection(_idx : int)
      if (wgt != null)
         var p : params
         p.idx := _idx
         wgt.GenerateEvent("SetListSelection", p)
      end
   end
   
   func GetRentTimeLeftClr() : int
      return $uiEconomy.GetItemRentTintColor((string)mouseOverItemId.Get())
   end   
   
   func GetItemName() : string
      var ret     : string
      if ((bool)isRentTimer.Get())
         var itemId  : string = (string)mouseOverItemId.Get()
         if ($uiEconomy.GetItemOwnType(itemId) == $uiEnums.ITEM_OWN_TYPE_RENTED)
            ret := "carousel_rent_time_left"
         end
      end
      return ret
   end
   
   func GetRentTimeLeft() : wstring
      var ret     : wstring
      if ((bool)isRentTimer.Get())
         var itemId  : string = (string)mouseOverItemId.Get()
         if ($uiEconomy.GetItemOwnType(itemId) == $uiEnums.ITEM_OWN_TYPE_RENTED)
            //ret := $root.MakeUiTimerStringMinutes(GetRentTime(), true)
            ret := $root.MakeUiTimerSubHead(GetRentTime())
         end
      end
      return ret
   end
   
   func CallRenderBigVideo(_video : string)
      var video : string = GetMouseOverItemId()
      if (wgt != null and wgt.GetStateName() == "Visible" and video != "" and video != "unknown")
         $hq.TextureRenderWeaponShopStart(video)
      end      
   end
   
   func GetBigIconPic() : string
      var ret        : string = ""
      var videoPic   : string = ""
      var uiComp     : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(mouseOverItemId.Get())
      if ((bool)isVideoIcons.Get())
         videoPic := (string)uiComp.video.Get()
         CallRenderBigVideo(videoPic)
         isVideoVisible.Set(true)
      else
         ret := (string)uiComp.icon_big.Get()
         isVideoVisible.Set(false)
      end
      return ret
   end
   
   override GetLoadoutsHighlightedItem // () : string
      return GetMouseOverItemId()
   end
   
   override GetLoadoutsFilterId // () : string
      return $uiEnums.INV_TYPE_WEAPON
   end
      
   func GetBigIconVideo() : string
      var ret        : string = ""
      var uiComp     : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(mouseOverItemId.Get())
      ret := (string)uiComp.video.Get()
      return ret
   end
   
   func GetIsVideoIcons() : bool
      return true
   end
   
   func GetCatCount() : *
      var ret : int = 0
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         if (! IsVoid(shop.weapons.Get()) and shop.weapons.Get().Count() > (int)itemQuality.Get())
            var subshop    :  GL_ShopSection = (GL_ShopSection)shop.weapons.Get().Get((int)(itemQuality.Get()))
            ret := subshop.shelves.Get().Count()
         end         
      end
      return ret
   end
            
   func UpdateSelectedItem(val : *)
      descpanelVM.itemId.Set(val)
      offersModuleVM.UpdateItemId((string)val)
   end
   
   func OnSubTabSelected(p:params):bool
      if (! IsVoid(p.itemCatIdx))
         itemCat.Set((int)p.itemCatIdx)
         selectedIdx.Set(0)
         UpdateSubTab()
         BiLogShopState()
      end
      return true
   end
   
   func DoBlink()
      if (wgt != null)
         wgt.GenerateEvent("BlinkItemList")
      end
   end

   func UpdateSubTab()
      DoBlink()
   end

   func OnPanelButtonClicked(p:params):bool
      return false
   end
   
   func wc_OnPanelButtonClicked(p:params):bool
      selectedIdx.Set(0)
      return OnPanelButtonClicked(p)
   end
   
   
   func wcSelectedItem(p:params):bool
      return false
   end
   
   
   func OnItemSlotSelect(p:params):bool
      mouseOverIdx.Set((int)p.idx)
      if (! p.isFocusOnly)
         selectedIdx.Set((int)p.idx)         
      end
      //UpdateSelectedItem()      
      return true
   end
   
   func OnItemSlotMouseOut(p:params):bool
      mouseOverIdx.Set((int)selectedIdx.Get())
      //UpdateSelectedItem()
      return true
   end
         
   func GetSelectedItem() : GL_String
      var selectedIdxInt   : int = (int)selectedIdx.Get()
      var itemsList        : vector = GetItemList()
      if (selectedIdxInt >= 0 and selectedIdxInt < itemsList.Count())
         return itemsList.Get(selectedIdxInt)
      end
      return null
   end
   
   func GetMaxSections() : int
      return 5
   end
   
   func GetSections() : vector
      var sections   : vector
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         var i          : int
         for i := 0 to shop.weapons.Get().Count() - 1
            var subshop : GL_ShopSection = (GL_ShopSection)shop.weapons.Get().Get(i)
            var uiID    : string = (string)subshop.section_id.Get()
            var name    : string  = (string)((GL_ComponentUI)$UiGlobals.componentsUI.Get(uiID)).name.Get()
            if (name == "")
               name := uiID
            end
            var sectionDesc : params
            sectionDesc.label    := name
            sectionDesc.is_hot   := false
            sectionDesc.has_new  := subshop.HasNewItems()
            sections.Push(sectionDesc.Clone())
         end
      end
      while (sections.Count() < GetMaxSections())
         var sectionDesc : params
         sectionDesc.label    := ""
         sectionDesc.is_hot   := false
         sectionDesc.has_new  := false
         sections.Push(sectionDesc.Clone())
      end
      return sections
   end
   
   func GetItemCategories() : vector
      var itemCatList   : vector
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop          :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         if (! IsVoid(shop.weapons.Get()) and shop.weapons.Get().Count() > (int)itemQuality.Get())
            var subshop       :  GL_ShopSection = (GL_ShopSection)shop.weapons.Get().Get((int)(itemQuality.Get()))              
            var i             : int
            
            for i := 0 to subshop.shelves.Get().Count() - 1
               var shelf         : GL_ShopShelf    = (GL_ShopShelf)subshop.shelves.Get().Get(i) 
               var listElem      : params
               listElem.name     := (string)((GL_ComponentUI)$UiGlobals.componentsUI.Get(shelf.shelf_id.Get())).name.Get()
               listElem.id       := (string)shelf.shelf_id.Get()
               listElem.has_new  := shelf.HasNewItems()
               itemCatList.Push(listElem)
            end
         end
      end
      return itemCatList      
   end
   
   func CompareShopItems(itemA : GL_String, itemB : GL_String) : int
      var itemIdA    : string             = (string)itemA.value.Get()
      var itemIdB    : string             = (string)itemB.value.Get()
      var shopCompA  : GL_ComponentShop   = (GL_ComponentShop)$UiGlobals.componentsShop.Get(itemIdA)
      var shopCompB  : GL_ComponentShop   = (GL_ComponentShop)$UiGlobals.componentsShop.Get(itemIdB)
      var availA     : int                = (int)shopCompA.availability.Get()
      var availB     : int                = (int)shopCompB.availability.Get()
      var ret        : int                = 0      
      
      if (availA > availB)
         ret := 1
      elif (availA < availB)
         ret := -1
      end
      
      return ret      
   end
   
   func SortShopItems(items : vector) : vector
      var ret : vector = items
      ret.Sort(this, "CompareShopItems")
      return ret
   end
         
   func GetItemList() : vector
      var ret : vector = new vector
      if isActive.Get() == true
         if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
            var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
            if (! IsVoid(shop.weapons.Get()) and shop.weapons.Get().Count() > (int)itemQuality.Get())
               var subshop    :  GL_ShopSection = (GL_ShopSection)shop.weapons.Get().Get((int)(itemQuality.Get()))
               if (! IsVoid(subshop.shelves.Get()) and subshop.shelves.Get().Count() > (int)itemCat.Get())
                  var shelf      :  GL_ShopShelf   = (GL_ShopShelf)subshop.shelves.Get().Get((int)(itemCat.Get()))
                  if (! IsVoid(shelf.items.Get()))
                     ret := SortShopItems(shelf.items.Get())
                  end
               end
            end         
         end
      end
      return ret
   end      
   
   func GetSelectedItemId() : string
      var item :  string      
      var items : vector = itemList.Get()
      
      var idx : int = (int)selectedIdx.Get()
      if (idx >= 0 and idx < items.Count())  
         var glitem :  GL_String = (GL_String)items.Get(idx)
         item := (string)glitem.value.Get()
      end
      
      return item
   end

   func GetMouseOverItemId() : string
      var item :  string      
      var items : vector = itemList.Get()
      
      var idx : int = (int)mouseOverIdx.Get()
      if (idx >= 0 and idx < items.Count())  
         var glitem :  GL_String = (GL_String)items.Get(idx)
         item := (string)glitem.value.Get()
      end
            
      return item
   end   
   
   func HideShop(p : params) : bool
      isActive.Set(false)
      BiLogShopState("Hidden")
      return true
   end
   
   func CloseShop(p : params) : bool
      BiLogShopState("Initial")
      return true
   end
   
   func GetBiShopName() : string
      return $uiEnums.UI_BI_SHOP_WEAPON
   end
   
   func BiLogShopState(shopState : string = "Visible")
      if (shopState == "Visible")
         $UiBiLogger.LogGlobalStateChange($uiEnums.UI_BI_SHOP)
      end
      $UiBiLogger.LogShopState(GetBiShopName(), shopState, GetCurrentSectionId(), GetCurrentSubSectionId())      
   end
   
   func GetCurrentSectionId() : string
      var ret           : string = "undefined"
      var sectionIdx    : int    = (int)itemQuality.Get()
      var sectionsVec   : vector = sections.Get()
      if (sectionIdx >= 0 and sectionIdx < sectionsVec.Count())
         var rec : params = sectionsVec.Get(sectionIdx)
         ret := rec.label
      end
      return ret
   end
   
   func GetCurrentSubSectionId() : string
      var ret           : string = "undefined"
      var categoriesIdx : int    = (int)itemCat.Get()
      var categoriesVec : vector = itemCategories.Get()      
      if (categoriesIdx >= 0 and categoriesIdx < categoriesVec.Count())
         var rec : params = categoriesVec.Get(categoriesIdx)
         ret := rec.id
      end
      return ret
   end
   
   override LoadoutPanelSlotClicked // (p : params) : bool
      $root.GotoShopItem(p.itemId, p.itemType, p.itemSubType)
      return true
   end
end

class WeaponConfVM : ItemShopBaseVM
   var isItemInspectionMode   : ObservableProperty = $OM.Property(false)
   var isItemInspectionToggle : ObservableProperty = $OM.Property(false)
   var contentAlpha           : ObservableProperty = $OM.Property(100.0)
   var descModelState         : ObservableProperty = $OM.Property("Initial")
   var itemStats              : UiItemStatsVM      = new UiItemStatsVM()
   //
   func WeaponConfVM()
      shopType := $uiEnums.SHOP_TYPE_WEAPON
      isVideoIcons.Set(true)
      isRentTimer.Set(true)
   end   
   
   override GetLoadoutsObservable //() : ObservableProperty
      var udLocal : UserDataLocal = $UserDataStorage.local_user
      return udLocal.weapon_loadouts_unlocked
   end
      
   override OnPanelButtonClicked
      Log("ui~content", "wc_OnPanelButtonClicked: " + Params2Str(p))
      if (! IsVoid(p.widget.itemType) and ! p.widget.selected)
         var itemType :  int = p.widget.itemType
         if (itemType >= 0)
            itemCat.Set(0)
            itemQuality.Set(itemType)
            BiLogShopState()
         end
      end
      UpdateSelectedItem(mouseOverItemId.Get())
      DoBlink()
      return false
   end
   
   func ContentFade(isFadeIn : bool, isInstant : bool)
      var animName : string
      if (isFadeIn)
         if (isInstant)
            animName := "fadeOut"
         else
            animName := "fadeIn"
         end
      else
         if (isInstant)
            animName := "initial"
         else
            animName := "fadeOut"
         end
      end      
      if (isInstant)
         wgt.GotoAndStop(animName)
      else
         wgt.GotoAndPlay(animName)
      end
      ((UiWeaponConfScreen)wgt).OnToggleInspection()
   end
      
   func OnToggleInspectionMode(p : params) : bool
      if ((bool)isItemInspectionToggle.Get() == false)
         isItemInspectionToggle.Set(true)
         if ((bool)isItemInspectionMode.Get())
            isItemInspectionMode.Set(false)
            descModelState.Set("Collapsed")
            ContentFade(true, false)
         else
            descModelState.Set("Full")
            ContentFade(false, false)
         end
      end
      return true
   end
   
   override inputEvent//(p: params) : bool
      var ret : bool = true
      
      if ((bool)isItemInspectionMode.Get())
         var code          : int    = p.keyCode
         var isTerminated  : bool   = false
         if (code == $uiKeys.VK_ESC)
            isTerminated := true
            OnToggleInspectionMode(null)
         end
                  
         if (isTerminated)
            p.eventState.SetIsTerminated(true)
            ret := false
         end
      end
      
      return ret
   end

   
   func ShopDescModelOpened(p : params) : bool
      isItemInspectionMode.Set(true)
      isItemInspectionToggle.Set(false)
      return true
   end
   
   func ShopDescModelCollapsed(p : params) : bool
      isItemInspectionToggle.Set(false)
      return true
   end
   
   func StartWeaponUniversalDrag(p : params) : bool
      wgt.GenerateEvent("StartUniversalDrag", p)
      return true
   end

   override TermOverride //(p : params)
      //mouseOverItemId.Unsubscribe(descpanelVM, "UpdateItemId")
      BaseTerm()
   end
         
   func OpenedWeaponConfig(p : params) : bool
      isActive.Set(true)
      sections.Invalidate()
      itemCategories.Invalidate()
      itemQuality.OnChanged()
      itemList.Invalidate()   
      offersModuleVM.isWide.Set(true)
      catCount.Invalidate()
      if ($UiGlobals.shop.openParams.isValid)         
         $UiGlobals.shop.openParams.isValid := false
         itemQuality.Set($UiGlobals.shop.openParams.sectionIdx)
         itemCat.Set($UiGlobals.shop.openParams.shelfIdx)
         selectedIdx.Set($UiGlobals.shop.openParams.itemIdx)
         SetListSelection($UiGlobals.shop.openParams.itemIdx)
      else
         itemCat.Set(0)
         itemQuality.Set(0)
         SetListSelection(0)
      end
      BiLogShopState()
      ContentFade(true, true)
      isItemInspectionToggle.Set(false)
      isItemInspectionMode.Set(false)
      descModelState.Set("Initial")
      return true
   end
         
   override UpdateSelectedItem
      descpanelVM.itemId.Set(mouseOverItemId.Get())
      offersModuleVM.UpdateItemId((string)mouseOverItemId.Get())
      itemStats.itemId.Set(mouseOverItemId.Get())
      itemStats.compareItemId.Set($uiPlayerInfo.GetDefaultComparisonItem((string)mouseOverItemId.Get()))
   end   
   
   func OnWeaponPurchased(p : params) : bool
      offersModuleVM.Go2LoadoutAfterPurchase(p.itemID)
      return true
   end  
   
   func OnGotoInventoryBtnClicked(p : params) : bool
      $root.GotoInventoryItem(GetMouseOverItemId(), $uiEnums.ITEM_TYPE_WEAPON)
      return true
   end
end

class CrossOutLineHelper : UiWidget
   global event UpdateCrossOutLines()
      var textWidth : float = (float)Get("tfOldPriceWidth")
      GetWidget("lineOldPrice").Set("_width", textWidth + 5)
   end
end


class WpBg : UiWidgetContainer

override StartDrag   
   var pp: params
   pp.dragEvent   := "WeaponScreenDrag"
   pp.dragTarget  :=  this
   GenerateEvent("#StartWeaponUniversalDrag", pp)
   return null
end

func OnWeaponScreenDrag(p: params): bool
   if p.updateType == "start"
      $hf2pEngine.OnWeaponScreenDragStart($uiEnums.UI_RTTS_WEAPONS_SHOP)
   else if p.updateType == "update"
      $hf2pEngine.OnWeaponScreenDragUpdate($uiEnums.UI_RTTS_WEAPONS_SHOP, p.mouseOffset.x, p.mouseOffset.y)
   else if p.updateType == "end"
      $hf2pEngine.OnWeaponScreenDragUpdate($uiEnums.UI_RTTS_WEAPONS_SHOP, p.mouseOffset.x, p.mouseOffset.y)
      $hf2pEngine.OnWeaponScreenDragEnd($uiEnums.UI_RTTS_WEAPONS_SHOP)
   end
   return false
end

func OnMouseDown(p: params): bool
   StartDragManual()   
   return false
end

end
