import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.engine_ctrl
import ssl.hf2p.items_mgr
import ui.ui_economy
import ui.ui_player_info
import ssl.hf2p.user_service
import ssl.hf2p.user_data
import ssl.hf2p.ui_ingame
import ssl.lib.ui.ui_widget_manager
import ssl.observables
import ssl.hf2p.ui_globals
import ui.root
import ui.libs.hf2p_MainMenu_lib.hf2p_MainMenu_lib

class UiArmorLoadout : UiWidgetContainer

var armor               : params
var curArmorLoadoutIdx  : int
var viewParts           : bool = true 
 
 
func InitFocus()
   SetFocus()
end

func OpenArmoryLoadoutScr(p:params):bool
   $UserDataStorage.InvalidateArmorLoadouts()
   SetStateName("SeeArmorLoadout")
   return false
end

func OpenArmoryLoadoutAssign(p:params):bool
   Log("ui~armorLoadout", "OpenArmoryLoadoutAssign " + Params2Str(p))
   armor := p
   SetStateName("AssignArmor2Loadout")
   return false
end

func CloseArmoryLoadout(p:params):bool
   Log("ui~armorLoadout", "CloseArmoryLoadout")
   GenerateEvent("closeArmoryLoadout")
   return false
end

func AcceptArmoryLoadout(p:params):bool
   Log("ui~armorLoadout", "AcceptArmoryLoadout")
   GenerateEvent("closeArmoryLoadout")
   return false
end

func OnViewStatsBtnClicked(p:params):bool
   viewParts := ! viewParts
   ShowPartsOrStats(viewParts)
   BlinkArmorSlots()
   return false
end   

func onArmorLoadoutOfferCrClicked(p : params) : bool
   var loadoutIdx   : int = p.widget.GetWidget("_parent").GetWidget("_parent").Props().idx
   var shop         : GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
   var shopSection  : GL_ShopSection = shop.FindInternalSection("section_loadouts")
   var shopShelf    : GL_ShopShelf = shopSection.FindShelf("shelf_armor_loadouts")
   var loadoutId    : string = (string)shopShelf.items.Get().Get(loadoutIdx).value.Get()
   var shopComp     : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(loadoutId)
   var loadoutOffer : GL_ComponentShopOffer = (GL_ComponentShopOffer)shopComp.offers.Get().Get(0)
   var offerId      : string = (string)loadoutOffer.cr_offer.Get()
   var offerCr      : int = (int)loadoutOffer.cr_cost.Get()
   if (offerId != "")
      var par: params
      par.itemID        := loadoutId
      par.offer         := offerId
      par.priceCredit   := offerCr
      if (offerCr <= (int)$UserDataStorage.local_user.cr.Get())
         par.mbType     := "ConfirmBuy"
         par.callbackEvent    := "ArmorLoadoutUpdate"
      else
         par.mbType     := "Info"
         par.titleTxt   := "msg_ui_warning"
         par.messageTxt := "msg_ui_not_enough_cr"
      end
      $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)         
   end
  return false
end

func onArmorLoadoutOfferGpClicked(p : params) : bool
   var loadoutIdx   : int = p.widget.GetWidget("_parent").GetWidget("_parent").Props().idx
   var shop         : GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
   var shopSection  : GL_ShopSection = shop.FindInternalSection("section_loadouts")
   var shopShelf    : GL_ShopShelf = shopSection.FindShelf("shelf_armor_loadouts")
   var loadoutId    : string = (string)shopShelf.items.Get().Get(loadoutIdx).value.Get()
   var shopComp     : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(loadoutId)
   var loadoutOffer : GL_ComponentShopOffer = (GL_ComponentShopOffer)shopComp.offers.Get().Get(0)
   var offerId      : string = (string)loadoutOffer.gl_offer.Get()
   var offerGl      : int = (int)loadoutOffer.gl_cost.Get()
   if (offerId != "")
      var par: params
      par.itemID        := loadoutId
      par.offer         := offerId
      par.priceGold     := offerGl
      if (offerGl <= (int)$UserDataStorage.local_user.gold.Get())
         par.mbType     := "ConfirmBuy"
         par.callbackEvent    := "ArmorLoadoutUpdate"
      else
         par.mbType     := "Info"
         par.titleTxt   := "msg_ui_warning"
         par.messageTxt := "msg_ui_not_enough_gp"
      end
      $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)         
   end
   return false
end

func ArmorLoadoutUpdate(p : params) : bool
   ShowPartsOrStats(viewParts)
   return true
end

func onArmoryLoadoutClicked(p: params): bool
   Log("ui~armorLoadout", "onArmoryLoadoutClicked " + p.widget.idx)
	curArmorLoadoutIdx := p.widget.idx
   Log("ui~armorLoadout", "!!! " + (string)(p.widget.GetName()) + " !!!")
   // check item
   if (GetStateName() == "AssignArmor2Loadout")
      VisualizeAndEquip(p.widget.idx)
      //ArmoryAssignMsgBox()   
      $user_service.SetArmorLoadoutActive(0, p.widget.idx)
   else 
      $user_service.SetArmorLoadoutActive(0, p.widget.idx)
      GenerateEvent("onArmoryLoadoutClicked2", p)
   end
   return false
end

func onArmorSlotClicked(p: params): bool 
   Log("ui~armorLoadout", "onArmorSlotClicked")
   return false
end

func VisualizeAndEquip(_armorLoadoutIdx: int)
   Log("ui~armorLoadout", "VisualizeAndEquip " + (string)(viewParts))
   var armorId    : string = armor.armorId
   var armorType  : string = armor.armorType
   // Equip
   var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(armorId)
   
   $uiPlayerInfo.AssignItem2Loadout(curArmorLoadoutIdx, armorId)
   
   // Visualize //
   ShowPartsOrStats(viewParts)   
end

func BlinkArmorSlots()
   $root.playSound("screen_rollout")
   var i : int
   var loadOutIdx : int
   for loadOutIdx := 0 to 4
      var armorLoadout : * = Widgets().alslots.GetWidget("armorLoadout" + (string)(loadOutIdx)).Props()   
      armorLoadout.StartDefaultBlinking(loadOutIdx * 0.1 , 1.3)
   end
   for i := 1 to 4
      Widgets().alslots.Get("armorOfferPanel" + i).StartDefaultBlinking(i * 0.1 , 1.3)
   end 
end

func OnArmoryAssignMsgBoxClosed(p: params): bool
   Log("ui~armorLoadout", "OnArmoryAssignMsgBoxClosed")
   return false         
end
   
func ArmoryAssignMsgBox()
   Log("ui~armorLoadout", "ArmoryAssignMsgBox")
   var   pp          : params
   pp.txtTrans       := false
   pp.isSkip         := true
   pp.itemID         := armor.armorId   
   pp.messageTxt     := GetItemName(armor.armorId)
   pp.callbackEvent  := "OnArmoryAssignMsgBoxClosed"
   pp.mbType         := "AssignInfo"
   pp.titleTxt       := "msg_ui_assigned"
   pp.closeTimeout   := 2 
   GenerateEvent("MainMenuDialogRequest", pp)   
end

//func ShowHideBars()
   //var i : int
   //var barCount : int
   //var ud : UserData = (UserData) $UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
   //var lidx :  int = (int)ud.armor_loadouts.spartan.active_loadout_index.Get()
   //var armorloadout :  UD_ArmorLoadout = (UD_ArmorLoadout)ud.armor_loadouts.spartan.loadouts.Get().Get(lidx)
   //barCount := (int)armorloadout.bonuses_sorted_count.Get()
   //for i := 1 to barCount 
   //   Widgets().alslots.armorLoadout0.btnBox.armoryModuleCont.Get("statBar" + i).visible := true
   //end   
//end

func ShowPartsOrStats(_showParts:bool)
   Log("ui~armorLoadout", "ShowPartsOrStats")
   var loadOutIdx : int
   for loadOutIdx := 0 to 4
      var idx:int 
      var armorLoadout : * = Widgets().alslots.GetWidget("armorLoadout" + (string)(loadOutIdx)).Props()
      for idx := 1 to 5
         if (_showParts)
            //armorLoadout.btnBox.armoryModuleCont.Get("armorBtn" + idx).visible := true
            //armorLoadout.btnBox.armoryModuleCont.Get("statBar" + idx).alpha := 0
            //armorLoadout.subTxt := "carousel_suit_parts"
         else
            //armorLoadout.subTxt := "carousel_suit_power"
            //armorLoadout.btnBox.armoryModuleCont.Get("armorBtn" + idx).visible := false
            //armorLoadout.btnBox.armoryModuleCont.Get("statBar" + idx).alpha := 100
         end
      end
      if (_showParts)
         UpdateParts(loadOutIdx)
      else
         //ShowHideBars()
         //UpdateStats(loadOutIdx)
      end
   end
   if (_showParts)
      Widgets().viewStatsBtn.Set("label", "carousel_armor_stats")
      Get("DC2").IsStatsVisible.Set(false)
   else
      Widgets().viewStatsBtn.Set("label", "carousel_armor_parts")
      Get("DC2").IsStatsVisible.Set(true)
   end
   EnableFakeBg()
end

func CamView()
end

func UpdateParts(_loadoutIdx : int)
   Log("ui~armorLoadout", "UpdateParts")
   SetArmorPartsIconAndName(_loadoutIdx)
end

func UpdateStats(_loadoutIdx : int)
   Log("ui~armorLoadout", "UpdateStats")
   var armorLoadoutWidget : * = Widgets().alslots.GetWidget("armorLoadout" + (string)(_loadoutIdx)).Props()
   var loadout : UD_ArmorLoadout = $uiPlayerInfo.GetBackendLoadout(_loadoutIdx)
      
   //armorLoadoutWidget.btnBox.armoryModuleCont.statBar1.SetItem(loadout.head_armor.Get())
   //armorLoadoutWidget.btnBox.armoryModuleCont.statBar2.SetItem(loadout.shoulders_armor.Get())
   //armorLoadoutWidget.btnBox.armoryModuleCont.statBar3.SetItem(loadout.torso_armor.Get())
   //armorLoadoutWidget.btnBox.armoryModuleCont.statBar4.SetItem(loadout.hands_armor.Get())
   //armorLoadoutWidget.btnBox.armoryModuleCont.statBar5.SetItem(loadout.legs_armor.Get())
end

func SetArmorPartsIconAndName(_loadoutIdx : int)
   Log("ui~armorLoadout", "SetArmorPartsIconAndName")   
   var armorLoadoutWidget : * = Widgets().alslots.GetWidget("armorLoadout" + (string)(_loadoutIdx)).Props()
   //armorLoadoutWidget.btnBox.armoryModuleCont.armorBtn1.imageAttach.pic := "iconHelmet"
   //armorLoadoutWidget.btnBox.armoryModuleCont.armorBtn2.imageAttach.pic := "iconShoulder"
   //armorLoadoutWidget.btnBox.armoryModuleCont.armorBtn3.imageAttach.pic := "iconChest"
   //armorLoadoutWidget.btnBox.armoryModuleCont.armorBtn4.imageAttach.pic := "iconArm"
   //armorLoadoutWidget.btnBox.armoryModuleCont.armorBtn5.imageAttach.pic := "iconFoot"
   // armor class icons & name
   
   //var loadout : UD_ArmorLoadout = $uiPlayerInfo.GetBackendLoadout(_loadoutIdx)
   //armorLoadoutWidget.btnBox.armoryModuleCont.armorBtn1.setArmorClassIcn(loadout.head_armor.Get())
   //armorLoadoutWidget.btnBox.armoryModuleCont.armorBtn1.setArmorClassIcn(loadout.shoulders_armor.Get())
   //armorLoadoutWidget.btnBox.armoryModuleCont.armorBtn1.setArmorClassIcn(loadout.torso_armor.Get())
   //armorLoadoutWidget.btnBox.armoryModuleCont.armorBtn1.setArmorClassIcn(loadout.hands_armor.Get())
   //armorLoadoutWidget.btnBox.armoryModuleCont.armorBtn1.setArmorClassIcn(loadout.legs_armor.Get())
end

func TmpDisable()
   //var idx:int
   //var lidx:int   
   //for lidx := 0 to 4
   //   for idx := 1 to 5
   //      Widgets().alslots.Get("armorLoadout" + lidx).btnBox.armoryModuleCont.Get("statBar" + idx).visible := false
   //   end
   //end   
end

func GetItemName(_itemId:string):string
   var ret:string 
   if (_itemId != "")
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(_itemId)
      ret := (string)compUI.name.Get()
      return ret
   end
   return ret
end

handle OnChangeStateAny
   if (GetStateName() != "SeeArmorLoadout")
      Get("DC2").IsSeeState.Set(false)
   else
      Get("DC2").IsSeeState.Set(true)
   end
end

handle OnEnteringState("Initial")
end          

handle OnEnterState("Initial")
   Set("visible", false)           
end      

func BlinkWholeScreen()
   $root.playSound("armory_screen_appear_hud")
   StartDefaultBlinking()
end

func PrepareEnterLoadout(_showParts : bool)
   $hq.ShopVideoEndSafe()
   $hq.RenderLocalPlayer()
   $user_service.RequestData($UserDataStorage.local_user.uid.Get(), $uiEnums.USER_DATA_ARMOR_LOADOUT)
   $hq.ShowroomEnd()
   $hq.isInShowroom := false   
   viewParts := _showParts
   InitFocus()
   ShowPartsOrStats(viewParts)
   CamView()
end

func inputEvent(p : params) : bool
   if (GetStateName() != "ChoiceLoadoutBtn")
      if (p.keyCode != $uiKeys.VK_ENTER and p.keyCode != $uiKeys.VK_SPACE)
         p.eventState.SetIsTerminated()      
      end
      if (!IsChangingStateInProgress() and p.keyCode == $uiKeys.VK_ESC and ! p.isDown)
         if (Widgets().cancelBtn.visible)
            CloseArmoryLoadout(null)
         end
      elif (!IsChangingStateInProgress() and p.keyCode == $uiKeys.VK_ENTER and ! p.isDown)
         if (Widgets().doneBtn.visible)
            AcceptArmoryLoadout(null)
         end
      end
   end
   return false
end

handle OnEnteringState("SeeArmorLoadout")   
   PrepareEnterLoadout(true)
   
   Widgets().header.text            := "carousel_see_armor_loadout"
   Widgets().header.visible         := true
   Widgets().cancelBtn.visible      := true
   Widgets().cancelBtn.label        := "main_btn_back"
   Widgets().doneBtn.visible        := false
   Widgets().alslots.visible        := true
   //Widgets().tree.visible           := true
   //Widgets().viewStatsBtn.visible   := true
   Set("visible", true)
   //TmpDisable()
   AddTween("alpha", 1.0, Props().adelay, "linear")
   var i:int
   for i := 0 to 4
      Widgets().alslots.Get("armorLoadout" + i).mouseChildren := false
      //Widgets().alslots.Get("armorLoadout" + i).mouseEnabled := true  
   end  
   EnableFakeBg()
   BlinkWholeScreen()
end

handle OnLeavingState("SeeArmorLoadout")
   //
end

handle OnEnteringState("AssignArmor2Loadout")
   PrepareEnterLoadout(true)
   
   Widgets().header.text            := "carousel_assign_armor_loadout"
   Widgets().header.visible         := true
   Widgets().cancelBtn.visible      := true
   Widgets().cancelBtn.label        := "main_btn_back"
   Widgets().doneBtn.visible        := true
   Widgets().alslots.visible        := true
   //Widgets().tree.visible           := true
   //Widgets().viewStatsBtn.visible   := true
   Set("visible", true)
   //TmpDisable()   
   AddTween("alpha", 1.0, Props().adelay, "linear")
   var i:int
   for i := 0 to 4
      Widgets().alslots.Get("armorLoadout" + i).mouseChildren := false
   end
   EnableFakeBg()
   BlinkWholeScreen()
end  

handle OnEnteringState("SelectArmorLoadoutIngame")
   PrepareEnterLoadout(false)
   
   //Widgets().alslots.alpha := 100
   Widgets().header.text            := "carousel_assign_armor_loadout"
   Widgets().header.visible         := true
   Widgets().cancelBtn.visible      := false
   Widgets().cancelBtn.label        := "main_btn_back"
   Widgets().doneBtn.visible        := false
   Widgets().alslots.visible        := true
   //Widgets().tree.visible           := false
   //Widgets().viewStatsBtn.visible   := false
   Set("visible", true)
   //TmpDisable()   
   AddTween("alpha", 1.0, Props().adelay, "linear")
   var i:int
   for i := 0 to 4
      Widgets().alslots.Get("armorLoadout" + i).mouseChildren := false
   end
   EnableFakeBg()
   BlinkWholeScreen()
end

func EnableFakeBg()
   var p: params
   if (viewParts)
      p.state := "spartanUnit"
   else
      p.state := "spartanLoadout"
   end
   GenerateEvent("ChangeFakeBackground", p)
end

handle OnLeavingState("AssignArmor2Loadout")
   //      
end

func SetScreenAlpha(_alpha: float)
   Props().alpha := _alpha
end

func OnDialogShowTween(p: params): bool
   var alphaParm : float = p.dialogTweenParm
   if (GetStateName() != "Initial")
      SetScreenAlpha(100.0 - alphaParm * 95)
   end
   return true
end

end

class ArmorLoadoutsViewModel
   var IsStatsVisible : ObservableProperty = $OM.Property(false)
   var IsSeeState     : ObservableProperty = $OM.Property(false)
   var counter        : ObservableProperty = $OM.Calculated(this, "GetArmorLoadoutCounter")
   
   func GetArmorLoadoutCounter() : int
      var ret : int
      var udLocal : UserDataLocal = $UserDataStorage.local_user
      ret := (int)udLocal.armor_loadouts_unlocked.Get()
      return ret
   end
   
   func OfferPanelVisible(_loadoutIdx : int) : bool
      var ret : bool
      var udLocal : UserDataLocal = $UserDataStorage.local_user
      var unlockedArmorLoadouts : int = (int)udLocal.armor_loadouts_unlocked.Get()
      return ret
   end
   
   func OfferLineVisible(_loadoutIdx : int) : bool
      var ret : bool
      var hasLoadout : bool
      hasLoadout := _loadoutIdx < (int)counter.Get()
      if ((bool)IsSeeState.Get())
         if (hasLoadout)
            ret := false
         else
            ret := true
         end
      else
         ret := false
      end
      return ret
   end
   
   func EnableOfferBtns(_loadoutIdx : int) : bool
      var ret : bool
      if (_loadoutIdx > (int)counter.Get())
         ret := false
      else
         ret := true
      end
      return ret
   end
   
   func SetOfferPanelHeader(_loadoutIdx : int) : string
      var ret : string
      if (_loadoutIdx > (int)counter.Get())
         ret := "carousel_ui_btn_unavailable"
      else
         ret := "carousel_txt_non_purchased"
      end
      return ret
   end

end

class UiArmorLoadoutCont : UiFullscreenScreen
   
end
