import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.engine_ctrl
import ui.root
import ui.ui_party_monitor
import ui.ui_matchmaking
import ssl.observables
import ssl.hf2p.user_service
import ssl.hf2p.hq
import ssl.hf2p.user_data
import ssl.hf2p.ui_globals
import ui.hf2p_playerCard.hf2p_playerCard

class UiWidget_Lobby : UiSlidingScreenPageMainMenu

var   isSlidingElement  :  bool  = true
var   MAX_TEAM          :  int   = 16

func onLeftItemClicked(p:params):bool
   return true
end

func onLeftItemOver(p:params):bool
   return true
end

func onLeftItemOut(p:params):bool
   return true
end

func onRightItemClicked(p:params):bool
   return true
end

func onRightItemOver(p:params):bool
   return true
end

func onRightItemOut(p:params):bool
   return true
end  

//
//  MAP/MODE
//     

func SetTeamMode(_isTeamMode : bool)
   if (_isTeamMode)
      Widgets.superContainer.ArrangeRosters(2)
      Widgets.rosterCardLeft.x    := 23
      Widgets.rosterCardLeft.y    := 253
      Widgets.rosterCardRight.x   := 1563
      Widgets.rosterCardRight.y   := 253
      Widgets.waitingInfo.x       := 704
   else
      Widgets.superContainer.ArrangeRosters(1)
      Widgets.rosterCardLeft.x    := 106
      Widgets.rosterCardLeft.y    := 240
      Widgets.rosterCardRight.x   := 106
      Widgets.rosterCardRight.y   := 240
      Widgets.waitingInfo.x       := 1135
   end
end

func UpdateMapMode()
   var p: params
   p.state := "assymLobby"
   GenerateEvent("ChangeFakeBackground", p)
end      

func StartRosterLoop()
   if (GetStateName() == "Initial")
      return
   end
   Log("ui~content", "LOBBY::StartRosterLoop")
   $hq.ShowroomEnd()
   $hq.isInShowroom := false
end

func StopRosterLoop()
   Log("ui~content", "LOBBY::StopRosterLoop")
end

func StartHost()   
   Log("ui~content", "LOBBY::StartHost")      
   UpdateRightBtn(true)
end    

func onMPCountdownTimer(p:params): bool
   UpdateRightBtn(false)
   return true
end

func UpdateRightBtn(enableButton: bool = true)
   Widgets.superContainer.rightBtn.label := "lobby_btn_start_game"
   Widgets.superContainer.rightBtn.btnHighlight.frame := "green"
   Widgets.superContainer.rightBtn.btnBg.frame := "green"
   if (enableButton)
      Widgets.superContainer.rightBtn.enabled := true
   end
end

func IsCancellableMatch(_timerTime:int): bool
   return _timerTime >= 0 and _timerTime <= 5
end

func UnlockStartBtn()
   Widgets.superContainer.rightBtn.enabled := true
end
   
func InitFocus(_isStartGame : bool = false)
   if (_isStartGame)
      Widgets.superContainer.rightBtn.SetFocus()         
   else
      Widgets.superContainer.SetFocus()   
   end
end

handle OnEnterState("LobbyMatchmaking")
   Log("ui~content", "OnEnter LobbyMatchmaking")
   InitFocus()
   Widgets.superContainer.redTeam.SetSelectionIdx(0)
   StartRosterLoop()
   $uiPartyMonitor.EnterLobby($uiPartyMonitor.STATE_MATCHMAKING)
   GenerateEvent("#OnEnterLobbyMatchmaking")
end

handle OnExitState("LobbyMatchmaking")
   StopRosterLoop()
end

handle OnEnterState("Initial")
   Widgets.superContainer.SetStateName("Initial")
   GenerateEvent("#OnEnterLobbyInitial")
end

handle OnEnterState("LobbySelectPlaylist")
   Log("ui~content", "OnEnter LobbySelectPlaylist")
   $uiPartyMonitor.EnterLobby($uiPartyMonitor.STATE_FORMATION)
   Widgets.superContainer.redTeam.SetSelectionIdx(0)	            
   InitFocus(true)
   GenerateEvent("#OnEnterLobbyPlaylist")
end

handle OnExitState("LobbySelectPlaylist")
end

func SetScreenAlpha(_alpha: float)
end

func OnDialogShowTween(p: params): bool
   var alphaParm : float = p.dialogTweenParm
   if (GetStateName() != "Initial")
      SetScreenAlpha(100.0 - alphaParm * 95)
   end
   return true
end

func GetLobbyStateFromPartyMonitor(): string
   return $uiPartyMonitor.GetLobbyMode()
end

override PrepareSlide // ()
   var lobbyState : string = GetLobbyStateFromPartyMonitor()
   Log("ui~content", "PrepareSlide lobby state = " + lobbyState + ", curState = " + GetStateName())
   $hq.ShowroomEnd()
   $hq.isInShowroom := false
   if (lobbyState != "")
      Log("ui~content", "PrepareSlide lobby CHANGING")
      $UiBiLogger.LogGlobalStateChange($uiEnums.UI_BI_LOBBY)
      SetStateName(lobbyState)
   end   
   GenerateEvent("#OnPrepareLobbyScreen")
   StartDefaultBlinking(0.3)
end

override PrepareHideSlide // ()
   GenerateEvent("#OnHideLobbyScreen")
end

override DisableSlide // ()
   if (GetStateName() != "Initial")
      SetStateName("Initial")
   end
end

override SwitchToScreen //()
   $hq.ShowroomEnd()
   $hq.isInShowroom := false
end

end

class MapModeVM
   var icon          : ObservableProperty = $OM.Property("")
   var name          : ObservableProperty = $OM.Property("")
   var modeIcon      : ObservableProperty = $OM.Property("")
   var modeName      : ObservableProperty = $OM.Property("")
   var isMapMode     : ObservableProperty = $OM.Property(true)
   var isCustom      : ObservableProperty = $OM.Property(false)
   
   func Init()
      isMapMode.Subscribe(this, "UpdateMapMode") 
   end
   
   func Term()
      isMapMode.Unsubscribe(this, "UpdateMapMode") 
   end
   
   func UpdateMapMode()
      if ((bool)isCustom.Get())
         SetCustomMapMode()
      else
         if ((bool)isMapMode.Get())
            SetCurrentMapMode()
         else
            SetCurrentPlaylist()            
         end
      end
   end
   
   func SetCustomMapMode()
      var mapUIComp  : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get($UiGlobals.matchmaking.custom_game_maps_selection.Get())
      icon.Set(mapUIComp.icon.Get())
      name.Set(mapUIComp.name.Get())
      //$root.UiLog("Lobby: custom map = [" + (string)$UiGlobals.matchmaking.custom_game_maps_selection.Get() + "]")
      
      var modeUIComp  : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get($UiGlobals.matchmaking.custom_game_modes_selection.Get())
      modeIcon.Set("")
      //modeIcon.Set(modeUIComp.icon.Get())
      modeName.Set(modeUIComp.name.Get())
      //$root.UiLog("Lobby: custom mode = [" + (string)$UiGlobals.matchmaking.custom_game_modes_selection.Get() + "]")
   end
   
   func SetCurrentMapMode()
      var mapUIComp  : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get($UiGlobals.lobby.map_id.Get())
      icon.Set(mapUIComp.icon.Get())
      name.Set(mapUIComp.name.Get())
      //$root.UiLog("Lobby: current map = [" + (string)$UiGlobals.lobby.map_id.Get() + "]")
      
      var modeUIComp  : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get($UiGlobals.lobby.game_mode_id.Get())
      modeIcon.Set(modeUIComp.icon.Get())
      modeName.Set(modeUIComp.name.Get())
      //$root.UiLog("Lobby: current mode = [" + (string)$UiGlobals.lobby.game_mode_id.Get() + "]")
   end
   
   func GetMapName() : string
      UpdateMapMode()
      return (string)name.Get()
   end
   
   func GetMapIcon() : string
      UpdateMapMode()
      return (string)icon.Get()
   end
      
   func GetModeName() : string
      UpdateMapMode()
      return (string)modeName.Get()
   end
   
   func GetModeIcon() : string
      UpdateMapMode()
      return (string)modeIcon.Get()
   end
   
   func SetCurrentPlaylist()
      SetPlaylist((string)$UiGlobals.matchmaking.playlists_selection.Get())
   end
   
   func SetPlaylist(_id : string)
      if (_id != "")
         var uiComp : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(_id)
         icon.Set(uiComp.icon_big.Get())
         name.Set(uiComp.name.Get())         
         //$root.UiLog("Lobby: current playlist = [" + _id + "]")
      else
         icon.Set("")
         name.Set("")
      end
      modeIcon.Set("slayerMode")
      var plComp: GL_ComponentPlaylist = (GL_ComponentPlaylist)$UiGlobals.componentsPlaylist.Get($UiGlobals.matchmaking.playlists_selection.Get())
      modeName.Set("lobby_playlist_desc," + (string)(int)plComp.player_count_min.Get() + "," + (string)(int)plComp.player_count_max.Get() + "," + (string)(int)plComp.party_size_max.Get())
   end
   
   func Invalidate()
      UpdateMapMode()
   end
end

class LobbyVM : UiSlidingScreenMainMenuPageVM   
   var isScreenActive         : ObservableProperty = $OM.Property(false)
   var SelectedUID            : ObservableProperty = $OM.Property(0)
   var isVotingPhase          : ObservableProperty = $OM.Calculated(this, "GetIsVotingPhase")
   var playersList1           : ObservableProperty = $OM.Calculated(this, "GetPlayersList1")
   var playersList2           : ObservableProperty = $OM.Calculated(this, "GetPlayersList2")
   var rosterCardLeft         : PlayerCardVM       = new PlayerCardVM()
   var rosterCardRight        : PlayerCardVM       = new PlayerCardVM()
   var selectedPlayerIdx      : ObservableProperty = $OM.Property(0)
   var selectedPlayerIdx1     : ObservableProperty = $OM.Property(0)
   var selectedPlayerIdx2     : ObservableProperty = $OM.Property(0)
   var savedPlayerIdx         : ObservableProperty = $OM.Property(0)
   var savedPlayerIdx1        : ObservableProperty = $OM.Property(0)
   var savedPlayerIdx2        : ObservableProperty = $OM.Property(0)
   var selectedPlayerUID      : ObservableProperty = $OM.Property($UserDataStorage.invalidUID)
   var selectedPlayerUID1     : ObservableProperty = $OM.Calculated(this, "GetSelectedPlayerUID1")
   var selectedPlayerUID2     : ObservableProperty = $OM.Calculated(this, "GetSelectedPlayerUID2")
   var playlistsList          : ObservableProperty = $OM.Calculated(this, "GetPlaylists")
   var gameModesList          : ObservableProperty = $OM.Calculated(this, "GetGameModes")
   var gameMapsList           : ObservableProperty = $OM.Calculated(this, "GetGameMaps")
   var playlistsNames         : vector
   var selectedPlaylistIdx    : ObservableProperty = $OM.Property(0)
   var selectedGameModeIdx    : ObservableProperty = $OM.Property(0)
   var selectedGameMapIdx     : ObservableProperty = $OM.Property(0)
   var selectedPlaylist       : ObservableProperty = $OM.Property("")
   var selectedGameMode       : ObservableProperty = $OM.Property("")
   var selectedGameMap        : ObservableProperty = $OM.Property("")
   var mapMode                : MapModeVM          = new MapModeVM()
   var isWaiting              : ObservableProperty = $OM.Calculated(this, "GetIsWaiting")
   var screenState            : ObservableProperty = $OM.Property($uiEnums.LOBBY_SCREEN_STATE_NONE)
   var isTeamMode             : ObservableProperty = $OM.Property(false)
   var isTeamModeRoster       : ObservableProperty = $OM.Calculated(this, "GetIsTeamModeRoster")
   var wgt                    : UiWidget_Lobby     = null
   var waitingText            : ObservableProperty = $OM.Property("")
   var lobbyStateTxt          : ObservableProperty = $OM.Property("")
   var players1Vec            : vector
   var players2Vec            : vector
   var players1VecObservable  : ObservableProperty = $OM.Property(players1Vec)
   var players2VecObservable  : ObservableProperty = $OM.Property(players2Vec)
   
   var isPlaylistVisible      : ObservableProperty = $OM.Property(false)
   var isGameModeVisible      : ObservableProperty = $OM.Property(false)
   var isGameMapVisible       : ObservableProperty = $OM.Property(false)
   var isMapSelectorVisible   : ObservableProperty = $OM.Property(false)
   var isModeSelectorVisible  : ObservableProperty = $OM.Property(false)
   var isMapModeVisible       : ObservableProperty = $OM.Property(false)
   var isVotingMapsVisible    : ObservableProperty = $OM.Property(false)
   var isPlayers1Visible      : ObservableProperty = $OM.Property(false)
   var isPlayers2Visible      : ObservableProperty = $OM.Property(false)
   var isPlayers1Enabled      : ObservableProperty = $OM.Property(false)
   var isPlayers2Enabled      : ObservableProperty = $OM.Property(false)
   var isStartBtnVisible      : ObservableProperty = $OM.Property(false)
   var isCloseBtnVisible      : ObservableProperty = $OM.Property(true)
   var isWaitingMode          : ObservableProperty = $OM.Property(false)
   var isFlowPanelVisible     : ObservableProperty = $OM.Property(true)
   var isLobbyMode            : ObservableProperty = $OM.Property(true)
   
   var lobbyPlayerLocal       : GL_LobbyPlayer = new GL_LobbyPlayer()
   var lobbyPlayerInvalid     : GL_LobbyPlayer = new GL_LobbyPlayer()
   
   var internalPlayersLobby   :  vector
   var internalPlayersMM      :  vector
   var internalPlayersParty   :  vector
   
   
   override InitOverride //(p : params)
      rosterCardLeft.isLeft.Set(false)
      rosterCardRight.isLeft.Set(true)
      
      lobbyPlayerLocal.InitDefault()
      lobbyPlayerInvalid.InitDefault()
      UpdateLocalUid()
      
      wgt := p.widget
      selectedPlayerUID.Subscribe(this, "UpdateSelectedUID")
      selectedPlayerUID1.Subscribe(this, "UpdateSelectedUID")
      selectedPlayerUID2.Subscribe(this, "UpdateSelectedUID")
      isTeamModeRoster.Subscribe(this, "UpdateTeamMode")
      isFlowPanelVisible.Subscribe(this, "UpdateFlowPanelVisible")
      isLobbyMode.Subscribe(this, "UpdateIsLobbyMode")
      $UiGlobals.lobby.state.Subscribe(this, "UpdateLobbyState")
      $UiGlobals.matchmaking.state.Subscribe(this, "UpdateLobbyState")      
      $UiGlobals.matchmaking.queue.Subscribe(this, "UpdateLobbyState")
      $UserDataStorage.local_user.isPartyLeader.Subscribe(this, "UpdateLobbyState")
      
      $UiGlobals.matchmaking.playlists_selection.Subscribe(this, "UpdateMapMode")
      $UiGlobals.lobby.map_id.Subscribe(this, "UpdateMapMode")
      $UiGlobals.lobby.game_mode_id.Subscribe(this, "UpdateMapMode")
      
      $uiPartyMonitor.lobbyModeObservable.Subscribe(this, "UpdatePartyMonitorLobbyState")
      mapMode.Init()
      
      $UserDataStorage.local_user.uid.Subscribe(this, "UpdateLocalUid")

      screenState.Subscribe(this, "OnScreenStateChanged")         
      
      $UiGlobals.lobby.players.Subscribe(this, "UpdatePlayerVectors")
      $UiGlobals.matchmaking.group.Subscribe(this, "UpdatePlayerVectors")
      $UiGlobals.party.members.Subscribe(this, "UpdatePlayerVectors")
      $UiGlobals.lobby.team_count.Subscribe(this, "UpdatePlayerVectors")
   end
   
   override TermOverride //()
      $UiGlobals.party.members.Unsubscribe(this, "UpdatePlayerVectors")
      $UiGlobals.matchmaking.group.Unsubscribe(this, "UpdatePlayerVectors")
      $UiGlobals.lobby.players.Unsubscribe(this, "UpdatePlayerVectors")
      $UiGlobals.lobby.team_count.Unsubscribe(this, "UpdatePlayerVectors")
      mapMode.Term()      
      $UiGlobals.lobby.state.Unsubscribe(this, "UpdateLobbyState")
      $UiGlobals.matchmaking.state.Unsubscribe(this, "UpdateLobbyState")
      $UiGlobals.matchmaking.queue.Unsubscribe(this, "UpdateLobbyState")
      $UserDataStorage.local_user.isPartyLeader.Unsubscribe(this, "UpdateLobbyState")
      
      selectedPlayerUID.Unsubscribe(this, "UpdateSelectedUID")
      selectedPlayerUID1.Unsubscribe(this, "UpdateSelectedUID")
      selectedPlayerUID2.Unsubscribe(this, "UpdateSelectedUID")
      
      screenState.Unsubscribe(this, "OnScreenStateChanged")
      
      isTeamModeRoster.Unsubscribe(this, "UpdateTeamMode")
      isFlowPanelVisible.Unsubscribe(this, "UpdateFlowPanelVisible")
      isLobbyMode.Unsubscribe(this, "UpdateIsLobbyMode")
      
      $UiGlobals.matchmaking.playlists_selection.Unsubscribe(this, "UpdateMapMode")
      $UiGlobals.lobby.map_id.Unsubscribe(this, "UpdateMapMode")
      $UiGlobals.lobby.game_mode_id.Unsubscribe(this, "UpdateMapMode")
      
      $uiPartyMonitor.lobbyModeObservable.Unsubscribe(this, "UpdatePartyMonitorLobbyState")
      
      $UserDataStorage.local_user.uid.Unsubscribe(this, "UpdateLocalUid")
      
      $uiPartyMonitor.FinishMatchCountdown()
   end
   
   func UpdatePlayerVectors()
      if (wgt != null and wgt.GetStateName() != "Initial")
         internalPlayersLobby := $UiGlobals.lobby.players.Get()
         internalPlayersMM    := $UiGlobals.matchmaking.group.Get()
         internalPlayersParty := $UiGlobals.party.members.Get()
         UpdateRosterLists()
         UpdatePlayerSelections()
      end
   end
   
   func UpdatePartyMonitorLobbyState(_val : *)
      if (wgt != null)
         wgt.PrepareSlide()
      end
   end
   
   func votingMapClick(p:params) : bool
      var voteIdx : int = (int)p.widget.Props.voteIdx
      
      //var mapId : string = (string)p.widget.GetDC().map_id.Get()
      $hq.LobbyVote(voteIdx)
      $UiGlobals.lobby.UpdateVoteSetLength()
      
      return true
   end   

   func GetIsVotingPhase() : *
      var ret           : bool = false
      var lobbyStateIdx : int = (int)$UiGlobals.lobby.state.Get()      
      var voteVersion   : int = (int)$UiGlobals.lobby.vote_set_version.Get()
      ret := lobbyStateIdx == $uiEnums.LOBBY_STATE_VOTING
      if (lobbyStateIdx == $uiEnums.LOBBY_STATE_VOTING)
         ret := true
      end
      
      $UiGlobals.lobby.UpdateVoteSetLength()      
          
      
      return ret
   end   
   
   func LobbyVM()
   end
   
   func OnScreenStateChanged(_val : *)
      LobbyBlink(true)
   end
   
   func LobbyBlink(fast : bool = false)
      var delayBlink : float = 0.3
      var blinkSpeed : float = 1.0
      if (fast)
         delayBlink := 0.15
         blinkSpeed := 2.0
      end
      if (wgt != null)
         wgt.StartDefaultBlinking(delayBlink, blinkSpeed)
         wgt.GenerateEvent("SlidingScreenBlink")
      end
   end
   
   func IsCustomGame() : bool
      return (int)$UiGlobals.matchmaking.queue.Get() == $uiEnums.MM_QUEUE_TYPE_CUSTOM
   end
   
   func OnEnterLobby() : bool
      SetScreenActive(true)
      screenState.Set($uiEnums.LOBBY_SCREEN_STATE_MATCHMAKING)
      InvalidateAll(false)
      LobbyBlink()
      return true
   end
      
   func OnEnterLobbyPlaylist() : bool
      SetScreenActive(true)
      screenState.Set($uiEnums.LOBBY_SCREEN_STATE_PLAYLIST)
      InvalidateAll(true)
      LobbyBlink()
      return true
   end
   
   func OnEnterLobbyMatchmaking() : bool
      SetScreenActive(true)
      screenState.Set($uiEnums.LOBBY_SCREEN_STATE_MATCHMAKING)
      InvalidateAll(false)
      LobbyBlink()
      return true
   end      
   
   func OnEnterLobbyInitial() : bool
      SetScreenActive(false)
      screenState.Set($uiEnums.LOBBY_SCREEN_STATE_NONE)
      InvalidateAll(false)
      return true
   end      
   
   func InvalidateAll(reselectPLaylist : bool)
      var plIdx : int = GetPlaylistIdx((string)$UiGlobals.matchmaking.playlists_selection.Get())
      if (plIdx == -1)
         plIdx := 0
      end
      selectedPlaylistIdx.Set(plIdx)
      var playlists : vector = GetPlaylists()
      if playlists.Count() > selectedPlaylistIdx.Get()
         selectedPlaylist.Set(playlists.Get(selectedPlaylistIdx.Get()).id)
      end
      if (reselectPLaylist)
         ApplyCurrentPlaylist()
      end
      $hq.ShopVideoEndSafe()
      $hq.RenderLocalPlayer()
      UpdateRosterLists()
      playersList1.Invalidate()
      playersList2.Invalidate()
      playlistsNames.Clear()
      playlistsList.Invalidate()
      mapMode.Invalidate() 
      UpdateLobbyStateInternal(true)
      ResetPlayerSelections()
      UpdateMapMode()
      UpdatePlayerVectors()
      
      isCloseBtnVisible.Set(true)
      UpdateCloseBtnVisible()
   end
   
   func SetScreenActive(_active : bool)
      rosterCardLeft.isActive.Set(_active)
      rosterCardRight.isActive.Set(_active)
      isScreenActive.Set(_active)
   end
   
   func IsScreenActive() : bool
      var ret : bool = false
      ret := (bool)isScreenActive.Get()
      return ret
   end
   
   func ResetPlayerSelections()
      savedPlayerIdx1.Set(0)
      savedPlayerIdx2.Set(0)
      selectedPlayerIdx1.Set(0)
      selectedPlayerIdx2.Set(0)
      selectedPlayerIdx.Set(0)
      selectedPlayerUID.Set(GetPlayerUID(0, 0))
      selectedPlayerUID.Invalidate()
      selectedPlayerUID1.Invalidate()
      selectedPlayerUID2.Invalidate()
   end
   
   func GetPlayerTeamIdx(_uid : *) : int
      var i    : int
      var ret  := 0
      for i := 0 to players1Vec.Count() - 1
         var player : GL_LobbyPlayer = players1Vec.Get(i)
         if ($UserDataStorage.IsEqualUIDs(_uid, player.id.value.Get()))
            ret := (int)player.team_index2.Get()
            break
         end
      end
      for i := 0 to players2Vec.Count() - 1
         var player : GL_LobbyPlayer = players2Vec.Get(i)
         if ($UserDataStorage.IsEqualUIDs(_uid, player.id.value.Get()))
            ret := (int)player.team_index2.Get()
            break
         end
      end
      return ret
   end
   
   func UpdateSelectedUID(_uid : * = null)
      if ((bool)isTeamModeRoster.Get())
         rosterCardLeft.SetUID((GL_UID)selectedPlayerUID1.Get())
         rosterCardRight.SetUID((GL_UID)selectedPlayerUID2.Get())     
         rosterCardLeft.SetTeam((bool)isTeamMode.Get(), GetPlayerTeamIdx(((GL_UID)selectedPlayerUID1.Get()).value.Get()))
         rosterCardRight.SetTeam((bool)isTeamMode.Get(), GetPlayerTeamIdx(((GL_UID)selectedPlayerUID2.Get()).value.Get()))
      else
         rosterCardLeft.SetUID((GL_UID)selectedPlayerUID.Get())
         rosterCardRight.SetUID(lobbyPlayerInvalid.id)
         rosterCardLeft.SetTeam((bool)isTeamMode.Get(), GetPlayerTeamIdx(((GL_UID)selectedPlayerUID.Get()).value.Get()))
         rosterCardRight.SetTeam((bool)isTeamMode.Get(), 0)
      end
   end
   
   func GetPlayerUID(_teamIdx : int, _idx : int) : GL_UID
      var uid     : GL_UID = lobbyPlayerLocal.id
      var players : vector
      if (_teamIdx == 0)
         players := players1Vec
      elif (_teamIdx == 1)
         players := players2Vec
      end
      if ((bool)isTeamModeRoster.Get())
         uid := lobbyPlayerInvalid.id
      end      
      if (_idx >= 0 and _idx < players.Count())  
         var plr : GL_LobbyPlayer = (GL_LobbyPlayer)players.Get(_idx)
         uid := plr.GetUID()
      end
      if (! uid.IsValidVal())
         uid := lobbyPlayerLocal.id
      end
      return uid
   end      
         
   func GetSelectedPlayerUID1() : *
      var uid : GL_UID = lobbyPlayerLocal.id
      if ((bool)isTeamModeRoster.Get())
         uid := lobbyPlayerInvalid.id
      end
      var players    : vector = players1Vec
      var idx        : int    = (int)selectedPlayerIdx1.Get()
      if (idx >= 0 and idx < players.Count())  
         var plr : GL_LobbyPlayer = (GL_LobbyPlayer)players.Get(idx)
         uid := plr.GetUID()
      end
      if (idx == 0 and ! uid.IsValidVal())
         uid := lobbyPlayerLocal.id
      end
      return uid
   end
   
   func GetSelectedPlayerUID2() : *
      var uid : GL_UID = lobbyPlayerInvalid.id
      if ((bool)isTeamModeRoster.Get())
         uid := $UserDataStorage.invalidUID
      end
      var players   : vector = players2Vec
      var idx       : int    = (int)selectedPlayerIdx2.Get()
      if (idx >= 0 and idx < players.Count())  
         var plr : GL_LobbyPlayer = (GL_LobbyPlayer)players.Get(idx)
         uid := plr.GetUID()
      end
      if (idx == 0 and ! uid.IsValidVal())
         uid := lobbyPlayerLocal.id
      end
      return uid
   end
   
   func InvalidateSelectedPlayer(_renderModelIdx : int = -1)
      selectedPlayerUID1.Invalidate()
      selectedPlayerUID2.Invalidate()      
      selectedPlayerUID.Invalidate()
      UpdateSelectedUID()
      if (_renderModelIdx != -1)
         var uid : GL_UID = lobbyPlayerInvalid.id
         if (_renderModelIdx == 0)
            uid := (GL_UID)selectedPlayerUID.Get()
         elif (_renderModelIdx == 1)
            uid := (GL_UID)selectedPlayerUID1.Get()
         elif (_renderModelIdx == 2)
            uid := (GL_UID)selectedPlayerUID2.Get()
         end
      end
   end

   func GetSelectionLIRData(_listIdx : int, _idx : int) : GL_LobbyPlayer
      var ret     : GL_LobbyPlayer  = null
      var selIdx  : int             = _idx
      var data    : vector
      if (_listIdx == 1)
         data     := GetPlayersList2()
         //selIdx   := wgt.Widgets.superContainer.blueTeam.selection
         //ret := wgt.Widgets.superContainer.GetWidget("blueTeam").selectionItem.Get()
         //return ret
      elif (_listIdx == 0)
         data     := GetPlayersList1()
         //selIdx   := wgt.Widgets.superContainer.redTeam.selection
         //ret := wgt.Widgets.superContainer.GetWidget("redTeam").selectionItem.Get()
         //return ret
      end
      if (data != null and selIdx >= 0 and selIdx < data.Count())
         ret := data.Get(selIdx)
      end
      return ret
   end
   
   func HandlePlayerClick(_listIdx : int, _idx : int)
      var player : GL_LobbyPlayer = GetSelectionLIRData(_listIdx, _idx)
      if (player != null)
         if ((bool)player.isAddSlot.Get())
            wgt.GenerateEvent("OpenInvitePanel")
         end
      end
   end
   
   func UpdatePlayerSelections()
      if ((bool)isTeamModeRoster.Get())
         InvalidateSelectedPlayer(1)
         InvalidateSelectedPlayer(2)
      else
         selectedPlayerUID.Set(GetPlayerUID(0, (int)selectedPlayerIdx.Get()))
         InvalidateSelectedPlayer(0)
      end      
   end
   
   func lobbyLIR_itemClick1(p : params) : bool   
      if ((bool)isTeamModeRoster.Get())
         selectedPlayerIdx1.Set((int)p.index)  
         savedPlayerIdx1.Set((int)p.index)   
         InvalidateSelectedPlayer(1)
      else
         selectedPlayerIdx.Set((int)p.index)  
         savedPlayerIdx.Set((int)p.index)   
         selectedPlayerUID.Set(GetPlayerUID(0, (int)p.index))
         InvalidateSelectedPlayer(0)
      end
      HandlePlayerClick(0, p.index)
      return true
   end
   
   func lobbyLIR_itemClick2(p : params) : bool   
      if ((bool)isTeamModeRoster.Get())
         selectedPlayerIdx2.Set((int)p.index)  
         savedPlayerIdx2.Set((int)p.index)   
         InvalidateSelectedPlayer(2)
      else
         selectedPlayerIdx.Set((int)p.index)  
         savedPlayerIdx.Set((int)p.index)   
         selectedPlayerUID.Set(GetPlayerUID(1, (int)p.index))
         InvalidateSelectedPlayer(0)
      end
      HandlePlayerClick(1, p.index)
      return true
   end

   func lobbyLIR_itemRollOver1(p : params) : bool   
      if ((bool)isTeamModeRoster.Get())
         selectedPlayerIdx1.Set((int)p.index)  
         InvalidateSelectedPlayer(1)
      else
         selectedPlayerIdx.Set((int)p.index)  
         selectedPlayerUID.Set(GetPlayerUID(0, (int)p.index))
         InvalidateSelectedPlayer(0)
      end
      return true
   end
   
   func lobbyLIR_itemRollOver2(p : params) : bool   
      if ((bool)isTeamModeRoster.Get())
         selectedPlayerIdx2.Set((int)p.index)  
         InvalidateSelectedPlayer(2)
      else
         selectedPlayerIdx.Set((int)p.index)  
         selectedPlayerUID.Set(GetPlayerUID(1, (int)p.index))
         InvalidateSelectedPlayer(0)
      end
      return true
   end
   
   func lobbyLIR_itemRollOut1(p : params) : bool   
      if ((bool)isTeamModeRoster.Get())
         selectedPlayerIdx1.Set(savedPlayerIdx1.Get())
         InvalidateSelectedPlayer(1)
      else
         selectedPlayerIdx.Set(savedPlayerIdx.Get())
         selectedPlayerUID.Set(GetPlayerUID(0, (int)savedPlayerIdx.Get()))
         InvalidateSelectedPlayer(0)
      end
      return true
   end
   
   func lobbyLIR_itemRollOut2(p : params) : bool   
      if ((bool)isTeamModeRoster.Get())
         selectedPlayerIdx2.Set(savedPlayerIdx2.Get())
         InvalidateSelectedPlayer(2)
      else
         selectedPlayerIdx.Set(savedPlayerIdx.Get())
         selectedPlayerUID.Set(GetPlayerUID(1, (int)savedPlayerIdx.Get()))
         InvalidateSelectedPlayer(0)
      end
      return true
   end
      
   func UpdateLocalUid()
      lobbyPlayerLocal.id.value.Set($UserDataStorage.local_user.uid.Get())
      //lobbyPlayerLocal.id.value.Set($UserDataStorage.local_user.uid.Get())
   end
   
   func UpdateRosterLists()
      var   playersVec        : vector
      var   playersVecLocal   : vector
      var   i                 : int
      var   isTeamModeSet     : bool   = false
      var   maxPlayers        : int    = 8
      var   alwaysTeam        : bool   = false
      var   count1            : int    = 0
      var   count2            : int    = 0
      var   totalIdx          : int    = 0
      var   rosterIdx         : int    = 0
      var   lobbyState        : int    = (int)$UiGlobals.lobby.state.Get()
       var  totalPlayersInList: int    = -1
      
      if (players1Vec.Count() == 0)
         for i := 0 to maxPlayers - 1
            var playerRec1 : GL_LobbyPlayer = new GL_LobbyPlayer()
            var playerRec2 : GL_LobbyPlayer = new GL_LobbyPlayer()
            playerRec1.InitDefault()
            playerRec2.InitDefault()
            players1Vec.Push(playerRec1)
            players2Vec.Push(playerRec2)
         end
      end
      
      var isTeamsAllowed : bool = IsTeamModeAllowed()
      if ((int)$UiGlobals.lobby.team_count.Get() > 1)
         if (isTeamsAllowed)
            isTeamModeSet := true
         end
      end
      //hack
      //isTeamModeSet := true
                  
      var playlist      : string                = (string)$UiGlobals.matchmaking.playlists_selection.Get()
      var plComp        : GL_ComponentPlaylist  = (GL_ComponentPlaylist)$UiGlobals.componentsPlaylist.Get(playlist)
      var maxPlPlayers  : int                   = 0
      if (isTeamModeSet)
         maxPlPlayers := (int)plComp.player_count_max.Get() / 2
      else
         maxPlPlayers := (int)plComp.player_count_max.Get()
      end   
         
      if ($uiPartyMonitor.GetLobbyModeObservable() == $uiPartyMonitor.STATE_FORMATION)
         isTeamModeSet        := false
         playersVec           := internalPlayersParty
         totalPlayersInList   := playersVec.Count()
         
         $root.UiLog("Lobby: players count [formation] = " + (string)playersVec.Count())
         
         for i := 0 to playersVec.Count() - 1
            var   player      : GL_UID    = (GL_UID)playersVec.Get(i)
            var   teamIdx     : int       = 0
            var   curCount    : int
            
            if (! isTeamModeSet)
               teamIdx     := 0
            end
            
            if (teamIdx < 2)
               if (count1 >= maxPlayers or teamIdx == 1)
                  rosterIdx := 1
               else 
                  rosterIdx := 0
               end
            else
               rosterIdx := 0
            end
            teamIdx := rosterIdx
                     
            if (rosterIdx == 0)
               playersVecLocal   := players1Vec
               curCount          := count1
            else
               playersVecLocal   := players2Vec
               curCount          := count2
            end
            
            var playerRec : GL_LobbyPlayer = (GL_LobbyPlayer)playersVecLocal.Get(curCount)
            playerRec.id.value.Set(player.value.Get())
            playerRec.idx.Set(totalIdx)
            playerRec.localIdx.Set(curCount)
            playerRec.isTeamMode.Set(isTeamModeSet)
            playerRec.team_index2.Set(teamIdx)
            if (isTeamModeSet)
               playerRec.isSlotEnabled.Set(curCount < maxPlPlayers)
            else
               playerRec.isSlotEnabled.Set(totalIdx < maxPlPlayers)
            end
            playerRec.isAddSlot.Set(false)
            playerRec.isAddSlot.OnChanged()
            playerRec.lobbyState.Set(GetScreenStateVal())
            playerRec.id.value.OnChanged()

            if (rosterIdx == 0)
               count1 := count1 + 1
            else
               count2 := count2 + 1
            end
            totalIdx := totalIdx + 1
         end         
      elif (lobbyState != $uiEnums.LOBBY_STATE_NONE and lobbyState != $uiEnums.LOBBY_STATE_JOINING_SESSION)
         playersVec := internalPlayersLobby
         totalPlayersInList := playersVec.Count()
         
         $root.UiLog("Lobby: players count [lobby] = " + (string)playersVec.Count())
         for i := 0 to playersVec.Count() - 1
            var   player      : GL_LobbyPlayer  = (GL_LobbyPlayer)playersVec.Get(i)
            var   teamIdx     : int             = (int)player.team_index.Get()
            var   curCount    : int
            
            if (! isTeamModeSet)
               teamIdx     := 0
            end
            
            if (teamIdx < 2)
               if (count1 >= maxPlayers or teamIdx == 1)
                  rosterIdx := 1
               else 
                  rosterIdx := 0
               end
            else
               rosterIdx := 0
            end
            teamIdx := rosterIdx
                     
            if (rosterIdx == 0)
               playersVecLocal   := players1Vec
               curCount          := count1
            else
               playersVecLocal   := players2Vec
               curCount          := count2
            end
            
            var playerRec : GL_LobbyPlayer = (GL_LobbyPlayer)playersVecLocal.Get(curCount)
            playerRec.CopyVals(player)            
            playerRec.idx.Set(totalIdx)
            playerRec.localIdx.Set(curCount)
            playerRec.isTeamMode.Set(isTeamModeSet)
            playerRec.team_index2.Set(teamIdx)
            if (isTeamModeSet)
               playerRec.isSlotEnabled.Set(curCount < maxPlPlayers)
            else
               playerRec.isSlotEnabled.Set(totalIdx < maxPlPlayers)
            end
            playerRec.isAddSlot.Set(false)
            playerRec.isAddSlot.OnChanged()
            playerRec.lobbyState.Set(GetScreenStateVal())
            playerRec.id.value.OnChanged()

            if (rosterIdx == 0)
               count1 := count1 + 1
            else
               count2 := count2 + 1
            end
            totalIdx := totalIdx + 1
         end
      else
         playersVec           := internalPlayersMM
         isTeamModeSet        := false
         totalPlayersInList   := playersVec.Count()
         maxPlPlayers         := (int)plComp.player_count_max.Get()
         
         $root.UiLog("Lobby: players count [MM] = " + (string)playersVec.Count())
         for i := 0 to playersVec.Count() - 1
            var   player      : GL_UID  = (GL_UID)playersVec.Get(i)
            var   teamIdx     : int     = 0
            var   curCount    : int
            
            if (! isTeamModeSet)
               teamIdx     := 0
            end
            
            if (teamIdx < 2)
               if (count1 >= maxPlayers or teamIdx == 1)
                  rosterIdx := 1
               else 
                  rosterIdx := 0
               end
            else
               rosterIdx := 0
            end
            teamIdx := rosterIdx
                     
            if (rosterIdx == 0)
               playersVecLocal   := players1Vec
               curCount          := count1
            else
               playersVecLocal   := players2Vec
               curCount          := count2
            end
            
            var playerRec : GL_LobbyPlayer = (GL_LobbyPlayer)playersVecLocal.Get(curCount)
            playerRec.id.value.Set(player.value.Get())
            playerRec.team_index.Set(0)
            playerRec.idx.Set(totalIdx)
            playerRec.localIdx.Set(curCount)
            playerRec.isTeamMode.Set(isTeamModeSet)
            playerRec.team_index2.Set(teamIdx)
            if (isTeamModeSet)
               playerRec.isSlotEnabled.Set(curCount < maxPlPlayers)
            else
               playerRec.isSlotEnabled.Set(totalIdx < maxPlPlayers)
            end
            playerRec.lobbyState.Set(GetScreenStateVal())
            playerRec.isAddSlot.Set(false)
            playerRec.isAddSlot.OnChanged()
            playerRec.id.value.OnChanged()

            if (rosterIdx == 0)
               count1 := count1 + 1
            else
               count2 := count2 + 1
            end
            totalIdx := totalIdx + 1
         end
      end
      // fill the rest
      
      var isAddSlot : bool = GetScreenStateVal() == $uiEnums.LOBBY_SCREEN_STATE_PLAYLIST
      isAddSlot := isAddSlot and $UserDataStorage.local_user.IsPartyLeader()
      for rosterIdx := 0 to 1
         if (rosterIdx == 1)
            isAddSlot := false
         end
         
         var curCount : int
         if (rosterIdx == 0)
            playersVecLocal   := players1Vec
            curCount          := count1
         else
            playersVecLocal   := players2Vec
            curCount          := count2
         end
         
         while (curCount < maxPlayers)
            var playerRec : GL_LobbyPlayer = (GL_LobbyPlayer)playersVecLocal.Get(curCount)
            playerRec.SetInvalid()
            playerRec.idx.Set(totalIdx)
            playerRec.localIdx.Set(curCount)
            playerRec.isTeamMode.Set(isTeamModeSet)
            if (isTeamModeSet)
               playerRec.team_index2.Set(rosterIdx)
               playerRec.isSlotEnabled.Set(curCount < maxPlPlayers)
            else
               playerRec.team_index2.Set(0)
               playerRec.isSlotEnabled.Set(totalIdx < maxPlPlayers)
            end
            if ($uiPartyMonitor.GetLobbyModeObservable() == $uiPartyMonitor.STATE_FORMATION)
               playerRec.isSlotEnabled.Set(rosterIdx == 0)
            end
            playerRec.isAddSlot.Set(isAddSlot)
            playerRec.isAddSlot.OnChanged()
            playerRec.lobbyState.Set(GetScreenStateVal())
            isAddSlot := false
            //playerRec.id.value.OnChanged()
            
            curCount := curCount + 1
            totalIdx := totalIdx + 1
         end
      end
      
      isTeamMode.Set(isTeamModeSet)     
      //players1VecObservable.OnChanged()
      //players2VecObservable.OnChanged()
   end
   
   func GetTeamPlayers(_rosterTeam : int) : vector          
      var playersVecLocal : vector
      if (_rosterTeam == 0)
         playersVecLocal := players1VecObservable.Get()
      else
         playersVecLocal := players2VecObservable.Get()
      end
      return playersVecLocal
   end
      
   func GetPlayersList1() : vector
      return GetTeamPlayers(0)
   end
   
   func GetPlayersList2() : vector
      return GetTeamPlayers(1)
   end
   
   func GetPlaylistIdx(id : string) : int
      var ret        : int = -1
      var i          : int
      var playlists  : vector = GetPlaylists()
      for i := 0 to playlists.Count() - 1
         var playlistId : string = playlists.Get(i).id
         if (playlistId == id)
            ret := i
            break
         end
      end
      return ret
   end
         
   func playlistDropDownIndexChange(p : params) : bool      
      var idx : int = p.index
      if (idx >= 0 and idx < GetPlaylists().Count())
         selectedPlaylistIdx.Set(idx)
         selectedPlaylist.Set(GetPlaylists().Get(idx).id)
         ApplyCurrentPlaylist()
         UpdateMapMode()
      end
      return true
   end

   func gameModeIndexChange(p : params) : bool      
      var idx : int = p.index
      if (idx >= 0 and idx < GetGameModes().Count())
         selectedGameModeIdx.Set(idx)
         selectedGameMode.Set(GetGameModes().Get(idx).id)
         $hq.CustomGameSetMode(GetGameModes().Get(idx).id)
         UpdateMapMode()
      end
      return true
   end

   func gameMapIndexChange(p : params) : bool      
      var idx : int = p.index
      if (idx >= 0 and idx < GetGameMaps().Count())
         selectedGameMapIdx.Set(idx)
         selectedGameMap.Set(GetGameMaps().Get(idx).id)
         $hq.CustomGameSetMap(GetGameMaps().Get(idx).id)
         UpdateMapMode()
      end
      return true
   end
   
   func GetStepperIndexById(_elems : vector, _id : string) : int
      var ret        : int = 0
      var i          : int
      if (_id != "")
         for i := 0 to _elems.Count() - 1
            var elem : params = _elems.Get(i)
            if (elem.id == _id)
               ret := i
               break
            end
         end
      end
      return ret
   end
   
   func GetSelectedModeIdx() : int
      return GetStepperIndexById(GetGameModes(), (string)$UiGlobals.matchmaking.custom_game_modes_selection.Get())
   end
   
   func GetSelectedMapIdx() : int
      return GetStepperIndexById(GetGameMaps(), (string)$UiGlobals.matchmaking.custom_game_maps_selection.Get())
   end
   
   func SortByUiListId (p1 : params, p2 :  params): int
      var ret : int = 0
      var x   : int = 0
      var y   : int = 0
      
      if (! IsVoid(p1.uiListId))
         x := (int)(p1.uiListId)
      end
      if (! IsVoid(p2.uiListId))
         y := (int)(p2.uiListId)
      end
      
      if (x < y)
         ret := -1
      elif (x > y)
         ret := 1 
      end
      return ret
   end
   
   func StringsVecToStepperList(_vec : vector) : vector
      var ret        : vector
      var i          : int
      for i := 0 to _vec.Count() - 1
         var rec  : GL_String = (GL_String)_vec.Get(i)
         var id   : string = (string)rec.value.Get()
         var name : string = ""
         if (id != "")
            name := $UiGlobals.componentsUI.Get(id).name.Get()
         end
         var listElem      : params
         listElem.id       := id
         listElem.label    := name
         ret.Push(listElem)         
      end
      return ret
   end

   func GetGameModes() : vector
      var ret : vector = StringsVecToStepperList($UiGlobals.matchmaking.custom_game_modes.Get())
      return ret
   end
   
   func GetGameMaps() : vector
      var ret : vector = StringsVecToStepperList($UiGlobals.matchmaking.custom_game_maps.Get())
      return ret
   end

   func GetPlaylists() : vector
      if (playlistsNames.Count() == 0)
         var playlistsVec        : vector = $UiGlobals.matchmaking.playlists.Get()
         var playlistsVecChecked : vector
         var i                   : int
         for i := 0 to playlistsVec.Count() - 1
            var rec        : GL_String             = (GL_String)playlistsVec.Get(i)
            var id         : string                = (string)rec.value.Get()
            var pl         : GL_ComponentPlaylist  = (GL_ComponentPlaylist)$UiGlobals.componentsPlaylist.Get(id)
            var maxparty   : int                   = (int)pl.party_size_max.Get()
            if (maxparty > 1)
               playlistsVecChecked.Push(playlistsVec.Get(i))
            end
         end
         playlistsNames := StringsVecToStepperList(playlistsVecChecked)
      end
      return playlistsNames
   end
   
   func GetIsWaiting() : bool
      var   screenStateVal : int = (int)screenState.Get()
      var   ret : bool = false
      
      if (screenStateVal == $uiEnums.LOBBY_SCREEN_STATE_PLAYLIST)
         ret := false
      end
      return ret
   end
   
   func UpdateFlowPanelVisible(_val : * = null)
      if (wgt != null)
         var pp : params
         pp.isVisible := (bool)isFlowPanelVisible.Get()
         wgt.GenerateEvent("#ShowHideFlowButtons", pp)
      end
   end
   
   func UpdateCloseBtnVisible(_val : * = null)
      if (wgt != null)
         var pp : params
         pp.isCloseVisible := (bool)isCloseBtnVisible.Get()
         wgt.GenerateEvent("#SetSlidingIsCloseVisible", pp)
      end
   end
      
   func UpdateIsLobbyMode(_val : * = null)
      if (wgt != null)
         var pp : params
         pp.isLobbyMode := (bool)isLobbyMode.Get()
         //wgt.GenerateEvent("#SetSlidingLobbyMode", pp)
      end      
   end
   
   func UpdateLobbyState(_val : *)
      UpdateLobbyStateInternal(false)
   end
   
   func GetStateNameStr() : string
      var ret              : string = "UNKNOWN"
      var screenStateVal   : int    = GetScreenStateVal()
      if (screenStateVal == $uiEnums.LOBBY_SCREEN_STATE_NONE)
         ret := "NONE"
      elif (screenStateVal == $uiEnums.LOBBY_SCREEN_STATE_PLAYLIST)
         ret := "PLAYLIST"
      elif (screenStateVal == $uiEnums.LOBBY_SCREEN_STATE_MATCHMAKING)
         ret := "MATCHMAKING"
      elif (screenStateVal == $uiEnums.LOBBY_SCREEN_STATE_VOTING)
         ret := "VOTING"
      elif (screenStateVal == $uiEnums.LOBBY_SCREEN_STATE_COUNTDOWN)
         ret := "COUNTDOWN"
      elif (screenStateVal == $uiEnums.LOBBY_SCREEN_STATE_WAITING_MM)
         ret := "WAITING MM"
      elif (screenStateVal == $uiEnums.LOBBY_SCREEN_STATE_WAITING_LOBBY)
         ret := "WAITING LOBBY"
      elif (screenStateVal == $uiEnums.LOBBY_SCREEN_STATE_LOBBY_JOINING_SESSION)
         ret := "JOINING SESSION"
      end
            
      return ret
   end
   
   func UpdateLobbyStateInternal(_forceUpdate : bool = false)      
      var isPlaylists      : bool   = false
      var isMapMode        : bool   = false
      var isVotingMaps     : bool   = false
      var isPlayers1       : bool   = true
      var isPlayers2       : bool   = true
      var isPlayers1Enable : bool   = true
      var isPlayers2Enable : bool   = true
      var isStartBtn       : bool   = false
      var isCloseBtn       : bool   = true
      var isCloseLobby     : bool   = false
      var isWaiting        : bool   = false
      var isFlowPanel      : bool   = true
      var isLobbyModeSet   : bool   = false
      var waitingTextSet   : string = ""
      var lobbyStateTxtSet : string = ""
      var skipUpdate       : bool   = false
      var screenStateSet   : int    = (int)screenState.Get()
      var isCountdownSet   : bool   = false
      
      var mmStateIdx    : int    = (int)$UiGlobals.matchmaking.state.Get()
      var lobbyStateIdx : int    = (int)$UiGlobals.lobby.state.Get()

      $root.UiLog("Lobby: screenState = " + GetStateNameStr())
      $root.UiLog("Lobby: mmState= " + $UiGlobals.matchmaking.GetStateStr() + ", LobbyState = " + $UiGlobals.lobby.GetStateStr())
      $UiBiLogger.LogLobbyState($UserDataStorage.local_user.IsPartyLeader(), $UiGlobals.matchmaking.GetStateStr(), $UiGlobals.lobby.GetStateStr())
      if (GetScreenStateVal() == $uiEnums.LOBBY_SCREEN_STATE_NONE)
      elif (GetScreenStateVal() == $uiEnums.LOBBY_SCREEN_STATE_PLAYLIST)
         isWaiting         := false
         isStartBtn        := true
         isCloseBtn        := true
         isFlowPanel       := false
         isMapMode         := true
         isLobbyModeSet    := false
         isPlayers1        := true
         isPlayers2        := true
         if (IsCustomGame())
            if ($UserDataStorage.local_user.IsPartyLeader())
               lobbyStateTxtSet  := "lobby_txt_select_map_mode"
            else
               lobbyStateTxtSet  := "lobby_voted_for_map_mode"
            end
            isPlaylists          := true
         else
            if ($UserDataStorage.local_user.IsPartyLeader())
               lobbyStateTxtSet  := "lobby_select_playlist"
               isPlaylists          := true
            else
               lobbyStateTxtSet  := "lobby_selected_playlist"
            end
         end
      else
         isLobbyModeSet    := true
         if (mmStateIdx == $uiEnums.MATCHMAKING_STATE_NONE)
            screenStateSet := $uiEnums.LOBBY_SCREEN_STATE_WAITING_MM
            isWaiting         := true
            //isStartCloseBtn   := true
            isMapMode         := true
            isCloseBtn        := true
            isCloseLobby      := true
         else          
            if (mmStateIdx == $uiEnums.MATCHMAKING_STATE_IN_SESSION and lobbyStateIdx != $uiEnums.LOBBY_STATE_NONE)
               if (lobbyStateIdx == $uiEnums.LOBBY_STATE_VOTING)
                  screenStateSet := $uiEnums.LOBBY_SCREEN_STATE_VOTING
                  isPlayers1        := true
                  isPlayers2        := true
                  isVotingMaps      := true
                  isCloseBtn        := false
                  isCloseLobby      := true
                  lobbyStateTxtSet  := "lobby_vote_for_map_mode"
                  $root.playSound("menu_game_start")
               elif (lobbyStateIdx == $uiEnums.LOBBY_STATE_GAME_START_COUNTDOWN)
                  screenStateSet := $uiEnums.LOBBY_SCREEN_STATE_COUNTDOWN
                  isPlayers1        := true
                  isPlayers2        := true
                  isMapMode         := true
                  isCloseBtn        := false
                  isCloseLobby      := true
                  isCountdownSet    := true
                  lobbyStateTxtSet  := "lobby_voted_for_map_mode"
               elif (lobbyStateIdx == $uiEnums.LOBBY_STATE_WAITING_FOR_VOTING_SET)
                  screenStateSet    := $uiEnums.LOBBY_SCREEN_STATE_LOBBY_JOINING_SESSION
                  isPlayers1        := true
                  isPlayers2        := true
                  isMapMode         := true
                  isCloseBtn        := false
                  isCloseLobby      := true
                  lobbyStateTxtSet  := "lobby_waiting_voting_set"
                  waitingTextSet    := "lobby_state_waiting_voting_set"
               elif (lobbyStateIdx == $uiEnums.LOBBY_STATE_JOINING_SESSION)
                  screenStateSet := $uiEnums.LOBBY_SCREEN_STATE_LOBBY_JOINING_SESSION
                  isPlayers1        := true
                  isPlayers2        := true
                  isWaiting         := true
                  isCloseBtn        := true
                  isCloseLobby      := true
                  isMapMode         := true
                  if (IsCustomGame())
                     lobbyStateTxtSet  := "lobby_voted_for_map_mode"
                  else
                     lobbyStateTxtSet  := "lobby_selected_playlist"
                  end
                  waitingTextSet    := "lobby_state_joining_session"
               else
                  //screenState.Set(SCREEN_STATE_WAITING_LOBBY)
                  isPlayers1        := true
                  isPlayers2        := true
                  isWaiting         := true
                  isCloseBtn        := true
                  isCloseLobby      := true
                  isMapMode         := true
                  if (IsCustomGame())
                     lobbyStateTxtSet  := "lobby_voted_for_map_mode"
                  else
                     lobbyStateTxtSet  := "lobby_selected_playlist"
                  end
                  waitingTextSet    := "lobby_state_waiting_for_players"
                  skipUpdate        := true
               end            
            else
               if (mmStateIdx == $uiEnums.MATCHMAKING_STATE_WAITING_FOR_ENQUEUE)
                  screenStateSet := $uiEnums.LOBBY_SCREEN_STATE_WAITING_MM
                  isWaiting         := true
                  isFlowPanel       := true
                  isCloseBtn        := true
                  isCloseLobby      := true
                  isMapMode         := true
                  if (IsCustomGame())
                     lobbyStateTxtSet  := "lobby_voted_for_map_mode"
                  else
                     lobbyStateTxtSet  := "lobby_selected_playlist"
                  end
                  waitingTextSet    := "lobby_mm_state_waiting_for_enqueue"                  
               elif (mmStateIdx == $uiEnums.MATCHMAKING_STATE_IN_QUEUE)
                  screenStateSet := $uiEnums.LOBBY_SCREEN_STATE_WAITING_MM
                  isWaiting         := true
                  isFlowPanel       := true
                  isCloseBtn        := true
                  isCloseLobby      := true
                  isMapMode         := true
                  if (IsCustomGame())
                     lobbyStateTxtSet  := "lobby_voted_for_map_mode"
                  else
                     lobbyStateTxtSet  := "lobby_selected_playlist"
                  end
                  waitingTextSet    := "lobby_mm_state_in_queue"                 
               end
            end
         end      
      end
                      
      $UiGlobals.isDockerEnabled.Set(GetScreenStateVal() == $uiEnums.LOBBY_SCREEN_STATE_PLAYLIST or GetScreenStateVal() == $uiEnums.LOBBY_SCREEN_STATE_NONE)
      
      
      
      $uiPartyMonitor.SetIsMatchCountdown(isCountdownSet)
      if (IsCustomGame())
         isPlaylistVisible.Set(false)
         var isLeader : bool = (bool)$UserDataStorage.local_user.isPartyLeader.Get()
         isGameModeVisible.Set(isPlaylists and isLeader)
         isGameMapVisible.Set(isPlaylists and isLeader)
         $root.UiLog("LobbyMaps: playlists = " + (string)isPlaylists + ", leader = " + (string)isLeader)
      else
         isPlaylistVisible.Set(isPlaylists)
         isGameModeVisible.Set(false)
         isGameMapVisible.Set(false)
         $root.UiLog("LobbyMaps: playlists = none")
      end
      if (! skipUpdate or _forceUpdate)
         isMapModeVisible.Set(isMapMode)
         isVotingMapsVisible.Set(isVotingMaps)
         isPlayers1Visible.Set(isPlayers1)
         isPlayers2Visible.Set(isPlayers2)
         isPlayers1Enabled.Set(isPlayers1Enable)
         isPlayers2Enabled.Set(isPlayers2Enable)
         isStartBtnVisible.Set(isStartBtn)
         isCloseBtnVisible.Set(isCloseBtn)

         isWaitingMode.Set(isWaiting)
         waitingText.Set(waitingTextSet)
         lobbyStateTxt.Set(lobbyStateTxtSet)
      
         isFlowPanelVisible.Set(isFlowPanel)
         UpdateFlowPanelVisible()
         UpdateCloseBtnVisible()
         UpdateMapMode()
         UpdateTeamMode()

         isLobbyMode.Set(isLobbyModeSet)
         UpdateIsLobbyMode()
         
         screenState.Set(screenStateSet)
         UpdatePlayerSelections()
      end                  
   end   
   
   func UpdateTeamMode(_val : * = null)
      if (wgt != null)
         wgt.SetTeamMode((bool)isTeamModeRoster.Get())
      end
   end
   
   func GetIsTeamModeRoster() : bool
      var ret : bool = false
      if (GetScreenStateVal() == $uiEnums.LOBBY_SCREEN_STATE_COUNTDOWN)
         ret := (bool)isTeamMode.Get()
      end
      //hack
      //ret := true
      return ret
   end
   
   func IsTeamModeAllowed() : bool
      var ret : bool = false
      if (GetScreenStateVal() == $uiEnums.LOBBY_SCREEN_STATE_COUNTDOWN)
         ret := true
      end
      return ret
   end
   
   func GetScreenStateVal() : int
      return (int)screenState.Get()
   end   
   
   func UpdateMapMode(_val : * = null)   
      if (GetScreenStateVal() == $uiEnums.LOBBY_SCREEN_STATE_PLAYLIST or GetScreenStateVal() == $uiEnums.LOBBY_SCREEN_STATE_WAITING_MM or GetScreenStateVal() == $uiEnums.LOBBY_SCREEN_STATE_LOBBY_JOINING_SESSION) 
         $root.UiLog("Lobby: updating map playlist")
         mapMode.isCustom.Set(IsCustomGame())
         mapMode.isMapMode.Set(false)
         mapMode.Invalidate()
      elif (GetScreenStateVal() == $uiEnums.LOBBY_SCREEN_STATE_COUNTDOWN)
         $root.UiLog("Lobby: updating map countdown")
         mapMode.isCustom.Set(IsCustomGame())
         mapMode.isMapMode.Set(true)
         mapMode.Invalidate()
      elif (GetScreenStateVal() != $uiEnums.LOBBY_SCREEN_STATE_NONE)
         $root.UiLog("Lobby: updating map")
         mapMode.isCustom.Set(IsCustomGame())
         mapMode.isMapMode.Set(true)
         mapMode.Invalidate()
      end
   end
   
   func ApplyCurrentPlaylist()
      var idx : int = (int)selectedPlaylistIdx.Get()
      if (idx >= 0 and idx < GetPlaylists().Count())
         $uiPartyMonitor.SetPlaylist(GetPlaylists().Get(idx).id)      
      end
      UpdateRosterLists()
   end

   func ApplyCustomMapMode()
   end
   
   func onRightBtnClicked(): bool
      if (GetScreenStateVal() == $uiEnums.LOBBY_SCREEN_STATE_PLAYLIST)
         var plComp = (GL_ComponentPlaylist)$UiGlobals.componentsPlaylist.Get(selectedPlaylist.Get())
         if internalPlayersParty.Count() > plComp.party_size_max.Get()
            var pp : params
            pp.mbType            := "Info"
            pp.titleTxt          := "msg_too_big_party_title"
            pp.messageTxt        := "msg_too_big_party_text"
            wgt.GenerateEvent("MainMenuDialogRequest", pp)
            return true
         end
         if (! IsCustomGame())
            ApplyCurrentPlaylist()
         end
         wgt.GenerateEvent("onMatchmakeGame")
         $root.playSound("menu_game_start")
      end
      return true
   end
   
   func OnPrepareLobbyScreen(p : params) : bool
      SetScreenActive(true)
      return true      
   end
   
   func OnHideLobbyScreen(p : params) : bool
      SetScreenActive(false)
      return true      
   end
   
   func GetLobbyPartyHelperText() : string
      var ret : string
      if ($uiPartyMonitor.IsPartyOwner())
         ret := "lobby_party_helper_text_owner"
      else
         ret := "lobby_party_helper_text"
      end
      return ret
   end
   
   func GetLobbyHeaderText() : string
      var ret : string
      if ($uiPartyMonitor.IsPartyOwner())
         ret := "lobby_game_lobby_header_owner"
      else
         ret := "lobby_game_lobby_header"
      end
      return ret
   end
end
