import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.game_preferences
import ssl.hf2p.hq

class UiAudio : UiWidgetContainer

var is_inited :  bool = false

func sliderMasterVolumeValueChanged(p: params): bool
   Log("ui~content", "sliderMasterVolumeValueChanged EVENT")
   Widgets().sliderMasterVolume.Props().tf2 := (string)((int)(Widgets().sliderMasterVolume.slider.value))
   $hf2pPreferences.SetMasterVolume((int)(Widgets().sliderMasterVolume.slider.value), false)
return false
end

func sliderSFXVolumeVolumeValueChanged(p: params): bool
   Widgets().sliderSFXVolume.Props().tf2 := (string)((int)(Widgets().sliderSFXVolume.slider.value))
   $hf2pPreferences.SetSFXVolume((int)(Widgets().sliderSFXVolume.slider.value), false)
return false
end

func sliderMusicVolumeValueChanged(p: params): bool
   Widgets().sliderMusicVolume.Props().tf2 := (string)((int)(Widgets().sliderMusicVolume.slider.value))
   $hf2pPreferences.SetMusicVolume((int)(Widgets().sliderMusicVolume.slider.value), false)

return false
end

func sliderVoiceVolumeValueChanged(p: params): bool
   Widgets().sliderVoiceVolume.Props().tf2 := (string)((int)(Widgets().sliderVoiceVolume.slider.value))
   $hf2pPreferences.SetVoiceVolume((int)(Widgets().sliderVoiceVolume.slider.value), false)

return false
end

func sliderVoiceChatVolumeValueChanged(p: params): bool
   Widgets().sliderVoiceChatVolume.Props().tf2 := (string)((int)(Widgets().sliderVoiceChatVolume.slider.value))
   $hf2pPreferences.SetVoiceChatVolume((int)(Widgets().sliderVoiceChatVolume.slider.value), false)

return false
end

func Init()
   is_inited := true
   Widgets().sliderMasterVolume.slider.value := (float)$hf2pPreferences.GetMasterVolume()
   Widgets().sliderSFXVolume.slider.value := (float)$hf2pPreferences.GetSFXVolume()
   Widgets().sliderMusicVolume.slider.value := (float)$hf2pPreferences.GetMusicVolume()
   //Widgets().sliderVoiceVolume.value := (float)$hf2pPreferences.GetVoiceVolume()
   var stepperElems :  vector
   stepperElems.Push("settings_push_to_talk")
   stepperElems.Push("settings_open_channel")
   Widgets().stepperVoiceChatControl.SetData(stepperElems)
   Widgets().stepperVoiceChatControl.selection := $hf2pPreferences.GetVoiceChatControl()
   Widgets().sliderVoiceChatVolume.slider.value := (float)$hf2pPreferences.GetVoiceChatVolume()
end

func HaveUnsavedChanges() :  bool
   var result : int = 0
   
   if (!is_inited)
      return false
   end

   result := result + (int)(Widgets().sliderMasterVolume.slider.value != (float)$hf2pPreferences.GetMasterVolume())
   result := result + (int)(Widgets().sliderSFXVolume.slider.value != (float)$hf2pPreferences.GetSFXVolume())
   result := result + (int)(Widgets().sliderMusicVolume.slider.value != (float)$hf2pPreferences.GetMusicVolume())
   result := result + (int)(Widgets().stepperVoiceChatControl.selection != $hf2pPreferences.GetVoiceChatControl())
   result := result + (int)(Widgets().sliderVoiceChatVolume.slider.value != (float)$hf2pPreferences.GetVoiceChatVolume())
   
   Log("ui~content", "audio changes = " + (string)(result > 0))
   
   return (result > 0)
end

func Reset()
   var settings : params = $hf2pPreferences.GetDefaultSoundSettings()

   Widgets().sliderMasterVolume.slider.value := settings.master_volume
   Widgets().sliderSFXVolume.slider.value := settings.sfx_volume
   Widgets().sliderMusicVolume.slider.value := settings.music_volume
   //Widgets().sliderVoiceVolume.value := 100
   Widgets().stepperVoiceChatControl.selection := settings.voice_chat_control
   Widgets().sliderVoiceChatVolume.slider.value := settings.voice_chat_volume
end

func Apply()
   if (!is_inited)
      return
   end
   
   $hf2pPreferences.SetMasterVolume((int)(Widgets().sliderMasterVolume.slider.value), true)
   $hf2pPreferences.SetSFXVolume((int)(Widgets().sliderSFXVolume.slider.value), true)
   $hf2pPreferences.SetMusicVolume((int)(Widgets().sliderMusicVolume.slider.value), true)
   //$hf2pPreferences.SetVoiceVolume((int)(Widgets().sliderVoiceVolume.value), true)
   $hf2pPreferences.SetVoiceChatControl((int)(Widgets().stepperVoiceChatControl.selection))
   $hf2pPreferences.SetVoiceChatVolume((int)(Widgets().sliderVoiceChatVolume.slider.value), true)
   GenerateEvent("OnApplyFinished")
end

handle OnEnteringState("Initial")
   //AddTween("alpha", 0.0, Props().adelay, "linear")
end          

handle OnEnterState("Initial")
   Set("visible", false)            
end  
        
handle OnEnteringState("Visible")
   Init()
   Set("visible", true)
   //AddTween("alpha", 1.0, Props().adelay, "linear")
end

handle OnLeavingState("Visible")
   Init()
   Apply()
end

func SwitchToScreen()
   Log("ui~content", "Audio setting SwitchSlide")
   Props().visible := true
end

func PrepareSlide()
   Log("ui~content", "Audio setting EnableSlide")
   if (GetStateName() != "Visible")
      SetStateName("Visible")
   end
   GenerateEvent("OnEnterNewTab")
   Props().visible := true
   
   StartDefaultBlinking(0.5, 1.0)
   
   var p: params
   p.state := "settings"
   GenerateEvent("ChangeFakeBackground", p)
end

func PrepareHideSlide()
end

func DisableSlide()
   if (GetStateName() != "Initial")
      Log("ui~content", "Audio setting DisableSlide")
      Props().visible := false
      SetStateName("Initial")
   end
end
end
