import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.engine_ctrl
import ssl.hf2p.items_mgr
import ui.root
import ui.ui_economy
import ssl.hf2p.user_service
 
class UiChallengeComplete : UiWidgetContainer

var   dialogTweenTime   : float = 0.5   
var   challengeId       : string = ""
var   reward            : vector

func ShowChallengeScr(p : params)
   if (GetStateName() != "AnimIn")
      Props().visible := true
      Props().mouseChildren := true
      if (! IsVoid(p.challengeId))
         challengeId := p.challengeId
      end
      if (! IsVoid(p.reward))
         reward := p.reward
      end
      SetStateName("AnimIn")
   end
end

func onChallengeCompleteBtnClick(p : params) :  bool
   SetStateName("AnimOut")
   return false
end

handle OnEnteringState("Initial")                  
   Props().visible := false
end

handle OnEnteringState("AnimIn")
   AnimInBg()
   var p : params
   p.challengeId := challengeId
   p.rewards := reward
   GenerateEvent("#SetChallengeData", p)
end

handle OnEnterState("AnimIn")
   SetStateName("AnimOut") : 2
end

handle OnEnterState("AnimOut")
   $UiGlobals.notifications.MarkProcessedFirstByType($uiEnums.NOTIFICATION_CHALLENGE_COMPLETE)
   if (!$root.CheckAllNotifications())
      GenerateEvent("RewardBoxAnimFinished")
   end
   SetStateName("Initial")
end

func AnimInBg()
   Widgets().victoryAttach.bgChallengeAnim.GotoAndPlay("animIn")
end

func AddDialogTween(_start: float, _end: float)
   var tweenParm:params
   tweenParm.propName   := "dialogTweenParm"
   tweenParm.startVal   := _start      
   tweenParm.endVal     := _end
   tweenParm.duration   := dialogTweenTime
   tweenParm.fadeType   := "linear"
   Props().alpha        := _start
   AddTweenCb("DialogTween", tweenParm) 
end

func DialogTween(updType:string)
   var dialogTweenParm  : float = (float)(Props().dialogTweenParm)
   Props().alpha := dialogTweenParm
   if (dialogTweenParm > 0)
      Props().visible := true
   else
      Props().visible := false
   end

   var pp : params       
   dialogTweenParm := dialogTweenParm / 100.0
   pp.dialogTweenParm := dialogTweenParm
   GenerateEvent("DialogShowTween", pp)
end

end

class UiChallengeCompleteBoxVM
   
   var reward              : msgBoxRewardContVM  = new msgBoxRewardContVM()
   var challengeId         : ObservableProperty    = $OM.Property("")
   var challengeRewards    : ObservableProperty    = $OM.Property(new vector)
   var challengeName       : ObservableProperty = $OM.Calculated(this, "GetChallengeName")
   var challengeDesc       : ObservableProperty = $OM.Calculated(this, "GetChallengeDesc")
   var challengeIcon       : ObservableProperty = $OM.Calculated(this, "GetChallengeIcon")
   var containerFrame      : ObservableProperty = $OM.Calculated(this, "GetRewardsFrame")
   
   func SetChallengeData(p : params) : bool
      challengeId.Set((string)p.challengeId)
      challengeRewards.Set(p.rewards)
      challengeName.Invalidate()
      challengeDesc.Invalidate()
      challengeIcon.Invalidate()
      containerFrame.Invalidate()
      SetRewards()
      return true
   end
   
   func SetRewards()
      var rewardVec : vector = challengeRewards.Get()
      reward.rewardsVec.Set(rewardVec)
   end
   
   func GetChallengeIcon() : string
      var uiComp  : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get((string)challengeId.Get())
      var ret     : string          = (string)uiComp.icon.Get()
      return ret
   end
   
   func GetChallengeName() : string
      var uiComp  : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get((string)challengeId.Get())
      var ret     : string          = (string)uiComp.name.Get()
      return ret
   end
   
   func GetChallengeDesc() : string
      var uiComp  : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get((string)challengeId.Get())
      var ret     : string          = (string)uiComp.desc.Get()
      return ret
   end
   
   func GetRewardsFrame() : string
      var ret : string = "zero"
      var rewardsVec : vector = challengeRewards.Get()
      var count : int = rewardsVec.Count()
      if (count == 0)
         ret := "zero"
      elif (count == 1)
         ret := "one"
      elif (count == 2)
         ret := "two"
      else if (count >= 3)
         ret := "three"
      end
      return ret
   end
   
   func GetChallengeRewardTxt() : string
      var uiComp  : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get((string)challengeId.Get())
      var ret     : string          = " "
      return ret
   end
   
end

class msgBoxRewardContVM
   
   var rewardsVec       : ObservableProperty    = $OM.Property(new vector)
   var rewardId         : ObservableProperty    = $OM.Property("")
   var rewardValue      : ObservableProperty    = $OM.Property(0)
   
   func GetRewardId(idx : int) : string
      var ret : string= ""
      var rewardVec : vector = rewardsVec.Get()
      if (rewardVec.Count() > idx)
         ret := (string)rewardVec.Get(idx).name.Get()
      end
      return ret
   end
   
   func GetRewardValue(idx : int) : string
      var ret : string = "+"
      var val : int = 0
      var rewardVec : vector = rewardsVec.Get()
      if (rewardVec.Count() > idx)
         if ($uiEconomy.GetItemType(GetRewardId(idx)) == $uiEnums.ITEM_TYPE_TOKEN)
            val := $UiGlobals.Int64ToInt(rewardVec.Get(idx).value.Get())
         end   
      end
      return ret + val
   end
   
   func TokenFrame(idx : int) : string
      var ret : string
      ret := $UiGlobals.GetTokenFrame(GetRewardId(idx))
      return ret
   end
   
   func ShowTokenBox(idx : int) : bool
      var ret : bool = false
      if ($uiEconomy.GetItemType(GetRewardId(idx)) == $uiEnums.ITEM_TYPE_TOKEN)
         ret := true
      end
      return ret
   end
   
   func GetRewardLabel(idx : int) : string
      var uiComp  : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(GetRewardId(idx))
      var ret     : string
      if ($uiEconomy.GetItemType(GetRewardId(idx)) != $uiEnums.ITEM_TYPE_TOKEN)
         ret := (string)uiComp.name.Get()
      end   
      return ret
   end

   func GetRewardIcon(idx : int) : string
      var uiComp  : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(GetRewardId(idx))
      var ret : string
      if ($uiEconomy.GetItemType(GetRewardId(idx)) != $uiEnums.ITEM_TYPE_TOKEN)
         ret := (string)uiComp.icon.Get()
      end
      return ret
   end
   
end