import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.engine_ctrl
import ui.ui_party_monitor

class UiClientServerlist : UiWidgetContainer

var doUpdates: bool = false
var hostList : vector

func StartUpdates()
   doUpdates := true
   populateList()
end

func FinishUpdates()
   doUpdates := false
end

func populateList()
   Log("ui~client_serverlist", "LP::SERVERLIST::populateList()")
   if (! doUpdates)
      return
   end
   var i:int
   var ListVector: vector
   for i := 0 to hostList.Count() - 1
       
      var ListEntry:params
      var host: params = hostList.Get(i)
      ListEntry.text          := host.party_leader_name  // + " / " + host.party_leader_name
      ListEntry.type          := 0
      ListEntry.optionIndex	:= i*10 //host.squad_index         
      Log("ui~client_serverlist", "LP::SERVERLIST add item " + Params2Str(ListEntry))
      ListVector.Push(ListEntry)
   end

   Widgets().list.SetData(ListVector)
   populateList(): 3
end         
      
func onServerListItemSelected(p:params):bool
   if (GetStateName() != "Active" or $uiPartyMonitor.IsJoiningSquad())
      return false
   end
   
   Log("ui~client_serverlist", "LP::SERVERLIST::onServerListItemSelected() " + Params2Str(p))
   FinishUpdates()      
   if (p.index < hostList.Count())
      EnableListInput(false)
      $uiPartyMonitor.JoinSquad(hostList.Get(p.index).squad_index)
   else
      Log("ui~client_serverlist", "LP::SERVERLIST::onServerListItemSelected() - wrongIdx" + p.index)
   end
   return true
end

handle OnEnterState("Active")
   Log("ui~client_serverlist", "LP::SERVERLIST::Active: Enter")
   StartUpdates()
   EnableListInput(true)
end

handle OnExitState("Active")
   Log("ui~client_serverlist", "LP::SERVERLIST::Active: Leaving")
   FinishUpdates()
end      

func EnableListInput(_isInputEnabled: bool)
   Widgets().list.mouseEnabled    := _isInputEnabled
   Widgets().list.mouseChildren   := _isInputEnabled
end

func JoinHostFinished(p:params):bool
   EnableListInput(true)
   return true
end
end
