import ssl.lib.logging
import ssl.lib.types
import ssl.lib.objects
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.engine_ctrl
import ssl.hf2p.items_mgr
//import ssl.hf2p.title_storage
import ssl.hf2p.hq
import ui.ui_economy
import ui.ui_party_monitor
import ui.ui_matchmaking
import ui.ui_player_info
import ssl.lib.ui.ui_frame_mgr
import ssl.hf2p.user_data
import ssl.lib.ui.ui_widget_manager
import ui.roots.hf2p_main_menu_screen

class Root : UiFrameMgr

var mainMenu                     : UiHf2pMainMenu  = null
var isAcceptionErrors            : bool            = false
var pregameLevel                 : int    = 0
var pregameLevelProgress         : float  = 0.0
var pregameLevelId               : string = null
var pregameLevelNextId           : string = null
var pregameCredit                : int    = 0

var ui_sounds                    : psSECTION
var ui_damage_types              : psARRAY

var ui_tutorialStage             : int    = 0
var isSubscribedToSessionState   : bool   = false
var isConsoleEnabled             : bool = false

var isSpartanShop                : bool   = false

func StartAcceptingErrors()
   isAcceptionErrors := true
end

func StopAcceptingErrors()
   isAcceptionErrors := false
end

func IsAcceptingErrors() : bool
   return isAcceptionErrors
end

func GetTutorialState(): int
   return ui_tutorialStage
end

func SetTutorialState(_stage: int)
   ui_tutorialStage := _stage
end

func SetMainMenu(_mainMenu : UiHf2pMainMenu)
   mainMenu := _mainMenu
end

func GetMainMenu() :  UiHf2pMainMenu
   return mainMenu
end

handle OnInit
   isConsoleEnabled := (bool)($sslOptionsSys.GetVariable("Debug.EnableConsole"))
   
   ui_init_enums()
   ui_init_matchmaking()
   ui_init_economy()
   ui_init_player_info()
   ui_init_party_monitor()
   $uiPlayerInfo.Init()
   
   // TODO: Oleg. Remove LOG
   Log("ui~Root", "*** ROOT *** : OnInit()")
   ui_sounds         := GetData("ui_sounds").ui_sounds
   ui_damage_types   := GetData("ui_damage_types").ui_damage_types.ui_damage_types
   
end

handle OnTerm
   Hide("in_game_menu")
   Hide("menu_manager_as3")
   BackendConnectDisconnect($uiEnums.BACKEND_SESSION_OFFLINE)
   UnsubscribeFromSessionState()
   ui_term_matchmaking()
   ui_term_economy()
   ui_term_player_info()
   ui_term_party_monitor()   
   ui_term_enums()
end

func SubscribeToSessionState()
   if (! isSubscribedToSessionState)
      $UiGlobals.backend_session.state.Subscribe(this, "UpdateSessionState")
      $UiGlobals.party.state.Subscribe(this, "UpdatePartyState")
      isSubscribedToSessionState := true
   end
end

func UnsubscribeFromSessionState()
   if (isSubscribedToSessionState)
      $UiGlobals.party.state.Unsubscribe(this, "UpdatePartyState")
      $UiGlobals.backend_session.state.Unsubscribe(this, "UpdateSessionState")
      isSubscribedToSessionState := false
   end
end

func RecreateUiObjects()
   ui_recreate_enums()
   ui_recreate_matchmaking()
   ui_recreate_economy()
   ui_recreate_player_info()
   ui_recreate_party_monitor()
end

var gMainMenuState            : string    = "WELCOME_SCREEN"
var mainStartState            : string    = ""
var activeWidget              : string    = "MAINMENU"

func BackendConnectDisconnect(_connectionState : int)
   if (_connectionState == $uiEnums.BACKEND_SESSION_ONLINE)
      $UiGlobals.async_operations.BackendConnect()
      $UiGlobals.backend_requests.BackendConnect()
   else
      $UiGlobals.async_operations.BackendDisconnect()
      $UiGlobals.backend_requests.BackendDisconnect()
   end
end

func UpdateSessionState()
   BackendConnectDisconnect((int)$UiGlobals.backend_session.state.Get())
   $sslWidgetMgr.GenerateEvent("UpdateBackendSessionState")
end

func UpdatePartyState()
   $sslWidgetMgr.GenerateEvent("UpdatePartyState")
end

func GetMainStartState(): string
   return mainStartState
end

func SetMainStartState(_state: string)
   mainStartState := _state
end

func GetMainMenuState(): string
   return gMainMenuState
end

func SetMainMenuState(state : string)
   gMainMenuState := state
end

func GetIsDisconnect() : bool
   var backendSessionState : int = (int)$UiGlobals.backend_session.state.Get()
   var ret                 : bool = backendSessionState != $uiEnums.BACKEND_SESSION_ONLINE
   return ret
end

global event onHaloDisposeFromOldMap()
   $hq.SetCanRender(false)
   $sslWidgetMgr.GenerateEvent("HaloDisposeFromOldMap")
   gMainMenuState := "REMATCH"
   Reset()
   ForceUpdate(0)
end

func ReloadWidgets(_activeWidget : string)
   Hide("menu_manager_as3")
   activeWidget := _activeWidget
   Show("menu_manager_as3")   
end

global event OnLevelLoaded(state : int)
   $hf2pEngine.SuppressIngameInput(true)
   $hf2pEngine.InitUIScreenSounds()
   $hq.SetCanRender(true)
   SetMainStartState("Welcome")
   ReloadWidgets("MAINMENU")
end

global event OnIngameLevelLoaded(state : int)
   //$hf2pEngine.SuppressIngameInput(false)
   $root.pregameLevel := (int)$UserDataStorage.local_user.level.Get()
   $root.pregameLevelProgress := (float)$UserDataStorage.local_user.level_progress.Get()
   $root.pregameLevelId := (string)$UserDataStorage.local_user.level_id.Get()
   $root.pregameLevelNextId := (string)$UserDataStorage.local_user.level_next_id.Get()
   $root.pregameCredit := (int)$UserDataStorage.local_user.cr.Get()
   
   $hf2pEngine.TermUIScreenSounds()
   $hq.SetCanRender(false)
   $uiPartyMonitor.SetIsLeavedGame(false)
   ReloadWidgets("INGAME")
end

func CheckAllNotifications() : bool
   var ret  : bool = CheckLevelUp()
   if (!ret) 
      ret := CheckItemUnlocks()
   end
   if (!ret)
      ret := CheckChallengeUnlocks()
   end
   return ret
end

func CheckLevelUp() : bool
   var ret : bool = false
   var lastNotif : NT_Notification = $UiGlobals.notifications.GetFirstUnprocessedByType($uiEnums.NOTIFICATION_SESSION_LVLUP)
   var p : params
   if (lastNotif != null)
      var lvlUp : NT_LevelUp = (NT_LevelUp)$UiGlobals.notifications.GetNotifDetails(lastNotif)
      var levelId : string = (string)lvlUp.level_id.Get()
      var levelIdPrev : string = (string)lvlUp.level_previous.Get()
      var level : int =  (int)lvlUp.level.Get()
      var levelPrev : int = (int)lvlUp.level_previous.Get()
      var levelPromo : bool = (bool)lvlUp.is_special_promotion.Get()
      var levelUnlockItemsVec : vector = lvlUp.level_up_rewards.Get() // count
      p.rewardType     := "lvlUp"
      //p.showInPm       := showPm
      p.levelName      := levelId
      p.levelNamePrev  := levelIdPrev
      p.level          := level  
      p.levelPrev      := levelPrev
      p.levelPromo     := levelPromo
      p.lvlRewards     := levelUnlockItemsVec
      $sslWidgetMgr.GenerateEvent("RewardRequest", p)
      ret := true
   end   
   return ret
end   

func CheckItemUnlocks() : bool
   var ret : bool = false
   var lastNotif : NT_Notification = $UiGlobals.notifications.GetFirstUnprocessedByType($uiEnums.NOTIFICATION_SESSION_UNLOCK)
   var p : params
   if (lastNotif != null)
      var itemUnlocks : NT_NewItemsAvailable = (NT_NewItemsAvailable)$UiGlobals.notifications.GetNotifDetails(lastNotif)
      var unlockItemsVec : vector = itemUnlocks.new_items.Get()
      p.rewardType     := "itemUnlock"
      //p.showInPm       := showPm
      if (unlockItemsVec.Count() > 0)
         p.unlcItemsVec := unlockItemsVec
         $sslWidgetMgr.GenerateEvent("RewardRequest", p)
         ret := true
      end   
   end   
   return ret
end 

func CheckChallengeUnlocks() : bool
   var ret : bool = false
   var lastNotif : NT_Notification = $UiGlobals.notifications.GetFirstUnprocessedByType($uiEnums.NOTIFICATION_CHALLENGE_COMPLETE)
   var p : params
   if (lastNotif != null)
      var challengeComplete : NT_ChallengeComplete = (NT_ChallengeComplete)$UiGlobals.notifications.GetNotifDetails(lastNotif)
      p.challengeId := (string)challengeComplete.challenge_id.Get()
      p.reward := challengeComplete.rewards_tokens.Get()
      $sslWidgetMgr.GenerateEvent("ChallengeCompleteRequest", p)
      ret := true
   end   
   return ret
end

func uiPlaySound(snd : int)
	$hf2pEngine.PlaySound(snd)
end

var disabledSounds: params
global event playSound(id:string, section: string = "menu")
// scrolling list events: focusIn, focusOut, select, change, rollOver, rollOut, itemClick, itemDoubleClick, itemPress, itemRollOver, itemRollOut
// button events: focusIn, focusOut, select, rollOver, rollOut, press, doubleClick, click
//???msgbox events?
   var snd: * = ui_sounds.Get(section).Get(id) 
   if(!IsVoid(snd))
      if(IsVoid(disabledSounds.Get(snd)))
         Log("ui~Root", "->playSound(" + id + " -> " + snd + ")")
        // $music.PlaySound(snd)
 	     uiPlaySound((int)(snd))
      else
         Log("ui~Root", "->playSound(" + id + " -> " + snd + "(disabled))")
      end
   else
      Log("ui~Root", "->playSound(" + id + " -> " + snd + ")")
   end
end

global event stopSound(id: string, section: string = "menu")
   var snd: * = ui_sounds.Get(section).Get(id) 
   if(!IsVoid(snd))      
 	   $hf2pEngine.StopSound((int)(snd))
   else
      Log("ui~Root", "->stopSound(" + id + " -> " + snd + ")")
   end   
end
      
func RGB2Clr(r:int, g:int, b:int, a:int = 255): int
   var ret: int = r * 65536 + g * 256 + b
   return ret
end   
   
func GetDamageIcon(_damageType: int): string
   var ret : string = "__EMPTY__"
   if (_damageType >= 0 and _damageType < ui_damage_types.Count())
      ret := ui_damage_types.Get(_damageType).icon
   end
   return ret
end

func GetDamageDesc(_damageType: int): string
   var ret : string = ""
   if (_damageType >= 0 and _damageType < ui_damage_types.Count())
      ret := ui_damage_types.Get(_damageType).desc
   end
   return ret
end

func GetDamageName(_damageType: int): string
   var ret : string = ""
   if (_damageType >= 0 and _damageType < ui_damage_types.Count())
      ret := ui_damage_types.Get(_damageType).name
   end
   return ret
end

func GetItemIcon(_itemID: string, _isSmall:bool = false): string
   return GetItemIconAndScale(_itemID, _isSmall).iconName
end


func GetItemIconAndScale(_itemID: string, _isSmall:bool = false): params
   Log("ui~Root", "GetItemIconAndScale " + _itemID)
   var   ret      : params   
   ret.scale      := 1.0      
   ret.iconName   := ""

   if (_itemID != "")
      var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(_itemID)
      ret.scale := 1.0      
      if (_isSmall)
         ret.iconName   := (string)compUI.icon.Get()
      else
         ret.iconName   := (string)compUI.icon_big.Get()
      end
      
      if ($uiEconomy.IsItemWeapon(_itemID))
         if (_isSmall)
            ret.scale := 0.5
         else
            ret.scale := 3.5
         end
      elif ($uiEconomy.IsItemArmor(_itemID))
         ret.scale := 1.0
      else
         if (_isSmall)
            ret.scale := 0.7
         else
            ret.scale := 3.5
         end
      end
   end
   return ret
end

func MakeUiTimerString(t: int, _expiringTxt : bool = false, _showSeconds : bool = true): string   
   var ret : string = ""
   if (t > 0)
      var fullDays    : int = t / 60 / 60 / 24
      var fullHours   : int = t / 60 / 60 % 24
      var fullMinutes : int = t / 60 % 60
      var fullSeconds : int = t % 60
      if fullDays > 0 and fullSeconds + fullMinutes + fullHours > 0
         fullDays := fullDays + 1
      end
      if fullHours > 0 and fullSeconds + fullMinutes > 0
         fullHours := fullHours + 1
      end
      if fullMinutes > 0 and fullSeconds > 0
         fullMinutes := fullMinutes + 1
      end
      if fullDays > 0
         var label = "carousel_rent_time_day,"
         if fullDays > 1
            label := "carousel_rent_time_days,"
         end
         ret := label + (string)fullDays
      elif fullHours > 0
         var label = "carousel_rent_time_hour,"
         if fullHours > 1
            label := "carousel_rent_time_hours,"
         end
         ret := label + (string)fullHours
      elif fullMinutes > 0
         var label = "carousel_rent_time_minute,"
         if fullMinutes > 1
            label := "carousel_rent_time_minutes,"
         end
         ret := label + (string)fullMinutes
      elif fullSeconds > 0
         var label = "carousel_rent_time_second,"
         if fullSeconds > 1
            label := "carousel_rent_time_seconds,"
         end
         ret := label + (string)fullSeconds
      else
         ret := ""
      end
   else
      if (_expiringTxt)
         ret := "carousel_rent_time_expiring"
      else 
         ret := "0"
      end
   end   
   
   return ret
end

func MakeUiTimerStringMinutes(t: int, _expiringTxt : bool = false): string 
   return MakeUiTimerString(t, _expiringTxt, false)
end

func MakeUiTimerSubHead(t : int) : wstring
   var p : params
   var ret :  wstring
   if (MakeUiTimerStringMinutes(t) == "0")
      ret := $UiGlobals.String2WString("carousel_rent_time_expiring")
   else
      p.str1 := $UiGlobals.String2WString("carousel_rent_time_subheader,")
      p.str2 := $UiGlobals.TranslateText(MakeUiTimerStringMinutes(t))
      ret := p.str1 + p.str2 
   end
   return ret
end

func RestoreModelPermutations()
   $hq.ShowroomEnd()
   $hq.isInShowroom := false
end

func Float2Str2Dec(_val : float) : string
   var ret  : string 
   var v1   : int = (int)_val
   var v2   : int = (int)((_val - v1) * 100)
   ret := ((string)v1) + "." + ((string)v2)
   return ret
end

func MakeColorCodedText(_text : string, _colorCode : string) : string
   var ret : string = ""
   if (_text != "")
      ret := "<FONT COLOR=\"" + _colorCode + "\">" + _text + "</FONT>"
   end
   return ret
end

func MakeColorCodedWText(_text : *, _colorCode : string) : wstring
   var ret : wstring
   if (_text != "")
      var p : params
      p.tag1   := $UiGlobals.String2WString("<FONT COLOR=\"")
      p.color  := $UiGlobals.String2WString(_colorCode)
      p.tag2   := $UiGlobals.String2WString("\">")
      p.text   := _text
      p.tag3   := $UiGlobals.String2WString("</FONT>")
      
      ret := ret + p.tag1
      ret := ret + p.color
      ret := ret + p.tag2
      ret := ret + p.text
      ret := ret + p.tag3
   end
   return ret
end

func MakeLinkWText(_text : *, _linkName : string, _colorCode : string) : wstring
   var ret : wstring
   if (_text != "")
      var p : params
      if (_colorCode != "")
         p.prefix  := $UiGlobals.String2WString("<span class=\"" + _colorCode + "\"><a href=\"event:" + _linkName + "\">")
         p.text    := _text
         p.postfix := $UiGlobals.String2WString("</a></span>")
      else
         p.prefix  := $UiGlobals.String2WString("<span><a href=\"event:" + _linkName + "\">")
         p.text    := _text
         p.postfix := $UiGlobals.String2WString("</a></span>")
      end
      ret := ret + p.prefix
      ret := ret + p.text
      ret := ret + p.postfix
   end
   return ret
end

func UiLog(_str : string)
   if (isConsoleEnabled)
      var p : params
      p.str := _str
      $sslWidgetMgr.GenerateEvent("AddDebugPanelString", p)
   end
end

func DefMessageBox(_mbType : string, _header : string, _message : string, _event : string = "", _callbackTarget : * = null)
   var pp : params
   pp.titleTxt          := _header
   pp.messageTxt        := _message
   if (_event != "")
      pp.callbackEvent  := _event
   end
   if (_callbackTarget != null)
      pp.callbacktarget := _callbackTarget
   end
   pp.mbType            := _mbType
   $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", pp)
end

func sqrt(_val : float) : float
   var ret : float = _val / 2
   if (ret != 0)
      ret := 0.5 * (_val / ret + ret)
   end
   if (ret != 0)
      ret := 0.5 * (_val / ret + ret)
   end
   if (ret != 0)
      ret := 0.5 * (_val / ret + ret)
   end
   if (ret != 0)
      ret := 0.5 * (_val / ret + ret)
   end
   return ret
end

func FormatFloat(val : float, decimals : int) : string
   var ret : string
   ret := (string)(int)val
   var dec : vector
   var i : int
   var x : float = val
   for i := 0 to decimals - 1
      x := x * 10
      dec.Push(((int)x) % 10)
   end
   var zero : int = 0
   for i := decimals - 1 downto 0
      if dec.Get(i) != 0
         break
      end
      zero := zero + 1
   end
   if zero != decimals
      ret := ret + "."
      for i := 0 to decimals - zero - 1
         ret := ret + (string)dec.Get(i)
      end
   end
   return ret
end

func FormatArmorModifTempHack(_modifId : string, _val : float) : wstring
   var ret  : wstring
   var sign : string = "+"
   var val  : float  = _val
   var modifComp = (GL_ComponentGameplayModifier)$UiGlobals.componentsGameplayModifier.Get(_modifId) 
   var unit : string =(string)modifComp.units_id.Get()
   //var modifUiComp = (GL_ComponentUI)$UiGlobals.componentsUI.Get(unit)
   if val < 0
      sign := "-"
      val := -val
   end
   if (unit == "mod_unit_percent") 
      ret := $UiGlobals.TranslateText(unit + "," + sign + (string)(int)(val * 100 + 0.01))
   elif (unit == "mod_unit_meters")
      ret := $UiGlobals.TranslateText(unit + "," + sign + FormatFloat(val + 0.001, 2))
   elif (unit == "mod_unit_bool")
      ret := $UiGlobals.TranslateText(unit + "," + " ")
   elif (unit == "mod_unit_seconds")
      ret := $UiGlobals.TranslateText(unit + "," + sign + FormatFloat(val + 0.001, 2))
   elif (unit == "mod_unit_abs")
      ret := $UiGlobals.TranslateText(unit + "," + sign + (string)(int)(val + 0.01))
   elif (unit == "mod_unit_chance")
      ret := $UiGlobals.TranslateText(unit + "," + sign + (string)(int)(val * 100 + 0.01))
   end
   return ret
end

func MakeStringUntranslatable(str : *) : *
   var p : params
   p.str    := str
   p.tilde  := $UiGlobals.String2WString("~")
   p.ret    := p.str
   p.ret    := p.ret + p.tilde
   return p.ret
end

end // end of Root : UiFrameMgr
var $root : Root
