import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.engine_ctrl
import ssl.hf2p.items_mgr
import ssl.hf2p.user_service
import ui.root
import ui.ui_economy
import ssl.lib.objects
import ssl.hf2p.user_data

class UiPlayerInfo


var   armorLoadouts        :  vector
var   curArmorLoadoutIdx   :  int      = 0
var   isUpdatingCashGl     :  bool     = false
var   isUpdatingCashCr     :  bool     = false

func Init()
   var defEquip: params = GetDefaultLoadout()
   
   armorLoadouts.Clear()
   /*armorLoadouts.Push(GetBackendLoadoutParams(0))
   armorLoadouts.Push(GetBackendLoadoutParams(1))
   armorLoadouts.Push(GetBackendLoadoutParams(2))
   armorLoadouts.Push(GetBackendLoadoutParams(3))
   armorLoadouts.Push(GetBackendLoadoutParams(4))
   var ud : UserData = (UserData)$UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
   curArmorLoadoutIdx := (int)ud.armor_loadouts.spartan.active_loadout_index.Get()
   */
   armorLoadouts.Push(defEquip.Clone())
   armorLoadouts.Push(defEquip.Clone())
   armorLoadouts.Push(defEquip.Clone())
   armorLoadouts.Push(defEquip.Clone())
   armorLoadouts.Push(defEquip.Clone())
end

func GetBackendLoadout(_loadoutIdx : int) :  UD_ArmorLoadout
   var ud : UserData = (UserData)$UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
   var loadout : UD_ArmorLoadout = (UD_ArmorLoadout)(ud.armor_loadouts.spartan.loadouts.Get().Get((int)ud.armor_loadouts.spartan.active_loadout_index.Get()))
   return loadout   
end

func GetBackendLoadoutParams(_loadoutIdx : int) : params
   var loadout    : UD_ArmorLoadout = GetBackendLoadout(_loadoutIdx)
   var ret        : params
   ret.helmet     := loadout.head_armor.Get()
   ret.chest      := loadout.torso_armor.Get()
   ret.arms       := loadout.hands_armor.Get()
   ret.legs       := loadout.legs_armor.Get()
   ret.shoulder   := loadout.shoulders_armor.Get()
   return ret
end
   
func GetIsUpdatingCashGl(): bool
   return isUpdatingCashGl
end

func SetIsUpdatingCashGl(_isUpdatingCashGl : bool)
   isUpdatingCashGl := _isUpdatingCashGl
end

func GetIsUpdatingCashCr(): bool
   return isUpdatingCashCr
end

func SetIsUpdatingCashCr(_isUpdatingCashCr : bool)
   isUpdatingCashCr := _isUpdatingCashCr
end

func GetArmorLoadout(_idx: int): params
   return GetBackendLoadoutParams(_idx)
end

func GetCurArmorLoadout(): params
   return GetArmorLoadout(curArmorLoadoutIdx)
end

func GetEquippedLoadout(): params
   var ud : UserData = (UserData)$UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get())
   var idx := (int)ud.armor_loadouts.spartan.active_loadout_index.Get()
   return GetBackendLoadoutParams(idx)
end

func GetDefaultLoadout(): params
   var ret: params
   ret.helmet     := "helmet_01"
   ret.chest      := "chest_01"
   ret.shoulder   := "shoulder_01"
   ret.arms       := "arms_01"
   ret.legs       := "legs_01"
   return ret
end

func InitFromEquipped(_idx: int = -1)
   if (_idx == -1)
      Init()
      InitFromEquipped(0)
      //InitFromEquipped(1)
      //InitFromEquipped(2)
      //InitFromEquipped(3)
      //InitFromEquipped(4)
   else
      var curEquip: params = GetEquippedLoadout()
      armorLoadouts.Set(_idx, curEquip)
   end
end

func InitFromCurentEquipped()
   InitFromEquipped(curArmorLoadoutIdx)
end

func AssignItem2Loadout(_loadoutIdx: int, _itemId: string, _skipUpdate: bool = false)
   if ($uiEconomy.GetItemType(_itemId) == $uiEnums.ITEM_TYPE_ARMOR_SUIT)
      $user_service.SetLoadout(_loadoutIdx, _itemId)
   else
      $user_service.SetArmorLoadoutItem($hf2pEngine.GetUIPlayerModelId(), _loadoutIdx, _itemId)
   end
end

func AssignItem2CurrentLoadout(_itemId: string)
   AssignItem2Loadout(curArmorLoadoutIdx, _itemId)
end

func GetLevel() : int
   return (int)$UserDataStorage.local_user.level.Get()
end

func GetItemEquipStateInLoadout(_itemId : string, _loadoutIdx : int) : int
   var ret        : int = $uiEnums.CHALLENGE_ITEM_STATE_NOT_EQUIPPED
   var itemType   : int = $uiEconomy.GetItemType(_itemId)
   if (itemType == $uiEnums.ITEM_TYPE_ARMOR)
      var armorComp : GL_ComponentArmor = (GL_ComponentArmor)$UiGlobals.componentsArmor.Get(_itemId)
      ret := armorComp.GetEquipState(_loadoutIdx)
   elif (itemType == $uiEnums.ITEM_TYPE_ARMOR_SUIT)
      var armorComp : GL_ComponentArmorSuit = (GL_ComponentArmorSuit)$UiGlobals.componentsArmorSuit.Get(_itemId)
      ret := armorComp.GetEquipState(_loadoutIdx)
   else
      var loadout : UD_WeaponLoadout = $UserDataStorage.local_user.GetWeaponLoadout(_loadoutIdx)
      if (loadout != null)
         if (_itemId == (string)loadout.primary_weapon.Get())
            ret := $uiEnums.CHALLENGE_ITEM_STATE_EQUIPPED
         elif (_itemId == (string)loadout.secondary_weapon.Get())
            ret := $uiEnums.CHALLENGE_ITEM_STATE_EQUIPPED
         elif (_itemId == (string)loadout.grenades.Get())
            ret := $uiEnums.CHALLENGE_ITEM_STATE_EQUIPPED
         elif (_itemId == (string)loadout.consumable_first.Get())
            ret := $uiEnums.CHALLENGE_ITEM_STATE_EQUIPPED
         elif (_itemId == (string)loadout.consumable_second.Get())
            ret := $uiEnums.CHALLENGE_ITEM_STATE_EQUIPPED
         elif (_itemId == (string)loadout.consumable_third.Get())
            ret := $uiEnums.CHALLENGE_ITEM_STATE_EQUIPPED
         elif (_itemId == (string)loadout.consumable_fourth.Get())
            ret := $uiEnums.CHALLENGE_ITEM_STATE_EQUIPPED
         elif (_itemId == (string)loadout.booster.Get())
            ret := $uiEnums.CHALLENGE_ITEM_STATE_EQUIPPED
         end
      end
   end
   return ret
end

func GetItemEquipState(_itemId : string, _loadoutIdx : int = -1) : int
   var ret : int = $uiEnums.CHALLENGE_ITEM_STATE_LOCKED
   if ((GL_ComponentShop)$UiGlobals.componentsShop.Get(_itemId)).availability.Get() != 0
      ret := $uiEnums.CHALLENGE_ITEM_STATE_LOCKED
   else
      var ownType : int = $uiEconomy.GetItemOwnType(_itemId)
      if (ownType == $uiEnums.ITEM_OWN_TYPE_NONE)
         ret := $uiEnums.CHALLENGE_ITEM_STATE_UNAVAILABLE
      else
         var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(_itemId)
         if (_loadoutIdx == -1)
            var itemType      : int = $uiEconomy.GetItemType(_itemId)
            var totalLoadouts : int
            var i             : int
            
            if (itemType == $uiEnums.ITEM_TYPE_ARMOR or itemType == $uiEnums.ITEM_TYPE_ARMOR_SUIT)
               totalLoadouts := (int)$UserDataStorage.local_user.armor_loadouts_unlocked.Get()
            else
               totalLoadouts := (int)$UserDataStorage.local_user.weapon_loadouts_unlocked.Get()
            end
            
            for i := 0 to totalLoadouts - 1
               var itemLoadoutState : int = GetItemEquipStateInLoadout(_itemId, i)
               if (itemLoadoutState > ret)
                  ret := itemLoadoutState
               end
            end
         else
            ret := GetItemEquipStateInLoadout(_itemId, _loadoutIdx)
         end
      end
   end
   return ret
end

end // end of UiPlayerInfo

var $uiPlayerInfo : UiPlayerInfo

func ui_init_player_info()
   CreateObjectByClassName("UiPlayerInfo", "uiPlayerInfo")
end

func ui_term_player_info()
   DestroyObjectByName("uiPlayerInfo")
end

func ui_recreate_player_info()
   ui_term_player_info()
   ui_init_player_info()
end
