import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_button
import ssl.lib.logging
import ssl.lib.types
import ui.root
import ui.ui_player_info

class UiGoldSlot : UiWidgetButton

handle OnChangeStateAny
	Log("ui~Gp_Box", "OnChangeStateAny")
end

end

class UiGpBox : UiWidgetContainer

func AddGoldPoint(p:params):bool
   Log("ui~Gp_Box", "AddGoldPoint " + Params2Str(p))
   var addGp : int
   $UiGlobals.backend_requests.real_money_purchase.Start("gold100")
   //GenerateEvent("onCloseGoldScreen")
   return false
end   

end

class BuyGoldVM
   var slotIdx : int
   
   func Init(p : params)
      slotIdx := p.slotIdx
   end
   
   func GetGoldStr() : string
      var ret : string = ""
      ret := (string)(slotIdx * 100) + " GP"
      return ret
   end
   
   func GetPriceStr() : string
      var ret :  string = ""
      ret := (string)(slotIdx * 10) + " $"
      return ret 
   end
   
   func GetGoldIcon() : string
      var ret : string
      ret := "buyGoldIcon" + (string)slotIdx
      return ret
   end
   
end   