import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.engine_ctrl
import ssl.hf2p.items_mgr
import ssl.hf2p.hq
import ui.root
import ui.ui_economy
import ui.ui_player_info
import ui.hf2p_SlidingScreens.hf2p_WeaponConf.hf2p_WeaponConf
import ui.hf2p_SlidingScreens.hf2p_Spartan.hf2p_Spartan

class RestockScreen : UiSlidingScreenPageMainMenu

handle OnChangeState("Hidden")
   
end

func Init()
   Log("ui~content", "Armory_Init")
end

override SwitchToScreen // ()

end

handle OnEnterState("Hidden")
   Set("visible", false)
end          

handle OnEnteringState("Visible")
   Init()         
   Set("visible", true)  
end  

override PrepareSlide // ()
   if (GetStateName() != "Visible")
      SetStateName("Visible")
   end
   GenerateEvent("#OnRestockScreenOpened")
   StartDefaultBlinking(0.3)
end

override PrepareHideSlide // ()
   
end

override DisableSlide // ()
   if (GetStateName() != "Hidden")
      SetStateName("Hidden")
   end
end

end

class RestockMinimalOfferVM
   var itemId : string
   var offer : GL_ComponentShopOffer = null
   
   func Init(p : params)
      itemId := p.itemId
      offer := p.offer
   end
   
   func OnBuyForGold(p : params) : bool
      var offerVal : string = (string)offer.gl_offer.Get()
      if (offerVal != "")
         var par: params
         par.itemID        := itemId
         par.offer         := offerVal
         par.priceAmount   := (int)offer.gl_cost.Get()
         par.priceUnit     := $uiEnums.TOKEN_GOLD
         if ((int)offer.gl_cost.Get() <= (int)$UserDataStorage.local_user.gold.Get())
            par.mbType     := "ConfirmBuy"
            //par.callbackEvent := "OnItemPurchased"
         else
            par.mbType     := "Info"
            par.titleTxt   := "msg_ui_warning"
            par.messageTxt := "msg_ui_not_enough_gp"
         end
         $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
      end
      return true
   end
         
   func OnBuyForCredits(p : params) : bool
      var offerVal : string = (string)offer.cr_offer.Get()
      if (offerVal != "")
         var par: params
         par.itemID        := itemId
         par.offer         := offerVal
         par.priceAmount   := (int)offer.cr_cost.Get()
         par.priceUnit     := $uiEnums.TOKEN_CREDITS
         if ((int)offer.cr_cost.Get() <= (int)$UserDataStorage.local_user.cr.Get())
            par.mbType     := "ConfirmBuy"
            //par.callbackEvent := "OnItemPurchased"
         else
            par.mbType     := "Info"
            par.titleTxt   := "msg_ui_warning"
            par.messageTxt := "msg_ui_not_enough_cr"
         end
         $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)         
      end      
      return true
   end
end

class RestockScreenVM : UiSlidingScreenMainMenuPageVM
   var SelectedLoadoutIdx : ObservableProperty = $OM.Property(0)
   var RestockItems : ObservableProperty = $OM.Calculated(this, "GetRestockItems")
   var RenewAllCostCredits : ObservableProperty = $OM.Calculated(this, "GetRenewAllCostCredits")
   var RenewAllCostGold : ObservableProperty = $OM.Calculated(this, "GetRenewAllCostGold")
   var HotItems : ObservableProperty = $OM.Calculated(this, "GetHotItems")
   
   func RestockScreenVM()
      //RestockItems.Invalidate()
   end
   
   func EnableSelector(idx : int) : bool
      var ret : bool = false
      var udLocal : UserDataLocal = $UserDataStorage.local_user
      var counter :  int = (int)udLocal.weapon_loadouts_unlocked.Get()
      if (idx < counter)
         ret := true
      end
      return ret
   end
   
   func LoadoutSelectorClicked(p : params) : bool
      SelectedLoadoutIdx.Set(p.widget.Get("idx"))
      return true
   end
   
   func GetRestockItems() : vector
      var result : vector = new vector()
      var currentLoadout : UD_WeaponLoadout = $UserDataStorage.users.Get($UserDataStorage.local_user.uid.Get()).weapon_loadouts.spartan.loadouts.Get().Get(SelectedLoadoutIdx.Get())
      
      if IsAllowedToRestock((string)currentLoadout.primary_weapon.Get())
         result.Push(currentLoadout.primary_weapon.Get())
      end
      if IsAllowedToRestock((string)currentLoadout.secondary_weapon.Get())
         result.Push(currentLoadout.secondary_weapon.Get())
      end
      if IsAllowedToRestock((string)currentLoadout.grenades.Get())
         result.Push(currentLoadout.grenades.Get())
      end
      if IsAllowedToRestock((string)currentLoadout.consumable_first.Get())
         result.Push(currentLoadout.consumable_first.Get())
      end
      if IsAllowedToRestock((string)currentLoadout.consumable_second.Get())
         result.Push(currentLoadout.consumable_second.Get())
      end
      if IsAllowedToRestock((string)currentLoadout.consumable_third.Get())
         result.Push(currentLoadout.consumable_third.Get())
      end
      if IsAllowedToRestock((string)currentLoadout.consumable_fourth.Get())
         result.Push(currentLoadout.consumable_fourth.Get())
      end
      if IsAllowedToRestock((string)currentLoadout.booster.Get())
         result.Push(currentLoadout.booster.Get())
      end
      
      return result
   end
   
   func GetRestockItemCount() : int
      var items = RestockItems.Get()
      var itemCount : int = items.Count()
      return itemCount
   end
   
   func IsAllowedToRestock(itemId : string) : bool
      var componentInventory : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(itemId)
      var result : bool = componentInventory.ownership_type.Get() == $uiEnums.ITEM_OWN_TYPE_RENTED and $uiEconomy.GetItemRentTime(itemId) < $uiEnums.ITEM_RESTOCK_ALLOWED_SECONDS
      return result
   end
   
   func GetRenewAllCostCredits() : int
      var items : vector = RestockItems.Get()
      var result : int = 0
      var i : int
      for i := 0 to items.Count() - 1
         var itemId : string = items.Get(i)
         var shop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(itemId)
         var offer = shop.GetMinimalOffer()
         result += (int)offer.cr_cost.Get()
      end
      return result
   end
   
   func GetRenewAllCostGold() : int
      var items : vector = RestockItems.Get()
      var result : int = 0
      var i : int
      for i := 0 to items.Count() - 1
         var itemId : string = items.Get(i)
         var shop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(itemId)
         var offer = shop.GetMinimalOffer()
         result += (int)offer.gl_cost.Get()
      end
      return result
   end
   
   func OnRenewAllForCredits(p : params) : bool
      var items : vector = RestockItems.Get()
      if items.Count() > 0
         var offers : vector
         var i : int
         for i := 0 to items.Count() - 1
            var itemId : string = items.Get(i)
            var shop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(itemId)
            var offer = shop.GetMinimalOffer()
            offers.Push(offer.cr_offer.Get())
         end
         var par: params
         par.offers        := offers
         par.priceAmount   := RenewAllCostCredits.Get()
         par.priceUnit     := $uiEnums.TOKEN_CREDITS
         if (int)RenewAllCostCredits.Get() <= (int)$UserDataStorage.local_user.cr.Get()
            par.mbType     := $uiEnums.MB_TYPE_CONFIRM_BATCH_BUY
         else
            par.mbType     := "Info"
            par.titleTxt   := "msg_ui_warning"
            par.messageTxt := "msg_ui_not_enough_cr"
         end
         $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
      end
      return true
   end
   
   func OnRenewAllForGold(p : params) : bool
      var items : vector = RestockItems.Get()
      if items.Count() > 0
         var offers : vector
         var i : int
         for i := 0 to items.Count() - 1
            var itemId : string = items.Get(i)
            var shop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(itemId)
            var offer = shop.GetMinimalOffer()
            offers.Push(offer.gl_offer.Get())
         end
         var par: params
         par.offers        := offers
         par.priceAmount   := RenewAllCostGold.Get()
         par.priceUnit     := $uiEnums.TOKEN_GOLD
         if (int)RenewAllCostGold.Get() <= (int)$UserDataStorage.local_user.gold.Get()
            par.mbType     := $uiEnums.MB_TYPE_CONFIRM_BATCH_BUY
         else
            par.mbType     := "Info"
            par.titleTxt   := "msg_ui_warning"
            par.messageTxt := "msg_ui_not_enough_gp"
         end
         $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
      end
      return true
   end
   
   func GetHotItems() : vector
      var result : vector
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         if (! IsVoid(shop.bundles) and shop.bundles.Get().Count() > 0)
            var subshop    :  GL_ShopSection = (GL_ShopSection)shop.bundles.Get().Get(0)
            if (! IsVoid(subshop.shelves.Get()) and subshop.shelves.Get().Count() > 0)
               var shelf      :  GL_ShopShelf   = (GL_ShopShelf)subshop.shelves.Get().Get(0)
               if (! IsVoid(shelf.items.Get()))
                  result := shelf.items.Get()
               end
            end
         end         
      end
      return result
   end
   
   func OnRestockScreenOpened(p : params) : bool
      HotItems.Invalidate()
      return true
   end
   
   func OnBundleClicked(p : params) : bool
      var pp : params
      pp.urlComp := new vector
      pp.urlComp.Push("shop")
      pp.urlComp.Push("")
      pp.urlComp.Push(p.widget.GetDC().itemId.Get())
      $sslWidgetMgr.GenerateEvent("ShowShopItem", pp)
      return true
   end
end
