import ssl.lib.ui.ui_widget
import ssl.observables

native class UiWidgetList : UiWidget
   native func TestCallList()
   native func SetData(data:vector):bool
   native func SetSelectionIdx(idx:int):bool
   native func GetSelectionIdx():int
   native func GetItemData(idx:int):params
   
   var selectionIdx     : ObservableProperty = $OM.Property(-1)
   var selectionItem    : ObservableProperty = $OM.Property(null)
   var mouseOverIdx     : ObservableProperty = $OM.Property(-1)
   var mouseOverItem    : ObservableProperty = $OM.Property(null)
   var highlightedIdx   : ObservableProperty = $OM.Property(-1)
   var highlightedItem  : ObservableProperty = $OM.Property(null)
   var scrollPosition   : ObservableProperty = $OM.Property(0)
end
