native class UiWidgetManager
   native func LoadWidget(fileName: string, rootWidgetName: string, targetFrame: string, isLoadingScreen : bool = false): bool
   native func UnloadWidget(widgetName:string)
   native func ReloadWidget(widgetName:string)
   native func IsWidgetLoaded(widgetName:string): bool
   native func ReloadCurWidget()
	native func GetWidget(widgetName:string): object
	native func GenerateEvent(eventName:string, p:params = null)
	native func UpdateTexts(clearOnly:bool)   
   native func PrintUndeletedWidgets()
   native func PrintStats()
   native func UiLog(txt : string)
end
var $sslWidgetMgr : UiWidgetManager



