import ssl.lib.ui.ui_widget
import ssl.lib.types

native class UiWidgetContainer : UiWidget
   native func TestCallContainer()
   
// ssl-only
   func SaveState() : params
      var ret : params
      ret.stateName := GetStateName()
      return ret
   end
   
   func LoadState(p : params) : bool
      if (! IsVoid(p.stateName))
         var stateName : string = p.stateName
         if (stateName != GetStateName())
            SetStateName(p.stateName)
         end
      end
      return true
   end
end
