import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.engine_ctrl

class UiLeftPanel : UiWidgetContainer

var nextWidget    : string = ""
var nextState     : string = ""
var curWidget     : string = "sMain"  
var curState      : string = "sMain"
var isTmpHidden   : bool   = false
var isSwitching   : bool   = false
var switchRequest : params

var menuHistory: vector
var showRoster: bool = false

func ProcessRoster()
   Log("ui~leftPanel", "ProcessRoster")
   var i: int
   var hasRoster: bool = false
   for i := 0 to menuHistory.Count() - 1
      Log("ui~leftPanel", "ProcessRoster: menuHistory: " + i + " " + Params2Str(menuHistory.Get(i)))
      if (! IsVoid(Widgets().menuItems.Get(menuHistory.Get(i).curWidget).roster))            
         if (Widgets().menuItems.Get(menuHistory.Get(i).curWidget).roster)
            Log("ui~leftPanel", "ProcessRoster: has roster")
            hasRoster := true
            break
         end
      end
   end
   
   if (hasRoster != showRoster)
      showRoster := hasRoster
      
      if (showRoster)
         Log("ui~leftPanel", "ProcessRoster: show roster")
         GenerateEvent("showRoster")
      else
         GenerateEvent("hideRoster")
      end
   end
end

func ChangeGridMenu(nWidget: string, nState: string)
   if (isSwitching)
      switchRequest.nextWidget   := nWidget
      switchRequest.nextState    := nState
      switchRequest.isValid      := true
   else
      isSwitching := true
      nextWidget  := nWidget
      nextState   := nState
      DoSwitch()
      //SetStateName("MenuSwitch")
   end
end

func onBackBtnClicked(p:params):bool
   Log("ui~leftPanel", "LP::onBackBtnClicked")
   
   Widgets().menuItems.onBack()
   
   if (menuHistory.Count() > 0)
      Log("ui~leftPanel", "LP::menuHistory = " + menuHistory.Count())
      Log("ui~leftPanel", "LP::Pop() - " + Params2Str(menuHistory.Get(menuHistory.Last())))
      menuHistory.Pop()      
   end
   
   
   if (menuHistory.Count() == 0)
      Log("ui~leftPanel", "LP:: no history -> sMain")
      ChangeGridMenu("main", "sMain")
   else      
      var s : params = menuHistory.Get(menuHistory.Last())
      ChangeGridMenu(s.curWidget, s.curState)
   end
   
   return false
end

func onMenuGridItemClicked(p:params):bool 
   Log("ui~leftPanel", "LP::onMenuGridItemClicked: " + Params2Str(p))      
   ChangeGridMenu(p.nextWidget, p.nextState)
   return false
end

func onNewMenu(p:params):bool 
   Log("ui~leftPanel", "LP::onNewMenu: " + Params2Str(p))
   menuHistory.Clear()
   showRoster := false
   ChangeGridMenu(p.nextWidget, p.nextState)
   return false
end

func onLeftPanelReset():bool 
   Log("ui~leftPanel", "LP::onLeftPanelReset")
   /*var p: params
   p.nextWidget := "main"
   p.nextState := "sMain"
   onNewMenu(p)*/
   return false
end   

func onError(p:params):bool 
   Log("ui~leftPanel", "LP::onError: menuName = " + Params2Str(p))
   // TODO: Show Msg Box with message p.msg
   onBackBtnClicked(p)
   return false
end
   
handle OnLeavingState("Initial")
   Widgets().menuItems.main.StartDefaultBlinking(0.15)
end

handle OnLeavingState("Collapsed")
   Widgets().menuItems.main.StartDefaultBlinking(0.15)
end

handle OnEnterState("Initial")
   menuHistory.Clear()
   curState := "sMain"              
   curWidget := "main"
   nextState := ""
   nextWidget := ""
   
   var p: params
   p.curState := curState
   p.curWidget:= curWidget
   menuHistory.Push(p)
   
   Widgets().header.text := ""
   Widgets().menuItems.backBtn.visible := false
   Widgets().menuItems.SetStateName("Initial")
end   


func DoSwitch()
   var grid: * = Widgets().menuItems      

   curState := nextState                        
   curWidget := nextWidget

   var p: params
   p.curState := curState
   p.curWidget:= curWidget
   if (menuHistory.Count() > 0)
      var s : params = menuHistory.Get(menuHistory.Last())
      if (s.curState != p.curState)
         menuHistory.Push(p)      
      end
   else
      menuHistory.Push(p)
   end

   // set up back btn
   if (! IsVoid(grid.Get(curWidget).isBackBtn))
      var isBackBtn : bool = grid.Get(curWidget).isBackBtn
      Widgets().menuItems.backBtn.visible := isBackBtn
   else
      Widgets().menuItems.backBtn.visible := true
   end
   
   // set up roster
   ProcessRoster()
   
   // set up header
   if (! IsVoid(grid.Get(curWidget).header))
      Widgets().header.text := grid.Get(curWidget).header
   else
      Widgets().header.text := ""
   end
   
   Log("ui~leftPanel", "MenuSwitch: OnEnter: changing to " + curState)
   grid.state := "Initial"
   grid.SetStateName(curState)
   grid.StartDefaultBlinking(-0.2, 1.0)
   isSwitching := false
end

handle OnEnterState("MenuSwitch")
   DoSwitch()
end          

handle OnEnteringState("Collapsed")
   //AddTween("alpha", 0.0, 1.0, "linear")
end

handle OnEnteringState("Visible")
   isTmpHidden := false
end

handle OnEnterState("Visible")
   isSwitching := false
   if (! IsVoid(switchRequest.isValid) and switchRequest.isValid)
      switchRequest.isValid := false
      ChangeGridMenu(switchRequest.nextWidget, switchRequest.nextState)
   end
end

handle OnEnterState("Collapsed")
   //Set("visible", false)
end

handle OnLeavingState("Collapsed")
   isTmpHidden := false
   //Set("visible", true)
   //AddTween("alpha", 1.0, 1.0, "linear")
end

func DockerBtnEnabled(enable : bool)
   var pp : params
   pp.enabled := enable
   GenerateEvent("MailBtnEnabled", pp)
end

func OnDockerPanelOpen(p : params) : bool
   if (! isTmpHidden and GetStateName() != "Initial" and GetStateName() != "Collapsed")
      isTmpHidden := true
      SetStateName("Initial")
   end   
   return false
end

func OnDockerPanelClose(p : params) : bool
   if (isTmpHidden)
      isTmpHidden := false
      SetStateName("Visible")
      DockerBtnEnabled(false)
      DockerBtnEnabled(true) : 1
   end   
   return false
end

end
