import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ui.root
import ssl.lib.ui.ui_widget_list_item

class UiScPlayerLIR : UiWidgetListItem

override SetData //(p:params) 
   Props().name    := p.name
   Props().tag     := p.tag
   Props().kills   := (string)((int)(p.kills))
   Props().deaths  := (string)((int)(p.deaths))
   Props().assists := (string)((int)(p.assists))
   Props().score   := (string)((int)(p.score))
   Props().wscore  := (string)((int)(p.wscore))
   
   var localClrClr   : int = 240 * 65536 + 217 * 256 + 55
   var nonLocalClr   : int = 153 * 65536 + 153 * 256 +153
   var deadClr       : int = 50 * 65536 + 50 * 256 + 50
   var deadLocalClr  : int = 255 * 65536 + 0 * 256 + 0
   var lineClr       : int = nonLocalClr

   if (p.isDead)
      lineClr := deadClr
   end

   if (! IsVoid(p.isLocal) and p.isLocal)
      if (p.isDead)
         lineClr := deadLocalClr
      else
         lineClr := localClrClr
      end
   end

   Props().nameClr      := lineClr
   Props().tagClr       := lineClr
   Props().killsClr     := lineClr
   Props().deathsClr    := lineClr
   Props().assistsClr   := lineClr
   Props().scoreClr     := lineClr
   Props().wscoreClr    := lineClr

   var armorClassId: int = -1
   if (! IsVoid(p.armorClassId))
      armorClassId := (int)(p.armorClassId)
   end

   //I have commented the line below this because it have a error and script had not been working from this line!!!
   //Widgets().armorClassAttach.pic      := $root.GetArmorClassIcon(armorClassId) + "Sm"
   Widgets().armorClassAttach.scaleX   := 1
   Widgets().armorClassAttach.scaleY   := 1
   Widgets().armorClassAttach.x        := 3
   Widgets().armorClassAttach.y        := 4
   
   if (p.isBomb)
      Widgets().bombClassAttach.pic      := "emptyArmorClassSm"
      Widgets().bombClassAttach.scaleX   := 1
      Widgets().bombClassAttach.scaleY   := 1
      Widgets().bombClassAttach.x        := 221
      Widgets().bombClassAttach.y        := 4
   else
      Widgets().bombClassAttach.pic      := ""
   end
end
end

class UiScStatsLIR : UiWidgetListItem

override SetData //(p:params) 
   Props().name    := p.name
   Props().score   := (string)((int)(p.score))
end
end
