import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_list_item

import ssl.lib.logging
class UiHf2pGameStatWpnLIR : UiWidgetListItem

override SetData
   if (! IsVoid(p.wpnIdx))
      Props().wpnIdx := p.wpnIdx
   end
   if (! IsVoid(p.wpnName))
      Props().wpnName := p.wpnName
   end
   if (! IsVoid(p.killsText))
      Props().killsText := p.killsText
   end
   if (! IsVoid(p.killsValue))
      Props().killsValue := p.killsValue
   end
   if (! IsVoid(p.accuracyText))
      Props().accuracyText := p.accuracyText
   end
   if (! IsVoid(p.accuracyValue))
      Props().accuracyValue := p.accuracyValue
   end
   if (! IsVoid(p.wpnImage))
      Props().itemCont.pic    := p.wpnImage
      Props().itemCont.scaleX := 0.7
      Props().itemCont.scaleY := 0.7
   end
end
end

class UiHf2pGameStats : UiWidgetContainer

func setXpPanelValue(prevXp:int, nextXp:int, curXp:int)
     Log("ui~hf2p_gameStats", "setPbValue " + prevXp + " " + nextXp)	
	Props().prevXP    := (string)(prevXp) + " XP"
	Props().nextXP    := (string)(nextXp) + " XP"
	Props().currentXP := (string)(curXp) + " XP"
            
   Widgets().screenCont.progressBar.UpdateProgress(prevXp, nextXp, curXp)
	setPlrRankName(0) //$sslUserStates.GetLevel())
end

func setPlrRankName(lvl: int)
   Props().currentRankText := "Maxim" //$sslUserStates.GetLevelName(lvl)
   Props().nextRankText    := "Next Rank: " + "Optimus Maximus" //$sslUserStates.GetLevelName(lvl + 1)
end
end

class UiHf2pProgressBar : UiWidgetContainer

var isFirstUpdate: bool = true

func UpdateDefaultScale()
   if (! isFirstUpdate)
      return
   end
   
   isFirstUpdate := false
   var defScale: float := 1.0
   
   var childWidget: * := GetWidget(Props().barName)
   if (childWidget != null)
      defScale := childWidget.Props().scaleX
   end         
   Props().customScale := defScale
end

func UpdateProgress(minVal: float, maxVal:float, curVal:float)
   Props().minVal := minVal
   Props().maxVal := maxVal
   SetProgressValue(curVal)
end

func SetProgressValue(_curVal:float)
   var curVal : float = _curVal
   var minVal : float := Props().minVal
   var maxVal : float := Props().maxVal
   
   if (curVal < minVal)
      curVal := minVal
   end
   if (curVal > maxVal)
      curVal := maxVal
   end
   Props().curVal := curVal       
   
   var barScale: float = 0.0
   if (minVal != maxVal)
      barScale := (curVal - minVal) / (maxVal - minVal)
      if (barScale < 0)
         barScale := 0
      end
      if (barScale > 1)
         barScale := 1
      end
   end

   UpdateDefaultScale()
   barScale := barScale * Props().customScale
   
   var childWidget: * := GetWidget(Props().barName)
   if (childWidget != null)
      childWidget.Props().scaleX := barScale
   end         
end

func GetValue(): float
   return Props().curVal
end
end
