import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_button
import ssl.lib.logging
import ssl.lib.types
import ui.root
import ui.ui_player_info

class UiGoldSlot : UiWidgetButton

handle OnChangeStateAny
	Log("ui~Gp_Box", "OnChangeStateAny")
end

end

class UiGpBox : UiWidgetContainer

end

class BuyGoldVM
   var slotIdx          : ObservableProperty =  $OM.Property(0)
   var itemId           : ObservableProperty =  $OM.Calculated(this, "GetItemId")
   var currencyBundle   : ObservableProperty =  $OM.Calculated(this, "GetCurrencyBundle")
   var price            : ObservableProperty =  $OM.Calculated(this, "GetPrice")
   var priceOld         : ObservableProperty =  $OM.Calculated(this, "GetPriceOld")
   var salePercent      : ObservableProperty =  $OM.Calculated(this, "GetSalePercent")
   var saleTxt          : ObservableProperty =  $OM.Calculated(this, "GetSaleTxt")
   var amount           : ObservableProperty =  $OM.Calculated(this, "GetAmount")
   var amountFrame      : ObservableProperty =  $OM.Calculated(this, "GetAmountFrame")
   var amountTxt        : ObservableProperty =  $OM.Calculated(this, "GetAmountTxt")
   var bonusTxt         : ObservableProperty =  $OM.Calculated(this, "GetBonusTxt")
   var bonusLineFrame   : ObservableProperty =  $OM.Calculated(this, "GetBonusLineFrame")
   var priceTxt         : ObservableProperty =  $OM.Calculated(this, "GetPriceTxt")
   var priceOldTxt      : ObservableProperty =  $OM.Calculated(this, "GetPriceOldTxt")
   var uiComp           : ObservableProperty =  $OM.Calculated(this, "GetUiComp")
   var name             : ObservableProperty =  $OM.Calculated(this, "GetName")
   var isEnabled        : ObservableProperty =  $OM.Calculated(this, "GetIsEnabled")
   var isVisible        : ObservableProperty =  $OM.Calculated(this, "GetIsVisible")
   var isGlow           : ObservableProperty =  $OM.Calculated(this, "GetIsGlow")
   var isSuperGlow      : ObservableProperty =  $OM.Calculated(this, "GetIsSuperGlow")
   var isSale           : ObservableProperty =  $OM.Calculated(this, "GetIsSale")
   var isBestOffer      : ObservableProperty =  $OM.Calculated(this, "GetIsBestOffer")
   var isBonus          : ObservableProperty =  $OM.Calculated(this, "GetIsBonus")
   var wgt              : UiWidget           =  null
   
   func Init(p : params)
      wgt := p.widget
      slotIdx.Set(p.slotIdx)
   end
   
   func OnUpdateGoldPage(p : params) : bool
      currencyBundle.Invalidate()
      itemId.Invalidate()
      priceTxt.Invalidate()
      amountTxt.Invalidate()
      uiComp.Invalidate()
      return false
   end
   
   func GetGoldItemId(idx : int) : string
      var ret : string = ""      
      var shop = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get($UserDataStorage.local_user.race.Get())
      var section = shop.FindInternalSection("section_gold")
      if (section != null)
         var shelf = section.FindShelf("shelf_gold")
         if (shelf != null)
            var shelfItems : vector = shelf.items.Get()
            if (shelfItems != null and shelfItems.Count() > idx)
               ret := (string)shelfItems.Get(idx).value.Get()
            end
         end
      end      
      return ret      
   end
   
   func GetItemId() : string      
      var ret : string = GetGoldItemId((int)slotIdx.Get() - 1)
      return ret
   end
   
   func GetItemIdVal() : string
      return (string)itemId.Get()
   end
   
   func GetCurrencyBundle() : GL_ComponentInternalCurrencyBundle
      var ret        : GL_ComponentInternalCurrencyBundle   = null
      var itemIdVal  : string                               = GetItemIdVal()
      if (itemIdVal != "")
         ret := (GL_ComponentInternalCurrencyBundle)$UiGlobals.componentsInternalCurrencyBundle.Get(itemIdVal)
      end
      return ret
   end
   
   func GetCurrencyBundleVal() : GL_ComponentInternalCurrencyBundle
      return (GL_ComponentInternalCurrencyBundle)currencyBundle.Get()
   end      
      
   func GetUiComp() : GL_ComponentUI
      var ret : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(GetItemIdVal())
      return ret
   end
   
   func GetPrice() : int
      var ret     : int                                  = 0
      var bundle  : GL_ComponentInternalCurrencyBundle   = GetCurrencyBundleVal()
      if (bundle != null)
         ret := (int)bundle.external_currency_cost.Get()
      end
      return ret
   end
   
   func GetSalePercent() : float
      var ret     : float
      var bundle  : GL_ComponentInternalCurrencyBundle   = GetCurrencyBundleVal()
      if (bundle != null)
         ret := (float)((int)bundle.bundle_sale_amount.Get()) / 100.0
      end
      return ret
   end
   
   func GetSaleTxt() : string
      var ret        : string = ""
      var salePerc   : float  = (float)salePercent.Get()   
      if (salePerc > 0)
         ret := "main_gold_sale," + (string)(int)(salePerc * 100.0)
      end
      return ret
   end
            
   func GetPriceTxt() : wstring
      var ret : wstring
      var p : params
      p.txt0 := $UiGlobals.String2WString("main_gold_price," + (string)(int)price.Get() + ",")
      p.txt1 := GetCurrencyName()
      ret := p.txt0 + p.txt1
      return ret
   end   
   
   func GetCurrencyName() : wstring
      return $UiGlobals.TranslateText("main_price_rub")
   end

   func GetPriceOld() : int
      var ret        : int = 0
      if ((bool)isSale.Get())
         var priceVal   : int    = (int)price.Get()
         var salePerc   : float  = (float)salePercent.Get()
         if (salePerc > 0 and salePerc < 1)
            ret := (int)(priceVal / (1 - salePerc))
         end
      end
      return ret
   end
   
   func GetPriceOldTxt() : wstring
      var ret : wstring
      var p : params
      p.txt0 := $UiGlobals.String2WString("main_gold_price," + (string)(int)priceOld.Get() + ",")
      p.txt1 := GetCurrencyName()
      ret := p.txt0 + p.txt1
      return ret
   end
   
   func GetName() : string
      var compUI     : GL_ComponentUI  = (GL_ComponentUI)uiComp.Get()
      var ret        : string          = ""      
      if (compUI != null)
         ret := (string)compUI.name.Get()
      end
      return ret
   end
      
   func GetIsGlow() : bool
      return (bool)isBestOffer.Get()
   end
   
   func GetIsSuperGlow() : bool
      return (bool)isBestOffer.Get()
   end
   
   func GetAmountFrame() : string
      var ret : string = "tfGoldWhite"
      if ((bool)isGlow.Get())
         ret := "tfGoldGlow"
      end
      return ret
   end
   
   func GetIsSale() : bool
      return (float)salePercent.Get() > 0 
   end
   
   func GetIsBestOffer() : bool
      var ret     : bool                                 = false
      var bundle  : GL_ComponentInternalCurrencyBundle   = GetCurrencyBundleVal()
      if (bundle != null)
         ret := (int)bundle.bundle_is_best_value.Get() > 0
      end
      return ret
   end
   
   func GetGoldAmountFromItemId(_itemId : string) : int
      var compUI        : GL_ComponentUI  = (GL_ComponentUI)$UiGlobals.componentsUI.Get(_itemId)      
      var ret           : int             = -1
      var goldAmountStr : string          = (string)compUI.desc.Get()
      if (goldAmountStr != "")
         ret := $UiGlobals.Int64ToInt($UiGlobals.String2Int64(goldAmountStr))
      end
      return ret
   end
   
   func GetAmount() : int
      var ret     : int                                  = 0
      var bundle  : GL_ComponentInternalCurrencyBundle   = GetCurrencyBundleVal()
      if (bundle != null)
         ret := (int)bundle.internal_currency_received.Get()
      end
      return ret
   end
            
   func GetAmountTxt() : string
      var ret : string = (string)(int)amount.Get()
      return ret
   end
      
   func GetBonusTxt() : wstring
      var ret     : wstring
      var bundle  : GL_ComponentInternalCurrencyBundle   = GetCurrencyBundleVal()
      if (bundle != null)
         var baseAmount    : int = (int)bundle.internal_currency_received.Get()
         var bonusAmount   : int = (int)bundle.internal_currency_bonus.Get()
         if (bonusAmount > 0)
               var p : params
               p.txt1 := $UiGlobals.String2WString((string)(baseAmount - bonusAmount))
               p.txt2 := $UiGlobals.String2WString("main_gold_price_bonus," + (string)bonusAmount)
               p.txt2 := $root.MakeColorCodedWText(p.txt2, "#FDE577")
               p.txt := p.txt1
               p.txt := p.txt + p.txt2
               ret := p.txt            
         end
      end
      return ret
   end
   
   func GetBonusLineFrame() : string
      var ret : string = "blue"
      if ((bool)isGlow.Get())
         ret := "gold"
      end
      return ret
   end
   
   func GetIsBonus() : bool
      var ret : bool = (string)bonusTxt.Get() != ""
      return ret
   end
   
   func GetGoldIcon() : string
      var compUI     : GL_ComponentUI  = (GL_ComponentUI)uiComp.Get()
      var ret        : string          = ""      
      if (compUI != null)
         ret := (string)compUI.icon.Get()
      end
      return ret
   end
   
   func OnAddGoldPoint(p : params) : bool
      Log("ui~Gp_Box", "AddGoldPoint " + Params2Str(p))
      var par : params
      par.mbType           := $uiEnums.MB_TYPE_NO_YES
      par.msgImage         := "questIcon"
      par.callbackEvent    := "PurchaseGoldPoints"
      par.callbackTarget   := wgt.Props
      par.defButton        := $uiEnums.MB_DEF_BUTTON_CANCEL
      par.okSound          := "purchase_gold"
      par.titleTxt         := "msg_ui_gold_purchase"
      par.messageTxt       := "msg_ui_gold_purchase," + GetAmountTxt()
      $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
      return true
   end   

   func OnPurchaseGoldPoints(p : params) : bool
      if (p.isOK)
         var bundle : GL_ComponentInternalCurrencyBundle = GetCurrencyBundleVal()
         if (bundle != null)
            var pp : params
            pp.index := (int)slotIdx.Get()
            pp.amount := (int)amount.Get()
            pp.offer := (string)bundle.external_offer_id.Get()
            $UiGlobals.backend_requests.apply_offer.Start(pp, "GoldPurchasingFinished")
         end
      end
      return true
   end
   
   func GetIsEnabled() : bool
      return (int)price.Get() > 0
   end
   
   func GetIsVisible() : bool
      return (int)price.Get() > 0
   end
end   