import ssl.lib.ui.ui_widget_container
import ssl.hf2p.engine_ctrl
import ssl.hf2p.ui_globals

class UiScoreboardIngame : UiWidgetContainer
   
handle OnEnterState("Initial")
   Widgets().resultsHeader.visible := false
   Props().visible := false
end

handle OnEnteringState("Visible")
   Widgets().resultsHeader.visible  := true
   Widgets().resultsHeader.tf := "ingame_scoreboard_heading_scoring"
   Props().visible := true
end

handle OnEnteringState("PreGameVisible")
   Widgets().resultsHeader.visible  := false
   Props().visible := true
end

handle OnEnteringState("PostGameVisible")
   Widgets().resultsHeader.visible := true
   Widgets().resultsHeader.tf := "ingame_scoreboard_heading_results"
   GotoAndPlay("fadeIn")
   Widgets().list.StartDefaultBlinking(0.2)
   Widgets().PersonalStats.StartDefaultBlinking(0.2)
   Props().visible := true
end

handle OnLeavingState("PostGameVisible")
   GotoAndPlay("fadeOut")
end
end

class UiScoreboardTeamsVM
   var teams      : ObservableProperty = $OM.Calculated(this, "GetTeams")
   
   func GetTeams() : vector
      $UiGlobals.gameplay.scoreboard.version.Get()
      var i : int
      for i := 0 to $UiGlobals.gameplay.scoreboard.scoreboard_teams.Get().Count() - 1
         var team : GL_ScoreboardTeam = (GL_ScoreboardTeam)$UiGlobals.gameplay.scoreboard.scoreboard_teams.Get().Get(i)
         team.SetIdx(i)
      end
      return $UiGlobals.gameplay.scoreboard.scoreboard_teams.Get()
   end
   
   func IsTeamMode() : bool
      return $UiIngame.IsTeamMode()
   end
   
   func GetLeadingTeam() : int
      var ret : int = 0
      $UiGlobals.gameplay.scoreboard.version.Get()
      if ($UiGlobals.gameplay.scoreboard.teams_ranking.indices.Get().Count() > 0)
         ret := $UiGlobals.gameplay.scoreboard.teams_ranking.indices.Get().Get(0).value.Get()
      end
      return ret
   end   
   
   func GetAnim() : string
      var ret     : string = "redLeads"
      var leadIdx : int = GetLeadingTeam()
      if (leadIdx == 0)
         ret := "redLeads"
      elif (leadIdx == 1)
         ret := "blueLeads"
      end
      return ret
   end
end