import ssl.lib.ui.ui_widget_container

import ssl.hf2p.engine_ctrl
import ssl.lib.types
import ssl.lib.ui.ui_widget_list_item
import ssl.lib.logging
import ui.ui_party_monitor
import ui.ui_matchmaking
import ui.root
import ssl.hf2p.user_service
import ssl.hf2p.ui_globals
import ssl.hf2p.hq
import ui.libs.hf2p_Default_lib.hf2p_Default_lib

class UiLobbyVotingGroup : UiWidgetContainer

func InitForVoting()
   Widgets().mapElem1.InitForVoting()
   Widgets().mapElem2.InitForVoting()
   Widgets().mapElem3.InitForVoting()
end

func RearrangeMapButtons(p : params) : bool
   /*
   var btnIdx : int     = p.btnIdx
   var layer1 : string  = "layer1"
   var layer2 : string  = "layer2"
   var layer3 : string  = "layer3"
   if (btnIdx == 0)
      layer1 := "layer3"
      layer2 := "layer2"
      layer3 := "layer1"
   elif (btnIdx == 1)
      layer1 := "layer2"
      layer2 := "layer3"
      layer3 := "layer1"
   elif (btnIdx == 2)
      layer1 := "layer1"
      layer2 := "layer2"
      layer3 := "layer3"
   end
   Widgets().mapElem1.SetLayer(layer1)
   Widgets().mapElem2.SetLayer(layer2)
   Widgets().mapElem3.SetLayer(layer3)
   */
   
   return false
end  

end

class UiLobbyVotingGroupElem : UiWidgetContainer

var   mapId       :  int
var   isVoting    :  bool
var   votesCount  :  int = 0
var   tmpMapPic   :  string

func InitForVoting()
   isVoting                         := true
   Widgets().checkupElem.visible    := true
   Widgets().bg.votesLabelTxt.text  := "lobby_votes"
end

func InitForPreview()
   isVoting                         := false
   Widgets().checkupElem.visible    := false
   Widgets().bg.votesTxt.text       := ""
   Widgets().bg.votesLabelTxt.text  := ""
end

end

class UiLobbyRosterLIR : UiWidgetListItem

override SetData
   //Props().enabled      := false
   //Props().mouseEnabled := false
end

end

class UiLobbySuperContainer : UiWidgetContainer
     
var   isEditable        : bool = false
var   isVoting          : bool = false


func IsMapSelectionEnabled(): bool
   return false
end

func IsModeSelectionEnabled(): bool
   return false
end

func SetMapIcon(_mapIcon: string)
   Widgets().mapContainerElem.mapBtnCont.mapBtn.bg.mapIcon.pic := _mapIcon
end

func SetModeIcon(_mapIcon: string)
   Widgets().mapContainerElem.mapBtnCont.mapBtn.bg.modeIcon.pic := _mapIcon
end      

func ShowMapModeSelection(_mapMode: bool)
   Widgets().mapContainerElem.visible  := _mapMode
   Widgets().mapStepper.visible        := _mapMode
   Widgets().gameType.visible          := _mapMode
   Widgets().waitingTf.visible         := _mapMode
end

handle OnEnterState("MapModeSelection") 
   Props().visible := false         
end

func ArrangeRosters(_teamCount: int)
   var   x0    :  float    = 0
   var   midx  :  float    = 0 
   var   dist1 :  float    = 16
   var   dist2 :  float    = 24
   if (_teamCount == 1)
      x0 := 513
      midx := midx + x0
      Widgets().redTeam.x           := x0
      Widgets().headerRedTeam.x     := x0
      Widgets().headerRedTeam.text  := ""
      x0 := x0 + Widgets().redTeam.width + dist1

      midx := midx + x0
      Widgets().blueTeam.x          := x0
      Widgets().headerBlueTeam.x    := x0
      Widgets().headerBlueTeam.text := ""
      x0 := x0 + Widgets().blueTeam.width + dist2

      Widgets().mapContainerElem.x        := x0
      Widgets().mapContainerElem.y        := Widgets().blueTeam.y
      Widgets().votingGroup.x             := x0
      Widgets().votingGroup.y             := Widgets().blueTeam.y
      Widgets().mapStepper.x              := x0
      Widgets().gameType.x                := x0
      Widgets().waitingTf.x               := x0
      Widgets().playlistDropdown.x        := x0
      Widgets().playListDropDownHeader.x  := x0
      Widgets().gameModeDropdown.x        := x0
      Widgets().gameModeDropDownHeader.x  := x0
      Widgets().gameMapDropdown.x         := x0 + 288
      Widgets().gameMapDropDownHeader.x   := x0 + 288
      x0 := x0 + Widgets().mapContainerElem.mapBtnCont.mapBtn.width + dist2
      
      midx := midx / 2.0
      Widgets().headerNoTeam.x            := midx
      Widgets().headerNoTeam.text         := "lobby_txt_lobby_team"
      Widgets().headerNoTeam.visible      := true
   else
      x0 := 375
      Widgets().redTeam.x           := x0
      Widgets().headerRedTeam.x     := x0
      Widgets().headerRedTeam.text  := "lobby_txt_red_team"
      x0 := x0 + Widgets().redTeam.width + dist2

      Widgets().mapContainerElem.x        := x0
      Widgets().mapContainerElem.y        := Widgets().blueTeam.y
      Widgets().votingGroup.x             := x0
      Widgets().votingGroup.y             := Widgets().blueTeam.y
      Widgets().mapStepper.x              := x0
      Widgets().gameType.x                := x0
      Widgets().waitingTf.x               := x0
      Widgets().playlistDropdown.x        := x0
      Widgets().playListDropDownHeader.x  := x0
      Widgets().gameModeDropdown.x        := x0
      Widgets().gameModeDropDownHeader.x  := x0
      Widgets().gameMapDropdown.x         := x0 + 288
      Widgets().gameMapDropDownHeader.x   := x0 + 288
      x0 := x0 + Widgets().mapContainerElem.mapBtnCont.mapBtn.width + dist2
      
      Widgets().blueTeam.x          := x0
      Widgets().headerBlueTeam.x    := x0
      Widgets().headerBlueTeam.text := "lobby_txt_blue_team"
      x0 := x0 + Widgets().blueTeam.width + dist2
      
      Widgets().headerNoTeam.text      := x0
      Widgets().headerNoTeam.text      := ""
      Widgets().headerNoTeam.visible   := false
   end
   //float(Widgets().gameType.y) + Widgets().gameType.height + dist
end

func SetVotingMode(_isVoting: bool)
   if (_isVoting)
      Log("ui~lobby_superContainer", "OnGameMapStepperIndexChange_SetVotingMode - true")
      Widgets().votingGroup.InitForVoting()
   else
      Log("ui~lobby_superContainer", "OnGameMapStepperIndexChange_SetVotingMode - false")
      Widgets().mapContainerElem.mapBtnCont.mapBtn.InitForPreview()
   end
   isVoting := _isVoting
end
      
handle OnEnterState("Initial") 
end

end

class UiGameType : UiWidgetContainer

func OnMapModeStepperIndexChange(p: params): bool
   GenerateEvent("OnGameModeStepperIndexChange", p)
   return false
end
end

class UiMapStepper : UiWidgetContainer

func OnMapModeStepperIndexChange(p: params): bool
   Log("ui~mapStepper", "OnMapModeStepperIndexChange")
   GenerateEvent("OnGameMapStepperIndexChange", p)
   return false
end
end

class VotingGroupContGlow : UiWidgetContainer
   
end

class VotingGroupElemGlow : UiWidgetContainer
   var isMouseOver : bool = false
   
   func onVotingMouseDown(p : params) :  bool
      var pp : params
      pp.btnIdx := p.widget.Props().voteIdx2
      GenerateEvent("RearrangeMapButtons", pp)
      GotoAndPlay("down")
      //GotoAndStop(11) : 2
      //isMouseOver := true
      return false
   end
   
   func onVotingMouseOver(p : params) : bool
      if (! isMouseOver)
         isMouseOver := true
         GotoAndPlay("over")
      end
      return false
   end

   func onVotingMouseOut(p : params) : bool
      if (isMouseOver)
         isMouseOver := false
         GotoAndStop("up")
      end
      return false
   end
end

class rosterLIR_VM
   var uid           : ObservableProperty = $OM.Calculated(this, "GetUID")
   var uidVal        : ObservableProperty = $OM.Calculated(this, "GetUIDVal")
   var wgt           : UiWidget           = null
   var text          : ObservableProperty = $OM.Calculated(this, "GetText")
   var text1         : ObservableProperty = $OM.Calculated(this, "GetText1")
   var text2         : ObservableProperty = $OM.Calculated(this, "GetText2")
   var nickName      : ObservableProperty = $OM.Calculated(this, "GetNickName")
   var teamFrame     : ObservableProperty = $OM.Calculated(this, "GetTeamFrame")
   var playerIcon    : ObservableProperty = $OM.Calculated(this, "GetPlayerIcon")
   var bgTint        : ObservableProperty = $OM.Calculated(this, "GetBgTint")
   var isSlotEnabled : ObservableProperty = $OM.Calculated(this, "GetIsSlotEnabled")
   var isInvalidData : ObservableProperty = $OM.Calculated(this, "GetIsInvalidData")
   var isWaitingData : ObservableProperty = $OM.Calculated(this, "GetIsWaitingData")
   var lobbyPlayer   : ObservableProperty = $OM.Property($UiGlobals.lobby.invalidLobbyPlayer)
   var isSubscribed  : bool               = false
   var userContext   : UserContextMenu    = new UserContextMenu()
   
   func Init(p : params)
      userContext.canOpen := false
      wgt := p.widget
      UnsubscribeFromUID()
      if (! IsVoid(p.lobbyPlayer))
         lobbyPlayer.Set(p.lobbyPlayer)
      end
      SubscribeToUID()
      RequestData()
   end
   
   func SubscribeToUID()
      if (! isSubscribed)
         isSubscribed := true         
         GetLobbyPlayer().id.value.Subscribe(this, "OnUpdateUID")
      end
   end
   
   func UnsubscribeFromUID()
      if (isSubscribed)
         GetLobbyPlayer().id.value.Unsubscribe(this, "OnUpdateUID")
         isSubscribed := false
      end
   end
   
   func Term()
      UnsubscribeFromUID()
   end
   
   func OnUpdateUID(_val : *)
      userContext.uid      := GetLobbyPlayer().id.value.Get()
      userContext.canOpen  := $UserDataStorage.IsValidUID(userContext.uid) and ! GetIsEmptySlot() and ! GetIsAddSlot()
      RequestData()
   end
      
   func RequestData()
      if ($UserDataStorage.IsValidUID(GetLobbyPlayer().id.value.Get()))
         $user_service.RequestData(GetLobbyPlayer().id.value.Get(), $uiEnums.USER_DATA_BASE)
         $user_service.RequestData(GetLobbyPlayer().id.value.Get(), $uiEnums.USER_DATA_CUSTOMIZATIONS)
      end
   end
         
   func GetUID() : GL_UID
      var player  : GL_LobbyPlayer  = (GL_LobbyPlayer)lobbyPlayer.Get()
      var ret     : GL_UID          = player.GetUID()
      return ret
   end
   
   func GetUIDVal() : *
      var uidValue : GL_UID = (GL_UID)uid.Get()
      return uidValue.value.Get()
   end
   
   func UIDVal() : *
      return uidVal.Get()
   end
   
   func GetUserData() : UserData
      var ret : UserData = (UserData)$UserDataStorage.users.Get(UIDVal())
      return ret
   end
   
   func GetLobbyPlayer() : GL_LobbyPlayer      
      var ret : GL_LobbyPlayer = (GL_LobbyPlayer)lobbyPlayer.Get()
      return ret   
   end
      
   func GetPlayerIcon() : string
      var ret : string = ""
      if (IsValid() and ! GetIsEmptySlot() and ! GetIsWaitingData())
         ret := "iconHelmetLobby"
      end
      return ret
   end
   
   func GetText() : string
      var ret : string = ""
      return ret
   end
   
   func GetIdx() : int
      var ret : int = -1
      var player  : GL_LobbyPlayer = GetLobbyPlayer()
      ret := player.idx
      return ret
   end
   
   func GetText1() : wstring
      var ret        : wstring
      var colorCode  : string = "FFFFFF"
      if (IsValid())
         ret         := GetNickName()
         colorCode   := $UserDataStorage.GetPlayerStatusColorCode(GetUIDVal())
      end
      ret := $root.MakeColorCodedWText(ret, colorCode)      
      return ret
   end
   
   func GetIsEmptySlot() : bool
      var ret : bool = true
      if (IsValid())
         ret := false
      end
      return ret      
   end
   
   func GetLobbyScreenState() : int
      var ret : int = $uiEnums.LOBBY_SCREEN_STATE_NONE
      var player  : GL_LobbyPlayer = GetLobbyPlayer()      
      ret := (int)player.lobbyState.Get()
      return ret
   end
   
   func IsSelectPlaylist() : bool
      return GetLobbyScreenState() == $uiEnums.LOBBY_SCREEN_STATE_PLAYLIST
   end
   
   func GetIsAddSlot() : bool
      var ret : bool = false
      var player  : GL_LobbyPlayer = GetLobbyPlayer()      
      ret := (bool)player.isAddSlot.Get() and GetIsEmptySlot() and $UserDataStorage.local_user.IsPartyLeader()
      return ret      
   end
   
   func GetText2() : string
      var ret : string = ""      
      return ret
   end
   
   func GetSubText() : string
      var ret        : string = ""
      var isAddSlot  : bool   = GetIsAddSlot()
      if (isAddSlot)
         ret := "lobby_invite_player"
      else
         if (GetIsSlotEnabled())
            ret := "lobby_waiting"
         else
            ret := ""
         end
      end         
      return ret      
   end
   
   func GetIsEnabled() : bool
      GetUIDVal()
      return IsValid() or (GetIsAddSlot() or ! GetIsEmptySlot())
   end
   
   func GetPartyData() : GL_ComponentUserPartyData
      var partyData : GL_ComponentUserPartyData = (GL_ComponentUserPartyData)$UiGlobals.componentsUserPartyData.Get(GetUIDVal())
      return partyData
   end
   
   func GetIsPartyLeader() : bool
      return (bool)GetPartyData().is_party_leader.Get()
   end

   func GetIsPartyLeaderVisible() : bool
      return $UserDataStorage.local_user.IsPartyLeaderVisible() and GetIsPartyLeader()
   end
   
   func GetPartyIndicatorFrame() : int
      var ret : int = 0
      var idx : int = GetPartyIdxInt()
      if (idx >= 0 and idx < 8)
         ret := 1 + idx         
      end
      return ret
   end
   
   func GetIsPartyIndicatorVisible() : bool
      var ret : bool = GetPartyIdxInt() >= 0 and ! IsSelectPlaylist() and ! GetIsEmptySlot() //GetPartyIdxInt() >= 0 and IsSelectPlaylist()
      if (ret)
         ret := true
      end
      //ret := true
      return ret
   end
      
   func GetPartyIdxInt() : int
      var ret        : int = -1
      var partyData  : GL_ComponentUserPartyData = GetPartyData()
      ret := (int)partyData.party_icon_index.Get()
      return ret
   end
   
   func GetPartyIdx() : string
      var ret : string  = ""
      var idx : int     = GetPartyIdxInt()
      if (idx != -1)
         ret := (string)idx
      end
      // programmers art
      ret := ""
      return ret
   end
      
   func GetNickName() : wstring
      var ret : wstring = $UiGlobals.String2WString("")
      if (IsValid())            
         var ud : UserData = (UserData)$UserDataStorage.users.Get(UIDVal())
         ret := ud.base.full_nickname.Get()
         if (GetIsWaitingData())
            ret := $UiGlobals.String2WString("???")
         end
      end
      return ret      
   end
   
   func IsValid() : bool
      var ret : bool = $UserDataStorage.IsValidUID(UIDVal())
      return ret
   end
   
   func IsLocal() : bool
      var ret : bool = false
      if (IsValid())
         ret := $UserDataStorage.IsEqualUIDs(UIDVal(),  $UserDataStorage.local_user.uid.Get())
         
      end
      return ret
   end
   
   func GetIsSlotEnabled() : bool
      var playlist   : string                = (string)$UiGlobals.matchmaking.playlists_selection.Get()
      var plComp     : GL_ComponentPlaylist  = (GL_ComponentPlaylist)$UiGlobals.componentsPlaylist.Get(playlist)
      var ret        : bool                  = false
      var myIdx      : int                   = GetLocalSlotIdx()      

      if (myIdx < ((int)plComp.player_count_max.Get()) / 2)
         ret := true
      end
      
      ret := (bool)GetLobbyPlayer().isSlotEnabled.Get()
      return ret
   end
   
   func GetBgTint() : params
      var ret : params
      ret.a := 255
      ret.v := 255
      ret.r := 255
      ret.g := 255
      ret.b := 255
      if (! GetIsSlotEnabled())
         ret.r := 96
         ret.g := 96
         ret.b := 96
      end
      return ret
   end
   
   func GetSlotIdx() : int
      var ret : int = GetLobbyPlayer().idx
      return ret
   end
   
   func GetDebugTicks() : int
      var ret : int = GetLobbyPlayer().debugTicks
      return ret
   end
      
   func GetLocalSlotIdx() : int
      var ret : int = GetLobbyPlayer().localIdx
      return ret
   end
   
   func GetTeamFrame() : string
      var player  : GL_LobbyPlayer = GetLobbyPlayer()      
      var ret     : string = "white"      
      if (GetIsEmptySlot())
         if (GetIsAddSlot())
            ret := "add"
         else
            ret := "disabled"
         end
      else
         var teamIdx : int = 0 //(int)player.team_index.Get()
         teamIdx := player.team_index2
         if (player.isTeamMode)
            if (teamIdx == 0)
               ret := "red"
            elif (teamIdx == 1)
               ret := "blue"
            end
         end
      end
      return ret
   end
      
   func GetIsInvalidData() : bool
      var ret  : bool      = false
      var ud   : UserData  = GetUserData()
      ret := !(bool)ud.has_base.Get()
      return ret
   end
   
   func GetIsWaitingData() : bool
      var ret : bool
      ret := IsValid() and GetIsInvalidData()
      return ret
   end
   
   func GetLabel() : string
      var ud : UserData = GetUserData()
      var compUi : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(ud.customizations.account_label.Get())
      return (string)compUi.icon.Get()
   end
   
end
