import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.game_preferences

class UiStCommonControls : UiWidgetContainer  
   
var is_inited :  bool = false
   
func tryToCloseOrReturn() : bool //true if close
Log("ui~rebind_keys", "__________________________________________________ On Controls Selected")

   if (Widgets().controls_screen.GetStateName() != "Visible")
      Widgets().controls_screen.SetStateName("Visible")
      Widgets().rebinds_screen.SetStateName("Initial")
      return false
   end
   return true
end
   
func onControlsSelected(p:params):bool
Log("ui~rebind_keys", "__________________________________________________ On Controls Selected")

   if (Widgets().controls_screen.GetStateName() != "Visible")
      Widgets().controls_screen.SetStateName("Visible")
      Widgets().rebinds_screen.SetStateName("Initial")
   end
   return false
end

func onRebindSelected(p:params):bool
Log("ui~rebind_keys", "__________________________________________________ On Rebind Selected")
   if (Widgets().rebinds_screen.GetStateName() != "Visible")
      GenerateEvent("OnEnterSubscreen")
      Widgets().controls_screen.SetStateName("Initial")
      Widgets().rebinds_screen.SetStateName("Visible")
   end
   return false
end   
 
handle OnEnterState("Initial")
   Widgets().controls_screen.SetStateName("Initial")
   Widgets().rebinds_screen.SetStateName("Initial")
   Set("visible", false)            
end  
        
handle OnEnteringState("Visible")  
   Init()
   Widgets().controls_screen.SetStateName("Visible")
   Widgets().rebinds_screen.SetStateName("Initial")
   Set("visible", true)
end  

func SwitchToScreen()
   Log("ui~content", "Audio setting SwitchSlide")
   Props().visible := true
end

func PrepareSlide()
   Log("ui~content", "Audio setting EnableSlide")
   if (GetStateName() != "Visible")
      SetStateName("Visible")
   end
   GenerateEvent("OnEnterNewTab")
   Props().visible := true
   
   Widgets().controls_screen.SetStateName("Visible")
   Widgets().rebinds_screen.SetStateName("Initial")
   
   StartDefaultBlinking(0.5, 1.0)
   
   var p: params
   p.state := "s_controlls"
   GenerateEvent("ChangeFakeBackground", p)
end

func PrepareHideSlide()
end

func ReInit()
   is_inited := true
   Widgets().controls_screen.Init()
   Widgets().rebinds_screen.ReInit()
end

func Init()
   is_inited := true
   Widgets().controls_screen.Init()
   Widgets().rebinds_screen.Init()
end

func Reset()
   if (Widgets().rebinds_screen.GetStateName() == "Visible")
      Widgets().rebinds_screen.Reset()
      return
   end
   
   if (Widgets().controls_screen.GetStateName() == "Visible")
      Widgets().controls_screen.Reset()
      return
   end
end

func HaveUnsavedChanges() :  bool
   Log("ui~content", "Check controls result1")
   if (!is_inited)
      return false
   end
   
   Log("ui~content", "Check controls result2")
   var res : bool = Widgets().rebinds_screen.HaveUnsavedChanges()
   res := res or Widgets().controls_screen.HaveUnsavedChanges()
   Log("ui~content", "Check controls result  res = " + (string)res)
   return res
end

func Apply()
   if (!is_inited)
      return
   end
   
   Widgets().rebinds_screen.Apply()
   Widgets().controls_screen.Apply()
end

func DisableSlide()
   if (GetStateName() != "Initial")
      Log("ui~content", "Audio setting DisableSlide")
      Props().visible := false
      SetStateName("Initial")
   end
end
end