import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.items_mgr
import ui.ui_economy

import ui.ui_player_info
import ssl.hf2p.engine_ctrl
import ui.root

class UiOffersModuleContNew : UiWidgetContainer

end

class UiOffersModuleRentNew : UiWidgetContainer

end

class UiWcExpTimer : UiWidgetContainer

func Clear()
   Props.time := ""
end

end

class UiWcUiTileCostContS : UiWidgetContainer

end

/*************************************************************
* UiGenericShopTabsVM
* 
*************************************************************/
class UiGenericShopTabsVM
   var selectedTabIdx   : ObservableProperty = $OM.Property(0)
   var isShadingLine    : ObservableProperty = $OM.Property(false)
   var tabLabels        : ObservableProperty = $OM.Calculated(this, "GetTabLabels")
   var tabsCount        : ObservableProperty = $OM.Calculated(this, "GetTabsCount")
   var isActive         : ObservableProperty = $OM.Property(false)
      
   func GetTabsCount() : int
      return GetTabLabels().Count()
   end
      
   func GetTabLabels() : vector
      var ret : vector
      return ret
   end
   
   func SelectTab(idx : int)
      if (idx >= 0 and idx < GetTabsCount())
         selectedTabIdx.Set(idx)
      end 
   end
   
   func OnTabClicked(idx : int) : bool
      SelectTab(idx)
      return true
   end
   
   func OnTabClickedHandler(p : params) : bool
      var ret : bool = false
      if (!IsVoid(p.widget) and !IsVoid(p.widget.tabIdx))
         ret := OnTabClicked(p.widget.tabIdx)
      end
      return ret
   end
end

class ShopDescPanelVM
   var itemId : ObservableProperty = $OM.Property("")
   
   func Init(itemId : string)
      this.itemId.Set(itemId)
   end
   
   func GetName() : string
      return (string)$UiGlobals.componentsUI.Get(itemId.Get()).name.Get()
   end
   
   func GetDescription() : string
      return (string)$UiGlobals.componentsUI.Get(itemId.Get()).desc.Get()
   end
   
   func GetTechName() : string
      return (string)$UiGlobals.componentsUI.Get($UiGlobals.componentsItem.Get(itemId.Get()).career_tree.Get()).name.Get()
   end
   
   func GetEagleVisible() : bool
      var ret : bool = false
      var compShop : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(itemId.Get())
      var techId : string = (string)compShop.requirement.Get()
      if $UiGlobals.componentsShop.Exist(techId)
         ret := true
      end   
      return ret
   end
   
   func GetTechIcon() : string
      var ret : string = (string)$UiGlobals.componentsUI.Get($UiGlobals.componentsItem.Get(itemId.Get()).career_tree.Get()).icon.Get()
      return ret
   end
   
   func GetEuqippedState() : int
      var ret : int = 0
      if ((GL_ComponentShop)$UiGlobals.componentsShop.Get(itemId.Get())).availability.Get() != 0
         ret := $uiEnums.CHALLENGE_ITEM_STATE_LOCKED
      else
         var itemIdVal  : string = (string)itemId.Get()
         var itemType   : int    = $uiEconomy.GetItemType(itemIdVal)
         if (itemType == $uiEnums.ITEM_TYPE_ARMOR)
            var armorComp : GL_ComponentArmor = (GL_ComponentArmor)$UiGlobals.componentsArmor.Get(itemIdVal)
            ret := armorComp.GetShowroomEquipState($UserDataStorage.local_user.GetCurrentArmorLoadoutIdx())
         elif (itemType == $uiEnums.ITEM_TYPE_ARMOR_SUIT)
            //var armorComp : GL_ComponentArmorSuit = (GL_ComponentArmorSuit)$UiGlobals.componentsArmorSuit.Get(itemIdVal)
            //ret := armorComp.GetShowroomEquipState($UserDataStorage.local_user.GetCurrentArmorLoadoutIdx())
         else
            ret := $uiPlayerInfo.GetItemEquipState(itemIdVal)
         end
      end
      return ret
   end
   
   func GetStateText() : string
      var ret        : string
      var compShop   : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(itemId.Get())
      if ((string)compShop.requirement.Get() != "")
         var skillState : int    = GetEuqippedState()
         if (skillState == $uiEnums.CHALLENGE_ITEM_STATE_LOCKED)
            var techUI = $UiGlobals.componentsUI.Get($UiGlobals.componentsItem.Get(itemId.Get()).career_tree.Get())
            ret := "carousel_skill_not_learned," + techUI.name.Get()
         else
            if (skillState == $uiEnums.CHALLENGE_ITEM_STATE_NOT_EQUIPPED)
               ret := "carousel_chal_non_equipped"
            elif (skillState == $uiEnums.CHALLENGE_ITEM_STATE_PARTIALLY_EQUIPPED)
               ret := "carousel_chal_equipped_part"
            elif (skillState == $uiEnums.CHALLENGE_ITEM_STATE_EQUIPPED)
               ret := "carousel_chal_equipped"
            end
         end
      end
      return ret
   end
   
   func GetStateTextColor() : int
      var ret : int = $root.RGB2Clr(255, 0, 0)
      return ret
   end
   
   func GetChallengeRank() : int
      return $UiGlobals.componentsItem.Get(itemId.Get()).GetCurrentChallengeRank()
   end
   
   func GetPlrLevel() : int
      var ret  : int = (int)$UserDataStorage.local_user.level.Get()
      return ret
   end
   
   func GetUnlockDescTxt() : string
      var ret : string
      var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)itemId.Get())
      var itemLevel : int = (int)shopComp.unlock_level.Get()
      if GetPlrLevel() < itemLevel
         ret := "carousel_unlock_at_level," + (string)itemLevel
      else
         ret := ""
      end
      return ret
   end 
   
end

class UiShopDescPanel : UiWidgetContainer
   handle OnEnteringState("Initial")
      GotoAndStop(1)
   end   
end

class ShopDescModel : UiWidgetContainer
   handle OnEnteringState("Initial")
      GotoAndStop(1)      
      Widgets.desc.SetStateName("Initial")
   end
   
   handle OnEnterState("Full")
      GenerateEvent("#ShopDescModelOpened")
   end
   
   handle OnEnterState("Collapsed")
      GenerateEvent("#ShopDescModelCollapsed")
   end
end
