import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_button
import ui.root
import ssl.hf2p.ui_globals
import ssl.hf2p.user_data
import ui.libs.hf2p_Default_lib.hf2p_Default_lib
import ui.hf2p_SlidingScreens.hf2p_Lobby.hf2p_Lobby

/*************************************************************
* UiChat
* 
*************************************************************/
class UiChat : UiWidgetContainer
   func FocusInputText()
      Widgets().inputCont.inputTf.SetFocus()
   end
   
   func ClearInputText()
      Widgets().inputCont.inputTf.text := ""
   end
   
   func TweenChatSize(updType:string)
      GetDC().TweenChatSize(updType)
   end
   
   func CustomSet(propName : string, propVal : *) : bool
      if (propName == "tabsData")
         GetDC().SetTabsData(propVal)
         return true
      end
      return false
   end
   
   func focusIn(p : params) : bool
      if (! IsVoid(p.toWidget))
         var toWidget : UiWidget = p.toWidget
         if (toWidget.IsChildOf(this))
            //GetDC().FocusReceived()
         end
      end
      return false
   end
   
   func focusOut(p : params) : bool
      if (! IsVoid(p.toWidget))
         var toWidget   : UiWidget = p.toWidget
         if (! toWidget.IsChildOf(this))
            //GetDC().FocusLost()            
         end
      else
         //GetDC().FocusLost()
      end
      return false
   end
   
   func ProcessMouseDown(target : UiWidget)      
      var chatExpand = (UiWidget)(Widgets().expandBtn.object)
      var chatTabs   = (UiWidget)(Widgets().tabsCont.object)
      if (target.IsChildOf(this))
         if (!target.IsChildOf(chatExpand) and !target.IsChildOf(chatTabs))
            ClickedInside()
         end
      else
         ClickedOutside()
      end      
   end
   
   func ClickedInside()
      GetDC().FocusReceived()
   end
   
   func ClickedOutside()
      GetDC().FocusLost()      
   end   
end

/*************************************************************
* UiTabVM
* 
*************************************************************/
class UiTabVM
   var tabIdx           : int = 0
   var data             : ObservableProperty = $OM.Property("")
   var isSelected       : ObservableProperty = $OM.Property(false)
   
   func OnTabSelected()
      
   end
   
   func OnTabOut()
   end
end

/*************************************************************
* UiTabsVM
* 
*************************************************************/
class UiTabsVM
   var items         : vector
   var selectedTab   : ObservableProperty = $OM.Property(0)
   
   func GetMaxTabs() : int
      return 0
   end
   
   func GetDefaultEntry() : *
      var ret : params
      return ret
   end
   
   func GetTabs() : vector
      var ret : vector
      return ret
   end
   
   func SetItems(_items : vector)
      items :=_items
      ArrangeTabs()
   end
   
   func Refresh()
      var tabs          : vector = GetTabs()
      if (tabs.Count() > 0)
         var selectedIdx : int = GetSelectedTabIdx()
         if (selectedIdx >= tabs.Count())
            selectedIdx := tabs.Count() - 1
         elif (selectedIdx < 0)
            selectedIdx := 0
         end
         SetSelectedTabIdx(selectedIdx)
      end
   end
   
   func SetSelectedTabIdx(_tabIdx : int)
      selectedTab.Set(_tabIdx)
      var tabs : vector = GetTabs()
      var i    : int
      for i := 0 to tabs.Count() - 1
         var tab : UiTabVM = (UiTabVM)tabs.Get(i)
         if (_tabIdx == i)
            tab.OnTabSelected()
         else
            tab.OnTabOut()
         end
         tab.isSelected.Set(_tabIdx == i)
      end
   end
   
   func GetSelectedTabIdx() : int
      return (int)selectedTab.Get()
   end
   
   func GetSelectedTab() : UiTabVM
      var selectedIdx : int = GetSelectedTabIdx()
      var ret : UiTabVM = GetTabs().Get(selectedIdx)
      return ret
   end
   
   func GetSelectedTabData() : ObservableProperty
      var selectedIdx : int = GetSelectedTabIdx()
      var ret : UiTabVM = GetTabs().Get(selectedIdx)
      return ret.data
   end
   
   func ArrangeTabs()
      
   end
      
   func GetItems() : vector
      return items
   end
   
   func GetTabsCount() : int
      var ret : int = GetTabs().Count()
      return ret
   end
         
   func TabClicked(p : params) : bool
      var tab : UiTabVM = p.widget.GetWidget("_parent").GetDC()
      SetSelectedTabIdx(tab.tabIdx)
      return true
   end
end

/*************************************************************
* UiChatTabVMData
* 
*************************************************************/
class UiChatTabVMData
   var idx        : int       = 0
   var channel    : int       = 1
   var name       : wstring   = ""
   var privateUid : *         = $UserDataStorage.GetInvalidUID()
end

/*************************************************************
* UiChatTabVM
* 
*************************************************************/
class UiChatTabVM : UiTabVM
   var xoffset          :  ObservableProperty   = $OM.Property(0.0)
   var isValidTab       :  ObservableProperty   = $OM.Property(false)
   var tabWidth         :  ObservableProperty   = $OM.Property(100.0)
   var tabOffset        :  ObservableProperty   = $OM.Property(0.0)
   var notifOffset      :  ObservableProperty   = $OM.Property(0.0)
   var tabScale         :  ObservableProperty   = $OM.Property(1.0)
   var tabScaleInv      :  ObservableProperty   = $OM.Property(1.0)
   var isNewMessages    :  ObservableProperty   = $OM.Calculated(this, "GetIsNewMessages")
   var newMessagesCount :  ObservableProperty   = $OM.Calculated(this, "GetNewMessagesCountStr")
            
   func SetTabData(_data : *)
      data.Set(_data)
   end
   
   func GetChatData() : UiChatTabVMData
      return (UiChatTabVMData)data.Get()
   end
   
   func GetMessageStream() : GL_ChatStream
      var channel : int             = GetChatData().channel      
      var ret     : GL_ChatStream   = null
      if (channel == $uiEnums.CHAT_CHANNEL_ALL)
         ret := $UiGlobals.chat.general
      elif (channel == $uiEnums.CHAT_CHANNEL_PARTY)
         ret := $UiGlobals.chat.party
      elif (channel == $uiEnums.CHAT_CHANNEL_GAME_ALL)
         ret := $UiGlobals.chat.game_all_channel
      elif (channel == $uiEnums.CHAT_CHANNEL_PRIVATE)
         ret := $UiGlobals.chat.private_channel
      end
      return ret      
   end
   
   func GetChannelMessages() : vector
      var stream  : GL_ChatStream = GetMessageStream()
      var ret     : vector
      if (stream != null)
         ret := GetMessageStream().GetMessages()
      end
      return ret      
   end
   
   func GetCurrentMessagesCount() : int
      var ret : int = GetChannelMessages().Count()
      return ret
   end
   
   func GetIsNewMessages() : bool
      var ret : bool = !(bool)isSelected.Get() and GetNewMessagesCount() > 0
      return ret
   end
   
   override OnTabSelected//()
      UpdateTimestamp()
   end
   
   func GetLastViewTime() : *
      var stream  : GL_ChatStream   = GetMessageStream()
      var ret     : *               = $UiGlobals.IntToInt64(0)
      if (stream != null)
         ret := GetMessageStream().GetLastViewTime()
      end
      return ret
   end
      
   func UpdateTimestamp()
      var stream  : GL_ChatStream   = GetMessageStream()
      if (stream != null)
         GetMessageStream().UpdateLastViewTime()
         newMessagesCount.Invalidate()
      end
   end
   
   override OnTabOut//()
      if ((bool)isSelected.Get())
         UpdateTimestamp()
      end
   end
   
   func GetNewMessagesCount() : int
      var mes        : GL_ChatStreamMessage  = null
      var messages   : vector                = GetChannelMessages()
      var ret        : int                   = 0
      var i          : int
      var curCount   : int                   = GetCurrentMessagesCount() // subscribe to messsageCount
      
      for i := 0 to messages.Count() - 1
         mes := messages.Get(i)
         if ($UiGlobals.CmpInt64(GetLastViewTime(), mes.timestamp.Get()) < 0)
            ret := ret + 1
         end
      end
      return ret
   end      
   
   func GetNewMessagesCountStr() : string
      var ret : string  = (string)GetNewMessagesCount()
      return ret
   end      
end


/*************************************************************
* UiChatTabsVM
* 
*************************************************************/
class UiChatTabsVM : UiTabsVM
   var tabs             : vector
   var validTabsCount   : int = 0
   var totalWidth       : int = 730
   var offsets          : vector
   
   override GetMaxTabs//() : int
      return 10
   end
   
   override GetDefaultEntry//() : *
      var tabData :  UiChatTabVMData = null
      tabData           := new UiChatTabVMData()
      tabData.idx       := -1
      tabData.name      := ""
      tabData.channel   := -1
      return tabData
   end
   
   override GetTabs//() : vector      
      var ret : vector = tabs
      if (ret.Count() == 0)
         var i : int
         for i := 0 to GetMaxTabs() - 1
            var tab : UiChatTabVM = new UiChatTabVM()
            tab.tabIdx := i
            ret.Push(tab)
         end
      end
      return ret
   end
   
   func GetOffsets() : vector 
      var ret : vector = offsets
      if (ret.Count() == 0)
         var i : int
         
      end
      return ret      
   end
   
   override ArrangeTabs//()
      var i          : int
      var validTabs  : int = 0
      for i := 0 to GetMaxTabs() - 1
         var tab : UiChatTabVM = GetTab(i)
         if ((bool)tab.isValidTab.Get())
            validTabs := validTabs + 1
         end
      end  
      if (validTabs > 0)
         var tabWidth   : float  = (float)totalWidth / (float)validTabs 
         var tabIdx     : int    = 0
         for i := 0 to GetMaxTabs() - 1
            var tab : UiChatTabVM = GetTab(i)
            if ((bool)tab.isValidTab.Get())
               var baseWidth : float = 70.0
               if (i > 0 and i <= 2)
                  baseWidth := 71.0
               elif (i == 0 or i == (GetMaxTabs() - 1))
                  baseWidth := 85.0
               end
               tab.tabWidth.Set     (tabWidth)
               tab.tabScale.Set     (tabWidth / baseWidth)
               tab.tabScaleInv.Set  (1.0 / (float)tab.tabScale.Get())
               tab.tabOffset.Set    (tabIdx * tabWidth)
               tab.notifOffset.Set  (tabWidth - 32)
               tabIdx            := tabIdx + 1
            end
         end           
      end
   end
   
   func GetTab(_idx : int) : UiChatTabVM
      return GetTabs().Get(_idx)
   end
   
   func SetTabData(_idx : int, _data : *, _isValid : bool)
      GetTab(_idx).SetTabData(_data)
      GetTab(_idx).isValidTab.Set(_isValid)
   end
   
   override SetItems//(_items : vector)
      items.Clear()
      var i : int
      for i := 0 to GetMaxTabs() - 1
         var dataIdx : int = -1
         if (i == (GetMaxTabs() - 1))
            if (_items.Count() > 1)
               dataIdx := _items.Count() - 1
            end
         else
            if (i < _items.Count() - 1)
               dataIdx := i
            end
         end         
         if (dataIdx == -1)
            SetTabData(i, GetDefaultEntry(), false)
         else
            SetTabData(i, _items.Get(dataIdx), true)
         end
      end      
      ArrangeTabs()
   end
end


/*************************************************************
* UiChatVM
* 
*************************************************************/
class UiChatVM
   var tabs                   : UiChatTabsVM       = new UiChatTabsVM()
   var wgt                    : UiChat             = null
   var privateMessagesTarget  : ObservableProperty = $OM.Property($UiGlobals.GetInvalidUIDVal())
   var isMembersPanelEnabled  : ObservableProperty = $OM.Property(true)
   var isCollapsed            : ObservableProperty = $OM.Property(true)
   var isPlayerCardVisible    : ObservableProperty = $OM.Property(false)
   var chatSizeDiff           : ObservableProperty = $OM.Property((float)0)
   var chatSizeDiffDelayed    : ObservableProperty = $OM.Property((float)0)
   var rosterCard             : RosterCardVM       = new RosterCardVM()
   var playerUID              : GL_UID             = $UserDataStorage.NewEmptyUID()
   var chatDragStart          : float              = 0
   var userContext            : UserContextMenu    = new UserContextMenu()
   var chatStyleSheet         : UiSSMainChat       = new UiSSMainChat()
   var fullSize               : float              = 500
   
   func Init(p : params)
      wgt := p.widget
      tabs.selectedTab.Subscribe(this, "OnTabChange")
   end
   
   func Term()
      tabs.selectedTab.Unsubscribe(this, "OnTabChange")
   end
   
   func OnTabChange(_val : *)
      FocusReceived()
      if (! CanSendMessage())
         wgt.ClearInputText()
      end
   end
      
   func SetTabsData(tabsData : vector)
      tabs.SetItems(tabsData)
      tabs.Refresh()
   end
   
   func IsInParty() : bool
      var partyVec   : vector = $UiGlobals.party.members.Get()
      var ret        : bool   = partyVec.Count() > 1
      return ret
   end
      
   func IsInLobby() : bool
      var partyState : int    = (int)$UiGlobals.party.state.Get()
      var ret        : bool   = partyState == $uiEnums.PARTY_STATE_IN_GAME
      return ret
   end

   func GetTabsData() : vector
      var p    : params
      var vec  : vector
      
      var tabData : UiChatTabVMData = null
      
      tabData           := new UiChatTabVMData()
      tabData.idx       := vec.Count()
      tabData.name      := $UiGlobals.String2WString("main_chat_channel_news")
      tabData.channel   := $uiEnums.CHAT_CHANNEL_NEWS
      vec.Push(tabData)

      tabData           := new UiChatTabVMData()
      tabData.idx       := vec.Count()
      tabData.name      := $UiGlobals.String2WString("main_chat_channel_general")
      tabData.channel   := $uiEnums.CHAT_CHANNEL_ALL
      vec.Push(tabData)
      
      if (IsInParty())
         tabData           := new UiChatTabVMData()
         tabData.idx       := vec.Count()
         tabData.name      := $UiGlobals.String2WString("main_chat_channel_party")
         tabData.channel   := $uiEnums.CHAT_CHANNEL_PARTY
         vec.Push(tabData)
      end
      
      if (IsInLobby())
         tabData           := new UiChatTabVMData()
         tabData.idx       := vec.Count()
         tabData.name      := $UiGlobals.String2WString("main_chat_channel_lobby")
         tabData.channel   := $uiEnums.CHAT_CHANNEL_GAME_ALL
         vec.Push(tabData)
      end
      
      var ud : UserData = $UserDataStorage.GetLocalUserData()
      if ((bool)ud.has_base.Get())
         if (! $UiGlobals.IsZeroInt64(ud.base.clan_id.Get()))
            tabData           := new UiChatTabVMData()
            tabData.idx       := vec.Count()
            tabData.name      := $UiGlobals.String2WString("main_chat_channel_clan")
            tabData.channel   := $uiEnums.CHAT_CHANNEL_CLAN
            vec.Push(tabData)         
         end
      else
         $user_service.RequestData($UserDataStorage.local_user.uid.Get(), $uiEnums.USER_DATA_BASE)
      end     
      
      if (CanSendPrivate())
         tabData           := new UiChatTabVMData()
         tabData.idx       := vec.Count()
         tabData.name      := $UiGlobals.String2WString("main_chat_channel_private")
         tabData.channel   := $uiEnums.CHAT_CHANNEL_PRIVATE
         vec.Push(tabData)      
      end
      
      return vec
   end
      
   func UiChatVM()
   end
   
   func IsNewsVisible() : bool
      var selectedChannel : int = GetSelectedChannel()
      return selectedChannel == $uiEnums.CHAT_CHANNEL_NEWS
   end
   
   func IsMembersVisible() : bool
      var selectedChannel  : int    = GetSelectedChannel()
      var ret              : bool   = (bool)isMembersPanelEnabled.Get() and ! GetIsCollapsed() and selectedChannel != $uiEnums.CHAT_CHANNEL_NEWS
      return ret
   end
      
   func GetMembersPanelState() : string
      var isMembersVisible : bool   = IsMembersVisible()
      var ret              : string = "Hidden"
      if (isMembersVisible)
         ret := "Visible"
      end
      return ret
   end
   
   func IsMessagesVisible() : bool
      var selectedChannel : int = GetSelectedChannel()
      return selectedChannel != $uiEnums.CHAT_CHANNEL_NEWS
   end
      
   func GetMessagesPanelState() : string
      var isMembersVisible : bool   = IsMembersVisible()
      var ret              : string = "Small"
      if (! isMembersVisible)
         ret := "Full"
      end
      return ret
   end
   
   var testIdx : int = 0
   func ToggleMembers(p : params) : bool      
      isMembersPanelEnabled.Set(!(bool)isMembersPanelEnabled.Get())
      //isMembersPanelEnabled.Set(true)
      //testIdx := testIdx + 1
      
      //wgt.Widgets().testText.htmlText := "LINK test " + (string)testIdx + ": <a href=\"event:LNK1\"><font color=\"#FF0000\">LINK1</font></a>, <a href=\"event:LNK2\"><font color=\"#00FF00\">LINK2</font></a>"
      
      //wgt.Widgets().listMembers.txtArea.htmlText := GetMembersTxt()
      //wgt.Widgets().listMembers.txtAreaCont.htmlText := GetMembersTxt()
      //wgt.Widgets().listMembers.txtAreaCont.txtArea.scrollBar := "DefaultScrollBarSkinned"
      //wgt.Widgets().testText.htmlText := "LINK test " + (string)testIdx + ": <font color=\"#FF0000\">LINK1</font>, <font color=\"#00FF00\">LINK2</font>"
      //					htmlText   =   {
	//					binding   =   "{'LINK test: <a href='event:LNK1'><font color='#FF0000'>LINK1</font></a>, <a href='event:LNK2'><font color='#00FF0000'>LINK2</font></a>'}"
		//			}

      return true
   end
   
   func IsMembersBtnVisible() : bool
      var selectedChannel  : int    = GetSelectedChannel()
      var ret              : bool   = (bool)isMembersPanelEnabled.Get() and ! GetIsCollapsed() and selectedChannel != $uiEnums.CHAT_CHANNEL_NEWS
      return ret
   end
   
   func GetBgHeight() : float
      var ret : float = 103 //+ GetSizeDifference()
      return ret      
   end
   
   func GetUsersBgHeight() : float
      var ret : float = 56 + GetSizeDifference()
      return ret      
   end
   
   func GetUsersBgHeightDelayed() : float
      var ret : float = 56 + GetSizeDifferenceDelayed()
      return ret      
   end
   
   func GetChatHeight() : float
      var ret : float = 0
      //if (! GetIsCollapsed())
         ret := (float)chatSizeDiff.Get()         
      //end
      return ret
   end
      
   func GetChatHeightDelayed() : float
      var ret : float = 0
      ret := (float)chatSizeDiffDelayed.Get()         
      return ret
   end
   
   func ChatStartDrag(p : params) : bool
      chatDragStart     := (float)chatSizeDiff.Get()
      var pp: params
      pp.dragEvent   := "ChatDrag"
      pp.dragTarget  := wgt.Widgets().expandBtn.object
      StopSizeTween()
      wgt.Widgets().expandBtn.SetFocus()
      wgt.GenerateEvent("StartUniversalDrag", pp)
      return true
   end
   
   var dragCounter : int = 0
   func ChatDrag(p : params) : bool
      if (p.updateType == "update" or p.updateType == "start")
         var newSize : float = (float)(chatDragStart - p.mouseOffset.y)
         if (newSize < 0)
            newSize := 0
         end
         if (newSize > 700)
            newSize := 700
         end
         if (newSize > 0)
            isCollapsed.Set(false)
         else
            isCollapsed.Set(true)
         end
         chatSizeDiff.Set(newSize)
         if (dragCounter == 0)
            chatSizeDiffDelayed.Set(newSize)
         end
         dragCounter := dragCounter + 1
         if (dragCounter == 15)
            dragCounter := 0
         end
      elif (p.updateType == "end")
         fullSize := (float)chatSizeDiff.Get()
         chatSizeDiffDelayed.Set(chatSizeDiff.Get())
         if (! GetIsCollapsed())
            wgt.SetFocus()
         end
      end
      return true
   end
   
   func GetSizeDifference() : float
      var ret : float = 0
      ret := GetChatHeight()
      return ret
   end
   
   func GetSizeDifferenceDelayed() : float
      var ret : float = 0
      ret := (float)chatSizeDiffDelayed.Get()
      return ret
   end
   
   func IsSendVisible() : bool
      var selectedChannel  : int    = GetSelectedChannel()
      var ret              : bool   = selectedChannel != $uiEnums.CHAT_CHANNEL_NEWS
      return ret
   end

   func GetMembersBtnYPos() : float
      var ret              : float  = 94.5 + GetSizeDifference()
      return ret      
   end
   
   func GetInputContYPos() : float      
      var ret              : float  = 93 + GetSizeDifference()
      return ret      
   end

   func GetSelectedChannel() : int
      var tabData : UiChatTabVMData = (UiChatTabVMData)tabs.GetSelectedTabData().Get()
      var ret     : int             = tabData.channel
      return ret
   end
   
   func FocusReceived()
      if (GetIsCollapsed())
         ToggleCollapsed(null)
      end
   end
   
   func FocusLost()
      if (! GetIsCollapsed())
         ToggleCollapsed(null)
      end
   end
   
   func ToggleCollapsed(p : params) : bool
      var curSize : float  = (float)chatSizeDiff.Get()
      var newSize : float  = curSize
      if (curSize == 0)
         newSize := fullSize
         if (newSize < 50)
            newSize := 500
         end
      else
         newSize := 0
      end
      var tweenParm : params
      tweenParm.propName   := "chatSize"
      tweenParm.startVal   := curSize         
      tweenParm.endVal     := newSize
      tweenParm.duration   := 0.128
      tweenParm.fadeType   := "linear"

      StopSizeTween()
      wgt.AddTweenCb("TweenChatSize", tweenParm) 
      //isCollapsed.Set(!GetIsCollapsed())
      return true
   end
   
   func StopSizeTween()
      wgt.RemTweens()      
   end
   
   func TweenChatSize(updType : string)
      var chatSize : float = (float)wgt.Get("chatSize")
      if (chatSize > 0)
         isCollapsed.Set(false)
      else
         isCollapsed.Set(true)
      end
      chatSizeDiff.Set(chatSize)
      if (updType == "complete")
         chatSizeDiffDelayed.Set(chatSize)         
         OnMessagesChanged(null)
      end
   end
   
   func GetIsCollapsed() : bool
      return (bool)isCollapsed.Get()
   end
   
   func GetChatYPos() : float
      var ret              : float  = -GetSizeDifference()
      return ret
   end
         
   func GetMembersListHeight() : float
      var ret              : float  = 37 + GetSizeDifferenceDelayed()
      return ret
   end
   
   func GetMessagesListHeight() : float
      var ret              : float  = 57 + GetSizeDifferenceDelayed()
      return ret
   end
   
   func GetMessagesListWidth() : float
      var ret              : float  = 695
      if (IsMembersVisible())
         ret := 495
      end
      return ret
   end
   
   func GetMessagesLIRWidth() : float
      var ret : float =  GetMessagesListWidth() - 30
      return ret
   end
      
   func GetNewsListHeight() : float
      var ret              : float  = 57 + GetSizeDifferenceDelayed()
      return ret
   end
   
   func GetMOTDYPos() : float      
      var ret              : float  = 105 + GetSizeDifference()
      return ret
   end
   
   func GetChatStream() : GL_ChatStream
      var ret              : GL_ChatStream   = null
      var selectedChannel  : int             = GetSelectedChannel()
      if (selectedChannel == $uiEnums.CHAT_CHANNEL_ALL)
         ret := $UiGlobals.chat.general
      elif (selectedChannel == $uiEnums.CHAT_CHANNEL_PARTY)
         ret := $UiGlobals.chat.party
      elif (selectedChannel == $uiEnums.CHAT_CHANNEL_GAME_ALL)
         ret := $UiGlobals.chat.game_all_channel
      elif (selectedChannel == $uiEnums.CHAT_CHANNEL_CLAN)
         ret := $UiGlobals.chat.clan_channel
      elif (selectedChannel == $uiEnums.CHAT_CHANNEL_PRIVATE)
         ret := $UiGlobals.chat.private_channel
      end
      return ret
   end
   
   func GetMembers() : vector
      var ret  : vector      
      if (IsMembersVisible())
         var stream : GL_ChatStream = GetChatStream()
         if (stream != null)
            ret := stream.GetMembers()
         end
      end      
      return ret      
   end
   
   func GetMessages() : vector
      var ret  : vector
      if (IsMessagesVisible())
         ret := $UiGlobals.GetChatMessages(GetSelectedChannel())
      end
      return ret
   end
   
   func UpdateStreamTimestamp()
      var stream : GL_ChatStream = GetChatStream()
      if (stream != null)
         stream.UpdateLastViewTime()
      end
   end
   
   func GetMessagesTxt() : wstring
      var messages   : vector = GetMessages()
      var ret        : wstring
      var mes        : GL_ChatStreamMessage= null      
      
      var i          : int
      for i := 0 to messages.Count() - 1
         var p : params
         mes   := messages.Get(i)
         p.msg := mes.GetFormattedText(true, false)
         ret   := ret + p.msg
      end
      
      UpdateStreamTimestamp()
      
      var str  : string
      var wp   : params
      wp.str   := ret
      str      := wp.str
      return ret
   end
   
   func GetMembersTxt() : wstring
      var members    : vector = GetMembers()
      var ret        : wstring
      var i          : int
      var member     : GL_UID = null
      for i := 0 to members.Count() - 1
         member := members.Get(i)         
         var ud      : UserData  = (UserData)$UserDataStorage.users.Get(member.value.Get())
         var nick    : wstring    = ud.base.full_nickname.Get()
         var isValid : bool      = true
         
         if ((bool)ud.has_base.Get())
         else
            if ($UserDataStorage.IsValidUID(member.value.Get()))
               $user_service.RequestData(member.value.Get(), $uiEnums.USER_DATA_BASE) : 0
            end
            if (nick == $UiGlobals.String2WString(""))
               isValid := false
            end
         end
         if (isValid)
            var link : string    = $UserDataStorage.UID2Str(member.value.Get())
            var p    : params         
            p.tilde  := $UiGlobals.String2WString("~")
            p.nl     := $UiGlobals.String2WString("\n~")
            p.nick   := nick
            p.nick   := p.nick + p.tilde
            p.nick   := $root.MakeLinkWText(p.nick, link, $UserDataStorage.GetUserColorCode(member.value.Get()))
            ret      := ret + p.nick
            ret      := ret + p.nl         
         end
      end
      var str  : string
      var wp   : params
      wp.str   := ret
      str      := wp.str
      return ret
   end
   
   func AutoScrollMemebers()
      wgt.Widgets().listMembers.txtAreaCont.txtArea.position := wgt.Widgets().listMembers.txtAreaCont.txtArea.maxScroll
   end
   
   func OnMembersChanged(p : params) : bool
      //AutoScrollMemebers()
      return true
   end
   
   func AutoScrollMessages()
      wgt.Widgets().listMessages.txtAreaCont.txtArea.position := wgt.Widgets().listMessages.txtAreaCont.txtArea.maxScroll   
   end
   
   func OnMessagesChanged(p : params) : bool
      AutoScrollMessages() : 0
      return true      
   end
   
   func GetMessagesHeight() : float
      var ret : float = 0
      ret := 44 + GetChatHeight()
      return ret      
   end
   
   func GetMessagesHeightDelayed() : float
      var ret : float = 0
      ret := 44 + GetChatHeightDelayed()
      return ret      
   end
   
   func GetMessagesWidth() : float
      var ret : float = 700
      if (IsMembersVisible())
         ret := 490
      end
      return ret      
   end
   
   func GetMembersHeight() : float
      var ret : float = 0
      ret := 44 + GetChatHeight()
      return ret      
   end
   
   func GetMembersHeightDelayed() : float
      var ret : float = 0
      ret := 44 + GetChatHeightDelayed()
      return ret      
   end
   
   func GetMembersWidth() : float
      var ret : float = 290
      return ret      
   end
   
   func SendMessage(p : params) : bool
      var txt     : string    = wgt.Widgets().inputCont.inputTf.text
      var wtxt    : wstring   = wgt.Widgets().inputCont.inputTf.wtext
      wgt.Widgets().inputCont.inputTf.text := ""
      if (txt != "" and CanSendMessage())
         var command : wstring = $hq.ChatExtractCommand(wtxt)
         if (command == $UiGlobals.String2WString(""))
            // send message
            var selectedChannel : int = GetSelectedChannel()
            if (selectedChannel == $uiEnums.CHAT_CHANNEL_ALL)
               $hq.ChatSendGeneral(wtxt)
            elif (selectedChannel == $uiEnums.CHAT_CHANNEL_PARTY)
               $hq.ChatSendParty(wtxt)
            elif (selectedChannel == $uiEnums.CHAT_CHANNEL_GAME_ALL)
               $hq.ChatSendGameAll(wtxt)
            elif (selectedChannel == $uiEnums.CHAT_CHANNEL_CLAN)
               $hq.ChatSendClan(wtxt)
            elif (selectedChannel == $uiEnums.CHAT_CHANNEL_PRIVATE)
               $hq.ChatSendPrivate(privateMessagesTarget.Get(), wtxt)
            end
         else
            $hq.ChatSendCommand(command)
         end
      end
      return true
   end
   
   func CanSendMessage() : bool
      var ret : bool  = true      
      var selectedChannel : int = GetSelectedChannel()
      if (selectedChannel == $uiEnums.CHAT_CHANNEL_NEWS)
         ret := false
      elif (selectedChannel == $uiEnums.CHAT_CHANNEL_PRIVATE)
         ret := CanSendPrivate()
      end
      return ret
   end
   
   func GetDefaultInputText() : wstring
      var ret : wstring = $UiGlobals.String2WString("main_chat_input")
      var selectedChannel : int = GetSelectedChannel()
      if (selectedChannel == $uiEnums.CHAT_CHANNEL_PRIVATE)
         if (CanSendPrivate())
            var ud   : UserData = (UserData)$UserDataStorage.users.Get(privateMessagesTarget.Get())
            var p    : params
            p.lb     := $UiGlobals.String2WString("[")
            p.nick   := ud.base.full_nickname.Get()
            p.rb     := $UiGlobals.String2WString("]: ~")
            ret      := p.lb
            ret      := ret + p.nick
            ret      := ret + p.rb
         else
            ret := $UiGlobals.String2WString("main_chat_input_private")
         end
      else if (!CanSendMessage())
         ret := $UiGlobals.String2WString("main_chat_input_disabled")
      end
      return ret      
   end
   
   func CanSendPrivate() : bool
      var ret : bool = false
      ret := $UserDataStorage.IsValidUID(privateMessagesTarget.Get()) and ! $UserDataStorage.IsLocalUID(privateMessagesTarget.Get())
      return ret
   end
   
   func OnSetChatPrivateUser(p : params) : bool
      if (! IsVoid(p.uid))
         SwithToPrivate(p.uid)
      end
      return true
   end
   
   func GetPlayerCardVM() : RosterCardVM 
      return rosterCard
   end
   
   func SwithToPrivate(_uid : *)
      privateMessagesTarget.Set(_uid)
      tabs.SetSelectedTabIdx(9)
   end
   
   func OnLinkClicked(p : params) : bool
      if (!IsVoid(p.text) and p.text != "")
         //SwithToPrivate($UiGlobals.String2Int64(p.text))
         isPlayerCardVisible.Set(false)
      end
      return true
   end
   
   func OnLinkMouseOver(p : params) : bool
      if (!IsVoid(p.text) and p.text != "")
         userContext.uid      := $UiGlobals.String2Int64(p.text)
         userContext.canOpen  := true
         isPlayerCardVisible.Set(false)
      else
         userContext.canOpen  := false
         isPlayerCardVisible.Set(false)
      end
      playerUID.value.Set($UiGlobals.GetInvalidUIDVal())
      rosterCard.SetUID(playerUID)
      return true
   end
   
   func OnLinkMouseOut(p : params) : bool      
      userContext.canOpen  := false
      playerUID.value.Set(userContext.uid)
      rosterCard.SetUID(playerUID)
      isPlayerCardVisible.Set(false)
      return true
   end
   
   func GetStyleSheet() : vector
      return chatStyleSheet.GetStyleSheet()
   end
end

/*************************************************************
* UiChatMessageLIRVM
* 
*************************************************************/
class UiChatMessageLIRVM
   var mes           : ObservableProperty = $OM.Property(null)
   var userContext   : UserContextMenu    = new UserContextMenu()
   
   func Init(p : params)
      if (! IsVoid(p.message))         
         var mesVal : GL_ChatStreamMessage = (GL_ChatStreamMessage)p.message
         if ($UserDataStorage.IsValidUID(mesVal.sender_user_id.Get()))
            $user_service.RequestData(mesVal.sender_user_id.Get(), $uiEnums.USER_DATA_BASE)
            userContext.uid := mesVal.sender_user_id.Get()
         end
         mes.Set(mesVal)
      end
   end
   
   func GetMessage() : GL_ChatStreamMessage
      var ret : GL_ChatStreamMessage = (GL_ChatStreamMessage)mes.Get()
      return ret
   end
      
   func GetText() : wstring
      var ret : wstring
      var mesVal : GL_ChatStreamMessage = GetMessage()
      if (mesVal != null)
         var ud : UserData = (UserData)$UserDataStorage.users.Get(mesVal.sender_user_id.Get())
         var p : params
         if ($UserDataStorage.IsValidUID(mesVal.sender_user_id.Get()))
            var nickName : wstring = ud.base.full_nickname.Get()
            p.nick   := $root.MakeColorCodedWText(nickName, $UserDataStorage.GetPlayerStatusColorCode(mesVal.sender_user_id.Get()))
         else
            p.nick   := $root.MakeColorCodedWText($UiGlobals.String2WString("SYSTEM"), "#FFFF00")
         end
         p.time      := $root.MakeColorCodedWText($UiGlobals.String2WString("[00:00] "), "#808080")
         p.delim     := $root.MakeColorCodedWText($UiGlobals.String2WString(" : "), "#808080")
         p.mes       := mesVal.text.Get()
         
         ret := ret + p.time
         ret := ret + p.nick
         ret := ret + p.delim
         ret := ret + p.mes
      end
      return ret
   end
end

/*************************************************************
* UiChatMembersLIRVM
* 
*************************************************************/
class UiChatMembersLIRVM
   var uid           : ObservableProperty = $OM.Property($UiGlobals.GetInvalidUIDVal())
   //var mes           : ObservableProperty = $OM.Property("")
   var userContext   : UserContextMenu    = new UserContextMenu()
   
   func Init(p : params)
      uid.Set($UiGlobals.GetInvalidUIDVal())
      if (! IsVoid(p.uid))
         if ($UserDataStorage.IsValidUID(p.uid))
            $user_service.RequestData(p.uid, $uiEnums.USER_DATA_BASE)
            userContext.uid := p.uid
         end
         uid.Set(p.uid)
      end
   end
   
   func GetUID() : *
      return uid.Get()
   end
   
   func GetUserData() : UserData
      var ud : UserData = (UserData)$UserDataStorage.users.Get(GetUID())
      return ud
   end
   
   func GetNickname() : wstring
      var ud   : UserData  = GetUserData()
      var ret  : wstring    = ud.base.full_nickname.Get()
      ret := $root.MakeColorCodedWText(ret, $UserDataStorage.GetPlayerStatusColorCode(GetUID()))
      return ret
   end   
end


/*************************************************************
* UiChatMessage
* 
*************************************************************/
class UiChatMessage : UiWidgetContainer
   func inputEvent(p : params) : bool
      var isTerminated  : bool   = false
      var keyCode       : int    = p.keyCode
      if (p.isDown == false)
         if (keyCode == $uiKeys.VK_ENTER)
            GenerateEvent("#SendMessage")
            isTerminated := true
         end
      end
      if (keyCode == $uiKeys.VK_DOWN or keyCode == $uiKeys.VK_UP or keyCode == $uiKeys.VK_TAB)
         isTerminated := true
      end
      if (isTerminated)
         p.eventState.SetIsTerminated(isTerminated)
      end
      return false
   end
   
   func focusIn(p : params) : bool
      return false
   end
end


/*************************************************************
* UiChatMembersListCont
* 
*************************************************************/
class UiChatMembersListCont : UiWidgetContainer
   handle OnEnteringState("Initial")
      Props().visible := false
   end
   
   handle OnEnteringState("Visible")
      Props().visible := true      
   end
end

/*************************************************************
* UiChatMessagesListCont
* 
*************************************************************/
class UiChatMessagesListCont : UiWidgetContainer
   handle OnEnteringState("Small")
      Props().x      := 215
      //Widgets().listContentAttach.messages._width := 475
   end
   
   handle OnEnteringState("Full")
      Props().x      := 10
      //Widgets().listContentAttach.messages._width := 695
   end   
end

/*************************************************************
* ChatTab
* 
*************************************************************/
class ChatTab : UiWidgetButton
   func focusIn(p : params) : bool
      return false
   end   
end

/*************************************************************
* ChatExpandBtn
* 
*************************************************************/
class ChatExpandBtn : UiWidgetButton
   override StartDrag   
      GenerateEvent("#ChatStartDrag")
      return null
   end   
   
   func OnChatDrag(p : params) : bool
      GenerateEvent("#ChatDrag", p)
      return false
   end      
   
   func focusIn(p : params) : bool
      return false
   end
   
   func focusOut(p : params) : bool
      return false
   end
end