import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_button
import ui.root
import ssl.hf2p.ui_globals
import ssl.hf2p.user_data
import ui.libs.hf2p_Default_lib.hf2p_Default_lib
import ui.hf2p_SlidingScreens.hf2p_Lobby.hf2p_Lobby
import ui.libs.hf2p_Chat_lib.hf2p_Chat_lib

/*************************************************************
* UiIngameChatMessageCont
* 
*************************************************************/
class UiIngameChatMessageCont : UiWidgetContainer
   var MESSAGE_PHASE_INITIAL        : int    = 0
   var MESSAGE_PHASE_VISIBLE        : int    = 1
   var MESSAGE_PHASE_FORCE_VISIBLE  : int    = 2
   var MESSAGE_PHASE_HIDDEN         : int    = 3
   
   var phase                        : int    = MESSAGE_PHASE_INITIAL   
   var suspendTimeOff               : float  = 0
   
   func StartFadeIn(_fadeOutDelay : float)
      if (phase != MESSAGE_PHASE_VISIBLE and phase != MESSAGE_PHASE_HIDDEN)
         var fadeoutDelay : float = _fadeOutDelay
         if (phase == MESSAGE_PHASE_INITIAL)
            DoFadeIn()
         elif (phase == MESSAGE_PHASE_FORCE_VISIBLE)
            fadeoutDelay := fadeoutDelay + suspendTimeOff
         end
         KillDelays()
         phase := MESSAGE_PHASE_VISIBLE            
         StartFadeOut() : fadeoutDelay, FADE_IN_DELAY
      end
   end
   
   func HideMessage()
      RemTweens()
      KillDelays()     
      SetInitial()
   end
      
   func SetInitial()
      KillDelays()
      GotoAndStop("hidden")
      phase := MESSAGE_PHASE_INITIAL
   end
         
   func StartFadeOut()
      if (phase != MESSAGE_PHASE_HIDDEN and phase != MESSAGE_PHASE_INITIAL)
         DoFadeOut()
         KillDelays()
         phase := MESSAGE_PHASE_HIDDEN
      end
   end
   
   func SetVisible(_suspendTimeOff : float)
      KillDelays()
      if (phase != MESSAGE_PHASE_FORCE_VISIBLE)
         if (phase != MESSAGE_PHASE_VISIBLE)
            DoFadeIn()            
         end
         phase := MESSAGE_PHASE_FORCE_VISIBLE
      end
      suspendTimeOff := _suspendTimeOff
   end
   
   func StartPosTween(_varName : string, _from : float, _to : float, _time: float, _isNew : bool)
      //Set(_varName, _to)
      //return
      
      if (_isNew)
         //RemTweens()
         Set(_varName, _to)
      else
         var curVal : float = (float)Get(_varName)
         if (curVal != _to)
            //RemTweens()
         
            var tweenParm : params
            tweenParm.propName   := _varName
            //tweenParm.startVal   := curVal
            tweenParm.endVal     := _to
            tweenParm.duration   := _time
            tweenParm.fadeType   := "linear"

            AddTweenCb("TweenFunc", tweenParm) 
         end
      end
      
   end
   
   func KillDelays()
      delay kill, this, FADE_IN_DELAY
      delay kill, this, FADE_OUT_DELAY
   end
   
   func DoFadeOut()
      GotoAndPlay("fadeOut")
   end
   
   func DoFadeIn()
      GotoAndPlay("fadeIn")
   end
end

/*************************************************************
* UiIngameChat
* 
*************************************************************/
class UiIngameChat : UiWidgetContainer
   
   func FocusInputText()
      Widgets().ingameChatCont.inputCont.inputTf.textField.SetFocus()
   end
   
   func ClearInputText()
      Widgets().ingameChatCont.inputCont.inputTf.text := ""
   end
   
   handle OnEnterState("Hidden")
      Props().visible := false
      GenerateEvent("#IngameChatClosed")
   end
   
   handle OnEnterState("Visible")
      Props().visible := true
      GenerateEvent("#IngameChatVisible")
   end
   
   handle OnEnterState("Active")
      Props().visible := true
      ClearInputText()
      FocusInputText()
      GenerateEvent("#IngameChatActive")
   end
   
   func GetMessageById(_mesId : string) : UiIngameChatMessageCont
      var ret : UiIngameChatMessageCont = (UiIngameChatMessageCont)Widgets().ingameChatCont.messagesCont.GetWidget(_mesId)
      return ret
   end
   
end

/*************************************************************
* UiIngameChatMessageVM
* 
*************************************************************/
class UiIngameChatMessageVM   
   var mes           :  ObservableProperty   = $OM.Property(null)
   var ypos          :  ObservableProperty   = $OM.Property(0.0)
   var xpos          :  ObservableProperty   = $OM.Property(0.0)
   var xrot          :  ObservableProperty   = $OM.Property(0.0)
   var yrot          :  ObservableProperty   = $OM.Property(0.0)  
   var zrot          :  ObservableProperty   = $OM.Property(0.0)  
   var mesObservable :  ObservableProperty   = $OM.Calculated(this, "GetMessageText")
      
   func GetMessageText() : wstring
      var ret     : wstring
      var mesVal  :  GL_ChatStreamMessage = (GL_ChatStreamMessage)mes.Get()
      if (mesVal != null)
         ret := mesVal.GetFormattedText(false, true)
      end
      return ret
   end
   
   func Invalidate()
      mesObservable.Invalidate()
   end      
end

/*************************************************************
* UiIngameChatVM
* 
*************************************************************/
class UiIngameChatVM
   var wgt                    : UiIngameChat       = null
   var messagesMap            : ObservableMap      = $OM.Map()
   var currentChannel         : int                = -1
   var messagesMapObservable  : ObservableProperty = $OM.Calculated(this, "GetChatMessages")
   var isSubscribedToStream   : bool               = false
   var isInteractive          : ObservableProperty = $OM.Property(false)
   var uiStyleSheet           : UiSSIngameChat     = new UiSSIngameChat()

   func Init(p : params)
      wgt := p.widget
   end
   
   func Term()
      UnsubscribeFromChannel()
   end
         
   func UiIngameChatVM()
   end
   
   func GetStyleSheet() : vector
      return uiStyleSheet.GetStyleSheet()
   end
   
   func GetChatChannel() : int
      var ret : int = $uiEnums.CHAT_CHANNEL_ALL
      return ret
   end   
   
   func GetMessagesVector() : vector
      return $UiGlobals.GetChatMessages(GetChatChannel())
   end
      
   func SubscribeToChannel(_channel : int)
      UnsubscribeFromChannel()
      currentChannel := _channel
      var stream : GL_ChatStream = $UiGlobals.GetChatMessagesStream(currentChannel)
      if (stream != null)
         stream.messages.Subscribe(this, "UpdateChatMessages")
      end
      UpdateChatMessages()
      messagesMapObservable.Invalidate()
   end
   
   func UnsubscribeFromChannel()
      var stream : GL_ChatStream = $UiGlobals.GetChatMessagesStream(currentChannel)
      if (stream != null)
         stream.messages.Unsubscribe(this, "UpdateChatMessages")
      end
      messagesMap.Clear()
      currentChannel := -1
   end
   
   func SetChannel(_channel : int)
      if (currentChannel != _channel)
         SubscribeToChannel(_channel)
      end
   end   
   
   func GetChatMessages() : ObservableMap
      return messagesMap
   end   
   
   func IsInteractive() : bool
      return (bool)isInteractive.Get()
   end
   
   func UpdateChatMessages() : ObservableMap      
      var chatStream    : GL_ChatStream   = $UiGlobals.GetChatMessagesStream(currentChannel)
      var messagesList  : vector          = GetMessagesVector()
      var i             : int
      var isFull        : bool   = false
      var totalHeight   : float  = 0
      var maxHeight     : float  = 200
      var idx           : int    = 0
      var rotScale      : float  = 0.1      
      
      for i := messagesList.Count() - 1 downto 0    
         idx := idx + 1
         var mes     : GL_ChatStreamMessage     = messagesList.Get(i)
         var mesId   : string = "message_" + i
         var isOld   : bool   = false         
         if (chatStream != null)
            isOld := $UiGlobals.CmpInt64(chatStream.GetLastViewTime(), mes.timestamp.Get()) >= 0
         end
         
         if (isFull)
            if (messagesMap.Contains(mesId))
               var mesWgt : UiIngameChatMessageCont = wgt.GetMessageById(mesId)
               if (mesWgt != null)
                  mesWgt.HideMessage()
               end
               messagesMap.Remove(mesId)
            end
         else
            var mesVM   : UiIngameChatMessageVM = null
            var isNew   : bool                  = false
            
            if (messagesMap.Contains(mesId))
               mesVM := (UiIngameChatMessageVM)messagesMap.Get(mesId)
            elif (! isOld)
               isNew := true
               mesVM := new UiIngameChatMessageVM()
               messagesMap.Insert(mesId, mesVM)
            end
            
            if (mesVM != null)            
               mesVM.mes.Set(mes)
               var mesWgt : UiIngameChatMessageCont = wgt.GetMessageById(mesId)
               if (mesWgt != null)
                  mesVM.Invalidate()
                  var textHeight : float = mesWgt.Widgets().messageCont.Props().textFieldHeight
                  totalHeight := totalHeight + textHeight + 3
                  if (totalHeight > maxHeight)
                     isFull := true
                  end
                  var factor01   : float = totalHeight / maxHeight
                  var factor10   : float = 1 - factor01
                  if (factor10 < 0) 
                     factor10 := 0
                  end
                  var factor     : float = 10 * factor01
                  var ypos       : float = 200 - totalHeight
                  var xpos       : float =   factor * 0.5
                  var xrot       : float = - factor * 1.0 * rotScale
                  var yrot       : float = - factor * 5.0 * rotScale
                  var zrot       : float =   factor * 4.0 * rotScale
                  var animTime   : float = 0.20
                  
                  mesWgt.StartPosTween("y",           (float)mesVM.ypos.Get(), ypos, animTime, isNew)
                  mesWgt.StartPosTween("x",           (float)mesVM.xpos.Get(), xpos, animTime, isNew)
                  mesWgt.StartPosTween("xrotation",   (float)mesVM.xrot.Get(), xrot, animTime, isNew)
                  mesWgt.StartPosTween("yrotation",   (float)mesVM.yrot.Get(), yrot, animTime, isNew)
                  mesWgt.StartPosTween("rotation",    (float)mesVM.zrot.Get(), zrot, animTime, isNew)
                  
                  if (IsInteractive())
                     mesWgt.SetVisible(factor10 * 5)
                  else
                     var isFullClose : bool = totalHeight > (maxHeight * 0.75)
                     if (isFullClose)
                        mesWgt.StartFadeOut()
                     else
                        mesWgt.StartFadeIn(7.0)
                     end
                  end
               end
            end
         end
      end
      
      if (chatStream != null)
         chatStream.UpdateLastViewTime()
      end
      
      return messagesMap
   end
   
   func GetChatTarget() : string      
      var ret           : string = ""
      var channelDesc   : string = $UiGlobals.GetChatStreamName(GetChatChannel())
      if (channelDesc != "")
         ret := "[{STRING}]:~" + channelDesc
      end
      ret := "[ALL]:~"
      return ret
   end
   
   func SendMessage(p : params) : bool
      var txt  : string    = wgt.Widgets().ingameChatCont.inputCont.inputTf.text
      var wtxt : wstring   = wgt.Widgets().ingameChatCont.inputCont.inputTf.wtext
      wgt.Widgets().ingameChatCont.inputCont.inputTf.text := ""
      if (txt != "")
         // send message
         var selectedChannel : int = GetChatChannel()
         if (selectedChannel == $uiEnums.CHAT_CHANNEL_ALL)
            $hq.ChatSendGeneral(wtxt)
         elif (selectedChannel == $uiEnums.CHAT_CHANNEL_PARTY)
            $hq.ChatSendParty(wtxt)
         elif (selectedChannel == $uiEnums.CHAT_CHANNEL_GAME_ALL)
            $hq.ChatSendGameAll(wtxt)
         elif (selectedChannel == $uiEnums.CHAT_CHANNEL_CLAN)
            $hq.ChatSendClan(wtxt)
         end
      end
      return true
   end
   
   func IngameChatClosed(p : params) : bool
      isInteractive.Set(false)
      UnsubscribeFromChannel()
      UpdateChatMessages()
      return true
   end
   
   func IngameChatActive(p : params) : bool
      SetChannel($uiEnums.CHAT_CHANNEL_ALL)
      isInteractive.Set(true)
      UpdateChatMessages()
      return true      
   end   
   
   func IngameChatVisible(p : params) : bool
      SetChannel($uiEnums.CHAT_CHANNEL_ALL)
      isInteractive.Set(false)
      UpdateChatMessages()
      return true      
   end   
end

/*************************************************************
* UiIngameChatMessage
* 
*************************************************************/
class UiIngameChatMessage : UiWidgetContainer
   func inputEvent(p : params) : bool
      var isTerminated  : bool   = false
      var keyCode       : int    = p.keyCode
      if (p.isDown == false)
         if (keyCode == $uiKeys.VK_ENTER)
            GenerateEvent("#SendMessage")
            isTerminated := true
         end
      end
      
      // SHOULD BE PROCESSED SOMEWHERE ELSE, TO BLOCK OPENING OF MAINMENU
      if (keyCode == $uiKeys.VK_ESC)
         isTerminated := true
      end
      
      if (keyCode == $uiKeys.VK_DOWN or keyCode == $uiKeys.VK_UP or keyCode == $uiKeys.VK_TAB)
         isTerminated := true
      end
      if (isTerminated)
         p.eventState.SetIsTerminated(isTerminated)
         
         // SHOULD BE PROCESSED SOMEWHERE ELSE TOO
         if ($UiIngame.chat.IsVisible())
            $UiIngame.chat.state.Set($uiEnums.INGAME_WIDGET_STATE_HIDDEN)
         end
         
      end
      return false
   end
   
   func focusIn(p : params) : bool
      return false
   end
end
