import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_manager
import ssl.hf2p.engine_ctrl
import ssl.hf2p.items_mgr
import ssl.observables
import ssl.hf2p.ui_globals
import ssl.hf2p.hq
import ui.root
import ui.ui_economy
import ui.ui_player_info

class UiBoostScr : UiWidgetContainer  

handle OnEnteringState("ContentVisible")
   Log("ui~UiBoostScreen", "UiBoostScreen_ContentVisible")
   //BoostScreenInit()
   GenerateEvent("UpdateBoosts")
   $UiBiLogger.LogGlobalStateChange($uiEnums.UI_BI_BUY_MODIFIERS)
   Set("visible", true)
end

handle OnEnteringState("ContentInitial")
   Log("ui~UiBoostScreen", "UiBoostScreen_ContentInitial")
   Set("visible", false)
end

func BoostScreenInit()
   var i : int
   var shop : GL_ShopRace = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get(GetRaceIdx())
   var shopSection  : GL_ShopSection = shop.FindInternalSection("section_account_modifiers")
   var shopShelf    : GL_ShopShelf = shopSection.FindShelf("shelf_account_modifiers")
   for i := 0 to shopShelf.items.Get().Count() - 1  
      var modifId      : string = (string)shopShelf.items.Get().Get(i).value.Get()
      FillModifiers(modifId)
   end
end

func FillModifiers(modifId : string)
   $UiGlobals.shop.race_shops.Get().Get($UserDataStorage.local_user.race.Get()).FindInternalSection("section_account_modifiers").FindShelf("shelf_account_modifiers")
   var compUi       : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(modifId)
   var shopComp     : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(modifId)
   var modifOffer   : GL_ComponentShopOffer = (GL_ComponentShopOffer)shopComp.offers.Get().Get(0)
end

func GetRaceIdx() : int
   var idx: int = (int)$UserDataStorage.local_user.race.Get()
   return idx
end

end // UiBoostScr

class BoostOfferLine : UiWidgetContainer
   
   func onBoostGpBtnClick(p : params) : bool
      var offer = (GL_ComponentShopOffer)GetDC()
      var boostId       : string = (string)GetParentWidget().GetDC().modif_id.Get()
      var offerId       : string  = offer.GetGlOffer()
      var offerGl       : int     = offer.GetGlCost()
      var par           : params
      par.mbType        := "ConfirmBuy"
      par.itemID        := boostId
      par.isGold        := true
      par.offer         := offerId
      par.priceAmount   := offerGl
      par.priceUnit     := $uiEnums.TOKEN_GOLD
      //par.callbackEvent := "OnBoostPurchased"
      par.titleTxt      := "msg_ui_boost_buy"
      par.messageTxt    := ""
      par.subTxt        := "msg_ui_boost_buy_message"
      $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
      return false
   end
   
   func onBoostCrBtnClick(p : params) : bool
      var offer = (GL_ComponentShopOffer)GetDC()
      var boostId       : string = (string)GetParentWidget().GetDC().modif_id.Get()
      var offerId       : string  = offer.GetCrOffer()
      var offerCr       : int     = offer.GetCrCost()
      var par           : params
      par.mbType        := "ConfirmBuy"
      par.itemID        := boostId
      par.isGold        := false
      par.offer         := offerId
      par.priceAmount   := offerCr
      par.priceUnit     := $uiEnums.TOKEN_CREDITS
      //par.callbackEvent := "OnBoostPurchased"
      par.titleTxt      := "msg_ui_boost_buy"
      par.messageTxt    := ""
      par.subTxt        := "msg_ui_boost_buy_message"
      $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
      return false
   end
   
end

class BoostVM
   var itemIdx : int
   
   var modif_id : ObservableProperty = $OM.Calculated(this, "GetModifId")
   
   func Init(p : params)
      itemIdx := p.idx
   end
   
   func OnUpdateBoosts(p : params) : bool
      modif_id.Invalidate()
      return false
   end
   
   func GetModifId() : string
      var ret : string = ""
      if (! IsVoid ($UiGlobals.shop.race_shops))
         var shop = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get($UserDataStorage.local_user.race.Get())
         if (!IsVoid(shop.FindInternalSection("section_account_modifiers")))
            var section = shop.FindInternalSection("section_account_modifiers")
            if (section != null and ! IsVoid(section.FindShelf("shelf_account_modifiers")))
               var shelf = section.FindShelf("shelf_account_modifiers")
               if (shelf != null and ! IsVoid(shelf.items.Get()))
                  if (itemIdx <= shelf.items.Get().Count() - 1) 
                     ret := (string)shelf.items.Get().Get(itemIdx).value.Get()
                  end   
               end
            end
         end
      end   
      return ret
   end
   
   func GetOffer(offer_idx : int) : GL_ComponentShopOffer
      if ($root.IsLoggedIn())
         var shopComp    : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)modif_id.Get())
         if (shopComp.offers.Get().Count() > 0)
            var ret = (GL_ComponentShopOffer)shopComp.offers.Get().Get(offer_idx)
            return ret
         end
      end
      return null
   end
   
   func GetOfferCostLabel(val : int) : string
      var ret : string = "carousel_offer_na_small"
      if (val > 0)
         ret := (string)val
      end
      return ret
   end
   
   func EnableOfferLine(val : int) : bool
      var ret : bool = false
      if (val > 0)
         ret := true
      end
      return ret
   end
   
   func GetRentTime() : int
      var ret     : int
      var itemId  : string = (string)modif_id.Get()
      if ($uiEconomy.GetItemOwnType(itemId) == $uiEnums.ITEM_OWN_TYPE_RENTED)
         var uiInventoryItem : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(itemId)
         var ownTime : int = (int)uiInventoryItem.ownership_time.Get() - (int)$UiGlobals.timer.Get()
         ret := ownTime
      end
      return ret   
   end
   
   func GetRentLabel() : wstring
      var ret     : wstring      
      var itemId  : string = (string)modif_id.Get()
      if ($uiEconomy.GetItemOwnType(itemId) == $uiEnums.ITEM_OWN_TYPE_RENTED)
         ret := $root.MakeUiTimerStringMinutes(GetRentTime(), true)
         //ret := $root.MakeUiTimerSubHead(GetRentTime())
      end
      return ret
   end
   
   func GetCompUI() : GL_ComponentUI
      var ret : GL_ComponentUI = null
      if ($root.IsLoggedIn())
         ret := (GL_ComponentUI)$UiGlobals.componentsUI.Get(modif_id.Get())
      end
      return ret
   end
   
   func GetSubHeader() : string
      var ret : string = ""
      if ((string)modif_id.Get() == "xp_booster")
         ret := "main_ui_xp"
      elif ((string)modif_id.Get() == "cr_booster")
         ret := "main_ui_cr"
      elif ((string)modif_id.Get() == "challenges_booster")
         ret := "main_ui_challenge"   
      end
      return ret
   end
   
   func GetTint(idx : int) :  params
      var p : params
      if (idx == 0) // crClr
         p.r  := 67
         p.g  := 195
         p.b  := 232
      elif (idx == 1) // xpClr
         p.r  := 30
         p.g  := 195
         p.b  := 131
      elif (idx == 2)
         p.r  := 159
         p.g  := 120
         p.b  := 199
      end
      return p
   end
   
end // BoostVM
