import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_button
import ui.root
import ssl.hf2p.ui_globals
import ssl.hf2p.user_data
import ui.libs.hf2p_Default_lib.hf2p_Default_lib
import ui.hf2p_SlidingScreens.hf2p_Lobby.hf2p_Lobby
import ssl.lib.types
import ssl.lib.ui.ui_widget_text_area

/*************************************************************
* UiChat
* 
*************************************************************/
class UiChat : UiWidgetContainer
   func OnSetFocusInputText(p : params) : bool
      $sslWidgetMgr.GenerateEvent("closeRosterDockerAsNiceAsYouCan")
      ClickedInside()
      FocusInputText()
      return false
   end
   
   func FocusInputText()
      Widgets.inputCont.inputTf.SetFocus()
   end
   
   func ClearInputText()
      Widgets.inputCont.inputTf.text := ""
   end
   
   func TweenChatSize(updType:string)
      GetDC().TweenChatSize(updType)
   end
   
   func CustomSet(propName : string, propVal : *) : bool
      if (propName == "tabsData")
         GetDC().SetTabsData(propVal)
         return true
      end
      return false
   end
   
   func focusIn(p : params) : bool
      if (! IsVoid(p.toWidget))
         var toWidget : UiWidget = p.toWidget
         if (toWidget.IsChildOf(this))
            //GetDC().FocusReceived()
         end
      end
      return false
   end
   
   func focusOut(p : params) : bool
      if (! IsVoid(p.toWidget))
         var toWidget   : UiWidget = p.toWidget
         if (! toWidget.IsChildOf(this))
            //GetDC().FocusLost()            
         end
      else
         //GetDC().FocusLost()
      end
      return false
   end
   
   func ProcessMouseDown(target : UiWidget)      
      var chatExpand = (UiWidget)(Widgets.expandBtn.object)
      var chatTabs   = (UiWidget)(Widgets.tabsCont.object)
      if (target.IsChildOf(this))
         if (!target.IsChildOf(chatExpand) and !target.IsChildOf(chatTabs))
            ClickedInside()
         end
      else
         ClickedOutside()
      end      
   end
   
   func ClickedInside()
      $UiBiLogger.LogChatState("Expanded", "")
      GetDC().FocusReceived()
   end
   
   func ClickedOutside()
      $UiBiLogger.LogChatState("Collapsed", "")
      GetDC().FocusLost()      
   end   
end

/*************************************************************
* UiTabVM
* 
*************************************************************/
class UiTabVM
   var tabIdx           : int = 0
   var data             : ObservableProperty = $OM.Property(null)
   var isSelected       : ObservableProperty = $OM.Property(false)
   
   func OnTabSelected()
      
   end
   
   func OnTabOut()
   end
   
   func IsValid() : bool
      return true
   end
end

/*************************************************************
* UiTabsVM
* 
*************************************************************/
class UiTabsVM
   var items         : vector
   var selectedTab   : ObservableProperty = $OM.Property(0)
   var countChanged  : bool               = false
   
   func GetMaxTabs() : int
      return 0
   end
   
   func GetDefaultEntry() : *
      var ret : params
      return ret
   end
   
   func GetTabs() : vector
      var ret : vector
      return ret
   end
   
   func SetItems(_items : vector)
      items :=_items
      ArrangeTabs()
   end
   
   func CheckSelectedTabIdx()
      var tabs : vector = GetTabs()
      if (tabs.Count() > 0)
         var selectedIdx : int = GetSelectedTabIdx()
         if (selectedIdx >= tabs.Count())
            selectedIdx := tabs.Count() - 1
         elif (selectedIdx < 0)
            selectedIdx := 0
         end
         
         var isValidTab : bool = false
         while (selectedIdx >= 0 and selectedIdx < tabs.Count())
            var tabVM : UiTabVM = tabs.Get(selectedIdx)
            if (tabVM.IsValid())
               isValidTab := true
               break
            else
               selectedIdx := selectedIdx + 1
            end
         end
         if (! isValidTab)
            while (selectedIdx >= 0 and selectedIdx < tabs.Count())
               var tabVM : UiTabVM = tabs.Get(selectedIdx)
               if (tabVM.IsValid())
                  isValidTab := true
                  break
               else
                  selectedIdx := selectedIdx - 1
               end
            end
         end
         if (isValidTab)
            SetSelectedTabIdx(selectedIdx)
         else
            SetSelectedTabIdx(0)
         end
      end      
   end
   
   func Refresh()
      CheckSelectedTabIdx()
      if (countChanged)
         countChanged := false
         InvalidateCurrentTab()
      end
   end
   
   func InvalidateCurrentTab()
      
   end
   
   func SetSelectedTabIdx(_tabIdx : int)
      if (_tabIdx != (int)selectedTab.Get())
         selectedTab.Set(_tabIdx)
         var tabs : vector = GetTabs()
         var i    : int
         for i := 0 to tabs.Count() - 1
            var tab : UiTabVM = (UiTabVM)tabs.Get(i)
            if (_tabIdx == i)
               tab.OnTabSelected()
            else
               tab.OnTabOut()
            end
            tab.isSelected.Set(_tabIdx == i)
         end
         SelectedTabUpdated()
      end
   end
   
   func SelectedTabUpdated()
      
   end
   
   func GetSelectedTabIdx() : int
      return (int)selectedTab.Get()
   end
   
   func GetSelectedTab() : UiTabVM
      var selectedIdx : int = GetSelectedTabIdx()
      var ret : UiTabVM = GetTabs().Get(selectedIdx)
      return ret
   end
   
   func GetSelectedTabData() : ObservableProperty
      var selectedIdx : int = GetSelectedTabIdx()
      var ret : UiTabVM = GetTabs().Get(selectedIdx)
      return ret.data
   end
   
   func ArrangeTabs()
      
   end
      
   func GetItems() : vector
      return items
   end
   
   func GetTabsCount() : int
      var ret : int = GetTabs().Count()
      return ret
   end
         
   func TabClicked(p : params) : bool
      var tab : UiTabVM = p.widget.GetParentWidget().GetDC()
      SetSelectedTabIdx(tab.tabIdx)
      return false
   end
end

/*************************************************************
* UiChatTabVMData
* 
*************************************************************/
class UiChatTabVMData
   var idx           : int       = 0
   var channel       : int       = 1
   var name          : wstring   = ""
   var streamName    : string    = ""
   var privateUid    : *         = $UserDataStorage.GetInvalidUID()
   var isTextValid   : bool      = false   
   var txtIdx        : int       = -1
end

/*************************************************************
* UiChatTabVM
* 
*************************************************************/
class UiChatTabVM : UiTabVM
   var xoffset          :  ObservableProperty   = $OM.Property(0.0)
   var isValidTab       :  ObservableProperty   = $OM.Property(false)
   var tabWidth         :  ObservableProperty   = $OM.Property(100.0)
   var tabOffset        :  ObservableProperty   = $OM.Property(0.0)
   var notifOffset      :  ObservableProperty   = $OM.Property(0.0)
   var tabScale         :  ObservableProperty   = $OM.Property(1.0)
   var tabScaleInv      :  ObservableProperty   = $OM.Property(1.0)
   var isNewMessages    :  ObservableProperty   = $OM.Calculated(this, "GetIsNewMessages")
   var newMessagesCount :  ObservableProperty   = $OM.Calculated(this, "GetNewMessagesCountStr")
   
   var userContext      : UserContextMenu = new UserContextMenu()
   
   func Init(p : params)
   end
   
   func Term()
      var stream = GetMessageStream()
      if stream != null
         GetMessageStream().Term()
      end
   end
   
   override IsValid // () : bool
      return (bool)isValidTab.Get()
   end
   
   func SetTabData(_data : *)
      data.Set(_data)
      userContext.uid := GetChatData().privateUid
      var stream = GetMessageStream()
      if stream != null
         GetMessageStream().Init(GetChatData().channel)
      end
   end
   
   func GetChatData() : UiChatTabVMData
      return (UiChatTabVMData)data.Get()
   end
   
   func GetMessageStream() : GL_ChatStream
      var channel : int             = GetChatData().channel
      var ret     : GL_ChatStream   = $UiGlobals.GetChatMessagesStream(channel, GetChatData().privateUid)      
      return ret      
   end
   
   func GetChannelMessages() : vector
      var stream  : GL_ChatStream = GetMessageStream()
      var ret     : vector
      if (stream != null)
         ret := stream.GetMessages()
      end
      return ret      
   end
   
   func GetCurrentMessagesCount() : int
      var ret : int = GetChannelMessages().Count()
      return ret
   end
   
   func GetIsNewMessages() : bool
      var ret : bool = false
      if data.Get().channel == $uiEnums.CHAT_CHANNEL_PRIVATE and (IsVoid(data.Get().privateUid) or $UserDataStorage.IsEqualUIDs(data.Get().privateUid, $UserDataStorage.GetInvalidUID()))
         //compound private tab
         var i : int
         for i := 0 to $UiGlobals.chat.private_channels.Count() - 1
            var stream : GL_ChatStream = $UiGlobals.chat.private_channels.Get(i)
            ret := stream.NewMessagesCount() > 0
         end
      else
         //other tabs
         ret := !(bool)isSelected.Get() and GetNewMessagesCount() > 0
      end
      return ret
   end
   
   override OnTabSelected//()
      UpdateTimestamp()
   end
   
   func GetLastViewTime() : *
      var stream  : GL_ChatStream   = GetMessageStream()
      var ret     : *               = $UiGlobals.IntToInt64(0)
      if (stream != null)
         ret := GetMessageStream().GetLastViewTime()
      end
      return ret
   end
      
   func UpdateTimestamp()
      var stream  : GL_ChatStream   = GetMessageStream()
      if (stream != null)
         GetMessageStream().UpdateLastViewTime()
         newMessagesCount.Invalidate()
      end
   end
   
   override OnTabOut//()
      var stream = GetMessageStream()
      if stream != null and stream.channel != $uiEnums.CHAT_CHANNEL_PRIVATE
         stream.Deactivate()
      end
      if ((bool)isSelected.Get())
         UpdateTimestamp()
      end
   end
   
   func GetNewMessagesCount() : int
      var stream  : GL_ChatStream = GetMessageStream()
      var ret     : int
      if (stream != null)
         ret := stream.GetNewMessagesCount(stream.channel != $uiEnums.CHAT_CHANNEL_PRIVATE)
      end
      return ret      
   end      
   
   func GetNewMessagesCountStr() : string
      var ret : string  = (string)GetNewMessagesCount()
      return ret
   end      
   
   func GetCloseButtonVisible() : bool
      return !IsVoid(data.Get().privateUid) and !$UserDataStorage.IsEqualUIDs(data.Get().privateUid, $UserDataStorage.GetInvalidUID())
   end
end


class UiPrivateChatTab
   var uid : ObservableProperty = $OM.Property($UserDataStorage.GetInvalidUID())
   var isPinned : ObservableProperty = $OM.Property(true)
   
   func Init(p : params)
      uid.Set(p.uid)
   end
end

/*************************************************************
* UiChatTabsVM
* 
*************************************************************/
class UiChatTabsVM : UiTabsVM
   var parentVM         : UiChatVM = null
   var tabs             : vector
   var validTabsCount   : int = 0
   var totalWidth       : int = 730
   var offsets          : vector
   
   func Init(p : params)
      var i : int
      for i := 0 to GetMaxTabs() - 1
         var tab : UiChatTabVM = new UiChatTabVM()
         tab.tabIdx := i
         tab.Init(p)
         tabs.Push(tab)
      end
   end
   
   func Term()
      var i : int
      for i := 0 to tabs.Count() - 1
         var tab = (UiChatTabVM)tabs.Get(i)
         tab.Term()
      end
   end
   
   override GetMaxTabs//() : int
      return 10
   end
   
   override GetDefaultEntry//() : *
      var tabData :  UiChatTabVMData = null
      tabData           := new UiChatTabVMData()
      tabData.idx       := -1
      tabData.name      := ""
      tabData.channel   := -1
      return tabData
   end
   
   override GetTabs//() : vector      
      var ret : vector = tabs
      return ret
   end
   
   func GetOffsets() : vector 
      var ret : vector = offsets
      if (ret.Count() == 0)
         var i : int
         
      end
      return ret      
   end
   
   override ArrangeTabs//()
      var i          : int
      var validTabs  : int = 0
      for i := 0 to GetMaxTabs() - 1
         var tab : UiChatTabVM = GetTab(i)
         if ((bool)tab.isValidTab.Get())
            validTabs := validTabs + 1
         end
      end  
      if (validTabs > 0)
         var tabWidth   : float  = (float)totalWidth / (float)validTabs 
         var tabIdx     : int    = 0
         for i := 0 to GetMaxTabs() - 1
            var tab : UiChatTabVM = GetTab(i)
            if ((bool)tab.isValidTab.Get())
               var baseWidth : float = 70.0
               if (i == 0 or i == (GetMaxTabs() - 1))
                  baseWidth := 85.0
               end
               tab.tabWidth.Set     (tabWidth)
               tab.tabScale.Set     (tabWidth / baseWidth)
               tab.tabScaleInv.Set  (1.0 / (float)tab.tabScale.Get())
               tab.tabOffset.Set    (tabIdx * tabWidth)
               tab.notifOffset.Set  (tabWidth - 32)
               tabIdx            := tabIdx + 1
            end
         end           
      end
   end
   
   func GetTab(_idx : int) : UiChatTabVM
      return GetTabs().Get(_idx)
   end
   
   func SetTabData(_idx : int, _data : *, _isValid : bool)
      GetTab(_idx).SetTabData(_data)
      GetTab(_idx).isValidTab.Set(_isValid)
   end
   
   override SetItems//(_items : vector)
      if (items.Count() != _items.Count())
         countChanged := true
      end
      items := _items
      var i : int
      for i := 0 to GetMaxTabs() - 1
         var dataIdx : int = -1
         if (i == (GetMaxTabs() - 1))
            if (_items.Count() > 1)
               dataIdx := _items.Count() - 1
            end
         else
            if (i < _items.Count() - 1)
               dataIdx := i
            end
         end         
         if (dataIdx == -1)
            SetTabData(i, GetDefaultEntry(), false)
         else
            SetTabData(i, _items.Get(dataIdx), true)
         end
      end      
      ArrangeTabs()      
   end
   
   
   override SelectedTabUpdated //()
      if parentVM.gotoPrivateFlag
         parentVM.selectedMemberIdx.Set(-1)
      else
         if parentVM.IsPrivateTab() and !parentVM.IsPinnedPrivateTab()
            var selectedIdx : int = (int)parentVM.selectedMemberIdx.Get()
            if parentVM.selectedPrivateMemberIdx != selectedIdx
               var p : params
               p.index := parentVM.selectedPrivateMemberIdx
               parentVM.OnSelectedMemberChanged(p)
               //parentVM.selectedMemberIdx.Set(parentVM.selectedPrivateMemberIdx)
            end
         end
      end
   end   
   
   override InvalidateCurrentTab // ()
      parentVM.InvalidateCurrentTab()
   end   
end

/*************************************************************
* UiChatVM
* 
*************************************************************/
class UiChatVM
   var tabs                   : UiChatTabsVM       = new UiChatTabsVM()
   var wgt                    : UiChat             = null
   var privateMessagesTarget  : ObservableProperty = $OM.Property($UiGlobals.GetInvalidUIDVal())
   var isMembersPanelEnabled  : ObservableProperty = $OM.Property(true)
   var isCollapsed            : ObservableProperty = $OM.Property(true)
   var chatSizeDiff           : ObservableProperty = $OM.Property((float)0)
   var chatSizeDiffDelayed    : ObservableProperty = $OM.Property((float)0)
   var playerUID              : GL_UID             = $UserDataStorage.NewEmptyUID()
   var chatDragStart          : float              = 0
   var userContext            : UserContextMenu    = new UserContextMenu()
   var chatStyleSheet         : UiSSMainChat       = new UiSSMainChat()
   var fullSize               : float              = 500
   var isFirstGetTabsData     : bool               = true
   var isPinnedPrivateTab     : ObservableProperty = $OM.Calculated(this, "GetIsPinnedPrivateTab", true)
   var isGeneralPrivateTab    : ObservableProperty = $OM.Calculated(this, "GetIsGeneralPrivateTab", true)
   
   var privateTabs            : ObservableProperty = $OM.Property(new vector)
   var maximumPrivateTabs     : int                = 4
   var selectedMemberIdx      : ObservableProperty = $OM.Property(-1)
   var selectedPrivateMemberIdx: int               = -1
   var gotoPrivateFlag        : bool               = false
   
   //var messagesTxtObservable     : ObservableProperty = $OM.Calculated(this, "GetMessagesTxt", true)
   var membersObservable         : ObservableProperty = $OM.Calculated(this, "GetMembers", true)
   var membersTxtObservable      : ObservableProperty = $OM.Calculated(this, "GetMembersTxt", true)
   var isMessagesTxtUpdating     : bool               = false
   var isMessagesTxtInvalidated  : bool               = false
   var isMembersUpdating         : bool               = false
   var isMembersInvalidated      : bool               = false
   var isMembersTxtUpdating      : bool               = false
   var isMembersTxtInvalidated   : bool               = false
   
   var textFieldToStreamMap      : vector
   var maxTextfields             : int = 10
   
   var cachedTabData : params
   var cachedTabsData : vector
   
   func Init(p : params)
      ResetTextFieldMappings()
      
      var i : int
      var privateTabs : vector = this.privateTabs.Get()
      for i := 0 to $UiGlobals.chat.private_channels.Count() - 1
         var stream : GL_ChatStream = $UiGlobals.chat.private_channels.Get(i)
         if (stream.tabState == "opened")
            if privateTabs.Count() < maximumPrivateTabs
               privateTabs.Push(stream.private_chat_uid)
            end
         end         
      end
      
      wgt := p.widget
      tabs.parentVM := this
      tabs.Init(p)
      tabs.selectedTab.Subscribe(this, "OnTabChange")
      $UiGlobals.news.Subscribe(this, "OnNewsUpdated")
   end
   
   func ResetTextFieldMappings()
      var i : int
      textFieldToStreamMap.Clear()
      textFieldToStreamMap.Push("news")
      for i := 1 to maxTextfields - 1
         textFieldToStreamMap.Push("")
      end      
   end
   
   func Term()
      tabs.Term()
      $UiGlobals.news.Unsubscribe(this, "OnNewsUpdated")
      tabs.selectedTab.Unsubscribe(this, "OnTabChange")
      tabs.parentVM := null
   end
   
   func BiLogs()
      var data : UiChatTabVMData = (UiChatTabVMData)tabs.GetSelectedTabData().Get()
      if (IsPrivateTab())
         if (IsPinnedPrivateTab())
            $UiBiLogger.LogChatState($uiEnums.UI_BI_CHAT_VISIBLE, "private tab")
         else
            $UiBiLogger.LogChatState($uiEnums.UI_BI_CHAT_VISIBLE, "all private tab")
         end
      else
         $UiBiLogger.LogChatState($uiEnums.UI_BI_CHAT_VISIBLE, (string)data.name)
      end
   end
      
   func UpdateNews()
      var selectedChannel : int = GetSelectedChannel()
      if (selectedChannel == $uiEnums.CHAT_CHANNEL_NEWS)
         var p : params
         p.txt    := GetNewsText()
         p.txtIdx := 0
         wgt.GenerateEvent("SetChatTabText", p)      
         UpdateCurrentOpenedTab()
      end
   end
      
   func GetPrivateChatTabData(uid : *) : UiChatTabVMData
      var tabData : UiChatTabVMData = GetTabDataCache("p" + $UserDataStorage.UID2Str(uid))
      return tabData
   end
   
   func GetTextfieldIdxFromParams(p : params) : int
      var txtIdx : int = -1      
      
      if (p.channel == $uiEnums.CHAT_CHANNEL_PRIVATE)
         if (IsPinnedPrivateTab())
            var tabData : UiChatTabVMData = GetSelectedTabData()
            if (tabData != null and $UserDataStorage.IsEqualUIDs(p.private_chat_uid, tabData.privateUid))
               txtIdx := tabData.txtIdx
            end
         else
            var members : vector = $UiGlobals.chat.GetPrivateMembers()
            if (int)selectedMemberIdx.Get() >= 0 and (int)selectedMemberIdx.Get() < members.Count()
               if ($UserDataStorage.IsEqualUIDs(members.Get((int)selectedMemberIdx.Get()).value.Get(), p.private_chat_uid))
                  txtIdx := GetTabDataCache("private").txtIdx
               end
            end
         end                  
      else
         txtIdx := p.uiStreamIdx
      end
      
      return txtIdx      
   end
   
   func OnSetChatText(p : params) : bool      
      var txtIdx : int = GetTextfieldIdxFromParams(p)
      if (txtIdx != -1)
         p.txtIdx := txtIdx
         wgt.GenerateEvent("SetChatTabText", p)         
      end
      return false
   end
      
   func OnAppendChatText(p : params) : bool
      var txtIdx : int = GetTextfieldIdxFromParams(p)
      if (txtIdx != -1)
         p.txtIdx := txtIdx
         wgt.GenerateEvent("AppendChatTabText", p)            
      end            
      return false
   end
   
   func OnNewsUpdated(_val : *)
      UpdateNews()
   end
   
   func InvalidateCurrentTab()
      OnTabChange(tabs.selectedTab.Get())
   end
   
   func GetNewsText() : wstring
      var   ret      :  wstring
      var   newsVec  :  vector   = $UiGlobals.news.Get()
      var   i        :  int      
      var   p        :  params      
      
      p.text := ret
      for i := 0 to newsVec.Count() - 1
         var newsRec : GL_News = (GL_News)newsVec.Get(i)
         p.text := p.text + newsRec.formattedText.Get()
      end      
      ret := p.text
      
      return ret
   end
   
   func GetSelectedTabData() : UiChatTabVMData
      var ret : UiChatTabVMData = (UiChatTabVMData)tabs.GetSelectedTabData().Get()
      return ret
   end
   
   func UpdateCurrentOpenedTab()
      var p                : params
      var tabData          : UiChatTabVMData= GetSelectedTabData()
      if (tabData != null)
         p.txtIdx          := tabData.txtIdx
      else
         p.txtIdx          := -1 
      end
      p.isFull             := !IsMembersVisible()
      p.width              := GetMessagesWidth()
      p.height             := GetMessagesHeightDelayed()
      p.autoScrollLastLine := GetSelectedChannel() != $uiEnums.CHAT_CHANNEL_NEWS
      wgt.GenerateEvent("ShowChatTabMessages", p)
   end
      
   func OnTabChange(_val : *)
      BiLogs()
      var selectedChannel : int = GetSelectedChannel()
      if (selectedChannel == $uiEnums.CHAT_CHANNEL_NEWS)
         UpdateNews()
      else
         var stream = GetChatStream()
         if stream != null
            stream.Deactivate()
         end
         if (! CanSendMessage())
            wgt.ClearInputText()
         end
         if IsPrivateTab()
            //if $UserDataStorage.IsEqualUIDs(tabs.tabs.Get(_val).data.Get().privateUid, $UserDataStorage.GetInvalidUID())
            if !IsPinnedPrivateTab()
               var members : vector = $UiGlobals.chat.GetPrivateMembers()
               if (int)selectedMemberIdx.Get() >= 0 and (int)selectedMemberIdx.Get() < members.Count()
                  privateMessagesTarget.Set(members.Get((int)selectedMemberIdx.Get()).value.Get())
                  stream := $UiGlobals.chat.GetPrivateChannel(privateMessagesTarget.Get())
               else
                  stream := null
                  privateMessagesTarget.Set($UserDataStorage.GetInvalidUID())
                  var p : params
                  p.txt    := $UiGlobals.String2WString("")
                  p.txtIdx := GetTabDataCache("private").txtIdx
                  $sslWidgetMgr.GenerateEvent("SetChatTabText", p)
               end
            else
               privateMessagesTarget.Set(tabs.tabs.Get(_val).data.Get().privateUid)
            end
         end
         UpdateCurrentOpenedTab()
         if stream != null
            stream.Activate()
         end
      end
   end
      
   func SetTabsData(tabsData : vector)
      tabs.SetItems(tabsData)
      tabs.Refresh()
      wgt.GenerateEvent("#TabsUpdated")
   end
   
   func IsInParty() : bool
      var partyVec   : vector = $UiGlobals.party.members.Get()
      var ret        : bool   = partyVec.Count() > 1
      return ret
   end
      
   func IsInLobby() : bool
      var partyState : int    = (int)$UiGlobals.party.state.Get()
      var ret        : bool   = partyState == $uiEnums.PARTY_STATE_IN_GAME
      return ret
   end

   func GetTabDataCache(id : string) : UiChatTabVMData
      var cache : * = cachedTabData.Get(id)
      if IsVoid(cache)
         return null
      end
      return (UiChatTabVMData)cache
   end

   func SetTabDataTextField(tabData : UiChatTabVMData, invalidateText : bool = false) : int
      var stream        : GL_ChatStream   = $UiGlobals.GetChatMessagesStream(tabData.channel, tabData.privateUid)
      var txtIdx        : int             = -1
      
      var streamName    : string = tabData.streamName
      if (stream == null)
         
      end
      
      if (invalidateText)
         stream.isTextValid := false
      end
      
      stream.updateWholeText := tabData.channel == $uiEnums.CHAT_CHANNEL_PRIVATE
      
      if (tabData.channel == $uiEnums.CHAT_CHANNEL_PRIVATE)
         stream.updateWholeText := true
         if ($UserDataStorage.IsValidUID(tabData.privateUid))
            streamName := "private"
         else
            streamName := "private_common"
         end
      end
      
      if (stream.uiStreamIdx != -1)
         var curStreamName : string = textFieldToStreamMap.Get(stream.uiStreamIdx)
         if (curStreamName == streamName)
            txtIdx := stream.uiStreamIdx
         end
      end
      
      if (txtIdx == -1)
         var i : int
         for i := 0 to maxTextfields - 1
            var curStreamName : string = textFieldToStreamMap.Get(i)
            if (curStreamName == "")
               txtIdx := i
               stream.SetUiStreamIdx(txtIdx)
               textFieldToStreamMap.Set(i, streamName)
               break
            end
         end
      end
      
      return txtIdx
   end
   
   func FreeStreamTextfield(stream : GL_ChatStream)
      if (stream != null and stream.uiStreamIdx != -1)
         textFieldToStreamMap.Set(stream.uiStreamIdx, "")
         stream.uiStreamIdx := -1
      end
   end
   
   func GetTabsData() : vector
      var p    : params
      var vec  : vector
      
      var tabData : UiChatTabVMData = null
      
      ResetTextFieldMappings()
      
      tabData := GetTabDataCache("news")
      if tabData == null
         tabData              := new UiChatTabVMData()
         tabData.name         := $UiGlobals.String2WString("main_chat_channel_news")
         tabData.channel      := $uiEnums.CHAT_CHANNEL_NEWS
         tabData.streamName   := "news"
         tabData.txtIdx       := 0
         cachedTabData.Set(tabData.streamName, tabData)
      end
      tabData.idx := vec.Count()
      vec.Push(tabData)

      tabData := GetTabDataCache("all")
      if tabData == null
         tabData              := new UiChatTabVMData()
         tabData.name         := $UiGlobals.String2WString("main_chat_channel_general")
         tabData.channel      := $uiEnums.CHAT_CHANNEL_ALL
         tabData.streamName   := "all"
         cachedTabData.Set("all", tabData)
      end
      tabData.txtIdx := SetTabDataTextField(tabData, isFirstGetTabsData or tabData.idx != vec.Count())
      tabData.idx    := vec.Count()
      vec.Push(tabData)
      
      if (IsInParty())
         tabData := GetTabDataCache("party")
         if tabData == null
            tabData              := new UiChatTabVMData()
            tabData.name         := $UiGlobals.String2WString("main_chat_channel_party")
            tabData.channel      := $uiEnums.CHAT_CHANNEL_PARTY
            tabData.streamName   := "party"
            cachedTabData.Set("party", tabData)
         end
         tabData.txtIdx := SetTabDataTextField(tabData, isFirstGetTabsData or tabData.idx != vec.Count())
         tabData.idx    := vec.Count()
         vec.Push(tabData)
      else
         $UiGlobals.GetChatMessagesStream($uiEnums.CHAT_CHANNEL_PARTY).SetUiStreamIdx(-1)
      end
      
      if (IsInLobby())
         tabData := GetTabDataCache("lobby")
         if tabData == null
            tabData              := new UiChatTabVMData()
            tabData.name         := $UiGlobals.String2WString("main_chat_channel_lobby")
            tabData.channel      := $uiEnums.CHAT_CHANNEL_GAME_ALL
            tabData.streamName   := "lobby"
            cachedTabData.Set("lobby", tabData)
         end
         tabData.txtIdx := SetTabDataTextField(tabData, isFirstGetTabsData or tabData.idx != vec.Count())
         tabData.idx    := vec.Count()
         vec.Push(tabData)
      else
         $UiGlobals.GetChatMessagesStream($uiEnums.CHAT_CHANNEL_GAME_ALL).SetUiStreamIdx(-1)
      end
      
      var ud : UserData = $UserDataStorage.GetLocalUserData()
      if ((bool)ud.has_base.Get())
         if (! $UiGlobals.IsZeroInt64(ud.base.clan_id.Get()))
            tabData := GetTabDataCache("clan")
            if tabData == null
               tabData              := new UiChatTabVMData()
               tabData.name         := $UiGlobals.String2WString("main_chat_channel_clan")
               tabData.channel      := $uiEnums.CHAT_CHANNEL_CLAN
               tabData.streamName   := "clan"
               cachedTabData.Set("clan", tabData)
            end
            tabData.txtIdx := SetTabDataTextField(tabData, isFirstGetTabsData or tabData.idx != vec.Count())
            tabData.idx := vec.Count()
            vec.Push(tabData)         
         else
            $UiGlobals.GetChatMessagesStream($uiEnums.CHAT_CHANNEL_CLAN).uiStreamIdx := -1
         end
      else
         $user_service.RequestData($UserDataStorage.local_user.uid.Get(), $uiEnums.USER_DATA_BASE)
      end     
      
      var i : int
      for i := 0 to $UiGlobals.chat.private_channels.Count() - 1
         var stream: GL_ChatStream = $UiGlobals.chat.private_channels.Get(i)
         stream.SetUiStreamIdx(-1)         
      end
      
      var privateTabs : vector = this.privateTabs.Get()
      for i := 0 to privateTabs.Count() - 1
         var streamName : string = "p" + $UserDataStorage.UID2Str(privateTabs.Get(i))
         tabData := GetTabDataCache(streamName)
         if tabData == null
            tabData              := new UiChatTabVMData()
            tabData.name         := ""
            tabData.channel      := $uiEnums.CHAT_CHANNEL_PRIVATE
            tabData.privateUid   := privateTabs.Get(i)
            tabData.streamName   := streamName
            cachedTabData.Set(streamName, tabData)            
         end
         tabData.txtIdx := SetTabDataTextField(tabData, isFirstGetTabsData or tabData.idx != vec.Count())
         tabData.idx    := vec.Count()
         vec.Push(tabData)      
         
         if $UserDataStorage.users.Get(privateTabs.Get(i)).has_base.Get() == false
            $user_service.RequestData(privateTabs.Get(i), $uiEnums.USER_DATA_BASE)
         end
      end
      
      tabData := GetTabDataCache("private")
      if tabData == null
         tabData              := new UiChatTabVMData()
         tabData.name         := $UiGlobals.String2WString("main_chat_channel_private")
         tabData.channel      := $uiEnums.CHAT_CHANNEL_PRIVATE
         tabData.streamName   := "private"
         cachedTabData.Set("private", tabData)
      end
      tabData.txtIdx := SetTabDataTextField(tabData, isFirstGetTabsData or tabData.idx != vec.Count())
      tabData.idx    := vec.Count()
      vec.Push(tabData)      
      
      var dataIsTheSame = true
      if vec.Count() != cachedTabsData.Count()
         dataIsTheSame := false
      else
         for i := 0 to vec.Count() - 1
            if vec.Get(i).channel != cachedTabsData.Get(i).channel
               dataIsTheSame := false
            elif vec.Get(i).channel == $uiEnums.CHAT_CHANNEL_PRIVATE and !$UserDataStorage.IsEqualUIDs(vec.Get(i).privateUid, cachedTabsData.Get(i).privateUid)
               dataIsTheSame := false
            end
         end
      end
      if !dataIsTheSame
         cachedTabsData := vec
      end
      
      isFirstGetTabsData := false
      
      return cachedTabsData
   end
   
   func OnOpenNewPrivateChat(p:params) : bool
      if $UiGlobals.chat.GetPrivateChannel(p.uid).tabState == "opened"
         return true
      end
      var privateTabs : vector = this.privateTabs.Get()
      if privateTabs.Count() < maximumPrivateTabs
         privateTabs.Push(p.uid)
         this.privateTabs.OnChanged()
         
         $UiGlobals.chat.GetPrivateChannel(p.uid).tabState := "opened"
      end
      return true
   end
   
   func OnCleanChat(p : params) : bool
      tabs.SetSelectedTabIdx(0)
      privateTabs.Get().Clear()
      privateTabs.OnChanged()
      return true
   end
         
   func ClosePrivateTab(p : params) : bool
      var privateTabs : vector = this.privateTabs.Get()
      var pUid : * = p.widget.GetParentWidget().GetDC().data.Get().privateUid
      var i : int
      for i := 0 to privateTabs.Count() - 1
         var pUid2 : * = privateTabs.Get(i)
         if !IsVoid(pUid) and !IsVoid(pUid2) and $UserDataStorage.IsEqualUIDs(pUid, pUid2)
            privateTabs.Erase(i, 1)
            var stream : GL_ChatStream = $UiGlobals.GetChatMessagesStream($uiEnums.CHAT_CHANNEL_PRIVATE, pUid)
            if (stream != null)
               FreeStreamTextfield(stream)
            end
            this.privateTabs.OnChanged()
            $UiGlobals.chat.GetPrivateChannel(pUid).tabState := "closed"
            break
         end
      end
      
      var isAnythingOpened : bool = false
      for i := 0 to $UiGlobals.chat.private_channels.Count() - 1
         var stream : GL_ChatStream = $UiGlobals.chat.private_channels.Get(i)
         if stream.tabState == "none"
            var pp : params
            pp.uid := stream.private_chat_uid
            OnOpenNewPrivateChat(pp)
            isAnythingOpened := true
            break
         end
      end
      
      if (!isAnythingOpened)
         OnTabChange(tabs.selectedTab.Get())
      end
      
      return true
   end
   
   func UiChatVM()
   end
   
   func IsNewsVisible() : bool
      var selectedChannel : int = GetSelectedChannel()
      return selectedChannel == $uiEnums.CHAT_CHANNEL_NEWS
   end
   
   func IsMembersVisible() : bool
      var selectedChannel  : int    = GetSelectedChannel()
      var ret              : bool   = (bool)isMembersPanelEnabled.Get() and ! GetIsCollapsed() and selectedChannel != $uiEnums.CHAT_CHANNEL_NEWS
      if IsPrivateTab()
         if IsPinnedPrivateTab()
            ret := false
         else
            ret := true
         end
      end
      if selectedChannel == $uiEnums.CHAT_CHANNEL_ALL
         ret := false
      end
      return ret
   end
      
   func GetMembersPanelState() : string
      var isMembersVisible : bool   = IsMembersVisible()
      var ret              : string = "Hidden"
      if (isMembersVisible)
         ret := "Visible"
      end
      return ret
   end
   
   func IsMessagesVisible() : bool
      return true
   end
         
   var testIdx : int = 0
   func ToggleMembers(p : params) : bool      
      isMembersPanelEnabled.Set(!(bool)isMembersPanelEnabled.Get())
      //isMembersPanelEnabled.Set(true)
      //testIdx := testIdx + 1
      
      //wgt.Widgets.testText.htmlText := "LINK test " + (string)testIdx + ": <a href=\"event:LNK1\"><font color=\"#FF0000\">LINK1</font></a>, <a href=\"event:LNK2\"><font color=\"#00FF00\">LINK2</font></a>"
      
      //wgt.Widgets.listMembers.txtArea.htmlText := GetMembersTxt()
      //wgt.Widgets.listMembers.txtAreaCont.htmlText := GetMembersTxt()
      //wgt.Widgets.listMembers.txtAreaCont.txtArea.scrollBar := "DefaultScrollBarSkinned"
      //wgt.Widgets.testText.htmlText := "LINK test " + (string)testIdx + ": <font color=\"#FF0000\">LINK1</font>, <font color=\"#00FF00\">LINK2</font>"
      //					htmlText   =   {
	//					binding   =   "{'LINK test: <a href='event:LNK1'><font color='#FF0000'>LINK1</font></a>, <a href='event:LNK2'><font color='#00FF0000'>LINK2</font></a>'}"
		//			}

      return true
   end
   
   func TabsUpdated(p : params) : bool
      UpdateCurrentOpenedTab()
      return true
   end
   
   func IsMembersBtnVisible() : bool
      var selectedChannel  : int    = GetSelectedChannel()
      var ret              : bool   = (bool)isMembersPanelEnabled.Get() and ! GetIsCollapsed() and selectedChannel != $uiEnums.CHAT_CHANNEL_NEWS
      return ret
   end
   
   func IsPrivateTab() : bool
      if GetSelectedChannel() == $uiEnums.CHAT_CHANNEL_PRIVATE
         return true
      end
      return false
   end
      
   func GetIsGeneralPrivateTab() : bool
      if IsPrivateTab() and (IsVoid(GetChatStream().private_chat_uid) or $UserDataStorage.IsEqualUIDs(GetChatStream().private_chat_uid, $UserDataStorage.GetInvalidUID()))
         return true
      end
      return false      
   end
   
   func IsGeneralPrivateTab() : bool
      return GetIsGeneralPrivateTab()
   end
   
   func GetIsPinnedPrivateTab() : bool
      if IsPrivateTab() and !(IsVoid(GetChatStream().private_chat_uid) or $UserDataStorage.IsEqualUIDs(GetChatStream().private_chat_uid, $UserDataStorage.GetInvalidUID()))
         return true
      end
      return false
   end
   
   func IsPinnedPrivateTab() : bool
      return GetIsPinnedPrivateTab()
   end
   
   func CanShowHideMembers() : bool
      if IsPrivateTab()
         return false
      end
      if GetSelectedChannel() == $uiEnums.CHAT_CHANNEL_ALL
         return false
      end
      return true
   end
   
   func GetBgHeight() : float
      var ret : float = 103 //+ GetSizeDifference()
      return ret      
   end
   
   func GetUsersBgHeight() : float
      var ret : float = 56 + GetSizeDifference()
      return ret      
   end
   
   func GetUsersBgHeightDelayed() : float
      var ret : float = 56 + GetSizeDifferenceDelayed()
      return ret      
   end
   
   func GetChatHeight() : float
      var ret : float = 0
      //if (! GetIsCollapsed())
         ret := (float)chatSizeDiff.Get()         
      //end
      return ret
   end
      
   func GetChatHeightDelayed() : float
      var ret : float = 0
      ret := (float)chatSizeDiffDelayed.Get()
      return ret
   end
   
   func ChatStartDrag(p : params) : bool
      chatDragStart     := (float)chatSizeDiff.Get()
      var pp: params
      pp.dragEvent   := "ChatDrag"
      pp.dragTarget  := wgt.Widgets.expandBtn.object
      StopSizeTween()
      wgt.Widgets.expandBtn.SetFocus()
      wgt.GenerateEvent("StartUniversalDrag", pp)
      return true
   end
   
   func UpdateChatSizeDelayed(newSize : float)
      chatSizeDiffDelayed.Set(newSize)
      UpdateCurrentOpenedTab()
   end
      
   func ChatDrag(p : params) : bool
      if (p.updateType == "update" or p.updateType == "start")
         var newSize : float = (float)(chatDragStart - p.mouseOffset.y)
         if (newSize < 0)
            newSize := 0
         end
         if (newSize > 700)
            newSize := 700
         end
         if (newSize > 0)
            isCollapsed.Set(false)
         else
            isCollapsed.Set(true)
         end
         chatSizeDiff.Set(newSize)
         
         UpdateChatSizeDelayed(newSize)
         
      elif (p.updateType == "end")
         fullSize := (float)chatSizeDiff.Get()
         UpdateChatSizeDelayed((int)chatSizeDiff.Get())
         if (! GetIsCollapsed())
            wgt.SetFocus()
         end
      end
      return true
   end
   
   func GetSizeDifference() : float
      var ret : float = 0
      ret := GetChatHeight()
      return ret
   end
   
   func GetSizeDifferenceDelayed() : float
      var ret : float = 0
      ret := (float)chatSizeDiffDelayed.Get()
      return ret
   end
   
   func IsSendVisible() : bool
      var selectedChannel  : int    = GetSelectedChannel()
      var ret              : bool   = selectedChannel != $uiEnums.CHAT_CHANNEL_NEWS
      return ret
   end

   func GetMembersBtnYPos() : float
      var ret              : float  = 94.5 + GetSizeDifference()
      return ret      
   end
   
   func GetInputContYPos() : float      
      var ret              : float  = 93 + GetSizeDifference()
      return ret      
   end

   func GetSelectedChannel() : int
      var tabData : UiChatTabVMData = (UiChatTabVMData)tabs.GetSelectedTabData().Get()
      if tabData == null
         return $uiEnums.CHAT_CHANNEL_NONE
      end
      var ret     : int             = tabData.channel
      return ret
   end
   
   func TabClicked(p : params) : bool
      FocusReceived()
      return true
   end

   func FocusReceived()
      if (GetIsCollapsed())
         ToggleCollapsed(null)
      end
   end
   
   func FocusLost()
      if (! GetIsCollapsed())
         ToggleCollapsed(null)
      end
   end
   
   func ToggleCollapsed(p : params) : bool
      var curSize : float  = (float)chatSizeDiff.Get()
      var newSize : float  = curSize
      if (curSize == 0)
         newSize := fullSize
         if (newSize < 50)
            newSize := 500
         end
      else
         newSize := 0
      end
      var tweenParm : params
      tweenParm.propName   := "chatSize"
      tweenParm.startVal   := curSize         
      tweenParm.endVal     := newSize
      tweenParm.duration   := 0.128
      tweenParm.fadeType   := "linear"

      StopSizeTween()
      wgt.AddTweenCb("TweenChatSize", tweenParm) 
      //isCollapsed.Set(!GetIsCollapsed())
      return true
   end
   
   func StopSizeTween()
      wgt.RemTweens()      
   end
   
   func TweenChatSize(updType : string)
      var chatSize : float = (float)wgt.Get("chatSize")
      if (chatSize > 0)
         isCollapsed.Set(false)
      else
         isCollapsed.Set(true)
      end
      chatSizeDiff.Set(chatSize)
      if (updType == "complete")         
         UpdateChatSizeDelayed(chatSize)
      end
   end
   
   func GetIsCollapsed() : bool
      return (bool)isCollapsed.Get()
   end
   
   func GetChatYPos() : float
      var ret              : float  = -GetSizeDifference()
      return ret
   end
         
   func GetMembersListHeight() : float
      var ret              : float  = 37 + GetSizeDifferenceDelayed()
      return ret
   end
   
   func GetMessagesListHeight() : float
      var ret              : float  = 57 + GetSizeDifferenceDelayed()
      return ret
   end
   
   func GetMessagesListWidth() : float
      var ret              : float  = 695
      if (IsMembersVisible())
         ret := 495
      end
      return ret
   end
   
   func GetMessagesLIRWidth() : float
      var ret : float =  GetMessagesListWidth() - 30
      return ret
   end
         
   func GetMOTDYPos() : float      
      var ret              : float  = 105 + GetSizeDifference()
      return ret
   end
   
   func GetChatStream() : GL_ChatStream
      var ret              : GL_ChatStream   = null
      var selectedChannel  : int             = GetSelectedChannel()
      ret := $UiGlobals.GetChatMessagesStream(GetSelectedChannel(), tabs.GetSelectedTabData().Get().privateUid)
      return ret
   end
   
   func GetMembers() : vector
      var ret  : vector      
      if (! isMembersUpdating)
         isMembersInvalidated   := false
         isMembersUpdating      := true
         
         if (IsMembersVisible())
            var stream : GL_ChatStream = GetChatStream()
            if stream == $UiGlobals.chat.ui_channel_private
               ret := $UiGlobals.chat.GetPrivateMembers()
            elif stream == $UiGlobals.chat.ui_channel_general
               ret := new vector
            elif stream == $UiGlobals.chat.ui_channel_party
               ret := $UiGlobals.party.members.Get()
            elif stream == $UiGlobals.chat.ui_channel_game_all
               var lobbyState : int = (int)$UiGlobals.lobby.state.Get()
               //if (lobbyState != $uiEnums.LOBBY_STATE_NONE and lobbyState != $uiEnums.LOBBY_STATE_JOINING_SESSION)
               //   ret := $UiGlobals.lobby.players.Get()
               //else
                  ret := $UiGlobals.matchmaking.group.Get()
               //end
            else
               if (stream != null)
                  ret := stream.GetMembers()
               end
            end
         end      
         
         isMembersUpdating := false
         if (isMembersInvalidated)
            membersObservable.Invalidate()
         end
      else
         isMembersInvalidated := true
      end
      return ret      
   end
   
   func GetMessages() : vector
      var ret  : vector
      if (IsMessagesVisible())
         var channelIdx : int = GetSelectedChannel()
         var isPinnedPrivateTab : bool = !$UserDataStorage.IsEqualUIDs(tabs.GetSelectedTabData().Get().privateUid, $UserDataStorage.GetInvalidUID())
         var members : vector = membersObservable.Get()
         var selectedMember : GL_UID = null
         var selectedMemberIdx : int = (int)this.selectedMemberIdx.Get()
         if selectedMemberIdx >= 0 and selectedMemberIdx < members.Count()
            selectedMember := members.Get(selectedMemberIdx)
         end
         if channelIdx == $uiEnums.CHAT_CHANNEL_PRIVATE and !isPinnedPrivateTab
            if (selectedMember != null)
               ret := $UiGlobals.GetChatMessages(channelIdx, selectedMember.value.Get())
            end
         else
            ret := $UiGlobals.GetChatMessages(channelIdx, tabs.GetSelectedTabData().Get().privateUid)
         end
      end
      return ret
   end
   
   func UpdateStreamTimestamp()
      var stream : GL_ChatStream = GetChatStream()
      if stream == $UiGlobals.chat.ui_channel_private
         if (int)selectedMemberIdx.Get() >= 0 and (int)selectedMemberIdx.Get() < $UiGlobals.chat.GetPrivateMembers().Count()
            stream := $UiGlobals.chat.GetPrivateChannel($UiGlobals.chat.GetPrivateMembers().Get((int)selectedMemberIdx.Get()).value.Get())
         end
      end
      if (stream != null)
         stream.UpdateLastViewTime()
      end
   end
   
   
   func GetMembersTxt() : wstring
      var ret        : wstring
      return ret
   end
         
   func GetMessagesHeight() : float
      var ret : float = 0
      ret := 46 + GetChatHeight()
      if (GetSelectedChannel() == $uiEnums.CHAT_CHANNEL_NEWS)
         ret := ret + 55
      end
      return ret      
   end
   
   func GetMessagesHeightDelayed() : float
      var ret : float = 0
      ret := 46 + GetChatHeightDelayed()
      if (GetSelectedChannel() == $uiEnums.CHAT_CHANNEL_NEWS)
         ret := ret + 55
      end
      return ret      
   end
   
   func GetMessagesWidth() : float
      var ret : float = 705
      if (IsMembersVisible())
         ret := 500
      end
      return ret      
   end
   
   func GetMessagesMaskWidth() : float
      var ret : float = 705
      return ret      
   end
   
   func GetMembersHeight() : float
      var ret : float = 0
      ret := 54 + GetChatHeight()
      return ret      
   end
   
   func GetMembersHeightDelayed() : float
      var ret : float = 0
      ret := 54 + GetChatHeightDelayed()
      return ret      
   end
   
   func GetMembersWidth() : float
      var ret : float = 290
      return ret      
   end
   
   func SendMessage(p : params) : bool
      var txt     : string    = wgt.Widgets.inputCont.inputTf.text
      var wtxt    : wstring   = wgt.Widgets.inputCont.inputTf.wtext
      wgt.Widgets.inputCont.inputTf.text := ""
      if (txt != "" and CanSendMessage())
         var command : wstring = $hq.ChatExtractCommand(wtxt)
         if (command == $UiGlobals.String2WString(""))
            // send message
            //wtxt := $UiGlobals.EscapeString(wtxt)
            var stream : GL_ChatStream = null
            var msg = new GL_ChatStreamMessage()
            msg.sender_user_id := $OM.Property($UserDataStorage.local_user.uid.Get())
            msg.addressee_user_id := $OM.Property($UserDataStorage.GetInvalidUID())
            msg.timestamp := $OM.Property($UiGlobals.GetCurrentTimeStamp())
            msg.text := $OM.Property(wtxt)
            msg.directMsg := true
            var selectedChannel : int = GetSelectedChannel()
            
            if (selectedChannel == $uiEnums.CHAT_CHANNEL_ALL)
               $hq.ChatSendGeneral(wtxt)
               stream := $UiGlobals.chat.general
               msg.originalChannel := $uiEnums.CHAT_CHANNEL_ALL
               
            elif (selectedChannel == $uiEnums.CHAT_CHANNEL_PARTY)
               $hq.ChatSendParty(wtxt)
               stream := $UiGlobals.chat.party
               msg.originalChannel := $uiEnums.CHAT_CHANNEL_PARTY
               
            elif (selectedChannel == $uiEnums.CHAT_CHANNEL_GAME_ALL)
               $hq.ChatSendGameAll(wtxt)
               stream := $UiGlobals.chat.game_all_channel
               msg.originalChannel := $uiEnums.CHAT_CHANNEL_GAME_ALL
               
            elif (selectedChannel == $uiEnums.CHAT_CHANNEL_CLAN)
               $hq.ChatSendClan(wtxt)
               stream := $UiGlobals.chat.clan_channel
               msg.originalChannel := $uiEnums.CHAT_CHANNEL_CLAN
               
            elif (selectedChannel == $uiEnums.CHAT_CHANNEL_PRIVATE)
               $hq.ChatSendPrivate(privateMessagesTarget.Get(), wtxt)
               stream := $UiGlobals.chat.GetPrivateChannel(privateMessagesTarget.Get())
               msg.addressee_user_id := $OM.Property(privateMessagesTarget.Get())
               msg.originalChannel := $uiEnums.CHAT_CHANNEL_PRIVATE
               $UiGlobals.chat.CopyMessage(msg, $UiGlobals.chat.ui_channel_general, $uiEnums.CHAT_CHANNEL_PRIVATE, true)
               $UiGlobals.chat.CopyMessage(msg, $UiGlobals.chat.ui_channel_clan, $uiEnums.CHAT_CHANNEL_PRIVATE, true)
               $UiGlobals.chat.CopyMessage(msg, $UiGlobals.chat.ui_channel_party, $uiEnums.CHAT_CHANNEL_PRIVATE, true)
               $UiGlobals.chat.CopyMessage(msg, $UiGlobals.chat.ui_channel_game_all, $uiEnums.CHAT_CHANNEL_PRIVATE, true)
               $UiGlobals.chat.CopyMessage(msg, $UiGlobals.chat.ui_channel_ingame, $uiEnums.CHAT_CHANNEL_PRIVATE, true)
            end
            
            stream.messages.Get().Push(msg)
            stream.messages.OnChanged()
         else
            $hq.ChatSendCommand(command)
         end
      end
      return true
   end
   
   func CanSendMessage() : bool
      var ret : bool  = true      
      var selectedChannel : int = GetSelectedChannel()
      if (selectedChannel == $uiEnums.CHAT_CHANNEL_NEWS)
         ret := false
      elif (selectedChannel == $uiEnums.CHAT_CHANNEL_PRIVATE)
         ret := CanSendPrivate()
      end
      return ret
   end
   
   func GetDefaultInputText() : wstring
      var ret : wstring = $UiGlobals.String2WString("main_chat_input")
      var selectedChannel : int = GetSelectedChannel()
      if (selectedChannel == $uiEnums.CHAT_CHANNEL_PRIVATE)
         if (CanSendPrivate())
            var ud   : UserData = (UserData)$UserDataStorage.users.Get(privateMessagesTarget.Get())
            var p    : params
            p.lb     := $UiGlobals.String2WString("")
            p.nick   := ud.base.full_nickname.Get()
            p.rb     := $UiGlobals.String2WString(": ~")
            ret      := p.lb
            ret      := ret + p.nick
            ret      := ret + p.rb
         else
            ret := $UiGlobals.String2WString("main_chat_input_private")
         end
      else if (!CanSendMessage())
         ret := $UiGlobals.String2WString("main_chat_input_disabled")
      end
      ret := $UiGlobals.TranslateWText(ret)
      return ret      
   end
   
   func CanSendPrivate() : bool
      var ret : bool = false
      ret := $UserDataStorage.IsValidUID(privateMessagesTarget.Get()) and ! $UserDataStorage.IsLocalUID(privateMessagesTarget.Get())
      return ret
   end
   
   func OnSetChatPrivateUser(p : params) : bool
      if (! IsVoid(p.uid))
         SwitchToPrivate(p.uid)
      end
      return true
   end
      
   func SwitchToPrivate(_uid : *)
      var stream : GL_ChatStream = null
      stream := $UiGlobals.chat.GetPrivateChannel(_uid)
      if stream == null
         stream := new GL_ChatStream()
         //stream.members := $OM.Property(new vector)
         stream.messages := $OM.Property(new vector)
         //stream.members.Get().Push(new GL_UID())
         //stream.members.Get().Get(0).value := $OM.Property(_uid)
         stream.private_chat_uid := _uid
         $UiGlobals.chat.private_channels.Push(stream)
         var glUid = new GL_UID()
         glUid.value := $OM.Property(_uid)
         $UiGlobals.chat.GetPrivateMembers().Push(glUid)
         $UiGlobals.chat.private_members.OnChanged()
      end

      var p : params
      p.uid := _uid
      $sslWidgetMgr.GenerateEvent("OpenNewPrivateChat", p)
      
      privateMessagesTarget.Set(_uid)
      
      GotoPrivateTab(_uid) : 0
   end
   
   func GotoPrivateTab(_uid : *)
      var foundPinnedTab = false
      var i : int
      for i := 0 to tabs.tabs.Count() - 1
         var tabData : UiChatTabVMData = (UiChatTabVMData)tabs.tabs.Get(i).data.Get()
         if $UserDataStorage.IsEqualUIDs(tabData.privateUid, _uid)
            tabs.SetSelectedTabIdx(i)
            $sslWidgetMgr.GenerateEvent("SetFocusInputText") : 0
            foundPinnedTab := true
            break
         end
      end
      
      if !foundPinnedTab
         gotoPrivateFlag := true
         tabs.SetSelectedTabIdx(9)
         gotoPrivateFlag := false
         for i := 0 to $UiGlobals.chat.GetPrivateMembers().Count() - 1
            if $UserDataStorage.IsEqualUIDs($UiGlobals.chat.GetPrivateMembers().Get(i).value.Get(), _uid)
               selectedMemberIdx.Set(i):0
               break
            end
         end
         $sslWidgetMgr.GenerateEvent("SetFocusInputText") : 0
      end
   end
   
   func OnLinkClicked(p : params) : bool
      if (!IsVoid(p.text) and p.text != "")
         //SwitchToPrivate($UiGlobals.String2Int64(p.text))
      end
      return true
   end
   
   func OnLinkMouseOver(p : params) : bool
      if (!IsVoid(p.text) and p.text != "")
         userContext.uid      := $UiGlobals.String2Int64(p.text)
         userContext.canOpen  := true
      else
         userContext.canOpen  := false
      end
      playerUID.value.Set($UiGlobals.GetInvalidUIDVal())
      return true
   end
   
   func OnLinkMouseOut(p : params) : bool      
      userContext.canOpen  := false
      playerUID.value.Set(userContext.uid)
      return true
   end
   
   func GetStyleSheet() : vector
      return chatStyleSheet.GetStyleSheet()
   end
   
   func OnSelectedMemberChanged(p : params) : bool
      var members : vector = membersObservable.Get()
      selectedMemberIdx.Set(p.index)
      if p.index >=0 and p.index < members.Count()
         if GetSelectedChannel() == $uiEnums.CHAT_CHANNEL_PRIVATE and !IsPinnedPrivateTab()
            selectedPrivateMemberIdx := p.index
            if !$UserDataStorage.IsEqualUIDs(privateMessagesTarget.Get(), $UserDataStorage.GetInvalidUID())
               var stream = $UiGlobals.chat.GetPrivateChannel(privateMessagesTarget.Get())
               if stream != null
                  stream.Deactivate()
                  FreeStreamTextfield(stream)
               end
            end
            privateMessagesTarget.Set(members.Get(p.index).value.Get())
            var stream = $UiGlobals.chat.GetPrivateChannel(privateMessagesTarget.Get())
            if stream != null
               stream.Activate()
            end
         end
      end
      return true
   end
   
   func OnSendBtnClicked(p : params) : bool
      return SendMessage(p)
   end
end

/*************************************************************
* UiChatMessageLIRVM
* 
*************************************************************/
class UiChatMessageLIRVM
   var mes           : ObservableProperty = $OM.Property(null)
   var userContext   : UserContextMenu    = new UserContextMenu()
   
   func Init(p : params)
      if (! IsVoid(p.message))         
         var mesVal : GL_ChatStreamMessage = (GL_ChatStreamMessage)p.message
         if ($UserDataStorage.IsValidUID(mesVal.sender_user_id.Get()))
            $user_service.RequestData(mesVal.sender_user_id.Get(), $uiEnums.USER_DATA_BASE)
            userContext.uid := mesVal.sender_user_id.Get()
         end
         mes.Set(mesVal)
      end
   end
   
   func GetMessage() : GL_ChatStreamMessage
      var ret : GL_ChatStreamMessage = (GL_ChatStreamMessage)mes.Get()
      return ret
   end
      
   func GetText() : wstring
      var ret : wstring
      var mesVal : GL_ChatStreamMessage = GetMessage()
      if (mesVal != null)
         var ud : UserData = (UserData)$UserDataStorage.users.Get(mesVal.sender_user_id.Get())
         var p : params
         if ($UserDataStorage.IsValidUID(mesVal.sender_user_id.Get()))
            var nickName : wstring = ud.base.full_nickname.Get()
            p.nick   := $root.MakeColorCodedWText(nickName, $UserDataStorage.GetPlayerStatusColorCode(mesVal.sender_user_id.Get()))
         else
            p.nick   := $root.MakeColorCodedWText($UiGlobals.String2WString("SYSTEM"), "#FFFF00")
         end
         p.time      := $root.MakeColorCodedWText($UiGlobals.String2WString("[00:00] "), "#808080")
         p.delim     := $root.MakeColorCodedWText($UiGlobals.String2WString(" : "), "#808080")
         p.mes       := mesVal.text.Get()
         
         ret := ret + p.time
         ret := ret + p.nick
         ret := ret + p.delim
         ret := ret + p.mes
      end
      return ret
   end
end

/*************************************************************
* UiChatMembersLIRVM
* 
*************************************************************/
class UiChatMembersLIRVM
   var uid           : ObservableProperty = $OM.Property($UiGlobals.GetInvalidUIDVal())
   var parentVM      : UiChatVM = null
   //var mes           : ObservableProperty = $OM.Property("")
   var userContext   : UserContextMenu    = new UserContextMenu()
   var unreadMsgCount : ObservableProperty = $OM.Calculated(this, "GetUnreadMsgCount")
   
   func Init(p : params)
      uid.Set($UiGlobals.GetInvalidUIDVal())
      if (! IsVoid(p.uid))
         if ($UserDataStorage.IsValidUID(p.uid))
            $user_service.RequestData(p.uid, $uiEnums.USER_DATA_BASE)
            $user_service.RequestData(p.uid, $uiEnums.USER_DATA_PRESENCE)
            userContext.uid := p.uid
         end
         uid.Set(p.uid)
      end
      if (! IsVoid(p.chatVM))
         parentVM := (UiChatVM)p.chatVM
      end
   end
   
   func GetUID() : *
      return uid.Get()
   end
   
   func GetUserData() : UserData
      var ud : UserData = (UserData)$UserDataStorage.users.Get(GetUID())
      return ud
   end
   
   func GetNickname() : wstring
      var ud   : UserData  = GetUserData()
      var ret  : wstring    = ud.base.full_nickname.Get()
      ret := $root.MakeColorCodedWText(ret, $UserDataStorage.GetPlayerStatusColorCode(GetUID()))
      return ret
   end   
   
   func GetUnreadMsgCount() : int
      if parentVM.IsPrivateTab() and !parentVM.IsPinnedPrivateTab()
         var stream : GL_ChatStream = $UiGlobals.chat.GetPrivateChannel(GetUID())
         if stream != null
            if parentVM.IsPrivateTab()
               return stream.GetNewMessagesCount(false)
            else
               return stream.GetNewMessagesCount(true)
            end
         end
      end
      return 0
   end
      
   func GetStatusFrame() : string
      if GetUserData().presence.presence_state.Get() == $uiEnums.USER_PRESENCE_STATE_OFFLINE
         return "offline"
      elif GetUserData().presence.presence_state.Get() == $uiEnums.USER_PRESENCE_STATE_INGAME
         return "ingame"
      else
         return "online"
      end
   end
   
   func IsStatusVisible() : bool
      return (bool)GetUserData().has_presence.Get()
   end
end


/*************************************************************
* UiChatMessage
* 
*************************************************************/
class UiChatMessage : UiWidgetContainer
   func inputEvent(p : params) : bool
      var isTerminated  : bool   = false
      var keyCode       : int    = p.keyCode
      if (p.isDown == false)
         if (keyCode == $uiKeys.VK_ENTER)
            GenerateEvent("#SendMessage")
            isTerminated := true
         end
      end
      if (keyCode == $uiKeys.VK_DOWN or keyCode == $uiKeys.VK_UP or keyCode == $uiKeys.VK_TAB)
         isTerminated := true
      end
      var caretIndex : * = Get("caretIndex")
      var length  : * = Get("length")
      if (keyCode == $uiKeys.VK_LEFT and caretIndex == 0)
         isTerminated := true
      end
      if (keyCode == $uiKeys.VK_RIGHT and caretIndex == length)
         isTerminated := true
      end
      if (isTerminated)
         p.eventState.SetIsTerminated(isTerminated)
      end
      return false
   end
   
   func focusIn(p : params) : bool
      return false
   end
end


/*************************************************************
* UiChatMembersListCont
* 
*************************************************************/
class UiChatMembersListCont : UiWidgetContainer
   handle OnEnteringState("Initial")
      Props.visible := false
   end
   
   handle OnEnteringState("Visible")
      Props.visible := true      
   end
end

/*************************************************************
* UiChatMessagesListCont
* 
*************************************************************/
class UiChatMessagesListCont : UiWidgetContainer
   var maxTabs : int = 10
   
   handle OnEnteringState("Small")
      Props.x      := 210
      //Widgets.listContentAttach.messages._width := 475
   end
   
   handle OnEnteringState("Full")
      Props.x      := 5
      //Widgets.listContentAttach.messages._width := 695
   end   
   
   func OnSetChatTabText(p : params) : bool      
      var txtIdx : int = -1
      if (!IsVoid(p.txtIdx))
         txtIdx := p.txtIdx
      end
      if (txtIdx >= 0 and txtIdx < maxTabs)
         var txtArea : UiWidgetTextArea = (UiWidgetTextArea)GetWidget("txtAreaCont" + (string)txtIdx).GetWidget("txtArea")
         txtArea.Set("htmlText", p.txt)
      end
      return false
   end
   
   func OnAppendChatTabText(p : params) : bool
      var txtIdx : int = -1
      if (!IsVoid(p.txtIdx))
         txtIdx := p.txtIdx
      end
      if (txtIdx >= 0 and txtIdx < maxTabs)
         var txtArea : UiWidgetTextArea = (UiWidgetTextArea)GetWidget("txtAreaCont" + (string)txtIdx).GetWidget("txtArea")
         txtArea.AppendHtmlText(p.txt)
      end
      return false
   end
   
   func OnShowChatTabMessages(p : params) : bool
      var i       : int
      var txtIdx  : int    = -1
      var isFull  : bool   = false
      if (!IsVoid(p.txtIdx))
         txtIdx := p.txtIdx
      end
      if (!IsVoid(p.isFull))
         isFull:= p.isFull
      end
      for i := 0 to maxTabs - 1
         var txtArea : UiWidgetTextArea = (UiWidgetTextArea)GetWidget("txtAreaCont" + (string)i).GetWidget("txtArea")
         if (txtIdx == i)
            if (isFull)
               txtArea.Props.x := 0
            else
               txtArea.Props.x := 200
            end
            if (!IsVoid(p.width))
               txtArea.Props._width := p.width
            end
            if (!IsVoid(p.height))
               txtArea.Props._height := p.height
            end
            if (!IsVoid(p.autoScrollLastLine))
               txtArea.Props.autoScrollLastLine := p.autoScrollLastLine
            end
         end
         txtArea.Props.visible := txtIdx == i
      end
      return false      
   end
end

/*************************************************************
* ChatTab
* 
*************************************************************/
class ChatTab : UiWidgetButton
   func focusIn(p : params) : bool
      return false
   end   
end

/*************************************************************
* ChatExpandBtn
* 
*************************************************************/
class ChatExpandBtn : UiWidgetButton
   override StartDrag   
      GenerateEvent("#ChatStartDrag")
      return null
   end   
   
   func OnChatDrag(p : params) : bool
      GenerateEvent("#ChatDrag", p)
      return false
   end      
   
   func focusIn(p : params) : bool
      return false
   end
   
   func focusOut(p : params) : bool
      return false
   end
end