import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_manager
import ssl.hf2p.engine_ctrl
import ssl.hf2p.items_mgr
import ssl.observables
import ssl.hf2p.ui_globals
import ssl.hf2p.hq
import ui.root
import ui.ui_economy
import ui.ui_player_info

class UiLootBoxScr : UiWidgetContainer

handle OnEnterState("Initial")
   Set("visible", false)            
end 

handle OnEnterState("Hidden")
end          

handle OnEnteringState("Visible")
   Set("visible", true)
   LootBoxLayout()
end  

func LootBoxLayout()
   Widgets().LootBoxContainer.visible := true
   Widgets().LootBoxRoulette.visible := false
end

func LootBoxAssignBtnClick(p : params) : bool
   Widgets().LootBoxContainer.visible := false
   Widgets().LootBoxRoulette.visible := true
   return false
end

func SwitchToScreen()
end

func PrepareSlide()
   if (GetStateName() != "Visible")
      SetStateName("Visible")
   end
end

func PrepareHideSlide()
end

func DisableSlide()
   if (GetStateName() != "Hidden")
      SetStateName("Hidden")
   end
end

end

class UiLootBoxVM
   var lootItemList         : ObservableProperty = $OM.Calculated(this, "GetLootItemList")
   var selectedLootItemIdx  : ObservableProperty = $OM.Property(0)
   var selectedLootItem     : ObservableProperty = $OM.Calculated(this, "GetSelectedLootItem")
   
   func Init(p : params)
     //lootItemList.Invalidate()
   end
   
   func GetLootItemList() : vector
      var ret : vector
      var i : int
      for i := 0 to 5                     
         var listEntry:params		
         listEntry.label         := "wpn " + (string)i		         
         listEntry.img           := "battlerifle"
         ret.Push(listEntry)
      end
      return ret
   end
   
   func GetSelectedLootItem() : string
      // tmp
      var lootId : string = ""
      var lootVec   : vector = lootItemList.Get()
      var idx : int = (int)selectedLootItemIdx.Get()
      if (idx >= 0 and idx < lootVec.Count())  
         lootId := lootVec.Get(idx).label
      end
      return lootId
   end
   
   func onLootListClick(p : params) : bool
      selectedLootItemIdx.Set(p.index)
      return false
   end
   
end // UiLootBoxVM

class UiLootBoxLir
   
end
