import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_list_item

class UiFriendLir : UiWidgetListItem

var sessionID:string

override SetData // (p:params)
   Log("ui~friendLir", "friendLir SetData" + Params2Str(p))
   var isFriends : bool            
   //Set("visible", true)
   Set("text", p.Name)
   isFriends := GetWidget("_parent").Props().isFriendList
   if (!p.Joinable)
      Set("alpha", 50)
      Props().enabled := false
      Widgets().JoinOrAddButton.visible := false
      //Widgets().inviteButton.visible := false
   else
      Set("alpha", 100)
      Props().enabled := true
      Widgets().JoinOrAddButton.visible := true
      if (isFriends)
         if (p.InRoster)
            Set("alpha", 50)                    
            Props().enabled := false
            Widgets().JoinOrAddButton.enabled := false
         else
            Props().enabled := true
            Widgets().JoinOrAddButton.enabled := true
         end
         //Widgets().inviteButton.visible := true                 
      else
         Widgets().JoinOrAddButton.visible := true //false
         //Widgets().inviteButton.visible := false
      end 
   end
   //Set("text", "name")
   Props().mouseChildren := true
   Props().mouseEnabled := true
   Widgets().JoinOrAddButton.attachPoint.pic := "addRoster"
   sessionID := (string)(p.SessionID)
   Widgets().JoinOrAddButton.SetSessionId(sessionID) 
end

func onInviteBtnClick(p:params):bool
   Log("ui~friendLir", "onInviteBtnClick")
   var pp: params
   pp.sessionID := sessionID
   GenerateEvent("onInviteFriendRequest", pp)
   return false   
end

end

class UiJoinOrAddButton : UiWidgetContainer

var sessionId : string
func GetSessionId(): string
   Log("ui~JoinOrAddButton", "GetSessionId " + sessionId)
   return sessionId 
end

func SetSessionId(_sessionId:string)
   sessionId := _sessionId
end

end
