import ssl.lib.ui.ui_widget_container
import ssl.hf2p.game_preferences
import ssl.lib.logging
import ui.libs.hf2p_SlidingScreens.hf2p_sliding_screens_lib

class UiGameplay : UiSlidingScreenPageSettings

var is_inited :  bool = false

func sliderCameraFOVValueChanged(p: params): bool
   Widgets.sliderCameraFOV.Props.tf2 := (string)((int)(Widgets.sliderCameraFOV.slider.value))   
return false
end

override Init // ()
   is_inited := true
   Widgets.buttonHUDShake.selected        := $hf2pPreferences.GetHUDShake()
   Widgets.buttonSwearFilter.selected     := $hf2pPreferences.GetSwearFilter()
   Widgets.buttonAltCrosshair.selected    := $hf2pPreferences.GetAltCrosshair()
   Widgets.buttonGooeyCrosshair.selected  := $hf2pPreferences.GetGooeyCrosshair()
   
   var stepperElems :  vector
   stepperElems.Push("settings_brush_middle_version")
   stepperElems.Push("settings_brush_just_by_team")
   stepperElems.Push("settings_brush_by_armor")
   Widgets.stepperTeamColor.SetData(stepperElems)
   
   Widgets.stepperTeamColor.selection  := $hf2pPreferences.GetTeamColor()
   Widgets.sliderCameraFOV.slider.value := $hf2pPreferences.GetCameraFOV()
end

override HaveUnsavedChanges // () :  bool
   var result : int = 0
   
   if (!is_inited)
      return false
   end

   result := result + (int)(Widgets.buttonHUDShake.selected       != $hf2pPreferences.GetHUDShake())
   result := result + (int)(Widgets.buttonSwearFilter.selected    != $hf2pPreferences.GetSwearFilter())
   result := result + (int)(Widgets.buttonAltCrosshair.selected   != $hf2pPreferences.GetAltCrosshair())
   result := result + (int)(Widgets.buttonGooeyCrosshair.selected != $hf2pPreferences.GetGooeyCrosshair())

   result := result + (int)(Widgets.stepperTeamColor.selection    != $hf2pPreferences.GetTeamColor())
   result := result + (int)(Widgets.sliderCameraFOV.slider.value  != $hf2pPreferences.GetCameraFOV())
   
   return (result > 0)
end

override Reset // ()
   var settings : params = $hf2pPreferences.GetDefaultGameplaySettings()

   Widgets.buttonHUDShake.selected        := settings.hud_shake_enabled
   Widgets.stepperTeamColor.selection     := settings.team_color_mode
   Widgets.sliderCameraFOV.slider.value   := (int)settings.camera_fov
   Widgets.buttonSwearFilter.selected     := settings.swear_filter
   Widgets.buttonAltCrosshair.selected    := settings.alt_crosshair
   Widgets.buttonGooeyCrosshair.selected  := settings.gooey_crosshair
//   Widgets.buttonDisplayHints.selected := true
end

override Apply // ()
   if (!is_inited)
      return true
   end
   
   $hf2pPreferences.SetHUDShake(Widgets.buttonHUDShake.selected)
   $hf2pPreferences.SetTeamColor((int)Widgets.stepperTeamColor.selection)
   $hf2pPreferences.SetCameraFOV((int)Widgets.sliderCameraFOV.slider.value)
   $hf2pPreferences.SetSwearFilter(Widgets.buttonSwearFilter.selected)
   $hf2pPreferences.SetAltCrosshair(Widgets.buttonAltCrosshair.selected)
   $hf2pPreferences.SetGooeyCrosshair(Widgets.buttonGooeyCrosshair.selected)
   GenerateEvent("OnApplyFinished")
   
   return false
end

func OnResetTutorial(p:params) : bool
   // request confirmation
   var pp:params
   pp.callbackEvent  := "OnResetTutorialConfirm"
   pp.callbackTarget := Props
   pp.titleTxt       := "msg_ui_settings_confirm"      
   pp.messageTxt     := "msg_ui_settings_restart_tutorial"
   GenerateEvent("MainMenuDialogRequest", pp)

   return false
end

func OnResetTutorialConfirm(p:params):bool
   if (p.isOK) 
      $hf2pPreferences.ResetTutorial()
   end
   return false
end

handle OnEnteringState("Initial")
   AddTween("alpha", 0.0, Props.adelay, "linear")
end          

handle OnEnterState("Initial")
   Set("visible", false)            
end  
        
handle OnEnteringState("Visible")
   Init()
   Set("visible", true)
   AddTween("alpha", 1.0, Props.adelay, "linear")
end  

handle OnLeavingState("Visible")
   Init()
   Apply()
end

override SwitchToScreen // ()
   Log("ui~content", "Audio setting SwitchSlide")
   Props.visible := true
end

override PrepareSlide // ()
   Log("ui~content", "Audio setting EnableSlide")
   if (GetStateName() != "Visible")
      SetStateName("Visible")
   end
   GenerateEvent("OnEnterNewTab")
   Props.visible := true
   StartDefaultBlinking(0.5, 1.0)
   var p: params
   p.state := "s_gameplay"
   GenerateEvent("ChangeFakeBackground", p)
end

override PrepareHideSlide // ()
   StartDefaultBlinking(0.5, 1.0)
end

override DisableSlide // ()
   if (GetStateName() != "Initial")
      Log("ui~content", "Audio setting DisableSlide")
      Props.visible := false
      SetStateName("Initial")
   end
end
end
