import ssl.lib.ui.ui_widget_container

import ssl.hf2p.engine_ctrl
import ssl.lib.types
import ssl.lib.ui.ui_widget_list_item
import ssl.lib.logging
import ui.ui_party_monitor
import ui.ui_matchmaking
import ui.root
import ssl.hf2p.user_service
import ssl.hf2p.ui_globals
import ssl.hf2p.hq
import ui.libs.hf2p_Default_lib.hf2p_Default_lib

class UiLobbyVotingGroup : UiWidgetContainer

func InitForVoting()
   Widgets.mapElem1.InitForVoting()
   Widgets.mapElem2.InitForVoting()
   Widgets.mapElem3.InitForVoting()
end

func RearrangeMapButtons(p : params) : bool
   /*
   var btnIdx : int     = p.btnIdx
   var layer1 : string  = "layer1"
   var layer2 : string  = "layer2"
   var layer3 : string  = "layer3"
   if (btnIdx == 0)
      layer1 := "layer3"
      layer2 := "layer2"
      layer3 := "layer1"
   elif (btnIdx == 1)
      layer1 := "layer2"
      layer2 := "layer3"
      layer3 := "layer1"
   elif (btnIdx == 2)
      layer1 := "layer1"
      layer2 := "layer2"
      layer3 := "layer3"
   end
   Widgets.mapElem1.SetLayer(layer1)
   Widgets.mapElem2.SetLayer(layer2)
   Widgets.mapElem3.SetLayer(layer3)
   */
   
   return false
end  

end

class UiLobbyVotingGroupElem : UiWidgetContainer

var   mapId       :  int
var   isVoting    :  bool
var   votesCount  :  int = 0
var   tmpMapPic   :  string

func InitForVoting()
   isVoting                         := true
   Widgets.checkupElem.visible    := true
   Widgets.bg.votesLabelTxt.text  := "lobby_votes"
end

func InitForPreview()
   isVoting                         := false
   Widgets.checkupElem.visible    := false
   Widgets.bg.votesTxt.text       := ""
   Widgets.bg.votesLabelTxt.text  := ""
end

end

class UiLobbySuperContainer : UiWidgetContainer
     
var   isEditable        : bool = false
var   isVoting          : bool = false


func IsMapSelectionEnabled(): bool
   return false
end

func IsModeSelectionEnabled(): bool
   return false
end

func SetMapIcon(_mapIcon: string)
   Widgets.mapContainerElem.mapBtnCont.mapBtn.bg.mapIcon.pic := _mapIcon
end

func SetModeIcon(_mapIcon: string)
   Widgets.mapContainerElem.mapBtnCont.mapBtn.bg.modeIcon.pic := _mapIcon
end      

func ShowMapModeSelection(_mapMode: bool)
   Widgets.mapContainerElem.visible  := _mapMode
   Widgets.mapStepper.visible        := _mapMode
   Widgets.gameType.visible          := _mapMode
   Widgets.waitingTf.visible         := _mapMode
end

handle OnEnterState("MapModeSelection") 
   Props.visible := false         
end

func ArrangeRosters(_teamCount: int)
   var   x0    :  float    = 0
   var   midx  :  float    = 0 
   var   dist1 :  float    = 16
   var   dist2 :  float    = 24
   if (_teamCount == 1)
      x0 := 513
      midx := midx + x0
      Widgets.redTeam.x           := x0
      Widgets.headerRedTeam.x     := x0
      Widgets.headerRedTeam.text  := ""
      x0 := x0 + Widgets.redTeam.width + dist1

      midx := midx + x0
      Widgets.blueTeam.x          := x0
      Widgets.headerBlueTeam.x    := x0
      Widgets.headerBlueTeam.text := ""
      x0 := x0 + Widgets.blueTeam.width + dist2

      Widgets.mapContainerElem.x        := x0
      Widgets.mapContainerElem.y        := Widgets.blueTeam.y
      Widgets.votingGroup.x             := x0
      Widgets.votingGroup.y             := Widgets.blueTeam.y
      Widgets.mapStepper.x              := x0
      Widgets.gameType.x                := x0
      Widgets.waitingTf.x               := x0
      Widgets.playlistDropdown.x        := x0
      Widgets.playListDropDownHeader.x  := x0
      Widgets.gameModeDropdown.x        := x0
      Widgets.gameModeDropDownHeader.x  := x0
      Widgets.gameMapDropdown.x         := x0 + 288
      Widgets.gameMapDropDownHeader.x   := x0 + 288
      x0 := x0 + Widgets.mapContainerElem.mapBtnCont.mapBtn.width + dist2
      
      midx := midx / 2.0
      Widgets.headerNoTeam.x            := midx
      Widgets.headerNoTeam.text         := "lobby_txt_lobby_team"
      Widgets.headerNoTeam.visible      := true
   else
      x0 := 375
      Widgets.redTeam.x           := x0
      Widgets.headerRedTeam.x     := x0
      Widgets.headerRedTeam.text  := "lobby_txt_red_team"
      x0 := x0 + Widgets.redTeam.width + dist2

      Widgets.mapContainerElem.x        := x0
      Widgets.mapContainerElem.y        := Widgets.blueTeam.y
      Widgets.votingGroup.x             := x0
      Widgets.votingGroup.y             := Widgets.blueTeam.y
      Widgets.mapStepper.x              := x0
      Widgets.gameType.x                := x0
      Widgets.waitingTf.x               := x0
      Widgets.playlistDropdown.x        := x0
      Widgets.playListDropDownHeader.x  := x0
      Widgets.gameModeDropdown.x        := x0
      Widgets.gameModeDropDownHeader.x  := x0
      Widgets.gameMapDropdown.x         := x0 + 288
      Widgets.gameMapDropDownHeader.x   := x0 + 288
      x0 := x0 + Widgets.mapContainerElem.mapBtnCont.mapBtn.width + dist2
      
      Widgets.blueTeam.x          := x0
      Widgets.headerBlueTeam.x    := x0
      Widgets.headerBlueTeam.text := "lobby_txt_blue_team"
      x0 := x0 + Widgets.blueTeam.width + dist2
      
      Widgets.headerNoTeam.text      := x0
      Widgets.headerNoTeam.text      := ""
      Widgets.headerNoTeam.visible   := false
   end
   //float(Widgets.gameType.y) + Widgets.gameType.height + dist
end

func SetVotingMode(_isVoting: bool)
   if (_isVoting)
      Log("ui~lobby_superContainer", "OnGameMapStepperIndexChange_SetVotingMode - true")
      Widgets.votingGroup.InitForVoting()
   else
      Log("ui~lobby_superContainer", "OnGameMapStepperIndexChange_SetVotingMode - false")
      Widgets.mapContainerElem.mapBtnCont.mapBtn.InitForPreview()
   end
   isVoting := _isVoting
end
      
handle OnEnterState("Initial") 
end

end

class UiGameType : UiWidgetContainer

func OnMapModeStepperIndexChange(p: params): bool
   GenerateEvent("OnGameModeStepperIndexChange", p)
   return false
end
end

class UiMapStepper : UiWidgetContainer

func OnMapModeStepperIndexChange(p: params): bool
   Log("ui~mapStepper", "OnMapModeStepperIndexChange")
   GenerateEvent("OnGameMapStepperIndexChange", p)
   return false
end
end

class VotingGroupElemGlow : UiWidgetContainer
   var isMouseOver : bool = false
   
   func onVotingMouseDown(p : params) :  bool
      var pp : params
      pp.btnIdx := p.widget.Props.voteIdx2
      GenerateEvent("RearrangeMapButtons", pp)
      GotoAndPlay("down")
      //GotoAndStop(11) : 2
      //isMouseOver := true
      return false
   end
   
   func onVotingMouseOver(p : params) : bool
      if (! isMouseOver)
         isMouseOver := true
         GotoAndPlay("over")
      end
      return false
   end

   func onVotingMouseOut(p : params) : bool
      if (isMouseOver)
         isMouseOver := false
         GotoAndStop("up")
      end
      return false
   end
end

