import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container

class UiMenuGridRight : UiWidgetContainer

var currentArmorSelected: string = "[NONE]"
var currentLoadoutSelected: int = 0
var currentLoadoutSlot: int = 0

func SendSelectItem(_nextMenuName:string)
   Log("ui~menu_grid_right", "RP::GRID::SendSelectItem: menuName = " + _nextMenuName) 
   var p:params
   p.nextMenuName := _nextMenuName
   GenerateEvent("selectItem", p)
end

func onMenuItemClicked(p:params):bool
   Log("ui~menu_grid_right", "RP::GRID::onMenuItemClicked " + Params2Str(p))
   if (! IsVoid(p.widget.nextMenu))
      currentArmorSelected := "[NONE]"
      SendSelectItem(p.widget.nextMenu)
   end
   return false
end

func onMenuItemClickedArmor(p:params):bool
   Log("ui~menu_grid_right", "RP::GRID::onMenuItemClickedArmor " + Params2Str(p))
   if (!IsVoid(p.widget.nextMenu) and !IsVoid(p.widget.armorSet))
      currentArmorSelected := p.widget.armorSet
      SendSelectItem(p.widget.nextMenu)
   end
   return false
end

func onLoadoutItemSelectedClick(p:params):bool
   currentArmorSelected   := p.armorSet
   currentLoadoutSelected := p.LoadoutIdx
   currentLoadoutSlot     := p.LoadoutSlot
   SendSelectItem(p.nextMenu)
   return false
end

func GetWidgetByState(curMenu: string): string
   if (curMenu == "sMain")
      return "main"         
   else if (curMenu == "sArmorSelection")      
      return "armorSelection"
   else if (curMenu == "sPaintArmor")
      return "itemPaint"
   else if (curMenu == "sShowClassItems")
      return "itemClassShow"
   else if (curMenu == "sStoreSelection")
      return "storeSelection"
  else if (curMenu == "sProfile")
     return "profile"
   else if (curMenu == "sEditLoadout")
      return "pageEditLoadout"
   else if (curMenu == "sItemSelectLoadout")
      return "pageItemSelectLoadout"
   end
   
   return ""      
end

handle OnEnterState("sMain")
   Widgets().main.OnShowGrid()
end

handle OnEnterState("sPaintArmor")
   Widgets().itemPaint.Init()
end

handle OnEnterState("sShowClassItems")
   Widgets().itemClassShow.object.populateList(currentArmorSelected)
end

handle OnEnterState("sProfile")
   Log("ui~menu_grid_right", "state sPtofile")
end

handle OnEnterState("sEditLoadout")
   Widgets().pageEditLoadout.object.populateListPrivate()
end

handle OnEnterState("sItemSelectLoadout")
   Widgets().pageItemSelectLoadout.object.populateList(currentArmorSelected, currentLoadoutSelected, currentLoadoutSlot)
end
end
