import ssl.lib.ui.ui_widget_container
import ssl.hf2p.engine_ctrl
import ssl.observables
import ssl.lib.ui.bindings.bindings
import ssl.hf2p.ui_globals
import ssl.hf2p.user_data
import ui.libs.hf2p_KillerPanel_lib.hf2p_KillerPanel_lib

class UiPodiumLoadout : UiWidgetContainer
   handle OnEnteringState("Winner")
      Props().visible := true
      $root.playSound("podium_stats_loadout_appear")
   end
   handle OnEnteringState("Visible") // (name : string)
      Props().visible := true
   end
   handle OnEnterState("Win") // (name : string)
      Props().visible := true
      GotoAndPlay("fadeIn")
   end
   handle OnEnterState("Visible") // (name : string)
      SetStateName("Initial") : 1.0
   end   
   handle OnEnterState("Initial") // (name : string)
      Props().visible := false
   end   
end

class UiPodiumPoints : UiWidgetContainer
   handle OnEnteringState("Winner") // (name : string)
      Props().visible := true
   end
   handle OnEnteringState("Visible") // (name : string)
      Props().visible := true
   end
   handle OnEnterState("Win") // (name : string)
      Props().visible := true
      GotoAndPlay("fadeIn")
   end
   handle OnEnterState("Visible") // (name : string)
      SetStateName("Initial") : 1.0
   end   
   handle OnEnterState("Initial") // (name : string)
      Props().visible := false
   end   
end

class UiPodiumPlaceScreen : UiWidgetContainer


var current_stage    : int    = -1
var podium_players   : params
var debug_on         : bool   = false
var isSubscribed     : bool   = false

func ShowPoints(_place : int)
   if (_place == 0)
      Widgets().points.SetStateName("Winner")
   else
      Widgets().points.SetStateName("Initial")
   end   
end

func ShowLoadout(_place : int)
   if (_place == 0)
      Widgets().loadout.SetStateName("Winner")
   else
      Widgets().loadout.SetStateName("Initial")
   end
end

func FillSkillAndWeaponStats(playerUID : *, placeIdx : int)

   var ud               : UserData              = (UserData)$UserDataStorage.users.Get(playerUID)
   var scoreboardPlayer : GL_ScoreboardPlayer   = $UiGlobals.gameplay.scoreboard.FindPlayer(playerUID)
   var playerScore      : string                = ""
   
   if (scoreboardPlayer != null)
      Widgets().points.killsContainer.tfNum.text      := (string)(scoreboardPlayer.kills.Get())
      Widgets().points.assistsContainer.tfNum.text    := (string)(scoreboardPlayer.assists.Get())
      Widgets().points.headshotsContainer.tfNum.text  := (string)(scoreboardPlayer.deaths.Get())
      Widgets().points.meleeContainer.tfNum.text      := (string)(scoreboardPlayer.wp.Get())
      
      playerScore := (string)(scoreboardPlayer.wp.Get())
   else
      Widgets().points.killsContainer.tfNum.text      := " ???"
      Widgets().points.assistsContainer.tfNum.text    := " ???"
      Widgets().points.headshotsContainer.tfNum.text  := " ???"
      Widgets().points.meleeContainer.tfNum.text      := " ???"
      
      playerScore := " ???"
   end
   ShowPoints(placeIdx) : 0.25
   
   /*
   if (stage == "Third")
      inner_p := podium_players.Name3rd
   else if (stage == "Second")
      inner_p := podium_players.Name2nd
   else if (stage == "First")
      inner_p := podium_players.Name1st
   end
   
   Widgets().points.killsContainer.tfNum.text     := (string)(inner_p.kills)
   Widgets().points.assistsContainer.tfNum.text   := (string)(inner_p.assists)
   Widgets().points.headshotsContainer.tfNum.text := (string)(inner_p.deaths)
   Widgets().points.meleeContainer.tfNum.text     := (string)(inner_p.melee)
   Widgets().loadout.topLeftPanel.tfNIckName.text := inner_p.name
   */
   
   //Widgets().loadout.topLeftPanel.tfNIckName.text := inner_p.name
      
   var playerName    : wstring = ud.base.full_nickname.Get()   
   if (placeIdx == 0)
      $root.playSound("podium_1st_highlight")
      Widgets().podium.firstPlaceAnimContainer.nicknameTfContainer.tf.text    := playerName
      Widgets().podium.firstPlaceAnimContainer.scoreContainer.tf.text         := playerScore
   elif (placeIdx == 1)
      $root.playSound("podium_2nd_highlight")
      Widgets().podium.secondPlaceAnimContainer.nicknameTfContainer.tf.text   := playerName
      Widgets().podium.secondPlaceAnimContainer.scoreContainer.tf.text        := playerScore
   elif (placeIdx == 2)
      $root.playSound("podium_3rd_highlight")
      Widgets().podium.thirdPlaceAnimContainer.nicknameTfContainer.tf.text    := playerName
      Widgets().podium.thirdPlaceAnimContainer.scoreContainer.tf.text         := playerScore
   end

   var p : params
   p.uid := playerUID
   GenerateEvent("#SetPodiumLoadoutUID", p)
   Widgets().loadout.topLeftPanel.nicknameTf.tfNIckName := playerName
   ShowLoadout(placeIdx) : 0.25
end

handle OnTerm
   if (isSubscribed)
      $UiGlobals.gameplay.podium.state.Unsubscribe(this, "PodiumUpdate")
      $UiGlobals.gameplay.podium.participants_version.Unsubscribe(this, "PodiumUpdate")            
      isSubscribed := false
   end
end

handle OnEnteringState("Initial")
   bLog("UI/PODIUM", "Initial")
   if (isSubscribed)
      $UiGlobals.gameplay.podium.state.Unsubscribe(this, "PodiumUpdate")
      $UiGlobals.gameplay.podium.participants_version.Unsubscribe(this, "PodiumUpdate")            
      isSubscribed := false
   end
end

handle OnEnterState("Initial")
   Props().visible := false
end

handle OnEnteringState("Visible")
   bLog("UI/PODIUM", "Visible")
   Widgets().points.visible   := false
   Widgets().loadout.visible  := false
   Props().visible := true
   if (! isSubscribed)
      isSubscribed := true         
      if ($UiGlobals.gameplay.podium.participants.Get().Count() > 0)
         PodiumUpdate(null)
      end
      $UiGlobals.gameplay.podium.state.Subscribe(this, "PodiumUpdate")
      $UiGlobals.gameplay.podium.participants_version.Subscribe(this, "PodiumUpdate")
   end
   SetFocus()
end

func StartPodiumAnim(_idx : int)
   if (_idx == 0)
      Widgets().podium.firstPlaceAnimContainer.SetStateName("Visible")
   elif (_idx == 1)
      Widgets().podium.secondPlaceAnimContainer.SetStateName("Visible")
   elif (_idx == 2)      
      Widgets().podium.thirdPlaceAnimContainer.SetStateName("Visible")
   end
end

func PodiumUpdate(_val : *)
   var podiumState : int = (int)$UiGlobals.gameplay.podium.state.Get()
   if (podiumState == $uiEnums.PODIUM_STATE_SHOW_OFF)
      var top3 : vector = $UiGlobals.gameplay.podium.participants.Get()
      var idx  : int    = top3.Count() - 1
      if (idx >= 0)
         var uid  : *   = top3.Get(idx).id.Get()
         var place: int = top3.Get(idx).place.Get()
         if (place >= 0 and place < 3)
            FillSkillAndWeaponStats(uid, place)
            StartPodiumAnim(place)            
         end
      end
   elif (podiumState == $uiEnums.PODIUM_STATE_SCOREBOARD)
      GenerateEvent("OnPodiumPlayEnded")
   end
end

handle OnEnterState("Visible")

   //Props().visible := true
end

handle OnEnteringState("Third")
   //current_stage := 3
   //$hf2pEngine.ShowFinishedPostpone(current_stage)
   //FillSkillAndWeaponStats("Third")
end

handle OnEnterState("Third")
   current_stage := 3
   //SetStateName("Second")
end

handle OnEnteringState("Second")
   //current_stage := 2
   //$hf2pEngine.ShowFinishedPostpone(current_stage)
   //FillSkillAndWeaponStats("Second")
end

handle OnEnterState("Second")
   current_stage := 2
   //SetStateName("First")
end

handle OnEnteringState("First")
   //current_stage := 1
   //$hf2pEngine.ShowFinishedPostpone(current_stage)
   //FillSkillAndWeaponStats("First")
end

handle OnEnterState("First")
   current_stage := 1
   //GenerateEvent("OnPodiumPlayEnded")
end
end

class UiPodiumVM
   var loadoutVM           : UiKillerLoadoutVM  = new UiKillerLoadoutVM()
   
   func SetPodiumLoadoutUID(p : params) : bool
      loadoutVM.isVisible.Set(true)
      loadoutVM.SetUid(p.uid)
      return true
   end
end
