import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.engine_ctrl
import ui.root

class UiLowerPanel : UiWidgetContainer
 
func Init()
end
   

func SetCreepingLine(p:params)
   Widgets().creepingLine.tf.SetCreepingLine(p)
end

func CreepingLineTest(txt:string)
   var creepParm: params
   creepParm.text         := txt
   creepParm.refreshTime  := 100
   creepParm.delta        := -1000

   SetCreepingLine(creepParm)      
end

handle OnEnteringState("Hidden")
   Log("ui~lowerPanel", "Lower panel OnEntering HIDDEN!!!")
   CreepingLineTest("UI_LP_INV")
   GotoAndPlay("fadeOut")
end   

handle OnEnterState("Hidden")
   Log("ui~lowerPanel", "Lower panel onEnter HIDDEN!!!")
end   

handle OnEnteringState("Visible")
   Log("ui~lowerPanel", "Lower panel OnEntering VISIBLE!!!")
   ApplyAlign()
   Init()
   Widgets().chatCont.newsList.GenerateEvent("#UpdateNews")
   Set("visible", true)
   Set("alpha", 100.0)
   CreepingLineTest("UI_LP_VIS")
   GotoAndPlay("fadeIn")
   StartDefaultBlinking(15.0/35.0)
end   

handle OnEnterState("Visible")
   Log("ui~lowerPanel", "Lower panel onEnter VISIBLE!!!")
   CreepingLineTest("UI_LOWP_VIS")   
end   
end

class UiLowerPanelSettings : UiWidgetContainer
   handle OnEnteringState("Visible")
      Set("visible", true)
      GotoAndPlay("fadeIn")
      StartDefaultBlinking(17.0/35.0)
   end   

   handle OnEnteringState("Hidden")
      Set("visible", true)
      GotoAndPlay("fadeOut")
   end   
end

class UiLowerPanelExit : UiWidgetContainer
   handle OnEnteringState("Visible")
      Set("visible", true)
      GotoAndPlay("fadeIn")
      //Props().label := "main_ui_exit_game"
      //Props().textField := "main_ui_exit_game"
      StartDefaultBlinking(17.0/35.0)
   end

   handle OnEnteringState("Hidden")
      Set("visible", true)
      GotoAndPlay("fadeOut")
   end   
end

class UiNewsListVM
   var newsList : ObservableProperty = $OM.Calculated(this, "GetNewsList")
   
   func UiNewsListVM()
      newsList.Invalidate()
   end
   
   func Init()
      newsList.Invalidate()
   end
   
   func UpdateNews(p : params) : bool
      newsList.Invalidate()
      return true
   end
   
   func GetNewsList() : vector
      var   ret      : vector
      var   newsVec  : vector = $UiGlobals.news.Get()
      var   i        : int
      var   num      : int = 0
      
      for i := 0 to newsVec.Count() - 1
         var newsRec       : GL_News = (GL_News)newsVec.Get(i)
         var newsElem      : params
         newsElem.header1  := "main_news_author"
         newsElem.header2  := "main_news_date"
         newsElem.header3  := "main_news_message"
         newsElem.text1    := (string)newsRec.author.Get()
         newsElem.text2    := (string)newsRec.date.Get()
         newsElem.text3    := (string)newsRec.text.Get()
         num               := num + 1
         ret.Push(newsElem)
      end      
      /*
      for i := 0 to 10
         var newsElem      : params
         newsElem.header1  := "main_news_author"
         newsElem.header2  := "main_news_date"
         newsElem.header3  := "main_news_message"
         newsElem.text1    := "user_" + (string)i
         newsElem.text2    := (string)i + ".01.2099"
         newsElem.text3    := "everything's borrowed"
         num               := num + 1
         ret.Push(newsElem)
      end      
      */
      return ret
   end
end

class UiNewsListLIR : UiWidgetListItem
   override SetData
      Props().mouseEnabled    := false
      Props().mouseChildren   := false
   end
end