import ssl.lib.logging
import ssl.lib.ui.ui_widget_container
import ssl.hf2p.engine_ctrl
import ssl.hf2p.ui_globals
import ssl.hf2p.user_service
import ui.root
import ui.hf2p_SlidingScreens.hf2p_Lobby.hf2p_Lobby


class ProfilePresentScreen : UiWidgetContainer

handle OnEnteringState("Initial")
end   

handle OnEnterState("Initial")
   Set("visible", false)            
end   

handle OnEnteringState("Visible")
   Set("visible", true)       
end   

handle OnEnterState("Visible")
   Log("ui~content", "OnEnterState")         
end   

func onLabelTabClicked() : bool
   return false
end

func onEmblemTabClicked() : bool
   return false
end

func PrepareSlide()
   if (GetStateName() != "Visible")
      SetStateName("Visible")
   end
   EnableFakeBg()
end
 
func PrepareHideSlide()
end

func DisableSlide()
   if (GetStateName() != "Initial")
      SetStateName("Initial")
   end
end

func EnableFakeBg()
   var p: params
   p.state := "profile_present"
   GenerateEvent("ChangeFakeBackground", p)
end

end // ProfilePresentScreen

class ProfilePresentVM
   var labelList        : ObservableProperty = $OM.Calculated(this, "GetLabelsList")
   var rosterCard       : RosterCardVM       = new RosterCardVM() 
   
   func Init(p : params)
      var plrId : * = GetUID()
      /*
      if ($UserDataStorage.IsValidUID(plrId))
         $user_service.RequestData(plrId, $uiEnums.USER_DATA_BASE)
         $user_service.RequestData(plrId, $uiEnums.USER_DATA_STATS)            
         $user_service.RequestData(plrId, $uiEnums.USER_DATA_ARMOR_LOADOUT)
         $user_service.RequestData(plrId, $uiEnums.USER_DATA_WEAPON_LOADOUT)
      end
      */
   end
   
   func GetLabelsList() : vector
      var   vec : vector    
      var   p           : params
      var i : int
      for i := 0 to 6
         p.name     := "label"
         p.icon     := "profilePresentation"
         vec.Push(p.Clone())
      end   
      return vec
   end
   
   func GetPlayerCardVM() : RosterCardVM
      var plrId : * = GetUID()
      if ($UserDataStorage.IsValidUID(plrId))
         
      end
      rosterCard.isActive.Set(true)
      rosterCard.SetTeam(false, 0)
      var uid : GL_UID = new GL_UID
      uid.value := $OM.Property(GetUID())
      rosterCard.SetUID(uid)
      return rosterCard
   end
   
   func GetUID() : *
      return $UserDataStorage.local_user.uid.Get()
   end
   
   func IsLocalUser() : bool
      return $UserDataStorage.IsLocalUID(GetUID())
   end
   
   func GetUserName() : wstring
      var ud   : UserData  = GetUserData()
      var ret  : wstring    = ud.base.full_nickname.Get()
      ret := $root.MakeColorCodedWText(ret, $UserDataStorage.GetPlayerStatusColorCode(GetUID()))
      return ret
   end

   func GetUserData() : UserData
      var ret : UserData = (UserData) $UserDataStorage.users.Get(GetUID())
      return ret
   end
     
end