import ssl.lib.logging
import ssl.lib.types
import ssl.lib.ui.ui_widget_container
import ssl.lib.ui.ui_widget_manager
import ssl.hf2p.engine_ctrl
import ssl.hf2p.items_mgr
import ssl.observables
import ssl.hf2p.ui_globals
import ssl.hf2p.user_data
import ssl.hf2p.hq
import ui.root
import ui.ui_economy
import ui.ui_player_info
import ui.libs.hf2p_ChallengesScreen_lib.hf2p_ChallengesScreen_lib
import ui.libs.hf2p_ItemPopup_lib.hf2p_ItemPopup_lib

class UiTechTreeScr : UiSlidingScreenPageMainMenu  

handle OnEnteringState("Visible")
   $UiBiLogger.LogGlobalStateChange($uiEnums.UI_BI_SKILL_TREE)
   Log("ui~UiTechTreeScr", "UiTechTreeScr_Visible")
   Set("visible", true)
   SetAdditionalScreenOptions()
end

handle OnEnteringState("Initial")
   Log("ui~UiTechTreeScr", "UiTechTreeScr_Initial")
   Set("visible", false)
end

func SetAdditionalScreenOptions()
   //Widgets.treeContent.techTreeList.Set("direction", "vertical")
   Widgets.techTreeCard.visible := false
   StartDefaultBlinking(0.2, 2.0)
   //Widgets.tfUnlocked.tf := " "
end

func CloseTechCard(p : params) :  bool
   Widgets.techTreeCard.visible := false
   Widgets.treeContent.techTreeList.SetFocus()
   return false
end

func OpenTechCard(p : params) :  bool
   Widgets.techTreeCard.visible := true
   Widgets.techTreeCard.popupCard.cancelBtn.SetFocus()
   $root.playSound("tab_select")
   return false
end
 
func onTechListScroll(p : params) : bool
   /*
   var defRot    : int = -20
   var scrollPos : int = p.widget.Get("scrollPosition")
   var newPos    : int = defRot + (scrollPos * 10)
   var delta     : int = defRot - (scrollPos * 10)
   var i : int
   for i := delta to newPos
      Widgets.treeContent.techTreeList.yrotation := (float)i
   end
   */
   return false
end

override PrepareSlide // ()
   if (GetStateName() != "Visible")
      SetStateName("Visible")
      GenerateEvent("#OpenTechTree")
   end
end

override PrepareHideSlide // ()
end

override DisableSlide // ()
   if (GetStateName() != "Initial")
      SetStateName("Initial")
      GenerateEvent("#CloseTechTree")
   end
end

func BlinkFast(_isTreeMode : bool)
   if (_isTreeMode)
      Widgets.treeContent.StartDefaultBlinking(0, 2.0)
   end
end

func BlinkFull(_isTreeMode : bool)
   StartDefaultBlinking(0, 1.0)
end

end // UiTechTreeScr

class UiTechCard : UiWidgetContainer  
   func inputEvent(p : params) : bool
      var isTerminated : bool = false
      if (p.keyCode == $uiKeys.VK_ESC)
         isTerminated := true         
      end
      if (!p.isDown)
         GetDC().CloseCard()
      end
      if (isTerminated)
         p.eventState.SetIsTerminated()
      end
      return !isTerminated
   end   
end // UiTechCard

class UiTechTreeLir : UiWidgetListItem

end // UiTechTreeLir

class UiTechTreeVM : UiSlidingScreenMainMenuPageVM
   
   var wgt                       : UiTechTreeScr      = null
   var techTreeTileList          : ObservableProperty = $OM.Calculated(this, "GetTechTreeList")
   var clsDesc                   : ObservableProperty = $OM.Calculated(this, "GetClassDesc")
   var clsIcon                   : ObservableProperty = $OM.Calculated(this, "GetClassIcon")
   var techClassIdx              : ObservableProperty = $OM.Property(0)
   var isTreeMode                : ObservableProperty = $OM.Property(true)
   var techCardPopupVM           : UiTechCardVM       = new UiTechCardVM()
   
   override InitOverride //(p : params)
      wgt := p.widget
      techCardPopupVM.Init()
      techCardPopupVM.parentVM := this
      techCardPopupVM.wgt := wgt.Widgets.techTreeCard.popupCard.object
   end   
   
   override TermOverride //()
      techCardPopupVM.Term()
   end
   
   func OpenTechTree(p : params) : bool
      techTreeTileList.Invalidate()
      clsDesc.Invalidate()
      clsIcon.Invalidate()
      isActive.Set(true)
      isTreeMode.Set(true)
      if ((bool)$UiGlobals.techOpenFirstTime.Get())
         var udLocal : UserDataLocal = $UserDataStorage.local_user
         var classIdx : int = (int)udLocal.class_id.Get()
         techClassIdx.Set(classIdx)
         $UiGlobals.techOpenFirstTime.Set(false)
      end
      //wgt.BlinkFull(GetIsTreeMode())
      if ($UiGlobals.techOpenTechId != "")
         var tabIdx : int = FindTechItemTabIdx($UiGlobals.techOpenTechId)
         if tabIdx != -1
            techClassIdx.Set(tabIdx)
            if ((bool)isTreeMode.Get())
               $UiBiLogger.LogSkilTreeState(GetTechTreeLabel((int)techClassIdx.Get()), $uiEnums.UI_BI_SKILL_VIEW_TREE)
            else
               $UiBiLogger.LogSkilTreeState(GetTechTreeLabel((int)techClassIdx.Get()), $uiEnums.UI_BI_SKILL_VIEW_LIST)
            end   
         end
         $UiGlobals.techOpenTechId := ""
      end
      return false
   end   
   
   func FindTechItemTabIdx(techItemId : string) : int
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         if (! IsVoid(shop.career.Get()))
            var i : int
            var j : int
            var k : int
            for i := 0 to shop.career.Get().Count() - 1
               var subshop : GL_ShopSection = (GL_ShopSection)shop.career.Get().Get(i)
               for j := 0 to subshop.shelves.Get().Count() - 1
                  var shelf      :  GL_ShopShelf   = (GL_ShopShelf)subshop.shelves.Get().Get(j)
                  for k := 0 to shelf.items.Get().Count() - 1
                     if shelf.items.Get().Get(k).value.Get() == techItemId
                        return i
                     end
                  end
               end
            end
         end
      end
      return -1
   end
   
   func CloseTechTree(p : params) : bool
      isActive.Set(false)
      return false
   end   
      
   func CloseTechCard()
      wgt.CloseTechCard(null)
      techCardPopupVM.isCardOpen.Set(false)
   end   
   
   func OnTechCardBgClicked(p : params) : bool
      CloseTechCard()
      return true
   end
   
   func OpenTechCard(p : params) : bool
      wgt.GenerateEvent("OpenTechCard")
      techCardPopupVM.SetChallengeTech(p.tech)
      wgt.Widgets.techTreeCard.StartDefaultBlinking(-0.25, 2.0)
      return false
   end
   
   func GetIsTreeMode() : bool
      return (bool)isTreeMode.Get()
   end
   
   func RefreshFast()
      wgt.BlinkFast(GetIsTreeMode())      
   end
   
   func OnToggleContent(p : params) : bool
      isTreeMode.Set(!GetIsTreeMode())
      RefreshFast()
      return true
   end
   
   func GetToggleBtnLabel() : string
      var ret : string
      if ((bool)isTreeMode.Get())
         ret := "carousel_research_list_view"
         $UiBiLogger.LogGlobalStateChange($uiEnums.UI_BI_SKILL_TREE)
      else
         ret := "carousel_research_tree_view"
         $UiBiLogger.LogGlobalStateChange($uiEnums.UI_BI_SKILL_CHALLENGES)
      end      
      return ret
   end
   
   func GetTabIdx() : int
      return (int)techClassIdx.Get()
   end
   
   func GetItemChallenges() : vector
      isActive.Get()
            
      var ret : vector
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         if (!IsVoid(shop) and shop!=null and ! IsVoid(shop.career.Get()) and shop.career.Get().Count() > GetTabIdx())
            var subshop : GL_ShopSection = (GL_ShopSection)shop.career.Get().Get(GetTabIdx())
            if (! IsVoid(subshop.shelves))
               var i : int
               for i := 0 to subshop.shelves.Get().Count() - 1
                  var shelf      :  GL_ShopShelf   = (GL_ShopShelf)subshop.shelves.Get().Get(i)
                  if (! IsVoid(shelf.items.Get()))
                     var j : int
                     for j := 0 to shelf.items.Get().Count() - 1
                        var techId : string = (string)shelf.items.Get().Get(j).value.Get()
                        if (techId != $uiEnums.TECH_EMPTY and techId != $uiEnums.TECH_COMING)
                           var p : params
                           p.challengeItemId := techId
                           ret.Push(p)
                        end
                     end   
                  end
               end   
            end
         end
      end
      return ret      
   end
   
   func GetTechTreeList() : vector
      var ret : vector
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         if (!IsVoid(shop) and shop!=null and ! IsVoid(shop.career.Get()) and shop.career.Get().Count() > (int)(techClassIdx.Get()))
            var subshop : GL_ShopSection = (GL_ShopSection)shop.career.Get().Get((int)(techClassIdx.Get()))
            if (! IsVoid(subshop.shelves))
               var i : int
               var j : int
               for i := 0 to subshop.shelves.Get().Count() - 1
                  var shelf      :  GL_ShopShelf   = (GL_ShopShelf)subshop.shelves.Get().Get(i)
                  if (! IsVoid(shelf.items.Get()))
                     for j := 0 to shelf.items.Get().Count() - 1
                        var p : params
                        p.techId := shelf.items.Get().Get(j)
                        p.techClsIdx := (int)techClassIdx.Get() 
                        p.leftArrow := 0
                        p.centerArrow := 0
                        p.rightArrow := 0
                        ret.Push(p)
                     end   
                  end
               end
               i := 0
               while i < ret.Count() - 5
                  var compShop : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(ret.Get(i).techId.value.Get())
                  var targetTech : string
                  if i % 5 != 0
                     targetTech := ret.Get(i + 4).techId.value.Get()
                     for j := 0 to compShop.unlocks.Get().Count() - 1
                        if targetTech == compShop.unlocks.Get().Get(j).value.Get()
                           var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(targetTech)
                           if shopComp.availability.Get() != $uiEnums.TECH_STATUS_AVAILABLE
                              ret.Get(i).leftArrow := 1
                           else
                              ret.Get(i).leftArrow := 2
                           end
                        end
                     end
                  end
                  if i % 5 != 4
                     targetTech := ret.Get(i + 6).techId.value.Get()
                     for j := 0 to compShop.unlocks.Get().Count() - 1
                        if targetTech == compShop.unlocks.Get().Get(j).value.Get()
                           var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(targetTech)
                           if shopComp.availability.Get() != $uiEnums.TECH_STATUS_AVAILABLE
                              ret.Get(i).rightArrow := 1
                           else
                              ret.Get(i).rightArrow := 2
                           end
                        end
                     end
                  end
                  targetTech := ret.Get(i + 5).techId.value.Get()
                  for j := 0 to compShop.unlocks.Get().Count() - 1
                     if targetTech == compShop.unlocks.Get().Get(j).value.Get()
                        var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(targetTech)
                        if shopComp.availability.Get() != $uiEnums.TECH_STATUS_AVAILABLE
                           ret.Get(i).centerArrow := 1
                        else
                           ret.Get(i).centerArrow := 2
                        end
                     end
                  end
                  i += 1
               end
            end
         end
      end
      return ret
   end
   
   func GetTechTreeListVec() : vector
      return techTreeTileList.Get()
   end
   
   func GetFirstTech() : string
      var ret     : string = ""
      var elems   : vector = GetTechTreeListVec()
      var i       : int
      for i := 0 to elems.Count() - 1
         var id : string = elems.Get(i).techId.value.Get()
         if (id != $uiEnums.TECH_EMPTY)
            ret := id
            break
         end
      end
      return ret
   end
   
   func GetTokenFrame() : string
      isActive.Get()
      var ret : string = $UiGlobals.GetTokenFrame(GetCurrentTokenType())
      return ret
   end
   
   func GetTechPointsInt() : int
      var ret     : int = 0
      var tokenId : string = GetCurrentTokenType()
      ret := $UiGlobals.Int64ToInt($UserDataStorage.local_user.GetTokenCount(tokenId))
      return ret
   end
   // TODO : prop invalidate
   func GetTechPoints() : string
      isActive.Get()
      return (string)GetTechPointsInt()
   end
   
   func GetCurrentTokenType() : string
      var techId     : string             = GetFirstTech()
      var compShop   : GL_ComponentShop   = (GL_ComponentShop)$UiGlobals.componentsShop.Get(techId)
      var ret        : string             = compShop.GetTokenType()
      return ret
   end
   
   func GetSumTechItems() : int
      var sum : int = 0
      var techVec : vector = techTreeTileList.Get()
      var i : int
      for i := 0 to techVec.Count() - 1
         if ((string)techVec.Get(i).techId.value.Get() != $uiEnums.TECH_EMPTY and (string)techVec.Get(i).techId.value.Get() != $uiEnums.TECH_COMING)
            sum := sum + 1
         end
      end   
      return sum
   end
   
   func GetSumOwnedTechItems() : int
      var sum : int = 0
      var techVec : vector = techTreeTileList.Get()
      var i : int
      for i := 0 to techVec.Count() - 1
         var invComp : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)techVec.Get(i).techId.value.Get())
         var ownType : int = (int)invComp.ownership_type.Get()
         if (ownType == $uiEnums.ITEM_OWN_TYPE_PURCHASED)
            sum := sum + 1
         end
      end   
      return sum
   end
   
   func GetTechTreeLabel(tabIdx : int) : string
      //hack (isActive)
      var ret : string
      if ((bool)isActive.Get())
         if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
            var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
            if (! IsVoid(shop.career.Get()) and shop.career.Get().Count() > tabIdx)
               var subshop : GL_ShopSection = (GL_ShopSection)shop.career.Get().Get(tabIdx)
               var uiID    : string = (string)subshop.section_id.Get()
               var name    : string  = (string)((GL_ComponentUI)$UiGlobals.componentsUI.Get(uiID)).name.Get()
               if (name == "")
                  name := uiID
               end
               ret := name
            end
         end
      else
         ret := ""
      end
      return ret
   end
   
   func GetTabClassIcon(tabIdx : int) : string
      var ret : string
      if ((bool)isActive.Get())
         if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
            var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
            if (! IsVoid(shop.career.Get()) and shop.career.Get().Count() > tabIdx)
               var subshop : GL_ShopSection = (GL_ShopSection)shop.career.Get().Get(tabIdx)
               var uiID    : string = (string)subshop.section_id.Get()
               var icon    : string  = (string)((GL_ComponentUI)$UiGlobals.componentsUI.Get(uiID)).icon_med.Get()
               if (icon == "")
                  icon := uiID
               end
               ret := icon
            end
         end
      else
         ret := ""
      end
      return ret
   end
   
   func BigHeaderVisible() : bool
      return (bool)$UiGlobals.techSelectView.Get()
   end
   
   func GetTechSubHeader() : wstring
      var ret : wstring
      var p : params
      p.t1 := $root.MakeColorCodedWText($UiGlobals.String2WString((string)GetSumOwnedTechItems()), "#FFFFFF")
      p.t2 := " / " + GetSumTechItems() + " "
      //p.t3 := $root.MakeColorCodedWText($UiGlobals.String2WString("carousel_unlocked"), "#546A83")
      p.t3 := $root.MakeLinkWText($UiGlobals.String2WString("carousel_unlocked"), "link", "")
      ret := p.t1 + p.t2 + p.t3
      return ret
   end
   
   func GetClassDesc() : string
      var ret : string
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         if (! IsVoid(shop.career.Get()) and shop.career.Get().Count() > (int)techClassIdx.Get())
            var subshop : GL_ShopSection = (GL_ShopSection)shop.career.Get().Get((int)techClassIdx.Get())
            var uiID    : string = (string)subshop.section_id.Get()
            var desc    : string  = (string)((GL_ComponentUI)$UiGlobals.componentsUI.Get(uiID)).desc.Get()
            if (desc == "")
               desc := "TECH CLASS DESC UI"
            end
            ret := desc
         end
      end
      return ret
   end
   
   func GetClassIcon() : string
      var ret : string
      if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
         var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
         if (! IsVoid(shop.career.Get()) and shop.career.Get().Count() > (int)techClassIdx.Get())
            var subshop : GL_ShopSection = (GL_ShopSection)shop.career.Get().Get((int)techClassIdx.Get())
            var uiID    : string = (string)subshop.section_id.Get()
            var icn    : string  = (string)((GL_ComponentUI)$UiGlobals.componentsUI.Get(uiID)).icon_big.Get()
            if (icn == "")
               icn := ""
            end
            ret := icn
         end
      end
      return ret
   end
   
   func IsTabEnabled(tabIdx : int) : bool
      var ret : bool = false
      if ((bool)isActive.Get())
         if (! IsVoid($UiGlobals.shop.race_shops) and $UiGlobals.shop.race_shops.Get().Count() > 0)
            var shop       :  GL_ShopRace    = (GL_ShopRace)$UiGlobals.shop.race_shops.Get().Get((int)$UserDataStorage.local_user.race.Get())
            if (! IsVoid(shop.career.Get()) and shop.career.Get().Count() > tabIdx)
               ret := true   
            end
         end   
      end
      return ret
   end
   
   func OnTechTreeTabClicked(p : params) : bool
      var clsIdx : int = p.widget.techClassIndex
      if (clsIdx >= 0 and clsIdx != (int)techClassIdx.Get())
         RefreshFast()
         techClassIdx.Set(clsIdx)
         if ((bool)isTreeMode.Get())
            $UiBiLogger.LogSkilTreeState(GetTechTreeLabel((int)techClassIdx.Get()), $uiEnums.UI_BI_SKILL_VIEW_TREE)
         else
            $UiBiLogger.LogSkilTreeState(GetTechTreeLabel((int)techClassIdx.Get()), $uiEnums.UI_BI_SKILL_VIEW_LIST)
         end
      end   
      return false
   end
   
   func onTechTreeListClick(p : params) : bool
      var idx : int = p.index
      return false
   end
   
   func GetTierLabel(scrollPos : int, idx : int) : string
      var ret : string = "T " + (string)(scrollPos + 1 + idx) + "~"
      return ret
   end
   
   func ShowItemInShop(_item : string)
      var url : vector
      url.Push("shop")
      url.Push("shop")
      url.Push(_item)
      var pp : params
      pp.urlComp := url
      wgt.GenerateEvent("CloseTechCard")
      wgt.GenerateEvent("ShowShopItem", pp)
   end   
end // UiTechTreeVM

class UiTechLirVM
   
   var wgt                  : UiWidget = null
   var tech                 : ObservableProperty = $OM.Property(null)
   var clsIndex             : ObservableProperty = $OM.Property(0)
   var techNameUi           : ObservableProperty = $OM.Calculated(this, "GetTechLabel")
   var techIcon             : ObservableProperty = $OM.Calculated(this, "GetTechIcon")
   var isLocked             : ObservableProperty = $OM.Calculated(this, "GetIsLocked")
   var leftArrow            : ObservableProperty = $OM.Property(0)
   var centerArrow          : ObservableProperty = $OM.Property(0)
   var rightArrow           : ObservableProperty = $OM.Property(0)

   func Init(p : params)
      wgt := p.widget
      if (! IsVoid(p.tech))
         tech.Set(p.tech.techId)
         clsIndex.Set(p.tech.techClsIdx)
         leftArrow.Set(p.tech.leftArrow)
         centerArrow.Set(p.tech.centerArrow)
         rightArrow.Set(p.tech.rightArrow)
      end
   end   
   
   func IsValid() : bool
      return !IsVoid(tech.Get()) and tech.Get() != null      
   end
   
   func IsTechComing() : bool
      var ret : bool = false
      if (IsValid())
         if ((string)tech.Get().value.Get() == $uiEnums.TECH_COMING)
            ret := true
         end
      end
      return ret
   end
   
   func IsTechEmpty() : bool
      var ret : bool = false
      if (IsValid())
         if ((string)tech.Get().value.Get() == $uiEnums.TECH_EMPTY)
            ret := true
         end
      end
      return ret
   end
   
   func OnTechLirClicked(p : params) : bool
      if (IsValid())
         var pp : params
         pp.tech := (string)tech.Get().value.Get()
         if (pp.tech != $uiEnums.TECH_EMPTY and !IsTechComing() and !(bool)$UiGlobals.techSelectView.Get())
            wgt.GenerateEvent("#OpenTechCard", pp)
         end   
      end
      return false
   end
   
   func GetTechLabel() : string
      var ret : string
      if (IsValid())
         var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(tech.Get().value.Get())
         ret := (string)compUI.name.Get() 
      end
      return ret
   end
   
   func GetTechIcon() : string
      var ret : string
      if (IsValid())
         var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(tech.Get().value.Get())
         ret := (string)compUI.icon_med.Get() 
      end
      return ret
   end
   
   func GetAlpha() :  float
      var ret :  float = 0
      if (IsValid())
         var techName : string
         techName := (string)tech.Get().value.Get() 
         if (techName != $uiEnums.TECH_EMPTY)
            ret := 100
         end
      end
      return ret
   end
      
   func GetStatusLabel() : string
      var ret : string
      if (IsValid())
         var shopComp     : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)tech.Get().value.Get())
         if (shopComp.offers.Get().Count() > 0)
            var offer : GL_ComponentShopOffer = (GL_ComponentShopOffer)shopComp.offers.Get().Get(0)
            var price :  GL_ComponentShopOfferPricing = (GL_ComponentShopOfferPricing)offer.pricing.Get().Get(0)
            var cost :  int = (int)price.cost.Get()
            var invComp : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)tech.Get().value.Get())
            var ownType : int = (int)invComp.ownership_type.Get()
            if (ownType == $uiEnums.ITEM_OWN_TYPE_PURCHASED)
               ret := "carousel_tree_tech_owned"
            else
               ret := "" + cost
            end
         end
      end
      return ret
   end
   
   func GetStatusFrame() : string
      var ret : string
      if (IsValid())
         var invComp : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)tech.Get().value.Get())
         var ownType : int = (int)invComp.ownership_type.Get()
         if (ownType == $uiEnums.ITEM_OWN_TYPE_PURCHASED)
            ret := "desc"
         else   
            ret := "cost"
         end
      end
      return ret
   end
   
   func GetTechIdStatus() : int
      var ret : int
      if (IsValid())
         var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get((string)tech.Get().value.Get())
         ret := (int)shopComp.availability.Get()
      end
      return ret
   end
   
   func ShowDefaultState() : bool
      var ret : bool = false
      if (IsValid())
         if (IsTechComing())
            return false
         end
         var invComp : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)tech.Get().value.Get())
         var ownType : int = (int)invComp.ownership_type.Get()
         if (GetTechIdStatus() == $uiEnums.TECH_STATUS_AVAILABLE)
            if (ownType == $uiEnums.ITEM_OWN_TYPE_PURCHASED)
               ret := true
            end   
         end
      end
      return ret
   end
   
   func ShowGoldState() : bool
      var ret : bool = false
      if (IsValid())
         var invComp : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)tech.Get().value.Get())
         var ownType : int = (int)invComp.ownership_type.Get()
         if (GetTechIdStatus() == $uiEnums.TECH_STATUS_AVAILABLE)
            if (ownType == $uiEnums.ITEM_OWN_TYPE_PURCHASED)
               if (IsChallengeComplete())
                  ret := true
               end   
            end   
         end
      end
      return ret
   end
   
   func GetTechId() : string
      var ret : string
      if (IsValid())
         ret := (string)tech.Get().value.Get()
      end
      return ret
   end
   
   func GetIsLocked() : bool
      var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(GetTechId())
      var ret : bool = shopComp.IsLocked()         
      return ret
   end
   
   func GetTokenFrame() : string
      var ret : string
      if (IsValid())
         ret := $UiGlobals.GetTokenFrame($UiGlobals.GetTokenType(GetTechId()))
      end
      return ret
   end
   
   func GetMedalFrame(rank : int) : string
      var ret  : string = ""
      if (rank == -1)
         ret := "gray"
      elif (rank == 0)
         ret := "bronze"
      elif (rank == 1)
         ret := "silver"
      elif (rank == 2)
         ret := "gold"
      else
         ret := "gray"
      end
      return ret
   end   
   
   func GetCurrentRank() : int
      var itemComp   : GL_ComponentItem   = (GL_ComponentItem)$UiGlobals.componentsItem.Get(GetTechId())
      var ret        : int                = itemComp.GetCurrentChallengeRank()         
      return ret
   end   
   
   func IsChallengeComplete() : bool
      var ret : bool
      var itemComp   : GL_ComponentItem   = (GL_ComponentItem)$UiGlobals.componentsItem.Get(GetTechId())
      ret := itemComp.IsComplete()
      return ret
   end
   
   func GetSubHeadFrame() : string
      var ret : string
      if (GetTechIdStatus() == $uiEnums.TECH_STATUS_DISABLE)
         ret := "lock" + clsIndex.Get() //"locked"   
      else
         ret := "color" + clsIndex.Get() //"unlocked"
      end
      return ret
   end
   
   func GetSubHeadTxt() : string
      var ret : string
      if (IsTechComing())
         return " ???"
      end
      if (CheckUnlockItemType() == $uiEnums.ITEM_TYPE_WEAPON)
         ret := "carousel_tech_weapon"
      elif (CheckUnlockItemType() == $uiEnums.ITEM_TYPE_ARMOR)
         ret := "carousel_tech_armor"
      elif (CheckUnlockItemType() == $uiEnums.ITEM_TYPE_ARMOR_SUIT)
         ret := "carousel_tech_suit"
      elif(CheckUnlockItemType() == $uiEnums.ITEM_TYPE_TACTICAL)
         ret := "carousel_tech_tactical" 
      elif (CheckUnlockItemType() == $uiEnums.ITEM_TYPE_UNKNOWN)
         if (GetUnlockTechItem() == "frag_grenade" or GetUnlockTechItem() == "plasma_grenade" or GetUnlockTechItem() == "spike_grenade" or GetUnlockTechItem() == "fire_grenade")
            ret := "carousel_tech_grenade"
         else
            ret := "carousel_tech_boost"
         end   
      end
      return ret 
   end
   
   func GetUnlockTechItem() : string
      var ret : string
      if (GetTechId() != "")
         var compShop : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(GetTechId())
         ret := compShop.GetUnlockItem()
      end
      return ret
   end
   
   func CheckUnlockItemType() : int
      var ret : int = $uiEconomy.GetItemType(GetUnlockTechItem())
      return ret
   end 
   
   func ShowDisableIconState() : bool
      var ret : bool = false
      if (GetTechIdStatus() == $uiEnums.TECH_STATUS_DISABLE)
         ret := true
      end
      return ret
   end
   
   func ShowDisableState() : bool
      var ret : bool = false
      if (GetTechIdStatus() == $uiEnums.TECH_STATUS_DISABLE)
         ret := true
      end
      if (IsTechComing())
         ret := true
      end
      return ret
   end
   
   func ShowCanBuyState() : bool
      var ret : bool = false
      if (IsValid())
         if (IsTechComing())
            return false
         end
         var invComp : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)tech.Get().value.Get())
         var ownType : int = (int)invComp.ownership_type.Get()
         if (GetTechIdStatus() != $uiEnums.TECH_STATUS_DISABLE)
            if (ownType != $uiEnums.ITEM_OWN_TYPE_PURCHASED)
               ret := true
            end
         end
      end
      return ret
   end
   
end // UiTechLirVM

class UiTechCardVM
   
   var parentVM            : UiTechTreeVM = null
   var techItem            : ObservableProperty   = $OM.Property("")
   var progress            : ChallengeProgressVM  = new ChallengeProgressVM()
   var itemType            : ObservableProperty   = $OM.Calculated(this, "CheckItemType")
   var unlockItem          : ObservableProperty   = $OM.Calculated(this, "GetUnlockItem")
   var itemStats           : UiItemStatsVM        = new UiItemStatsVM()
   // Armor stats 
   var unlockItems         : ObservableProperty   = $OM.Calculated(this, "GetUnlockItems")
   // Progress Bars  
   var isLocked            : ObservableProperty = $OM.Calculated(this, "GetIsLocked")
   
   var wgt                 : UiWidget           = null
   var techPriceIconXPos   : ObservableProperty = $OM.Calculated(this, "GetTechPriceIconXPos")
   var techPriceXPos       : ObservableProperty = $OM.Calculated(this, "GetTechPriceXPos")
   var techPriceLabelXPos  : ObservableProperty = $OM.Calculated(this, "GetTechPriceLabelXPos")
   var isCardOpen          : ObservableProperty   = $OM.Property(false)
      
   func Init()
      
   end
   
   func Term()
      itemStats.Term()
   end
   
   func SetChallengeTech(_techId : string)
      techItem.Set(_techId)
      itemStats.Init((string)unlockItem.Get())
      itemType.Invalidate()        
      progress.InitVM(_techId, GetItemComponent().GetNextChallengeId(), GetItemComponent().GetNextChallengeRank(), 0 , IsChallengeComplete())
      techPriceIconXPos.Invalidate()
      techPriceXPos.Invalidate()
      techPriceLabelXPos.Invalidate()
      isCardOpen.Set(true)
      $UiBiLogger.LogSkilTreeDetailsEvent("TechCardOpen", _techId, GetTechOwnershipType(), GetCardSubLabel1())
   end
   
   func GetIsLocked() : bool
      var ret : bool = true
      var invComp : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(GetTechId())
      var ownType : int = (int)invComp.ownership_type.Get()
      if (ownType == $uiEnums.ITEM_OWN_TYPE_PURCHASED)
         ret := false
      end
      return ret
   end
   
   func GetTechOwnershipType() : string
      var ret : string = ""
      var invComp : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(GetTechId())
      var ownType : int = (int)invComp.ownership_type.Get()
      if (ownType == $uiEnums.ITEM_OWN_TYPE_PURCHASED)
         ret := "PURCHASED"
      else
         ret := "NONE"
      end
      return ret
   end
   
   func OnTechCardViewBtnClick(p : params) : bool
      var item : string = GetUnlockItem()
      if (item != "")
         parentVM.ShowItemInShop(item)
      end
      return true
   end
   
   func CloseCard()
      parentVM.CloseTechCard()
   end
   
   func OnTechCardCancelViewBtnClick(p : params) : bool
      CloseCard()
      return true
   end
   
   func OnTechUnlocked(p : params) : bool
      if (p.isOK)
         
      end
      return false
   end
   
   func OnTechCardUnlockBtnClick(p : params) : bool
      var shopComp     : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(GetTechId())
      //var offer : GL_ComponentShopOffer = (GL_ComponentShopOffer)shopComp.offers.Get().Get(0)
      //var price :  GL_ComponentShopOfferPricing = (GL_ComponentShopOfferPricing)offer.pricing.Get().Get(0)
      //var cost :  int = (int)price.cost.Get()
      //var offerName : string = (string)price.offer.Get()
      if (shopComp.offers.Get().Count() > 0)
         var offer : GL_ComponentShopOffer = (GL_ComponentShopOffer)shopComp.offers.Get().Get(0)
         if (offer.pricing.Get().Count() > 0)
            var price :  GL_ComponentShopOfferPricing = (GL_ComponentShopOfferPricing)offer.pricing.Get().Get(0)
            var cost :  int = (int)price.cost.Get()
            var offerName : string = (string)price.offer.Get()
            var status : int = (int)shopComp.availability.Get()
            var par : params
            if (status == $uiEnums.TECH_STATUS_AVAILABLE)
               if (parentVM.GetTechPointsInt() >= cost)   
                  par.itemID           := GetTechId()
                  par.offer            := offerName
                  par.priceAmount      := cost
                  par.priceUnit        := (string)price.currency.Get()
                  par.mbType           := "ConfirmBuy"
                  par.callbackEvent    := "TechUnlocked"
                  par.callbackTarget   := wgt.Props
                  $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
               else
                  par.mbType     := "Info"
                  par.titleTxt   := "msg_ui_warning"
                  par.messageTxt := "msg_ui_not_enough_rp"
                  $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
               end
            else
               par.mbType     := "Info"
               par.titleTxt   := "msg_ui_warning"
               par.messageTxt := "msg_ui_tech_not_available"
               $sslWidgetMgr.GenerateEvent("MainMenuDialogRequest", par)
            end   
         end
      end
      return true
   end

   func OnTechCardCancelUnlockBtnClick(p : params) : bool   
      parentVM.CloseTechCard()
      return true
   end
   
   func EnableUnlockBtn() : bool
      var ret : bool = false
      /*
      var shopComp     : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(GetTechId())
      if (shopComp.offers.Get().Count() > 0)
         var offer : GL_ComponentShopOffer = (GL_ComponentShopOffer)shopComp.offers.Get().Get(0)
         if (offer.pricing.Get().Count() > 0)
            var price :  GL_ComponentShopOfferPricing = (GL_ComponentShopOfferPricing)offer.pricing.Get().Get(0)
            var cost :  int = (int)price.cost.Get()
            var status : int = (int)shopComp.availability.Get()
            if (parentVM.GetTechPointsInt() >= cost and status == $uiEnums.TECH_STATUS_AVAILABLE)   
               ret := true
            end
         end
      end
      */
      if (GetTechIdStatus() == $uiEnums.TECH_STATUS_AVAILABLE)
         ret := true
      end
      return ret
   end
   
   func ChallengeStatusFrame() : string
      var ret : string = "none"
      if (IsChallengeComplete() and (bool)isCardOpen.Get())
         ret := "goldBg"
      end
      return ret
   end
   
   func GetStatusLineFrame() : string
      var ret : string = "blue"
      var invComp : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(GetTechId())
      var ownType : int = (int)invComp.ownership_type.Get()
      if (GetTechIdStatus() != $uiEnums.TECH_STATUS_AVAILABLE or ownType != $uiEnums.ITEM_OWN_TYPE_PURCHASED)
         ret := "red"
      end
      return ret
   end
   
   func GetCardSubLabel1() : string
      var ret : string = ""
      //var invComp : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(GetTechId())
      //var ownType : int = (int)invComp.ownership_type.Get()
      var ownType : int = GetUnlockItemOwnType()
      if (ownType == $uiEnums.ITEM_OWN_TYPE_PURCHASED)
         ret := "carousel_tree_item_owned"
      elif (ownType == $uiEnums.ITEM_OWN_TYPE_RENTED)   
         ret := "carousel_tree_item_rented"
      end
      return ret
   end
   
   func GetCardSubLabel2() : string
      var ret : string = "carousel_tree_item_not_owned"
      //var invComp : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(GetTechId())
      //var ownType : int = (int)invComp.ownership_type.Get()
      var ownType : int = GetUnlockItemOwnType()
      if (ownType == $uiEnums.ITEM_OWN_TYPE_PURCHASED or ownType == $uiEnums.ITEM_OWN_TYPE_RENTED)
         ret := ""
      end
      return ret
   end
   
   func GetCardInfoTxt() : string
      var ret : string = "tech~"
      var invComp : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(GetTechId())
      var ownType : int = (int)invComp.ownership_type.Get()
      if (GetTechIdStatus() == $uiEnums.TECH_STATUS_AVAILABLE)
         if (ownType == $uiEnums.ITEM_OWN_TYPE_PURCHASED)
            ret := "carousel_tech_unlock"
         else
            ret := "carousel_tech_research" //"carousel_tech_lock"
         end
      else
         ret := "carousel_tech_lock" //"carousel_tech_disabled"
      end
      return ret
   end
   
   func GetCardInfoColor() : int
      var ret : int = 16777215
      var invComp : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get(GetTechId())
      var ownType : int = (int)invComp.ownership_type.Get()
      if (GetTechIdStatus() != $uiEnums.TECH_STATUS_AVAILABLE or ownType != $uiEnums.ITEM_OWN_TYPE_PURCHASED)
         ret := 16711680
      end
      return ret
   end
   
   func GetTechIdStatus() : int
      var ret : int
      if (IsValid())
         var shopComp : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(GetTechId())
         ret := (int)shopComp.availability.Get()
      end
      return ret
   end
   
   func GetItemRentTime() : string
      var ret :  string
      if ($uiEconomy.GetItemOwnType((string)unlockItem.Get()) == $uiEnums.ITEM_OWN_TYPE_RENTED)
         ret := $root.MakeUiTimerStringMinutes(GetUnlockRentTime(), true)
      end
      return ret
   end
   
   func GetUnlockItemOwnType() : int
      return $uiEconomy.GetItemOwnType((string)unlockItem.Get())
   end
   
   func GetUnlockRentTime() : int
      var ret        : int = 0
      var ownTypeVal : int = GetUnlockItemOwnType()
      if (ownTypeVal == $uiEnums.ITEM_OWN_TYPE_RENTED)
         var uiInventoryItem : GL_ComponentInventory = (GL_ComponentInventory)$UiGlobals.componentsInventory.Get((string)unlockItem.Get())
         var ownTime : int = (int)uiInventoryItem.ownership_time.Get() - (int)$UiGlobals.timer.Get()
         ret := ownTime
      end
      return ret      
   end
   
   func GetTechCostStr() : string
      var ret :  string = ""
      var shopComp     : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(GetTechId())
      if (shopComp.offers.Get().Count() > 0)
         var offer : GL_ComponentShopOffer = (GL_ComponentShopOffer)shopComp.offers.Get().Get(0)
         if (offer.pricing.Get().Count() > 0)
            var price :  GL_ComponentShopOfferPricing = (GL_ComponentShopOfferPricing)offer.pricing.Get().Get(0)
            var cost :  int = (int)price.cost.Get()
            ret := (string)cost
         end
      end
      return ret
   end
 
   func GetItemLabel() : string
      var ret : string
      if (GetTechId() != "")
         var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(GetTechId())
         ret := (string)compUI.name.Get() 
      end
      return ret
   end
   
   func GetItemIcon() : string
      var ret : string
      if (GetTechId() != "")
         var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(GetTechId())
         ret := (string)compUI.icon_med.Get()
      end
      return ret
   end
   
   func GetItemDesc() : string
      var ret : string
      if (GetTechId() != "")
         var compUI  : GL_ComponentUI = (GL_ComponentUI)$UiGlobals.componentsUI.Get(GetTechId())
         ret := (string)compUI.desc.Get() 
      end
      return ret
   end
   
   
   func GetUnlockItem() : string
      var ret : string
      if (GetTechId() != "")
         var compShop : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(GetTechId())
         ret := compShop.GetUnlockItem()
      end
      return ret
   end
   
   func GetUnlockItems() : vector
      var ret : vector
      if (GetTechId() != "")
         var compShop : GL_ComponentShop = (GL_ComponentShop)$UiGlobals.componentsShop.Get(GetTechId())
         ret := compShop.GetUnlockAllItems()
      end
      return ret
   end
   
   func CheckItemType() : int
      var ret : int = $uiEconomy.GetItemType((string)unlockItem.Get())
      return ret
   end
   
   func IsTechItemWeapon() : bool
      var ret :bool = false
      if ((int)itemType.Get() == $uiEnums.ITEM_TYPE_WEAPON)
         ret := true
      end
      return ret
   end
   
   func IsTechItemGrenade() : bool
      var ret :bool = false
      if ((int)itemType.Get() == $uiEnums.ITEM_TYPE_UNKNOWN)
         // HACK
         if ((string)unlockItem.Get() == "frag_grenade" or (string)unlockItem.Get() == "plasma_grenade" or (string)unlockItem.Get() == "spike_grenade" or (string)unlockItem.Get() == "fire_grenade")
            ret := true
         end   
      end
      return ret
   end
   
   func IsTechItemArmor() : bool
      var ret :bool = false
      if ((int)itemType.Get() == $uiEnums.ITEM_TYPE_ARMOR_SUIT)
         ret := true
      end
      return ret
   end
   
   func IsTechItemTactical() : bool
      var ret :bool = false
      if ((int)itemType.Get() == $uiEnums.ITEM_TYPE_TACTICAL)
         ret := true
      end
      return ret
   end 
   
   func IsTechItemBoost() : bool
      var ret : bool = false
      if ((int)itemType.Get() == $uiEnums.ITEM_TYPE_UNKNOWN)
         if ((string)unlockItem.Get() != "frag_grenade" and (string)unlockItem.Get() != "plasma_grenade" and (string)unlockItem.Get() != "spike_grenade" and (string)unlockItem.Get() != "fire_grenade")
            ret := true
         end
      end
      return ret
   end
   
   
   
   func GetItemComponent() : GL_ComponentItem
      var ret : GL_ComponentItem = (GL_ComponentItem)$UiGlobals.componentsItem.Get(GetTechId())
      return ret
   end
   
   func IsValid() : bool
      return techItem.Get() != ""
   end
   
   func GetTechId() : string
      var ret : string
      if (IsValid())
         ret := (string)techItem.Get()
      end
      return ret
   end
         
   func GetChallengeRank() : int
      return GetItemComponent().GetCurrentChallengeRank()
   end
   
   func IsChallengeComplete() : bool
      return GetItemComponent().IsComplete()
   end
   
   func GetMedalFrame(rank : int) : string
      var ret  : string = ""
      if (rank == -1)
         ret := "gray"
      elif (rank == 0)
         ret := "bronze"
      elif (rank == 1)
         ret := "silver"
      elif (rank == 2)
         ret := "gold"
      else
         ret := "gray"
      end
      return ret
   end   
   
   func GetCurrentRank() : int
      return GetChallengeRank()
   end   
   
   func GetTokenFrame() : string
      var ret : string = $UiGlobals.GetTokenFrame(GetCurrentTokenType())
      return ret
   end
      
   func GetCurrentTokenType() : string
      var compShop   : GL_ComponentShop   = (GL_ComponentShop)$UiGlobals.componentsShop.Get(GetTechId())
      var ret        : string             = compShop.GetTokenType()
      return ret
   end
   
   // ugly tech price centering stuff
   func GetTechPriceSpacing() : float
      return 5
   end
   
   func GetTechPriceLabelWidth() : float
      return wgt.Widgets.unlockBtn.tfPriceCard.tfWidth
   end

   func GetTechPriceWidth() : float
      return wgt.Widgets.unlockBtn.tfNumberCard.tfWidth
   end
   
   func GetTechPriceIconWidth() : float
      return wgt.Widgets.unlockBtn.tpIcon.width
   end
   
   func GetTechPriceContWidth() : float
      return GetTechPriceLabelWidth() + GetTechPriceWidth() + GetTechPriceIconWidth() + GetTechPriceSpacing() * 2
   end
   
   func GetTechPriceLabelXPos() : float
      var totalW  : float = GetTechPriceContWidth() 
      var ret     : float = - totalW / 2
      return ret      
   end
   
   func GetTechPriceXPos() : float
      var totalW  : float = GetTechPriceContWidth() 
      var ret     : float = GetTechPriceLabelXPos() + GetTechPriceLabelWidth () + GetTechPriceSpacing()
      return ret      
   end
   
   func GetTechPriceIconXPos() : float
      var totalW  : float = GetTechPriceContWidth() 
      var ret     : float = GetTechPriceLabelXPos() + GetTechPriceLabelWidth () + GetTechPriceWidth() + GetTechPriceSpacing() * 2
      return ret      
   end
end // class UiTechCardVM
