import ssl.lib.ui.ui_widget_container
import ui.ui_economy

class UiWcProgressBar : UiWidgetContainer

var   wpnID    : string
var   statID   : string
var   baseStat : int
var   blinkStartScale     : float = 0
var   blinkStartScaleCmp  : float = 0
var   maxTime          : float = 0.4

func SetScales(s1:float)
   Widgets().bar.scaleX     := s1*Props().maxScale1
   Widgets().subBar.scaleX  := 0
end

func Init(_wpnID: string, _statID: string, _baseStat:int = 0)
   wpnID    := _wpnID
   statID   := _statID  
   baseStat := _baseStat
   Update()
   PaintBar(_wpnID, "none")
end

func GetStatName() : string
   var ret:string := statID
   if (statID == "dmg")
      ret := "carousel_damage"
   else if (statID == "rof")
      ret := "carousel_rate_of_fire"
   else if (statID == "acc")
      ret := "carousel_accuracy"
   else if (statID == "clip")
      ret := "carousel_clip_size"
   else if (statID == "reload")
      ret := "carousel_reload_speed"
   end
   return ret
end

func PaintBar(_wpnId : string, _wpnAttrib : string)
   // r (100, 50, 50) 
   // g (50, 100, 50)
   // y (100, 100, 50)
   // b (50, 68, 100)
   // def (40, 50 , 60)
   var p : params
   p := $uiEconomy.GetWeaponPrimaryArrtibuteColor(_wpnAttrib)
   Widgets().bar.colorMult := p
   Widgets().subBar.colorMult := p
end


func Update()
   if (statID == "")
      Props().visible := false
      return
   else 
      Props().visible := true
   end

   if (baseStat > 100)
      baseStat := 100
   end
      
   SetScales(baseStat/100.0)
   //Props().text := GetStatName()
end
   
func BlinkOverride(_phase : int, _dt : float) : bool
   var ret :  bool = false
   if (_dt > maxTime)
      ret := true
   end
   
   if (_phase == 0)
      blinkStartScale    := Widgets().bar.scaleX
      blinkStartScaleCmp := Widgets().barCmp.scaleX
   elif (_phase == 1)
      var tmpScale : float = _dt / maxTime
      if (_dt >= 0)
         tmpScale := $root.sqrt(tmpScale)
      else 
         tmpScale := 0
      end
      
      if (tmpScale > 1)
         tmpScale := 1.0
      end
      if (tmpScale < 0)
         tmpScale := 0.0
      end
      //tmpScale := tmpScale * tmpScale
      var tmpScaleCmp : float
      tmpScaleCmp := tmpScale
      tmpScale       := blinkStartScale * tmpScale         
      tmpScaleCmp    := blinkStartScaleCmp * tmpScaleCmp
      Widgets().bar.scaleX := tmpScale
      Widgets().barCmp.scaleX := tmpScaleCmp
   elif (_phase == 2)
      Widgets().bar.scaleX := blinkStartScale
      Widgets().barCmp.scaleX := blinkStartScaleCmp
   end
   
   return ret
end   

end

